Descriptions changed
segmentio/action-destinations pull request #1006
Opened 2023-01-27 08:10 UTC by prathamesh-88

Simple Description changes for VWO Cloud and Device mode destinations. Minor change in the utility files 

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-02-01 11:52 UTC, prathamesh-88 commented
Hi @joe-ayoub-segment 
No worries. I've reverted the changes for Cloud Destination. Will be opening a separate PR for the same.

2023-02-01 13:17 UTC, joe-ayoub-segment requested changes
Hi @prathamesh-88 , 

It all looks good apart from the change being made to trait names. I commented inline. Could you clarify if this change will result in a change to the data being collected by customers who are already using the Integration please?

2023-02-01 13:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/src/destinations/vwo/utility.ts
> +    formattedAttributes[`segment.${key}`] = attributes[key]
hi @prathamesh-88 , this change will change the payload that gets sent to your platform when an identify() call comes to Segment. 

Is this going to be a problem for customers who are already using the vwo Integration? 
For example will it matter to a customer if a trait name changes from segment_first_name to segment.first_name? 

We need to be careful when making changes that change the data that customers are already collecting. Keen to hear your thoughts.

2023-02-01 13:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/src/destinations/vwo/utility.ts
> +  return 'segment.' + name
Same comment as above.

2023-02-01 14:05 UTC, prathamesh-88 commented
Hi @joe-ayoub-segment , thanks for the prompt response.
This destination is in private beta and is being tested internally. It's not available to the customers.

2023-02-17 12:03 UTC, joe-ayoub-segment approved these changes
Looks good. Partner indicated no customers are using it yet.

2023-02-17 13:45 UTC, merged