livelike-cloud action destination
segmentio/action-destinations pull request #1020
Opened 2023-02-03 10:23 UTC by akansal1599

This is the initial livelike-cloud destination.
This includes an action for tracking events and 3 presets for `track`, `page` and `screen` event types.

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [✓] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-02-07 13:46 UTC, joe-ayoub-segment requested changes

2023-02-07 13:46 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/livelike-cloud/trackEvent/generated-types.ts
> +  timestamp: string | number
type for timestamp should be string only

2023-02-07 13:46 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/livelike-cloud/trackEvent/generated-types.ts
> +  timestamp: string | number
Add comment to explain what format the timestamp should be in.

2023-02-07 13:46 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/livelike-cloud/trackEvent/generated-types.ts
> +  timestamp: string | number
Add comment to explain what format the timestamp should be in.

2023-02-07 13:46 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/livelike-cloud/trackEvent/generated-types.ts
> +   * A unique identifier for a user. Atleast one of `User ID` or `LiveLike User Profile ID` is mandatory.
Spelling correction "At least"

2023-02-07 13:46 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/livelike-cloud/trackEvent/generated-types.ts
> +   * A unique identifier for a user. Atleast one of `User ID` or `LiveLike User Profile ID` is mandatory.
Consider explaining the difference between the userId and the livelike_profile_id. What values should be passed for each field? How do they behave when sent to Livelike? Any advice you can give the customer?

2023-02-07 13:54 UTC, joe-ayoub-segment requested changes

2023-02-07 13:54 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/livelike-cloud/trackEvent/index.ts
> +        'A unique identifier for a user. Atleast one of `User ID` or `LiveLike User Profile ID` is mandatory.',
```suggestion
        'A unique identifier for a user. At least one of `User ID` or `LiveLike User Profile ID` is mandatory.',
```

2023-02-07 14:01 UTC, joe-ayoub-segment commented
Happy to approve this PR to go to Private Beta. Only changes required before we go to Public Beta are comments related.

2023-02-08 12:08 UTC, joe-ayoub-segment approved these changes
Looks good. New Integration.

2023-02-08 12:08 UTC, merged

2023-02-09 10:25 UTC, joe-ayoub-segment commented
Hi @akansal1599 , 
Just FYI the deployment didn't go out today due to an issue unrelated to your PR. It should be deployed later today.

2023-02-10 11:38 UTC, joe-ayoub-segment commented
Hi @akansal1599 , 
Unfortunately the deployment yesterday was cancelled (nothing related to your PR). The team plans to release next week. I'll confirm the date when I know more. Apologies for the inconvenience.

2023-02-10 14:29 UTC, akansal1599 commented
> Hi @akansal1599 , Unfortunately the deployment yesterday was cancelled (nothing related to your PR). The team plans to release next week. I'll confirm the date when I know more. Apologies for the inconvenience.

@joe-ayoub-segment Thanks for the update.

2023-02-16 13:09 UTC, joe-ayoub-segment commented
Hi @akansal1599 , 

This PR was deployed yesterday. You should be able to start testing it now!
It's available in Private Beta, so you'll need to access it via a specific URL.
https://app.segment.com/YOUR_WORKSPACE_SLUG/destinations/catalog/actions-livelike-cloud

If you've any follow up questions, including regarding adding meta data and documentation please email [partner-support@segment.com](mailto:partner-support@segment.com).