Twilio Studio as a Segment Action Destination
segmentio/action-destinations pull request #1023
Opened 2023-02-06 12:18 UTC by aradhakrishnan-twilio

First PR for Twilio Studio as an Action Destination

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-02-07 17:57 UTC, joe-ayoub-segment requested changes
hi @aradhakrishnan-twilio , 

Thanks for the PR! 

During our last call we discussed a few things, but it looks like you've made the call to not include them, which is totally fine. 

These are: 
1. Need to handle EU or US Engage Space  - I think it's OK to exclude this as we probably won't launch when using Personas as the phone source. 

2. Need to handle userId fallback to anonymousId when fetching phone from Engage - While I think the anonymousId isn't required for fetching the phone from Personas, I think it might be needed as part of your cache key when there is no userId in the payload. Please see the inline comment. 

Other than that I think we're good. I didn't actually test the code myself but I know that you'll be testing it extensively.

2023-02-07 17:57 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/twilio-studio/triggerStudioFlow/index.ts
> +      !shouldSendToStudio(`${payload.flowSid}_${payload.userId}`, stateContext, payload.coolingOffPeriod!)
hi @aradhakrishnan-twilio , 
When we eventually go live with the ID Sync capability, it's entirely possible and commonplace that API calls will be sent to this Integration which do not have the userId field populated. In this case the cache capability will probably not work. 

For this reason I suggest we fall back to the anonymousId also. Or, we could use the phone number instead of the userId in the cache key.

2023-02-07 18:12 UTC, aradhakrishnan-twilio commented on packages/destination-actions/src/destinations/twilio-studio/triggerStudioFlow/index.ts
> +      !shouldSendToStudio(`${payload.flowSid}_${payload.userId}`, stateContext, payload.coolingOffPeriod!)
Thanks @joe-ayoub-segment , we are doing a userId check in the line 61, so it won't reach here unless the payload has the userId.
Also, are you suggesting that it is a possibility that with ID Sync feature, the userid field might not be present anymore in the event payload ? Won't that be a backward compatibility issue for other destinations as well?
We considered keeping phone as the cache key but our PM brought up a scenario where multiple profiles can have same phone numbers and we didn't want to have cooldown between different profiles triggering the action, that's why we went with the userId.
With that being  said, if userId is going to be removed from the payload as part of the ID Sync for sure, then we might need to think of a different cache key for sure.
Do you think we can do a deployment with this right now and during the private beta once we are sure the ID sync is going to affect the userId, we can take a call? Otherwise I am totally fine to take this up with the team tomorrow for further discussion? Thoughts?

2023-02-07 18:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/twilio-studio/triggerStudioFlow/index.ts
> +      !shouldSendToStudio(`${payload.flowSid}_${payload.userId}`, stateContext, payload.coolingOffPeriod!)
Hi @aradhakrishnan-twilio , 

Yes it's possible (and likely) that some Segment events won't contain a userId at all. Those user profiles are considered 'anonymous', and only have an anonymousId. 

This sort of thing is very comment. For example, imaging if a user visits a website for the first time ever, they will be assigned an anonymousId. That user might then fill in a form and provide their phone number in the form. Now the user profile in Segment has an anonymousId and a phone number. But they still do not have a userId. However the customer may still want to be able to opt that user into a Twilio flow.

2023-02-07 19:08 UTC, aradhakrishnan-twilio commented on packages/destination-actions/src/destinations/twilio-studio/triggerStudioFlow/index.ts
> +      !shouldSendToStudio(`${payload.flowSid}_${payload.userId}`, stateContext, payload.coolingOffPeriod!)
Made the changes.

2023-02-07 20:50 UTC, joe-ayoub-segment approved these changes

2023-02-07 20:50 UTC, merged

2023-02-09 10:22 UTC, joe-ayoub-segment commented
hi @aradhakrishnan-twilio , 
Just FYI the deployment didn't go out today due to an issue unrelated to your PR. It should be deployed later today.

2023-02-10 11:35 UTC, joe-ayoub-segment commented
Hi @aradhakrishnan-twilio , 
Unfortunately the deployment yesterday was cancelled (nothing related to your PR). The team plans to release next week. I'll confirm the date when I know more. Apologies for the inconvenience.