New SalesWings API urls
segmentio/action-destinations pull request #1039
Opened 2023-02-09 14:34 UTC by denis-egorushkin-sw

The first version of the SalesWings (Actions) component added with https://github.com/segmentio/action-destinations/pull/945 is calling our general event submission API endpoints. These endpoints are called by our customers to submit tracking events from their backend systems.

For the events sent from Segment, we would like to be able to add specific logic in our backend (for example, we would need to store Segment user ID so that we could later implement a Source integration to update Segment profiles with the information calculated in SalesWings). That's why we have implemented new Segment specific backend endpoints, and we would like the destination to call them instead of our general purpose API.

The format of the requests to the new endpoints matches the action payload format, that's why the code responsible for the conversion to our general purpose API format is removed.

Additionally, this PR adds a new destination level setting that allows to select target SalesWings environment (live or test). This setting is intended to be used by us for end-to-testing of our backend changes against the SalesWings (Actions) component, and potentially by our customers if they would like to do initial setup on the test environment.

## Testing

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-02-09 16:14 UTC, joe-ayoub-segment commented
Thank you @denis-egorushkin-sw , acknowledging your PR. I'll schedule this for a review.

2023-02-14 15:49 UTC, joe-ayoub-segment requested changes
Hi @denis-egorushkin-sw , just a couple of things to consider / change. 
I assume that there's no customers using this yet and that you'll test the functionality end-to-end.

2023-02-15 15:03 UTC, denis-egorushkin-sw commented on packages/destination-actions/src/destinations/saleswings/generated-types.ts
> +  environment: string
Hi, exactly, no customer uses it yet.

2023-02-15 15:07 UTC, denis-egorushkin-sw commented on packages/destination-actions/src/destinations/saleswings/index.ts
>        return resp.status == 200
Hi @joe-ayoub-segment, thanks for the hint! I didn't notice it, because the resulting behavior is still correct (an error is thrown on 401 response so one cannot insert an invalid key), but the code with the status check is indeed redundant. I've removed the check.

2023-02-15 18:31 UTC, joe-ayoub-segment approved these changes

2023-02-16 08:01 UTC, denis-egorushkin-sw commented
Hi @joe-ayoub-segment, thanks for the review. Sorry, I forgot to commit the removal of an unused file, that's why the build failed. I've addressed it with https://github.com/segmentio/action-destinations/pull/1039/commits/fddf9efa5f3b434742f344f79f4f5b04bcf61927, could you please approve running the workflows once again?

2023-02-16 18:02 UTC, joe-ayoub-segment approved these changes
Reviewed and provided feedback which was implemented.

2023-02-16 18:02 UTC, merged

2023-02-16 18:04 UTC, joe-ayoub-segment commented
Thanks @denis-egorushkin-sw this will go out with the next deploy - planned for next week.

2023-02-23 13:27 UTC, joe-ayoub-segment commented
Hi @denis-egorushkin-sw this PR has been deployed live. Please verify and let me know if everything works as expected!