DOTORG-847: Add 'Create Gift' action
segmentio/action-destinations pull request #1056
Opened 2023-02-18 13:12 UTC by noahcooper

This PR updates the Blackbaud Raiser's Edge NXT Destination to add the "Create Gift" Action. Because Blackbaud requires that a gift has a constituent_id, this action can optionally be used to create one if one does not already exist. To accomplish this, the `fields` and `perform` function from the "Create or Update Individual Constituent" action are now exported. A customer can skip creating a constituent by supplying a non-null `constituent_id`.

Example basic `properties` object:

```
"properties": {
  "constituentId": "595250",
  "paymentMethod": "CreditCard",
  "revenue": 100
}
```

Example `properties` with basic properties to create a new constituent :

```
"properties": {
  "email": "test@example2.org",
  "firstName": "Noah",
  "lastName": "Cooper",
  "paymentMethod": "CreditCard",
  "revenue": 100
}
```

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-02-20 08:29 UTC, joe-ayoub-segment commented
hi @noahcooper , acknowledging this PR. Will review ASAP.

2023-02-20 18:39 UTC, joe-ayoub-segment requested changes
hi @noahcooper thanks for submitting this PR! There's so much in here that I decided to focus mainly on fields. 

Thanks for refactoring the perform() function in the pre-existing Action. 

I left a number of inline comments/suggestions/questions, and also noted that there are failing unit tests. 

<img width="840" alt="image" src="https://user-images.githubusercontent.com/45374896/220179295-314f19c5-4d69-438b-b69e-5de8b59705ec.png">

2023-02-20 18:39 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blackbaud-raisers-edge-nxt/createGift/index.ts
> +        '@path': '$.properties.acknowledgement.status'
What type of value should status field accept? Is there a limited list or can it be anything?

2023-02-20 18:39 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blackbaud-raisers-edge-nxt/createGift/index.ts
> +        label: 'Status',
What sort of values can be provided for a receipt status? Are there a limited number of them?

2023-02-22 04:02 UTC, noahcooper commented on packages/destination-actions/src/destinations/mixpanel/trackEvent/functions.ts
>  import { omit } from '@segment/actions-core'
Actually, this isn't happening because of my code editor. It looks like mixpanel (and a few other destinations) are getting fixed by `prettier` automatically.

2023-02-22 04:09 UTC, noahcooper commented on packages/destination-actions/src/destinations/mixpanel/trackEvent/functions.ts
>  import { omit } from '@segment/actions-core'
Perhaps it would be best to have a separate branch (or branches) to fix the issues `prettier` is fixing here?

2023-02-23 01:12 UTC, twilio-hwong commented on packages/destination-actions/src/destinations/blackbaud-raisers-edge-nxt/createGift/index.ts
> +    description: 'The recurring gift associated with the payment being added.',
Originally we are thinking of accepting a comma separated string and convert that to an array for the Blackbaud API, but I see there's a `multiple` option.

If we set this to true, does that mean we are expecting the customer to pass in an array for the field in the Segment event?

2023-02-24 23:08 UTC, twilio-hwong commented
@joe-ayoub-segment 

Addressed your comments with the following changes:
- Flattened the "Gift Amount" from an object into a number field
- Added choices to support dropdown values wherever applicable
- Added descriptions and choices to object fields wherever applicable, however these don't show up in the Action Tester
- Added the following options to applicable objects. However, I can still add new key/value pairs in the Action Tester, not sure if it's expected behavior
```
defaultObjectUI: 'keyvalue:only',
additionalProperties: false,
```

One last thing is whether you are comfortable with merging the linter changes in this PR, or if you want those to be separate. I can resolve the conflict or open a separate PR depending on your preference.

2023-02-28 18:49 UTC, noahcooper commented on packages/destination-actions/src/destinations/blackbaud-raisers-edge-nxt/__tests__/snapshot.test.ts
> +      eventData.last = 'Smith'
I don't think we want to hardcode this for all actions?

2023-02-28 19:00 UTC, noahcooper commented on packages/destination-actions/src/destinations/blackbaud-raisers-edge-nxt/utils/index.ts
>    const date = new Date(dateString)
Since we're using `getUTCDate`, etc., we should change this to:

```
const date = new Date((dateString + '').split('T')[0])
```

This basically drops the time and timezone offset, so the date is always exactly what it was provided as. In production, I'd expect customers to provide a date value like `2023-02-28` with no time or offset.

2023-03-01 12:11 UTC, joe-ayoub-segment commented
Local tests pass. Reviewed PR with Partner multiple times. No customers using the Integration yet.

2023-03-01 12:11 UTC, merged

2023-03-02 10:57 UTC, joe-ayoub-segment commented
Hi @noahcooper and @twilio-hwong , this PR has been deployed. I can see the Action in the Destination I set up. Please test and let me know if everything looks good!