Feat/toplyne destination action
segmentio/action-destinations pull request #1068
Opened 2023-02-24 11:38 UTC by ankitjena

The pull request is to add a new destination action for [Toplyne](https://toplyne.io). Using this segment users can directly send their data(from track, identify and group calls) to Toplyne. This will help Toplyne and it's users receive realtime data from segment without going through third party tools.

## Testing

We have tested end to end working of the actions included which go through our server and end up in our data warehouse.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-02-27 14:52 UTC, joe-ayoub-segment commented
Hi @ankitjena , 
Thank you for raising this PR for a new Integration! 
We've updated our process slightly to include a face to face meeting so that the reviewer can get a better idea of the intended behavior and use-cases for the new Integration. This will help us do a more informed review. 

Would you be OK scheduling a call with me via [Calendly](http://calendly.com/joe_ayoub/integration-workshop) please? 
If you can't find a time that works for you please let me know (and provide some suggestions) and I'll open up some more slots in the calendar. 

Thank you!

2023-02-28 10:59 UTC, joe-ayoub-segment requested changes
Generally looks very good. 

Most important item to address is the identifiers. See inline comment. 

Consider if you want to collect context object data

2023-02-28 10:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/toplyne/sendUserProfiles/index.ts
> +    creationTime: {
Please update the description to explain how creationTime works (as discussed)....

2023-02-28 10:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/toplyne/sendUserProfiles/index.ts
> +      default: {
How will we manage the anonymous => known user journey?

2023-02-28 10:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/toplyne/sendAccountProfiles/index.ts
> +  fields: {
Consider collecting the user identifier (userId or anonymousId) in order to link the account object to the user object, to compensate for lack of context.groupId in track() events.

2023-02-28 11:33 UTC, ankitjena commented
@joe-ayoub-segment is there some documentation on how to add presets?

2023-02-28 18:00 UTC, joe-ayoub-segment commented
Hi @ankitjena , 
Unfortunately there isn't. I'll be updating our docs in the next few weeks but this will be too late for you. 
Also, you can't test presets locally. 

However the following code should work. It needs to be added into the Destination object in your root index.ts file. 

`  presets: [
    {
      name: 'Send user profiles',
      subscribe: 'type = "identify"',
      partnerAction: 'sendUserProfiles',
      mapping: defaultValues(sendUserProfiles.fields)
    },
    {
      name: 'Send Account Profiles',
      subscribe: 'type = "group"',
      partnerAction: 'sendAccountProfiles',
      mapping: defaultValues(sendAccountProfiles.fields)
    },
    {
      name: 'Send events',
      subscribe: 'type = "track"',
      partnerAction: 'sendEvents',
      mapping: defaultValues(sendEvents.fields)
    }
  ]`

Best regards,
Joe

2023-03-06 14:08 UTC, joe-ayoub-segment commented
hi @ankitjena , 
Hope you are doing well. Just following up to see if you need any assistance with this?
Thanks,
Joe

2023-03-07 11:19 UTC, ankitjena commented
@joe-ayoub-segment Sorry for the delay, we were changing some things internally to support anonymousId thing. Have updated the PR. Can you re review?

Optimistic if we can be in the release tomorrow as well

2023-03-07 11:21 UTC, ankitjena commented on packages/destination-actions/src/destinations/toplyne/sendAccountProfiles/index.ts
> +  fields: {
Not doing this now, we have a way of grouping information internally. We will change the process a bit and will update this destination accordingly.

2023-03-07 11:21 UTC, ankitjena commented on packages/destination-actions/src/destinations/toplyne/sendUserProfiles/index.ts
> +      default: {
Done

2023-03-07 11:21 UTC, ankitjena commented on packages/destination-actions/src/destinations/toplyne/sendUserProfiles/index.ts
> +    creationTime: {
Done

2023-03-07 11:31 UTC, joe-ayoub-segment commented
Hi @ankitjena I just took a look at the code and there hasn't been a recent commit, so nothing has changed. Are you sure that some changes have been submitted?

2023-03-07 11:32 UTC, joe-ayoub-segment commented
Also @ankitjena  there's a couple of naming changes which will need to be added (which I missed the first time around). You can see them as comments in the root level index.ts file.

2023-03-07 11:32 UTC, joe-ayoub-segment requested changes

2023-03-07 11:32 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/toplyne/index.ts
> +  name: 'Toplyne',
```suggestion
  name: 'Toplyne Cloud Mode (Actions)',
```

2023-03-07 11:32 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/toplyne/index.ts
> +  slug: 'toplyne',
```suggestion
  slug: 'actions-toplyne-cloud',
```

2023-03-07 16:43 UTC, joe-ayoub-segment requested changes
Hi @ankitjena , 
It all looks good apart from one thing. I discussed the performBatch() with a colleague of mine, and chunking and then sending multiple requests from the performBatch will mess with the deliverability observability for the Integration. 

I'm following up to see if we can set specific batch size limits for different Destinations from our side, so in that case you would not need to chunk. 

However for now we'll need to remove the performBatch(). 

Is this something you could do please?
Remember to also remove the enableBatch field as well. 

Everything else looks good. 
Thank you!

2023-03-07 17:02 UTC, ankitjena commented
@joe-ayoub-segment That makes sense. Have removed it for now. Do verify once.

Also is there a way for us to know once you sort out the different batch sizes for destinations. Would definitely want to add it back then.

2023-03-08 11:06 UTC, joe-ayoub-segment approved these changes
Local tests pass. 
code looks good. 
New Integration so low risk.

2023-03-08 11:07 UTC, merged

2023-03-08 11:26 UTC, joe-ayoub-segment commented
Hi @ankitjena  - PR merged. We should be able to deploy later today!
I'm not aware that we have a mechanism for keeping Partner informed about specific feature requests. I can add a note to the JIRA ticket to ping you once it's live though. 

At the moment it is just a request and hasn't been committed to - but improving batch handling and error reporting is a focus for the team at the moment.

2023-03-08 12:16 UTC, ankitjena commented
@joe-ayoub-segment Thanks for the quick turnaround. Sure, I understand how feature requests work, so will be on lookout if docs are updated or anything.

Also the documentation PR is still open, had made the changes requested. As I understand both of these need go together. Pasting the PR link here https://github.com/segmentio/segment-docs/pull/4294

Will be looking forward to the release.

2023-03-08 13:21 UTC, joe-ayoub-segment commented
Thanks @ankitjena , 
Another colleague of mine will liaise with you regarding docs. 
Regarding the missed call earlier. Do you want to reschedule?

2023-03-08 18:00 UTC, joe-ayoub-segment commented
FYI @ankitjena today's deployment has been postponed due to an ongoing Datadog incident. 
We'll attempt to deploy tomorrow.

2023-03-09 04:41 UTC, ankitjena commented
@joe-ayoub-segment Yeah, we were also facing issue in monitoring due to that. And apologies I forgot to cancel our call. For now don't think we need to reschedule.

Also I had discussion with our team, we can enable batch support by making changes to our apis. So it doesn't have to chunk internally. As I understand segment's batch size is 1000 right.

2023-03-09 10:10 UTC, joe-ayoub-segment commented
Hi Ankit,
That's correct, Segment MAX MAX MAX batch size is 1000. However batch sizes
will usually be far smaller in reality.
Best regards,
Joe

On Thu, Mar 9, 2023 at 4:52 AM Ankit Jena ***@***.***> wrote:

> @joe-ayoub-segment
> <https://urldefense.com/v3/__https://github.com/joe-ayoub-segment__;!!NCc8flgU!f_hxcnlQnhqTseLZ24KUCEepQywJ8MyWJvnoF7lXcQtjzjAF7Vr9gIs-vs7gCb1bzFRVOqBqj4LezQ_eKpG9C2z1hA$>
> Yeah, we were also facing issue in monitoring due to that. And apologies I
> forgot to cancel our call. For now don't think we need to reschedule.
>
> Also I had discussion with our team, we can enable batch support by making
> changes to our apis. So it doesn't have to chunk internally. As I
> understand segment's batch size is 1000 right.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/segmentio/action-destinations/pull/1068*issuecomment-1461270078__;Iw!!NCc8flgU!f_hxcnlQnhqTseLZ24KUCEepQywJ8MyWJvnoF7lXcQtjzjAF7Vr9gIs-vs7gCb1bzFRVOqBqj4LezQ_eKpGDeH8v7g$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AK2F3MBHOTCIJVTMWATLVM3W3FNRFANCNFSM6AAAAAAVGZO2MI__;!!NCc8flgU!f_hxcnlQnhqTseLZ24KUCEepQywJ8MyWJvnoF7lXcQtjzjAF7Vr9gIs-vs7gCb1bzFRVOqBqj4LezQ_eKpENKSYx7A$>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-10 13:59 UTC, joe-ayoub-segment commented
Hi @ankitjena FYI we didn't get to deploy yesterday - deployment pushed to Monday.

2023-03-14 13:01 UTC, joe-ayoub-segment commented
hi @ankitjena this PR has been deployed. 
next steps are to do testing, create documentation (if you haven't already) and get the Catalog metadata created (if you haven't already). 

I'll send you an email with some details. 
Best regards,
Joe