Add GWEN destination, sendEvent and identifyUser actions
segmentio/action-destinations pull request #1093
Opened 2023-03-06 10:06 UTC by Hagej

This PR adds the GWEN (Gamify the World ENgine) destination as well as the `sendEvent` action for passing events to GWEN and the `identifyUser` action which (optionally) provides GWEN with user insights

## Testing

Unit tests should cover basic use cases and errors. 
End-to-end testing has been performed locally with no issues.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-03-06 13:28 UTC, joe-ayoub-segment commented
Hi @Hagej , 

Thanks for raising this PR!
Looks like it's for a new Integration :). Would you be able to schedule a call with me so we can run through the use-cases that customers will use this Integration for please? I'd also like to get a picture of the types of data which will be forwarded from Segment to this new Integration, as well as the identifiers which will be used.

You can schedule a call with me using [this Calendly link](http://calendly.com/joe_ayoub/integration-workshop).

Kind regards,
Joe

2023-03-09 11:49 UTC, joe-ayoub-segment commented
Hi @Hagej , just following up to see if you are OK with catching up to discuss your Integration?

2023-03-09 13:52 UTC, Hagej commented
Hi @joe-ayoub-segment 
Sorry for the delayed response
We have now booked a meeting for next week with me as well as our CEO and CTO! 

Talk to you then! 
Johan

2023-03-15 14:59 UTC, joe-ayoub-segment requested changes
Thanks for your time just now Magnus and team. Requested changes in comments.

2023-03-15 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/gwen/identifyUser/index.ts
> +      format: 'uuid',
The Segment userID field might be in any string format, so consider not forcing customers to provide a uuid format.

2023-03-15 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/gwen/identifyUser/index.ts
> +      format: 'ipv4',
Not sure if IP address from the context.ip location in the Segment event will always be an IPV4 address. Consider removing the format and just leaving it as a string.

2023-03-15 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/gwen/index.ts
> +  name: 'Gwen',
```suggestion
  name: 'Gwen (Actions)',
```

2023-03-15 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/gwen/index.ts
> +  slug: 'actions-gwen',
```suggestion
  slug: 'actions-cloud-gwen',
```

2023-03-15 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/gwen/index.ts
> +  // onDelete: async (request, { settings, payload }) => {
Please remove unnecessary comments

2023-03-15 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/gwen/index.ts
> +
Consider adding presets. Have a look at how Pipedrive did it.

2023-03-15 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/gwen/request-params.ts
> +  process.env.NODE_ENV === 'prod' ? 'https://gwen.insertcoin.se/graphql' : 'http://localhost:4000/graphql'
Consider changing this line to point just to the Prod address. I'm not sure if process.env.NODE_ENV will work as you expect.

2023-03-15 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/gwen/sendEvent/index.ts
> +      description: 'The data to be sent to GWEN'
The default location for 'data' in a `track()` event should point to the following: 

      default: {
        '@path': '$.properties'
      }

2023-03-15 15:10 UTC, Hagej commented on packages/destination-actions/src/destinations/gwen/identifyUser/index.ts
> +      format: 'uuid',
We want to try the formatting and see if it works as we force the UUID formatting on our side

2023-03-15 15:10 UTC, Hagej commented on packages/destination-actions/src/destinations/gwen/sendEvent/index.ts
> +      format: 'uuid',
We want to try the formatting and see if it works as we force the UUID formatting on our side

2023-03-15 16:22 UTC, joe-ayoub-segment approved these changes

2023-03-15 16:43 UTC, merged

2023-03-16 08:19 UTC, joe-ayoub-segment commented
hi @Hagej , FYI that yesterday's deploy didn't complete - expecting to complete it today.

2023-03-20 18:50 UTC, joe-ayoub-segment commented
hi @Hagej , this PR has been deployed. I'll share an email regarding next step.