Insider Integration
segmentio/action-destinations pull request #1094
Opened 2023-03-06 12:40 UTC by emreisik95

Insider Authentication, Update User Profile, and Track Event feature added.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-03-06 13:17 UTC, joe-ayoub-segment commented
Hi @emreisik95 , thanks for raising this PR. 
Looks like it's for a new Integration :). Would you be able to schedule a call with me so we can run through the use-cases that customers will use this Integration for please? I'd also like to get a picture of the types of data which will be forwarded from Segment to this new Integration, as well as the identifiers which will be used. 

You can schedule a call with me using [this Calendly link](http://calendly.com/joe_ayoub/integration-workshop). 

Kind regards,
Joe

2023-03-07 15:16 UTC, joe-ayoub-segment requested changes

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +  description: '',
add descrtiption

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +        '@path': '$.traits.firstName'
```suggestion
        '@path': '$.traits.first_name'
```

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +        '@path': '$.traits.lastName'
```suggestion
        '@path': '$.traits.last_name'
```

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: false,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      description: 'Anonymous user id.',
update description to indicate that userId or anonymousId is required.

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true,
remove

2023-03-07 15:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +      allowNull: true
remove

2023-03-07 15:19 UTC, joe-ayoub-segment requested changes
Hi team, 
Thanks for taking the time to catch up just now. 

Main items were: 
1. Add presets
2. Provide better descriptions
3. correct some default field mappings

During our call we didn't look at unit tests. I'll run them now to make sure they pass, and will review them to check how much code coverage there is.

2023-03-07 15:56 UTC, emreisik95 commented
Thank you for your help and code review @joe-ayoub-segment. 

@recep-insider @esezerguven will check the comments and will make the requested changes.

2023-03-09 09:50 UTC, emreisik95 commented
> Hi team, Thanks for taking the time to catch up just now.
> 
> Main items were:
> 
> 1. Add presets
> 2. Provide better descriptions
> 3. correct some default field mappings
> 4. Add additional fields to let customer select if email and phone should be treated as identifiers
> 
> During our call we didn't look at unit tests. I'll run them now to make sure they pass, and will review them to check how much code coverage there is.

Can you send us an example of the 4th item?

2023-03-09 11:46 UTC, joe-ayoub-segment commented
Hi @emreisik95 , this is what I was thinking (see attached video). Totally up to you if this makes sense for your platform or not. You are the subject matter experts!


https://user-images.githubusercontent.com/45374896/224013794-4b73bb1e-417b-4d78-b0c1-e107effdc632.mov

2023-03-09 14:51 UTC, recep-insider commented
@joe-ayoub-segment hello, when I try to run unit tests on my local I got these errors. 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/80676334/224061472-26c7859c-8461-43ea-af22-342bf5d0adce.png">

Do you any suggestion? Thanks.

2023-03-09 15:09 UTC, joe-ayoub-segment commented
Hi @recep-insider have you run `yarn && yarn build` first?

2023-03-09 15:13 UTC, recep-insider commented
> Hi @recep-insider have you run `yarn && yarn build` first?

Yes but when I run this command then I got another errors.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/80676334/224067708-66eb6f43-c88e-4f5e-bf75-20008d2942bf.png">

2023-03-09 15:15 UTC, joe-ayoub-segment commented
Are you able to try this first please: 
`yarn --ignore-optional && yarn build'

2023-03-09 15:17 UTC, recep-insider commented
> 

still same

2023-03-09 15:31 UTC, joe-ayoub-segment commented
Would you like to join a call ? Maybe I can help you debug.
https://twilio.zoom.us/j/94525165341?pwd=WTJyaWd0WVByOG11NURqWS9UdXVWUT09

On Thu, Mar 9, 2023 at 3:24 PM recep-insider ***@***.***>
wrote:

> still same
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/segmentio/action-destinations/pull/1094*issuecomment-1462233204__;Iw!!NCc8flgU!fPK5kcDMSzh2Ced8gol7k3kWaTq949rkICJdgnTqyhaGomIKG8XMDAWwMS4DAp_a-SIzI3Y8CVOvpg5yp5nnG9nSJQ$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AK2F3MDAW3S3Y74R7TOC24LW3HYB5ANCNFSM6AAAAAAVRCGDSY__;!!NCc8flgU!fPK5kcDMSzh2Ced8gol7k3kWaTq949rkICJdgnTqyhaGomIKG8XMDAWwMS4DAp_a-SIzI3Y8CVOvpg5yp5m8uIo3tA$>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-10 10:17 UTC, recep-insider commented
@joe-ayoub-segment Hello, I think we are ready to CR again.

2023-03-10 14:19 UTC, joe-ayoub-segment commented
Hi @recep-insider I'll schedule this for a review. Thank you!

2023-03-10 15:47 UTC, joe-ayoub-segment requested changes
Hi @recep-insider , 
There's a file which accidentally got edited and included in this PR. Could you remove it please?

Also I left some more comments/recommendations. I'll leave it up to you if you want to do anything with them. 

When you respond could you be clear about which comment you've decided to implement and which you decided not to please?

2023-03-10 15:47 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +        'Segment Anonymous ID. It is used as identifier when sending data to Insider. Either Anonymous ID or UUID is mandatory to send data.',
```suggestion
        'An Anonymous Identifier. The Anonymous Id string is used as identifier when sending data to Insider. Anonymous Id is required if the UUID field is empty.',
```

2023-03-10 15:47 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/trackEvent/index.ts
> +        "User's unique user ID. UserID should be string and it is used as identifier when sending data to Insider. Either Anonymous ID or UUID is mandatory to send data",
```suggestion
        "User's unique identifier. The UUID string is used as identifier when sending data to Insider. UUID is required if the Anonymous Id field is empty.",
```

2023-03-10 15:47 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/trackEvent/index.ts
> +      label: 'User ID',
```suggestion
      label: 'UUID',
```

2023-03-10 15:47 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/index.ts
> +    name: 'Track Calls',
```suggestion
    name: 'Record user event to Insider',
```

2023-03-10 15:47 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/index.ts
> +    name: 'Identify Calls',
```suggestion
    name: 'Create or update a user profile',
```

2023-03-10 15:47 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/updateUserProfile/index.ts
> +  title: 'Update User Profile',
```suggestion
  title: 'Create or update a user profile',
```

2023-03-10 15:47 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/insider-helpers.ts
> +        segment_anonymous_id: data.segment_anonymous_id
Hi @recep-insider I'm wondering if you should also offer the ability to allow the customer to specify if email and phone should be treated as identifiers for this Action as well?

2023-03-14 09:30 UTC, recep-insider commented on packages/destination-actions/src/destinations/insider/insider-helpers.ts
> +        segment_anonymous_id: data.segment_anonymous_id
Hi @joe-ayoub-segment, yes we will talk with team about that. Probably we will add it.

2023-03-14 09:33 UTC, recep-insider commented
@joe-ayoub-segment I added your request but please wait my update for review because we will add one more feature. after that I will update to you for review.

2023-03-14 09:46 UTC, esezerguven commented on packages/destination-actions/src/destinations/insider/trackEvent/index.ts
> +          '@if': {
Hi @joe-ayoub-segment, I need to add one more property here. order_id cart_id or checkout_id whatever if exists we need to map it as event_group_id. how we can coalesce 3 property ?

2023-03-15 07:09 UTC, recep-insider commented
@joe-ayoub-segment hello, we are ready to CR.

2023-03-15 10:44 UTC, joe-ayoub-segment commented
Thanks @recep-insider - I'll schedule this for review.

2023-03-15 11:28 UTC, esezerguven commented on packages/destination-actions/src/destinations/insider/trackEvent/index.ts
> +          '@if': {
Hi @joe-ayoub-segment did you have change to check this. I can add this part also before cr

2023-03-20 13:27 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/trackEvent/index.ts
> +          '@if': {
Hi @esezerguven , just seeing this now - it was a public holiday yesterday. 
Did you get the answer to your question? 
if not please feel free to schedule a call with me - we won't need the full hour, but we can probably solve your question and get your PR submitted for deployment this Wednesday. 

http://calendly.com/joe_ayoub/integration-workshop

2023-03-20 13:29 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/insider/trackEvent/index.ts
> +          '@if': {
I do have a call with Emre tomorrow, if you are able to join that?

2023-03-22 09:46 UTC, esezerguven reviewed
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/70070685/226864221-c260c7e3-d450-40e2-bf47-1b91a942c5af.png">
Hello @joe-ayoub-segment We will add new presets and actions as we talked in the meeting however is this possible to make an preset default disabled and default enable like in the image

2023-03-22 10:04 UTC, joe-ayoub-segment commented
Hi @esezerguven , sounds like a good plan. 
Presets will always be enabled by default, and it's not possible to have them pre-configured to be disabled. 
If the customer wants to create a new Mapping then they can click the blue button to create a mapping from an Action or Preset. This is usually sufficient. 

Let me know if you find this too restrictive (and tell me a little more about the use-case) and I might be able to provide some more guidance. 

![image](https://user-images.githubusercontent.com/45374896/226869007-48c1ec42-bc76-4678-9eef-c16bca170b05.png)

2023-04-04 14:53 UTC, joe-ayoub-segment commented
PR review details shared via email. 
Note branch doesn't build and tests don't pass. 
Asked for the 2 separate Destinations to be submitted in separate PRs.

2023-04-04 16:38 UTC, esezerguven commented
@joe-ayoub-segment hello joe we have seperate the pull requests. Can you please review here again and inform is there anything. Thanks

2023-04-05 09:35 UTC, joe-ayoub-segment approved these changes
Feedback implemented. 
Tests pass locally. Validate passes.

2023-04-05 09:47 UTC, merged

2023-04-13 20:55 UTC, joe-ayoub-segment commented
Hi @emreisik95  this PR has been deployed. I've emailed with follow up steps.