[HEAP]: Screen event name
segmentio/action-destinations pull request #1098
Opened 2023-03-08 03:28 UTC by murphpdx

- Updated the screen view and page view event names to reduce cardinality. The cardinality of these events was causing issues for us.
- Updated the identity check to ensure that we do not set identity if userId is set to '0'. This was a customer request. 
- Updated the identify call to allow customers to configure identity. Another customer request. 
- I've also removed the unnecessary request made to our identify endpoint. The add user properties endpoint can achieve the same result as the two calls. 

## Testing

I've sent test events using the event tester `./bin/run serve` and added additional unit tests. 

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-03-08 03:29 UTC, murphpdx commented on packages/destination-actions/src/destinations/heap/heapUtils.ts
> +  if (identity && isDefined(identity)) {
keeping the identity null check to keep the linter happy.

2023-03-08 11:29 UTC, joe-ayoub-segment commented
hi @murphpdx , acknowledging this PR. I'll get it reviewed ASAP.

2023-03-09 12:43 UTC, joe-ayoub-segment requested changes
Hi @murphpdx thanks for submitting these changes. 
There is a breaking change in there which is worth addressing or it will cause an incident. I've left inline comments for you to review.

2023-03-09 12:43 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/heap/trackEvent/index.ts
> +        '@path': '$.traits'
Usually you won't find customers adding a traits object at the root of the payload of a page(), screen() or track(). Instead they usually get added in the context object. 

```suggestion
        '@path': '$.context.traits'
```

2023-03-09 12:43 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/heap/trackEvent/index.ts
> +    if (isDefined(payload.identity)) {
Hi @murphpdx , should this call to add_user_properties be necessary if the traits field is empty?

2023-03-09 12:43 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/heap/trackEvent/index.ts
> +    traits: {
Adding a new optional field is safe, as long as it's referenced defensively (which it appears to be).

2023-03-09 12:43 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/heap/identifyUser/index.ts
> +        'A unique identity and maintain user histories across sessions and devices under a single profile. If no identity is provided we will add the anonymous_id to the event. More on identify: http
hi @murphpdx the description is a little tricky to understand from a grammatical point of view. "A unique identity and maintain user histories..."

2023-03-09 12:43 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/heap/identifyUser/index.ts
> +    identity: {
hi @murphpdx this is going to create a new optional field called 'identity', which is generally safe. 

However in the perform() function below you are throwing an error if this field value is falsy. 
Customers who already have the Heap Destination configured won't have this field setting saved to our database, so this field will always resolve to undefined which will result in an error being thrown (for those customers). This will break all identify() events for those specific customers.   

Some options we have here are: 
1. If your customers are OK with this, they can 'fix' their instances of the Destination by editing and then saving the identifyUser Action. This will ensure that the field settings are saved to the DB. 
2. rework your code so that you don't need to throw an error if the identity field is undefined. I'm not sure you'll be able to do this though. 

Happy to discuss other options if you like - let me know.

2023-03-09 12:43 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/heap/identifyUser/index.ts
> +    if (!payload.identity || !isDefined(payload.identity)) {
As mentioned above, this new optional 'identity' field will resolve as undefined for pre-existing instances of the Integration, which will result in errors being thrown for all events which are processed by this Action.

2023-03-09 12:43 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/heap/trackEvent/index.ts
> +          anonymous_id: payload.anonymous_id,
In the identifyUser action you check if the payload.anoymous_id field is truthy before adding it to the payload for the add_user_properties API call. 

Should that also be done here?

2023-03-09 16:54 UTC, murphpdx commented on packages/destination-actions/src/destinations/heap/identifyUser/index.ts
> +    identity: {
I chatted with the customer to let them know that this was a possibility and they still wanted the change. Will this still result in errors being thrown if a userId exists? I've kept the default mapping to userId.

2023-03-09 19:01 UTC, murphpdx commented on packages/destination-actions/src/destinations/heap/identifyUser/index.ts
> +    if (!payload.identity || !isDefined(payload.identity)) {
The identity field defaults to userId. Is this still going to cause a breaking change? I've talked to the customer about that possibility and they're ok with it.

2023-03-09 19:03 UTC, murphpdx commented on packages/destination-actions/src/destinations/heap/trackEvent/index.ts
> +          anonymous_id: payload.anonymous_id,
We can, it was my assumption that it's always on the payload. Is that not true?

2023-03-13 16:19 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/heap/trackEvent/index.ts
> +          anonymous_id: payload.anonymous_id,
hi @murphpdx 
The anonymousId is simply a GUID created by the client side Segment libraries which is stored in a cookie/local storage. 
It's only in the payload if the event is coming from a front end device such as a browser or a mobile iOS / Android app. If the event is coming from a back end service or raw HTTP POST request it's not going to contain an anonymousId, unless the customer explicitly adds it.

2023-03-13 18:24 UTC, joe-ayoub-segment requested changes
Hi @murphpdx - some comments/questions on the code. I didn't look at the unit tests.

2023-03-13 18:24 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/heap/identifyUser/index.ts
> +    if (!payload.user_id || !isDefined(payload.user_id)) {
Hi @murphpdx - am I correct in assuming that you want this Action to start rejecting identify() events which do not contain a user_id? If so is this OK with the current customer(s) using the Integration?

2023-03-13 18:30 UTC, murphpdx commented on packages/destination-actions/src/destinations/heap/trackEvent/index.ts
> +    if (isDefined(payload.identity) && (isDefined(payload.anonymous_id) || isDefined(payload.traits))) {
Yes, the logic is intentional. That's correct, you cannot call add user properties without identity. Identity is already on the track payload so you must have identity and anon id or traits.

2023-03-13 18:33 UTC, murphpdx commented on packages/destination-actions/src/destinations/heap/identifyUser/index.ts
> +    if (!payload.user_id || !isDefined(payload.user_id)) {
Yes this is correct. We can't associate user properties or identity with a user without an identity. The previous logic was incorrect and assigned an incorrect identity to the user. Adding incorrect identities will cause problems for our customers.

2023-03-13 19:30 UTC, merged

2023-03-16 08:15 UTC, joe-ayoub-segment commented
FYI @murphpdx - the deploy didn't go out yesterday. Expecting it to happen today.

2023-03-20 18:41 UTC, joe-ayoub-segment commented
Hi @murphpdx  - this PR has been deployed. Could you let me know if it works as expected please? I'm late notifying you as it was a public holiday here on Friday.