Acoustic PR
segmentio/action-destinations pull request #1105
Opened 2023-03-11 00:23 UTC by KWLandry-acoustic

_A summary of your pull request, including the what change you're making and why._
 
Acoustic Actions Destination submission

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [X] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-03-14 13:12 UTC, joe-ayoub-segment commented
Hi @KWLandry-acoustic , acknowledging your PR. Will review ASAP.

2023-03-15 12:02 UTC, joe-ayoub-segment commented
hi @KWLandry-acoustic , unit tests are failing. 
[unit-tests-failing.txt](https://github.com/segmentio/action-destinations/files/10979365/unit-tests-failing.txt)

2023-03-15 12:54 UTC, joe-ayoub-segment commented
hi @KWLandry-acoustic , 
Could the file names and folder names be updated so that: 
1. file names are all lower cased, with dashes used as word separators. e.g. my-file-name
2. folder names should be camel case. e.g myFolderName

2023-03-15 13:16 UTC, joe-ayoub-segment requested changes
Hi Kip, 

Thanks for submitting this PR. 
Still a few things to address. Happy to chat through them. 
I provided some recommended code replacements which you should be able to accept (for the presets). 

Thanks again,
Joe

2023-03-15 15:24 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic/receiveEvents/index.ts
> +    await preChecksAndMaint(request, settings)
Hi Joe, yes I can confirm and guarantee that createSegmentEventsTable will fire only once and only if the table does not exist, so, it might only fire the one time and only ever the one time. And, it's there as a standard for the Acoustic platform, that Customers can simply delete their data in a "Relational Table" that contains data such as this, as they feel the need to eliminate  "Supporting" data to queries that is no longer relevant which can be every month in the Marketing communications world. If you note, I put Table in quotes because this shouldn't be seen as an actual Table but an asset in the Acoustic Campaign product that provides supporting data, that is not primary or critical to the data model of the product itself. 
To that, creating this asset should complete within milliseconds every single time as it's not actually provisioning anything more than a query backed by a stored procedure in an actual DB. And even then, the stored procedure is scheduled  to execute, it's not waiting on that outcome as the validation assures all is correct to accomplish the asset creation.

I've considered several other approaches, and also reviewed others code, and with more than a few integrations leveraging multiple calls I believed this simplest form would be fine.

2023-03-15 15:29 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic/index.ts
> +    settings
Hi Joe, left over fragment, resolved now,

2023-03-15 15:49 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic/Utility/EventProcessing.ts
> +export function parseSections(section: { [key: string]: string }) {
Hi Joe, I did attempt flatten, flattendeep, and one other (flattenMap perhaps) earlier however it did not return the form I needed, if I add a safety to the recurse depth would that suffice?

2023-03-16 18:04 UTC, joe-ayoub-segment requested changes

2023-03-16 18:05 UTC, joe-ayoub-segment commented
Hi @KWLandry-acoustic I sent you a video by Slack of me walking through the remaining items.

2023-03-16 18:11 UTC, KWLandry-acoustic commented
Hi Joe,
I’ve updated the code for all of the areas that you cover in the video,
Including accepting both of the code changes you provided, etc…, etc… not sure why it’s not showing in the PR, I’ll refresh and see if I can see them,
But, again, everything is 100% according to your notes of the video,

Also, all tests passed, green,

***@***.***

Thanks,
Kip

Kip W. Landry
WW Solutions Architect

[signature_1720021682]

Office: (470) 702-9731


eMail: ***@***.******@***.***>






How Can Acoustic Help?

Acoustic Support Portal<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.goacoustic.com%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216462702&sdata=XmffYkTymIzwMoCV5w6ABYoHkat4%2BMcSeamDc14WGw0%3D&reserved=0>
Acoustic Blog<https://acoustic.com/blog/>
Subscribe for Product Updates and Releases<https://acoustic.com/client-signup/>
Call Acoustic Support @ +1 866-820-5136
Feedback and Product Ideas<https://ideas.goacoustic.com/>
What's New - Product Release Notes<https://help.goacoustic.com/hc/en-us/articles/360044265174-What-s-new-in-Experience-Analytics-Tealeaf->
Acoustic Support Chat<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.goacoustic.com%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216472694&sdata=HkhAuDooUo7kjHghJeMwhglWyBjOs8WIbNukx%2FTTQPc%3D&reserved=0>
Experience Analytics: Docs<https://developer.goacoustic.com/acoustic-exp-analytics/docs>
Getting Started<https://developer.goacoustic.com/acoustic-exp-analytics/docs/getting-started>
Product Status Pages for Outages or Reduced Service<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstatus.goacoustic.com%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216452705&sdata=fO2xPbwHhO9jYYh34puH6l%2FX1EjQzkExTPWYsIcftqY%3D&reserved=0>
UICapture Tutorials<https://developer.goacoustic.com/acoustic-exp-analytics/docs#section-uic-tutorials>
Docs-Privacy Masking-Blocking Sensitive Data<https://developer.goacoustic.com/acoustic-exp-analytics/docs/privacy-masking-and-blocking-sensitive-data>

Acoustic Help Center<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.goacoustic.com%2Fhc%2Fen-us&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216462702&sdata=bF5PXJwB7PIg%2BjkAv1UKt596kyJTZcLP%2FXoW0yEO6j0%3D&reserved=0>
Acoustic Support Handbook <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Facoustic.com%2Ffiles%2F2019%2F12%2FAcoustic-Support-Handbook-v2.pdf&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216472694&sdata=VoX6Tv%2BrYzP3yFmbsk1qa0PkjzBZUcrvwFNIEGrrsJA%3D&reserved=0>

Acoustic Legal<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Facoustic.com%2Fterms-conditions%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216482690&sdata=CIXFqpWMTeccbJAZKYpEVklzACQ3bkG4MujgpQ4XIPI%3D&reserved=0>
Acoustic Billing – ***@***.***> ***@***.******@***.***>




From: Joe Ayoub ***@***.***>
Reply-To: segmentio/action-destinations ***@***.***>
Date: Thursday, March 16, 2023 at 2:05 PM
To: segmentio/action-destinations ***@***.***>
Cc: Kip Landry ***@***.***>, Mention ***@***.***>
Subject: Re: [segmentio/action-destinations] Acoustic PR (PR #1105)


Hi @KWLandry-acoustic<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKWLandry-acoustic&data=05%7C01%7CKip.Landry%40acoustic.co%7C0e9e0b3220824adca0ac08db26490b2b%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C0%7C0%7C638145867426323791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LFT21JH0qJs0xl8bbQK1QYCOVqKG42knIofu1elf%2F3E%3D&reserved=0> I sent you a video by Slack of me walking through the remaining items.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsegmentio%2Faction-destinations%2Fpull%2F1105%23issuecomment-1472468520&data=05%7C01%7CKip.Landry%40acoustic.co%7C0e9e0b3220824adca0ac08db26490b2b%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C0%7C0%7C638145867426323791%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5k4BB1tvg%2BsTao6uehW1DBwADK9B54P2%2FxeHAsGAKaY%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYV2WAFOWED5SDIY5ZS3DD3W4NI67ANCNFSM6AAAAAAVXCXK4I&data=05%7C01%7CKip.Landry%40acoustic.co%7C0e9e0b3220824adca0ac08db26490b2b%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C0%7C0%7C638145867426479991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2cRrrJA1w2uBreDAvKcdQYP3C3b8%2BNm%2Bh4zOi0U9tHY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

The information contained in this electronic message and any attachments to this message are intended for the exclusive use of the addressee(s) and may contain Acoustic proprietary, confidential or privileged information. If you are not the intended recipient, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately and destroy all copies of this message and any attachments.

2023-03-20 13:38 UTC, joe-ayoub-segment approved these changes
hi @KWLandry-acoustic I'll merge this and get it deployed. 
Tests pass. 
I do have a concern about the OAuth implementation, but's get it live and see what happens (nothing to lose!). We can chat about it once it's been deployed.

2023-03-20 14:07 UTC, merged

2023-03-20 15:08 UTC, KWLandry-acoustic commented
Hi Joe,

Thanks, appreciate the effort and getting this in,

The Auth is a concern for me as well as I can’t see it to solve it, the code is as best I can guess works with that auth mechanism, I’ll jump on testing it as soon as I see it available at the url you provided,

Thanks,
Kip

Kip W. Landry
WW Solutions Architect

[signature_1720021682]

Office: (470) 702-9731


eMail: ***@***.******@***.***>






How Can Acoustic Help?

Acoustic Support Portal<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.goacoustic.com%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216462702&sdata=XmffYkTymIzwMoCV5w6ABYoHkat4%2BMcSeamDc14WGw0%3D&reserved=0>
Acoustic Blog<https://acoustic.com/blog/>
Subscribe for Product Updates and Releases<https://acoustic.com/client-signup/>
Call Acoustic Support @ +1 866-820-5136
Feedback and Product Ideas<https://ideas.goacoustic.com/>
What's New - Product Release Notes<https://help.goacoustic.com/hc/en-us/articles/360044265174-What-s-new-in-Experience-Analytics-Tealeaf->
Acoustic Support Chat<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.goacoustic.com%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216472694&sdata=HkhAuDooUo7kjHghJeMwhglWyBjOs8WIbNukx%2FTTQPc%3D&reserved=0>
Experience Analytics: Docs<https://developer.goacoustic.com/acoustic-exp-analytics/docs>
Getting Started<https://developer.goacoustic.com/acoustic-exp-analytics/docs/getting-started>
Product Status Pages for Outages or Reduced Service<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstatus.goacoustic.com%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216452705&sdata=fO2xPbwHhO9jYYh34puH6l%2FX1EjQzkExTPWYsIcftqY%3D&reserved=0>
UICapture Tutorials<https://developer.goacoustic.com/acoustic-exp-analytics/docs#section-uic-tutorials>
Docs-Privacy Masking-Blocking Sensitive Data<https://developer.goacoustic.com/acoustic-exp-analytics/docs/privacy-masking-and-blocking-sensitive-data>

Acoustic Help Center<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.goacoustic.com%2Fhc%2Fen-us&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216462702&sdata=bF5PXJwB7PIg%2BjkAv1UKt596kyJTZcLP%2FXoW0yEO6j0%3D&reserved=0>
Acoustic Support Handbook <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Facoustic.com%2Ffiles%2F2019%2F12%2FAcoustic-Support-Handbook-v2.pdf&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216472694&sdata=VoX6Tv%2BrYzP3yFmbsk1qa0PkjzBZUcrvwFNIEGrrsJA%3D&reserved=0>

Acoustic Legal<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Facoustic.com%2Fterms-conditions%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216482690&sdata=CIXFqpWMTeccbJAZKYpEVklzACQ3bkG4MujgpQ4XIPI%3D&reserved=0>
Acoustic Billing – ***@***.***> ***@***.******@***.***>




From: Joe Ayoub ***@***.***>
Reply-To: segmentio/action-destinations ***@***.***>
Date: Monday, March 20, 2023 at 9:38 AM
To: segmentio/action-destinations ***@***.***>
Cc: Kip Landry ***@***.***>, Mention ***@***.***>
Subject: Re: [segmentio/action-destinations] Acoustic PR (PR #1105)


@joe-ayoub-segment approved this pull request.

hi @KWLandry-acoustic<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKWLandry-acoustic&data=05%7C01%7CKip.Landry%40acoustic.co%7Cd2770d7a7afe48bf02a508db29486338%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C0%7C0%7C638149163115540987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9RJPObFfdh4WE0H4u7PwvOHe4pb7qHHEwIn2pLvTAfc%3D&reserved=0> I'll merge this and get it deployed.
Tests pass.
I do have a concern about the OAuth implementation, but's get it live and see what happens (nothing to lose!). We can chat about it once it's been deployed.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsegmentio%2Faction-destinations%2Fpull%2F1105%23pullrequestreview-1348570338&data=05%7C01%7CKip.Landry%40acoustic.co%7Cd2770d7a7afe48bf02a508db29486338%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C0%7C0%7C638149163115697209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S947xnR60%2B0RZqEywQ9wYE8N57qnoiErd5xuncwZV34%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYV2WAHEIUZOL3YSNVLEHLDW5BMVHANCNFSM6AAAAAAVXCXK4I&data=05%7C01%7CKip.Landry%40acoustic.co%7Cd2770d7a7afe48bf02a508db29486338%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C0%7C0%7C638149163115697209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R8EVKPQDrR0VYE2il2Ch7hkE00czckfL%2Bax2AoUF7%2B4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

The information contained in this electronic message and any attachments to this message are intended for the exclusive use of the addressee(s) and may contain Acoustic proprietary, confidential or privileged information. If you are not the intended recipient, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately and destroy all copies of this message and any attachments.

2023-03-23 08:15 UTC, joe-ayoub-segment commented
FYI @KWLandry-acoustic we didn't get the deploy finished yesterday. Expecting to complete it today.

2023-03-24 13:19 UTC, joe-ayoub-segment commented
hi @KWLandry-acoustic , the deployment completed but there was a misconfiguration which has caused it to not work. 
I've raised a PR to have this fixed. The fix will go out Wednesday next week. 
Apologies for the delay.

2023-03-26 22:21 UTC, KWLandry-acoustic commented
Hey Joe,
Thanks for the info., we’ll take a look Wednesday and let you know how it looks,

Thanks,
Kip

(Please Note: I will be out of Office Mar 22-24th returning Monday Mar 27th.
If there is a critical need please reach out to Mike Larkin,  ***@***.***)

Kip W. Landry
WW Solutions Architect

[signature_1720021682]

Office: (470) 702-9731


eMail: ***@***.******@***.***>






How Can Acoustic Help?

Acoustic Support Portal<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.goacoustic.com%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216462702&sdata=XmffYkTymIzwMoCV5w6ABYoHkat4%2BMcSeamDc14WGw0%3D&reserved=0>
Acoustic Blog<https://acoustic.com/blog/>
Subscribe for Product Updates and Releases<https://acoustic.com/client-signup/>
Call Acoustic Support @ +1 866-820-5136
Feedback and Product Ideas<https://ideas.goacoustic.com/>
What's New - Product Release Notes<https://help.goacoustic.com/hc/en-us/articles/360044265174-What-s-new-in-Experience-Analytics-Tealeaf->
Acoustic Support Chat<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.goacoustic.com%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216472694&sdata=HkhAuDooUo7kjHghJeMwhglWyBjOs8WIbNukx%2FTTQPc%3D&reserved=0>
Experience Analytics: Docs<https://developer.goacoustic.com/acoustic-exp-analytics/docs>
Getting Started<https://developer.goacoustic.com/acoustic-exp-analytics/docs/getting-started>
Product Status Pages for Outages or Reduced Service<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstatus.goacoustic.com%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216452705&sdata=fO2xPbwHhO9jYYh34puH6l%2FX1EjQzkExTPWYsIcftqY%3D&reserved=0>
UICapture Tutorials<https://developer.goacoustic.com/acoustic-exp-analytics/docs#section-uic-tutorials>
Docs-Privacy Masking-Blocking Sensitive Data<https://developer.goacoustic.com/acoustic-exp-analytics/docs/privacy-masking-and-blocking-sensitive-data>

Acoustic Help Center<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.goacoustic.com%2Fhc%2Fen-us&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216462702&sdata=bF5PXJwB7PIg%2BjkAv1UKt596kyJTZcLP%2FXoW0yEO6j0%3D&reserved=0>
Acoustic Support Handbook <https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Facoustic.com%2Ffiles%2F2019%2F12%2FAcoustic-Support-Handbook-v2.pdf&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216472694&sdata=VoX6Tv%2BrYzP3yFmbsk1qa0PkjzBZUcrvwFNIEGrrsJA%3D&reserved=0>

Acoustic Legal<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Facoustic.com%2Fterms-conditions%2F&data=02%7C01%7CKip.Landry%40acoustic.com%7Ceceef009d0964a47cf7d08d84068d149%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C1%7C0%7C637330166216482690&sdata=CIXFqpWMTeccbJAZKYpEVklzACQ3bkG4MujgpQ4XIPI%3D&reserved=0>
Acoustic Billing – ***@***.***> ***@***.******@***.***>




From: Joe Ayoub ***@***.***>
Reply-To: segmentio/action-destinations ***@***.***>
Date: Friday, March 24, 2023 at 9:19 AM
To: segmentio/action-destinations ***@***.***>
Cc: Kip Landry ***@***.***>, Mention ***@***.***>
Subject: Re: [segmentio/action-destinations] Acoustic PR (PR #1105)


hi @KWLandry-acoustic<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKWLandry-acoustic&data=05%7C01%7CKip.Landry%40acoustic.co%7C2b6181d9cd184766c39808db2c6a66c9%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C0%7C0%7C638152607775228375%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W8r8kQW5vC5KLhXPfGZ%2FVQGVDXE8rKm0PG9W0Jglvzg%3D&reserved=0> , the deployment completed but there was a misconfiguration which has caused it to not work.
I've raised a PR to have this fixed. The fix will go out Wednesday next week.
Apologies for the delay.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsegmentio%2Faction-destinations%2Fpull%2F1105%23issuecomment-1482785748&data=05%7C01%7CKip.Landry%40acoustic.co%7C2b6181d9cd184766c39808db2c6a66c9%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C0%7C0%7C638152607775228375%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JAZLgUe59MwImWWlPB3pDdbSuoqmYaoo%2B4wjPDUJbT4%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYV2WAHJNMHUVSJS6EF53Z3W5WNODANCNFSM6AAAAAAVXCXK4I&data=05%7C01%7CKip.Landry%40acoustic.co%7C2b6181d9cd184766c39808db2c6a66c9%7Cf0030524e8c84a4cbfecc0ab47d0f517%7C0%7C0%7C638152607775228375%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=polTmTSwQlgnWHs%2BRXMBRMLGM68RI2ke6B93poIMAIY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

The information contained in this electronic message and any attachments to this message are intended for the exclusive use of the addressee(s) and may contain Acoustic proprietary, confidential or privileged information. If you are not the intended recipient, you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately and destroy all copies of this message and any attachments.