[WIP] June destination
segmentio/action-destinations pull request #1110
Opened 2023-03-14 15:42 UTC by ferrucc-io

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-03-14 18:41 UTC, joe-ayoub-segment commented
hi @ferrucc-io , acknowledging this PR. 
As with any new Integration (or rewrite of an existing Integration) I'd like to ask you to schedule a call with me so we can run through the use-cases for this Integration. I'd also like to understand the types of events which will be sent from Segment to June, as well as the identifiers to be included in the events. 

Would you be OK scheduling a call with me via [this Calendly link](http://calendly.com/joe_ayoub/integration-workshop) please?

2023-03-14 19:43 UTC, ferrucc-io commented
Just scheduled a call for Thursday

2023-03-16 14:11 UTC, joe-ayoub-segment requested changes

2023-03-16 14:11 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/june/track/index.ts
> +        context: payload.context,
recommend a new field specifically for groupId. You could then merge in the value for this field (in the perform function) into the context object.

2023-03-16 14:14 UTC, joe-ayoub-segment approved these changes

2023-03-16 14:16 UTC, joe-ayoub-segment commented
June API is practically identical to the Segment API. 
Each Action is very simple and has presets available. 
Only recommendation (which will be done in a further PR) would be to add a specific field for groupId for both track() and page() calls.

2023-03-16 16:58 UTC, ferrucc-io commented
Interestingly I get an empty diff
![Screenshot 2023-03-16 at 17 57 47](https://user-images.githubusercontent.com/8315559/225695334-e08d8355-a176-4a8a-82c1-c7346c4bf5ad.png)

2023-03-16 18:12 UTC, joe-ayoub-segment commented
I think the issue relates to timestamps being executed in different timezones. When you run the tests they pass, but our CI is running in a different timezone....

2023-03-17 08:45 UTC, ferrucc-io commented
@joe-ayoub-segment just fixed it by running

```
TZ=UTC yarn jest --testPathPattern='./packages/destination-actions/src/destinations/june' --updateSnapshot
```

Basically snapshots need to have the correct timezone and it can be configured as an env variable

2023-03-20 13:56 UTC, joe-ayoub-segment commented
hi @ferrucc-io , the tests still fail for me unfortunately. 
These are the same tests which are run by CI, so it won't be possible to specify a variable when running. 

Is there another way you can fix this test?

2023-03-21 17:57 UTC, merged

2023-03-21 17:58 UTC, joe-ayoub-segment commented
Hi @ferrucc-io , 
I pushed a change to your fork which updated this PR. The change forces the tests to ignore the timestamp. 
PR is now merged and should be deployed this week.

2023-03-23 11:23 UTC, ferrucc-io commented
Awesome thanks for your help!

2023-03-23 12:17 UTC, joe-ayoub-segment commented
FYI @ferrucc-io the deploy didn't complete yesterday. Expecting to deploy this today.