[Salesforce] Delete operation
segmentio/action-destinations pull request #1155
Opened 2023-04-05 22:37 UTC by nick-Ag

This PR implements the Salesforce delete operation for every action. The operation will lookup a record given some traits and if that record exists, call the delete endpoint using it's Id. This is being added to reach feature parity with the Salesforce (Classic) integration, which allows deletions.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x] [Segmenters] Tested in the staging environment

The Delete operation being triggered:
<img width="1576" alt="Screenshot 2023-04-05 at 3 31 13 PM" src="https://user-images.githubusercontent.com/27820201/230226697-2754fe13-72d8-4ea8-a9c6-328cc9a0de0f.png">

The record being looked up for deletion:
<img width="1165" alt="Screenshot 2023-04-05 at 3 30 43 PM" src="https://user-images.githubusercontent.com/27820201/230226871-999d8ef5-fb83-49e8-9cd5-a4c8673be674.png">

The record is deleted:
<img width="1169" alt="Screenshot 2023-04-05 at 3 31 24 PM" src="https://user-images.githubusercontent.com/27820201/230226829-29fcc47a-0acb-4770-9949-6a8625860879.png">

2023-04-06 18:22 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/__tests__/lead.test.ts
> +    it('should delete a lead record given an Id', async () => {
Can we add tests for all Salesforce object types, in addition to `Lead`? Thanks, @nick-Ag !

2023-04-06 18:23 UTC, brennan requested changes
Can we add tests for all Salesforce object types, in addition to Lead? Thanks, @nick-Ag !

2023-04-06 20:58 UTC, nick-Ag commented
Hey @brennan , added those tests. Adding the `customObject` test revealed that the `customFields` field was required even for the delete operation, where it shouldn't be needed. So I made that field not required and only conditionally throw an error if it is not included when the operation is `create, update, upsert`. I stage tested and all looks good! Thanks for the testing suggestion.

Custom Fields required for custom action when operation is create:
<img width="1576" alt="Screenshot 2023-04-06 at 1 54 27 PM" src="https://user-images.githubusercontent.com/27820201/230492378-665d7d82-05a3-4fe3-8691-6ddf31271560.png">

No Custom Fields defined on this custom action, delete operation works fine:
<img width="1571" alt="Screenshot 2023-04-06 at 1 54 07 PM" src="https://user-images.githubusercontent.com/27820201/230492542-11cd8c12-67b9-48b8-b94e-335162a2020c.png">

2023-04-11 21:59 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/__tests__/opportunity.test.ts
> +    it('should delete an opprotunity record given an Id', async () => {
```suggestion
    it('should delete an opportunity record given an Id', async () => {
```

2023-04-11 21:59 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/__tests__/opportunity.test.ts
> +    it('should delete an opprotunity record given some lookup traits', async () => {
```suggestion
    it('should delete an opportunity record given some lookup traits', async () => {
```

2023-04-11 22:02 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/customObject/index.ts
> +      throw new Error('Custom fields are required for this operation.')
I think this should be an `IntegrationError`, similar to the other custom errors in Salesforce (Actions).

2023-04-11 22:02 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/customObject/index.ts
> +      throw new Error('Custom fields are required for this operation.')
Should be an `IntegrationError`, similar to the other custom errors in Salesforce (Actions).

2023-04-12 01:09 UTC, brennan approved these changes

2023-04-12 18:37 UTC, merged