Removed Action Name and Action Key and Action Description and introduced segment user id
segmentio/action-destinations pull request #1157
Opened 2023-04-06 14:48 UTC by gautamLL

_This PR removes action_key, action_name and action_description. Clients would not need to send action_key now which was mandatory, livelike will create the key automatically on their end so that clients don't have to make any changes to their existing integration._

## Testing
- [✓]Tested locally using Actions Tester.
- [✓]Removed actions tests for action_key 
- [✓]Added tests for  custom_id, user_id and livelike_profile_id
- [ ] [Segmenters] Tested in the staging environment

2023-04-11 12:22 UTC, joe-ayoub-segment commented
Thanks for raising this PR @gautamLL , I'll schedule it for review.

2023-04-11 14:27 UTC, joe-ayoub-segment requested changes
hi @gautamLL , 
The only potential issue I see is that you're introducing some new 'required' fields. 
This will break all existing instances of the Integration. 
However if you don't have any customers using the Integration we can let this through. 

Please clarify. 
Kind regads,
Joe

2023-04-11 14:27 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/livelike-cloud/trackEvent/index.ts
>        required: true,
Hi @gautamLL , 
Looks like you are adding a new required field to this Integration. 
That's something that will cause all pre-existing instances of the Integration to break. 
If you have any customers using the Integration, their Integrations will stop working. 
The customers would then have to create new instances of the Integration. 

If you don't have any customers using the Integrations already then we should be OK to let this change through. 
Please confirm. 
Kind regards,
Joe

2023-04-11 14:27 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/livelike-cloud/trackEvent/index.ts
> +      required: true,
note: this is adding another required field. If no customers are currently using the Integration we should be OK. Please confirm

2023-04-12 09:04 UTC, joe-ayoub-segment approved these changes

2023-04-12 09:05 UTC, joe-ayoub-segment commented
Partner confirmed that no customers are using this Integration. So OK to add new required fields.

2023-04-12 17:12 UTC, joe-ayoub-segment commented
Hi @gautamLL ,
There was an issue which caused the CI to break. It wasn't something your change did, but you'll need to pull in the latest files from segmentio/action-destinations main branch before your PR will pass CI. Can you do this please?
Cheers,
Joe

2023-04-13 09:03 UTC, gautamLL commented
Hi Joe
I just pull the latest changes and push that commit
Please let me know if any other thing is needed.
Thanks
Gautam Aggrawal

On Wed, Apr 12, 2023 at 10:42 PM Joe Ayoub ***@***.***> wrote:

> Hi @gautamLL <https://github.com/gautamLL> ,
> There was an issue which caused the CI to break. It wasn't something your
> change did, but you'll need to pull in the latest files from
> segmentio/action-destinations main branch before your PR will pass CI. Can
> you do this please?
> Cheers,
> Joe
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/segmentio/action-destinations/pull/1157#issuecomment-1505632149>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6YUGAL5A5KW5ME2XD6ZAILXA3O77ANCNFSM6AAAAAAWVQK2DE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-13 10:12 UTC, merged

2023-04-13 12:23 UTC, joe-ayoub-segment commented
Thanks @gautamLL , we'll get this out with our next deploy.

2023-04-13 20:53 UTC, joe-ayoub-segment commented
Hi @gautamLL this PR has been deployed. Please let me know if you are happy with the change.