[Podscribe] Add new destination
segmentio/action-destinations pull request #1166
Opened 2023-04-11 19:39 UTC by pitronalldak

This PR adds Podscribe as a new destination.
Podscribe is a verification and measurement company for advertising in podcasts.
For now we would handle the destination for 3 user actions _view_, _signup_, _purchase_

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-04-12 07:46 UTC, joe-ayoub-segment requested changes
Hi @pitronalldak , 
Thanks for raising this PR! 
Given that this is for a new Integration, would you be OK scheduling a call with me so I can get some background information about the use-cases for this Integration please?

I've got some questions and suggestions I'd like to run by you as well, specifically regarding identifiers and the types of 'track()' events you want to handle (in specific ways). 

You can schedule a call with me via this Calendly link: http://calendly.com/joe_ayoub/integration-workshop 

I look forward to hearing from you.
Joe

2023-04-12 07:46 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/podscribe/page/index.ts
> +      description: 'The if of the device sending the event.',
```suggestion
      description: 'The IP address of the device sending the event.',
```

2023-04-12 07:46 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/podscribe/index.ts
> +  name: 'Podscribe',
```suggestion
  name: 'Podscribe (Actions)',
```

2023-04-12 07:46 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/podscribe/track/index.ts
> +    }
hi @pitronalldak , 
There's a better way to do this using Presets. 
I can explain on a call.

2023-04-13 21:10 UTC, pitronalldak commented on packages/destination-actions/src/destinations/podscribe/track/index.ts
> +    }
@joe-ayoub-segment, thank you very much for your feedback.

The presets look fantastic. I have rewritten this part using them. Please let me know what you think.

Best regards.

2023-04-14 15:02 UTC, joe-ayoub-segment commented
Meeting notes from PR review session 

    email: {
      type: 'string',
      format: 'email',
      allowNull: true,
      description: 'email address of the user',
      label: 'Email address',
      default: {
        '@if': {
          exists: { '@path': '$.context.traits.email' },
          then: { '@path': '$.context.traits.email' },
          else: { '@path': '$.properties.email' }
        }
      }
    }

IP address should be required

    ip: {
      label: 'Ip',
      type: 'string',
      description: 'The IP address of the device sending the event.',
      required: true,
      default: {
        '@path': '$.context.ip'
      }
    },

event_type field change

    event_type: {
      type: 'string',
      required: true,
      description: 'Type of event to send',
      label: 'Event type',
      default: { '@path': '$.properties.event_type' }
    }

2023-04-14 17:00 UTC, pitronalldak commented
@joe-ayoub-segment Thank you for going through the Podscribe integration with me today.

I made several changes as you suggested.

However, I realized that I explained one thing incorrectly. 
We actually expect the client to send events:

**purchase**
```
analytics.track('Order Completed', {
  order_id: '50314b8e9bcf000000000000',
  total: 27.50,
  coupon: 'hasbros',
  currency: 'USD',
});
```

**signup**
```
analytics.track('Signed Up', {
 some_props: {}
});
```

To handle this scenario and eliminate the need for a `switch ... case ... `statement, I made two changes: 

- presets: https://github.com/segmentio/action-destinations/pull/1166/files#diff-9fcc98611453d5c9074b0de807d1486274ff7b6bafcacfccef8094bb5fb66fd1R7

- the custom field `podscribeEvent`:
https://github.com/segmentio/action-destinations/pull/1166/files#diff-8d7589419d9878d561aee6c571b1432f24361b6273ff9a0dbe82063756dd3556R96

Please let me know if you have any concerns about these changes.

2023-04-17 12:42 UTC, joe-ayoub-segment requested changes
Hi @pitronalldak , 
Just did a quick review. Didn't check that tests passed though so please make sure they do. 
Got a few recommendations, see inline comments. 
Thank you!
Joe

2023-04-17 12:42 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/podscribe/index.ts
> +  }
Consider adding a preset for page() events. 

```suggestion
  },
    {
    name: 'Page Calls',
    subscribe: 'type = "page"',
    partnerAction: 'page',
    mapping: defaultValues(page.fields)
  }
```

2023-04-17 12:42 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/podscribe/track/index.ts
> +      label: 'Ip',
```suggestion
      label: 'User IP address',
```

2023-04-17 12:42 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/podscribe/track/index.ts
> +    },
Consider adding the following, as you seem to reference specific sub fields in the perform() function: 

```suggestion
    properties: {
      label: 'Event properties',
      description: 'Properties to send with the event',
      type: 'object',
      additionalProperties: true,
      properties: {
        order_value: {
          label: 'Order Value',
          type: 'number',
          description: 'The total value of the order'
        },
        order_number: {
          label: 'Order Number',
          type: 'string',
          description: 'The order ID. A unique identifier for the order'
        }
        currency: {
          label: 'Currency',
          type: 'string',
          description: 'Currency code. e.g. USD for US dollar, EUR for Euro'
        }
        coupon: {
          label: 'Coupon',
          type: 'string',
          description: 'Coupon Code. A Discount code for the purchase'
        }
        num_items_purchased: {
          label: 'Number of Items Purchased',
          type: 'integer',
          description: 'The number of items purchased in this order'
        }
        is_new_customer: {
          label: 'Is New Customer',
          type: 'boolean',
          description: 'true value Indicates if the user is a new customer'
        },
        is_subscription: {
          label: 'Is Subscription',
          type: 'boolean',
          description: 'true value Indicates a subscription'
        },
      },
      default: {
        order_value: { '@path': '$.properties.order_value' },
        order_number: { '@path': '$.properties.order_number' },
        currency: { '@path': '$.properties.currency' },
        coupon: { '@path': '$.properties.coupon' },
        num_items_purchased: { '@path': '$.properties.num_items_purchased' },
        is_new_customer: { '@path': '$.properties.is_new_customer' },
        is_subscription: { '@path': '$.properties.is_subscription' }
      }
    }
```

2023-04-17 12:42 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/podscribe/page/index.ts
> +      type: 'string',
Should this field be required?

2023-04-17 16:43 UTC, pitronalldak commented
@joe-ayoub-segment  
Thank you, I appreciate the feedback. All suggestions are very helpful - updated.

2023-04-17 16:43 UTC, pitronalldak commented on packages/destination-actions/src/destinations/podscribe/page/index.ts
> +      type: 'string',
Thanks, updated

2023-04-17 17:10 UTC, joe-ayoub-segment commented
Hi @pitronalldak , 
Just a couple minor things to fix - tests are breaking so snapshots need to be updated. I've got a push ready here if you grant me permission to your repo?

2023-04-17 17:11 UTC, joe-ayoub-segment requested changes

2023-04-17 17:53 UTC, pitronalldak commented
@joe-ayoub-segment 
- Granted you permissions
- Fixed typos

All tests passed for me, what I am missing?

2023-04-18 11:55 UTC, joe-ayoub-segment approved these changes
Looks good. Tests passed locally.

2023-04-18 11:57 UTC, joe-ayoub-segment commented
hi @pitronalldak , PR approved. Just waiting on CI to pass.

2023-04-18 14:07 UTC, pitronalldak commented
@joe-ayoub-segment  Thank you!

The last step in the CI process failed. Is there anything I can do to fix it?

2023-04-18 19:30 UTC, merged

2023-04-19 19:36 UTC, joe-ayoub-segment commented
Hi @pitronalldak this PR has been deployed.