[Usermaven] Destination
segmentio/action-destinations pull request #1171
Opened 2023-04-12 11:40 UTC by seeratawan01

_This PR add the [Usermaven](https://usermaven.com/) destination._

## Testing
Tested all actions and endpoint and it seems like all data gets through correctly:
![image](https://user-images.githubusercontent.com/26021449/231445408-238752e5-563a-453b-a005-5fc6c9fcfbcd.png)

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-04-12 11:54 UTC, joe-ayoub-segment commented
Hi @seeratawan01 thanks for raising this PR. 
Looks like this is for a new Integration. Would you be able to schedule a call with me so I can get an understanding of the key use-cases you want to support with this Integration? I'm also interested in discussing the types of data you want to send to your platform, as well as the identifiers to be passed. 

You can schedule a call with me using this Calendly link: http://calendly.com/joe_ayoub/integration-workshop

I look forward to hearing from you, 
Joe

2023-04-13 08:59 UTC, azhard4int commented
> Hi @seeratawan01 thanks for raising this PR. Looks like this is for a new Integration. Would you be able to schedule a call with me so I can get an understanding of the key use-cases you want to support with this Integration? I'm also interested in discussing the types of data you want to send to your platform, as well as the identifiers to be passed.
> 
> You can schedule a call with me using this Calendly link: http://calendly.com/joe_ayoub/integration-workshop
> 
> I look forward to hearing from you, Joe

We have booked a time for Monday. Looking forward.

2023-04-17 11:49 UTC, joe-ayoub-segment requested changes
A few comments inline.

2023-04-17 11:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/usermaven/common-definitions.ts
> +  user: {
// email
    default: {
      '@if': {
        exists: { '@path': '$.traits.email' },
        then: { '@path': '$.traits.email' },
        else: { '@path': '$.properties.email' }
      }
    }
    
// first_name
    default: {
      '@if': {
        exists: { '@path': '$.traits.first_name' },
        then: { '@path': '$.traits.first_name' },
        else: { '@path': '$.properties.first_name' }
      }
    }

// last_name
    default: {
      '@if': {
        exists: { '@path': '$.traits.last_name' },
        then: { '@path': '$.traits.last_name' },
        else: { '@path': '$.properties.last_name' }
      }
    }

// user_created_at
    default: {
      '@if': {
        exists: { '@path': '$.traits.user_created_at' },
        then: { '@path': '$.traits.user_created_at' },
        else: { '@path': '$.properties.user_created_at' }
      }
    }

2023-04-17 11:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/usermaven/request-params.ts
> +    event_id: '',
consider adding a new field called event_id and mapping the default to:
'$.messageId'

2023-04-17 11:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/usermaven/track/index.ts
> +    ...commonFields
Add email as a specific field here. and remove from common fields

    email: {
      type: 'string',
      required: false,
      description: 'The user email address',
      label: 'Email address',
      default: {
        '@if': {
          exists: { '@path': '$.properties.email' },
          then: { '@path': '$.properties.email' },
          else: { '@path': '$.context.traits.email' }
        }
      }
    },

2023-04-17 11:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/usermaven/identify/index.ts
> +    ...commonFields
Add email as a field here, and remove from commonFields. 

    email: {
      type: 'string',
      required: true,
      description: 'The user email address',
      label: 'Email address',
      default: {'@path': '$.traits.email'} 
    },

2023-04-17 11:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/usermaven/request-params.ts
> +  if (payload?.context?.screen) {
Add a more defensive check for width and height to prevent null pointers.

2023-04-17 11:55 UTC, joe-ayoub-segment commented
Summary of feedback from PR: 
3 actions
Needs presets
perform() handler shared by all 3 Actions, which is OK, but validation on some data in the perform() could be a bit cleaner
Recommended refactoring some fields. 
User profile fields should split out from an user object
Company profile fields should be split out from a company object
Defaults need to be corrected
Descriptions need to be added for every Action
Descriptions should be added for all fields

2023-04-18 08:39 UTC, seeratawan01 commented
@joe-ayoub-segment we performed the requested changes, please review

2023-04-18 10:13 UTC, joe-ayoub-segment commented
Thank you @seeratawan01 I'll review now.

2023-04-18 10:30 UTC, joe-ayoub-segment requested changes
Hi @seeratawan01 , just a couple of minor items left. See inline

2023-04-18 10:30 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/usermaven/common-definitions.ts
> +    label: 'Referer',
```suggestion
    label: 'Referrer',
```

2023-04-18 10:30 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/usermaven/track/index.ts
> +    },
```suggestion
    event_attributes: {
      type: 'object',
      required: false,
      description: 'Attributes associated with the event',
      label: 'Event Attributes',
      default: { '@path': '$.properties' }
    },
```

2023-04-18 10:50 UTC, seeratawan01 commented
@joe-ayoub-segment done with the changes, thanks for the review.

2023-04-18 11:33 UTC, joe-ayoub-segment approved these changes
Thanks for making the update. Let's get this deployed so you can test.

2023-04-18 11:33 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/usermaven/common-definitions.ts
> +    description: 'Anonymous id',
```suggestion
    description: 'User Anonymous id',
```

2023-04-18 11:52 UTC, seeratawan01 commented on packages/destination-actions/src/destinations/usermaven/common-definitions.ts
> +    description: 'Anonymous id',
done

2023-04-18 12:36 UTC, azhard4int commented
@joe-ayoub-segment Will this be deployed today?

2023-04-18 19:29 UTC, merged

2023-04-19 19:38 UTC, joe-ayoub-segment commented
Hi @seeratawan01 this PR has now been deployed.