RevX Destination
segmentio/action-destinations pull request #1210
Opened 2023-04-26 07:50 UTC by asifrahiman

_Adding RevX destination to allow clients to send event data to RevX_

## Testing
- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-04-28 16:08 UTC, varadarajan-tw commented
Thank you for raising this PR! This seems like a net new destination. Our Partner Engineer will review this PR when he is back from PTO after 8th May.

2023-05-08 12:04 UTC, joe-ayoub-segment commented
hi @asifrahiman , 
Thanks for raising this PR. I was on PTO the last 2 weeks but am back now. 
For new Integrations I usually ask for a face to face meeting to review the use-cases, data being collected and identifiers. 
Would you be available to catch up?
You can schedule a call with me using this Calendly [link](http://calendly.com/joe_ayoub/integration-workshop). 

Best regards,
Joe

2023-05-09 09:44 UTC, joe-ayoub-segment reviewed
I did a quick review of the PR prior to our call later this week.

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    },
If the client_id is a global setting, it might be worth having this setting stored in the main destination.authentication.fields in the root index.ts file. 

Let's discuss when we meet.

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    },
the detault path at '$.context.device.type' will only contain a value when the event originates from a Mobile Device. 

Web and server side Segment SDKs will not provide any value at this location. 

Again let's discuss when we meet.

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +          else: { '@path': '$.context.device.idfa' }
Note: I've never seen the advertising Id being sent from this location in a Segment payload.

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    },
These 2 fields have the same label, which will confuse customers. I understand why you did it though - track() event payloads have the event name at '$.event' while page() event payloads have the page name at '$.name'. 

I'd recommend having a single field, and then doing something like this: 

'@if': {
          exists: { '@path': '$.event' },
          then: { '@path': '$.event' },
          else: { '@path': '$.name' }
          }

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    },
These 2 fields might be a bit confusing for customers. 
I take it the idfv is intended for iOS events only, and the device_id field is intended for Android?

Let's chat about this when we meet.

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    },
User traits can be located in a couple of different places in a Segment event. 

For identify() and group() calls you will find these values in the '$.traits' location.
For track() and page() calls you will find these values in the '$.context.traits' location.

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    },
Note: '$.context.app.version' will only be populated if the event originates from a mobile device. You won't get it from web or server side Segment SDKs

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    },
These fields will only be populated when the event originates from a Mobile device. You won't get them from web or server side Segment SDKs

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +        'The IP address of the user. Use "$remote" to use the IP address on the upload request. Amplitude will use the IP address to reverse lookup a user\'s location (city, country, region, and DMA)
Why is there a reference to Amplitude in this field description? Could be a typo?

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    },
Let's discuss why you decided to derive revenue when price and quantity fields are present. It might not be the most intuitive way to collect this information.

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    }
Why have this field defined at all? Is it needed?

2023-05-09 09:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +      json: data.payload
Looks like you are not doing any data manipulation before sending the payload to your platform. 
Let's discuss when we meet.

2023-05-09 09:44 UTC, joe-ayoub-segment reviewed
I did a quick review of the PR prior to our call later this week.

2023-05-09 10:58 UTC, asifrahiman commented
Hi @joe-ayoub-segment 
We have booked for a slot on friday evening 6:30pm. However would it be possible to schedule the call today or tomorrow as our client integration is pending since 1 week. We would like to take this up on urgent basis.

2023-05-10 09:58 UTC, joe-ayoub-segment commented
Hi @asifarahiman , unfortunately I don't have a timeslot available before Friday, I'm sorry.

2023-05-12 13:28 UTC, joe-ayoub-segment commented
Please add a preset. Here's the code to use: 

```
  authentication: {
    scheme: 'custom',
    fields: {
      client_id: {
        label: 'Revx Client ID',
        description: 'Revx specific client id. This can be found by contacting the RevX support team',
        type: 'string',
        required: true
      }
    }
  },
  presets: [
    {
      name: 'Send Revx Ping',
      subscribe: 'type = "track"',
      partnerAction: 'sendRevxPing',
      mapping: defaultValues(sendRevxPing.fields)
    }
  ],
  actions: {
    sendRevxPing
  }
}
```

2023-05-12 15:18 UTC, asifrahiman commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    }
@joe-ayoub-segment When converting data to type hidden we are getting the error "Data must be a string but it was an object.". Hence leaving it as object type

2023-05-12 16:08 UTC, asifrahiman commented
@joe-ayoub-segment We have updated the PR as per the review comments. Do let us know if any more changes are required.  If possible lets fast track the process as our client integration is pending due to this. 
Thank You

2023-05-15 10:02 UTC, joe-ayoub-segment requested changes

2023-05-15 10:02 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    },
You will need to remove the client_id from the Action as it's now being set in the Destination instead.

2023-05-15 10:27 UTC, asifrahiman commented on packages/destination-actions/src/destinations/revx/index.ts
> +      partnerAction: 'sendRevxPing'
Added defaultValues mapping

2023-05-15 10:27 UTC, asifrahiman commented on packages/destination-actions/src/destinations/revx/index.ts
> +  name: 'RevX',
Updated the name as per comment

2023-05-15 10:27 UTC, asifrahiman commented on packages/destination-actions/src/destinations/revx/index.ts
> +      subscribe: 'type = "identify" or type ="page"',
Updated as per comment

2023-05-15 10:29 UTC, asifrahiman commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +          else: { '@path': '$.context.device.idfa' }
Done

2023-05-15 10:29 UTC, asifrahiman commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +    }
Done

2023-05-15 10:34 UTC, asifrahiman commented
> Hi @asifrahiman , There's still a few thing that need to be addressed before I can approve / merge this PR.
> 
> Also, when we met you mentioned that you might like to send Audience data to your platform. If you want to do this you'll need to create a completely separate Destination which handles identify() calls in a very specific way. I'm happy to chat with you about this if you like. Please let me know.

We have updated the PR as per the final review comments. Do let us know if we have missed out anything. We will proceed with this integration as its sort of urgent for us and we have pressure from sales team as our client integration is pending because of this. We will raise a separate PR for the audience part. We can have a meeting for that when you are free.

2023-05-15 10:57 UTC, joe-ayoub-segment requested changes
Couple minor things - see inline. 

Also, can you make sure this command passes please?

yarn validate

It's failing as there was an issue with Tiktok's Destination when you forked. It's been fixed but you will need to pull over more recent files from the main repository

2023-05-15 10:57 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +              '@path': 'productId'
Should map to product_id in order to match Segment Spec: 

productId: {
              '@path': 'product_id'

2023-05-15 13:17 UTC, asifrahiman commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +        productId: { '@path': '$.properties.productId' }
updated the mapping

2023-05-15 13:17 UTC, asifrahiman commented on packages/destination-actions/src/destinations/revx/sendRevxPing/index.ts
> +              '@path': 'productId'
updated

2023-05-15 15:35 UTC, joe-ayoub-segment commented
> > 
> 
> @joe-ayoub-segment we are getting this failure while running yarn validate
> 
> ```
> ✖ Validating definition for VWO Cloud Mode (Actions): 
>     The authentication field "vwoAccountId" of type "number" does not contain a default value. It is recommended to choose a sane default to avoid validation issues.
>     The default value for field "vwoAccountId" is of type "undefined", but the type is set to "number".
> ```

Hi @asifrahiman I think this might be more of a warning. 
Just waiting for CI to pass now and then I'll merge.

2023-05-15 16:05 UTC, joe-ayoub-segment commented
hi @asifrahiman , PR merged. Will go out with our next deploy - should be Wednesday.

2023-05-15 16:54 UTC, asifrahiman commented
hi @joe-ayoub-segment 
Thank you very much for the fast processing of the PR. Looking forward for the merge.

Regards,
Asif Abdul Rahiman

2023-05-17 12:59 UTC, joe-ayoub-segment approved these changes

2023-05-17 12:59 UTC, merged

2023-05-18 12:10 UTC, joe-ayoub-segment commented
Hi @asifrahiman , 
This PR has been deployed. I'll forward you instructions via email. 

Best regards,
Joe