remove unlayer apikey and generateEmailHtml
segmentio/action-destinations pull request #1214
Opened 2023-04-27 15:43 UTC by zawadzkip

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-04-28 13:51 UTC, zawadzkip commented on packages/destination-actions/src/destinations/engage-messaging-sendgrid/sendEmail/index.ts
> +          statsClient?.incr('actions-personas-messaging-sendgrid.bodyUrl_failure', 1, tags)
do we need to configure anything in datadog for these to appear?

2023-04-28 16:19 UTC, hocaho commented on packages/destination-actions/src/destinations/engage-messaging-sendgrid/generated-types.ts
> -  unlayerApiKey?: string
I remember someone mentioning that removing destination action settings may cause issues (while adding is OK). Unfortunately, I can't recall who mentioned this 🤔 @pmunin can you confirm?

2023-05-01 17:33 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-sendgrid/generated-types.ts
> -  unlayerApiKey?: string
since that field is optional - I don't think it should matter. I guess @dlasky would be best person to confirm

2023-05-10 13:29 UTC, zawadzkip commented on packages/destination-actions/src/destinations/engage-messaging-sendgrid/generated-types.ts
> -  unlayerApiKey?: string
@pmunin @hocaho 

I talked a bit with @dlasky about it, sounds like the real issue is only adding required fields because the existing definitions in the DB wont have it, so it would require a CPS migration first.

Is it worthwhile having the AD throw an error for the design type and logging it as well?

2023-05-12 15:20 UTC, zawadzkip commented on packages/destination-actions/src/destinations/engage-messaging-sendgrid/index.ts
> -        label: 'Unlayer API Key',
Since we're removing this, do we think its worthwhile to just fail `design` bodyType requests?

2023-05-16 01:30 UTC, hocaho requested changes

2023-05-16 01:30 UTC, hocaho commented on packages/destination-actions/src/destinations/engage-messaging-sendgrid/sendEmail/index.ts
> +          throw new IntegrationError(
There are existing journeys that still have bodyType='design' with a valid bodyUrl that are currently broken. eg. project id `tPPVUnfirfSU5UEWREsQj3`, `rggwqjYmmSkBGAbFes1R8e`. This is the query for retrieving destination action config settings: `select * from destination_action_config_settings where project_id = 'tPPVUnfirfSU5UEWREsQj3';`

2023-05-23 12:53 UTC, closed without merging