Pint 1742
segmentio/action-destinations pull request #1216
Opened 2023-04-28 23:39 UTC by jumpingGrendel

This implements three endpoints for Airship:

1. Custom Events
2. Attributes
3. Tags

They leverage Segment event types (respectively)
1. Track
2. Identify
3. Group

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-05-08 11:56 UTC, joe-ayoub-segment commented
Hi @jumpingGrendel , 
Thanks for raising the PR. Apologies for the delay, I'm just back from PTO. 
Would you have some time to catch up and review this PR together please? You can schedule a call with me via this URL: 
http://calendly.com/joe_ayoub/integration-workshop

Kind regards,
Joe

2023-05-09 15:28 UTC, joe-ayoub-segment requested changes
Hi @jumpingGrendel , 
I did a review of the PR prior to us meeting. 
It's worth meeting to review this together. 

Most important items: 
1. Some hard coded mappings really should be fields (so customers can edit them)
2. Questions about the named_user_id identifier. 
3. Field and setting descriptions should be more helpful
4. .gitignore file should not be edited

Looking forward to catching up soon. 
Joe

2023-05-09 15:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +    airship_payload.add = { 'segment-integration': tags_to_add }
Would it be possible to allow the customer to specify the name of the tag group as well? instead of hard coding it to segment-integration? This is a limitation with the Classic Segment<>Airship Destination which would be great to fix with this newer iteration!

2023-05-09 15:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/manageTags/index.ts
> +      description: 'The identifier assigned in Airship as the Named User',
In most cases, the Segment userId is unlikely to be an Airship Named User ID. The Segment userId is usually the customer's main canonical ID for their user. This is probably worth a chat...

Does the user profile with the specific named user ID need to already exist in Airship, or will it be possible to have Airship create a user profile with the any value that's passed as a named user ID?

Is there a way to do an Upsert opteration to Airship which will create a user if they don't exist already, or update an existing user? If so, is it possible to do this with any identifier?

2023-05-09 15:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +    user: {
This field is called named_user_id in the manageTags Action. Should we keep it consistant?

2023-05-09 15:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +        '@path': '$.receivedAt'
Probably best to map this to the timestamp field, not the receivedAt field. 

```suggestion
        '@path': '$.timestamp'
```

2023-05-09 15:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +  }
What about handling null values?

2023-05-09 15:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/customEvents/index.ts
> +      required: false,
Why is this field not required? Won't the API call to Airship fail if there is no named_user_id?

2023-05-09 15:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +    payload.properties.source = 'segment'
```suggestion
    payload.properties.source = 'Segment'
```

2023-05-09 15:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +          const new_attribute_key: string = trait_to_attribute_map(k)
We could/should expose the trait_to_attribute_map mapping to the customer/user and let them map each item as they wish. 
I can explain when we meet.

2023-05-09 23:12 UTC, jumpingGrendel commented on packages/destination-actions/src/destinations/airship/index.ts
> +            named_user_id: '549ce761-56c9-4899-9026-816d0c3bffd1'
yes. The API will return a 200 if the auth is correct, it does the named user lookup later.

2023-05-10 22:20 UTC, jumpingGrendel commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +    payload.properties.source = 'segment'
Functionality in our current destination integration uses lowercase, I'm reluctant to change it because I don't want to break anyone's reporting.

2023-05-10 22:23 UTC, jumpingGrendel commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +    airship_payload.add = { 'segment-integration': tags_to_add }
It's not really a limitation; tag groups (in Airship) are namespaces, so having one per partner is valuable. Customers can set tag names to whatever they want, ones that come from segment will always be in the `segment-integration` group.

2023-05-10 22:23 UTC, jumpingGrendel commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +  }
I guess? Let's discuss Friday.

2023-05-12 15:43 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/manageTags/index.ts
> +  defaultSubscription: 'type = "group"',
Agreed to set the defaultSubscription for this Action to be an empty string ''. 
Also agreed to set the Tag Name field default setting to be as follows: 

'@path': '$.traits.airship_tags'

2023-05-12 15:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/manageTags/index.ts
> +      description: 'Tag to add or remove',
e.g. Tag to add or remove. Values for each tag should be boolean only. a true value creates a tag, a false value removes a tag. Non boolean values will be ignored.

2023-05-12 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +    airship_payload.add = { 'segment-integration': tags_to_add }
Discussed this in person. Would be nice to be able to do the following: 

```
    tag_group: {
      label: 'Tag Group',
      description: 'The Tag Group to sync your tags to',
      type: 'string',
      required: true,
      default: 'segment-integration'
    }
```

2023-05-15 23:28 UTC, jumpingGrendel commented
@joe-ayoub-segment I believe all your comments/suggestions have been addressed. Thanks!

2023-05-22 10:48 UTC, joe-ayoub-segment commented
Thanks @jumpingGrendel I'll review now!

2023-05-24 15:37 UTC, joe-ayoub-segment requested changes
Some minor changes to be made.

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +    'Set user attributes in Airship with data from Segment. Some preset attributes are predefined, but all must be created in Airship before use. More information here: https://docs.airship.com/guide
```suggestion
    'Set user attributes in Airship with data from Segment. Some common user attributes are predefined in the attributes field, however note that all must be created in Airship before use. More information here: https://docs.airship.com/guides/messaging/user-guide/audience/segmentation/attributes/project/#adding-attributes',
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/index.ts
> +        // default: process.env.DEFAULT_ACCESS_TOKEN,
remove comment line

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/index.ts
> +
Please add this array here: 


  presets: [
    {
      name: 'Custom Events',
      subscribe: 'type = "track"',
      partnerAction: 'customEvents',
      mapping: defaultValues(customEvents.fields)
    }, 
    {
      name: 'Set Attributes',
      subscribe: 'type = "identify"',
      partnerAction: 'setAttributes',
      mapping: defaultValues(setAttributes.fields)
    }],

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/index.ts
> +import type { DestinationDefinition } from '@segment/actions-core'
```suggestion
import type { DestinationDefinition, defaultValues } from '@segment/actions-core'
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/manageTags/index.ts
> +      required: false,
```suggestion
      required: true,
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/manageTags/index.ts
> +        'Tag name to add or remove. Values for each tag should be boolean only. a true value creates a tag, a false value removes a tag. Non-boolean values will be ignored.',
```suggestion
        'Tag name to add or remove. Values for each tag should be boolean only. A true value creates a tag, a false value removes a tag. Non-boolean values will be ignored.',
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/manageTags/index.ts
> +        'The Tag Group to sync your tags to. Normally, this should be `segment-integration`, but set it here if it should be something else. Note: the Tag Group used must be valid and exist in Airshi
```suggestion
        'The Tag Group to sync your tags to. This defaults to`segment-integration` but can be overridden with this field. Note: the Tag Group used must be valid and exist in Airship.',
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/manageTags/index.ts
> +  title: 'Tags',
```suggestion
  title: 'Manage Tags',
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +        zipcode: { '@path': '$.traits.zipcode' },
```suggestion
        zipcode: { '@path': '$.traits.address.postalCode' },
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +        city: { '@path': '$.traits.city' },
```suggestion
        city: { '@path': '$.traits.address.city' },
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +        region: { '@path': '$.traits.region' },
```suggestion
        region: { '@path': '$.traits.address.region' },
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +        birthdate: { '@path': '$.traits.birthdate' },
```suggestion
        birthdate: { '@path': '$.traits.birthday' },
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +        mobile_phone: { '@path': '$.traits.mobile_phone' },
```suggestion
        mobile_phone: { '@path': '$.traits.phone' },
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +        company: { '@path': '$.traits.company' },
```suggestion
        company: { '@path': '$.traits.company_name' },
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +        advertising_id: { '@path': '$.traits.advertising_id' }
```suggestion
        advertising_id: { '@path': '$.context.device.advertisingId' }
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/setAttributes/index.ts
> +        country: { '@path': '$.traits.country' },
```suggestion
        country: { '@path': '$.traits.address.country' },
```

2023-05-24 15:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +    payload.properties.source = 'segment'
```suggestion
    payload.properties.source = 'Segment'
```

2023-05-24 15:37 UTC, joe-ayoub-segment requested changes
Some minor changes to be made.

2023-05-25 10:04 UTC, joe-ayoub-segment approved these changes

2023-05-25 10:04 UTC, merged

2023-05-30 14:34 UTC, joe-ayoub-segment commented
Hi @jumpingGrendel , your PR has been deployed. I'll send instructions for next steps via email.