Fix VWO destination error
segmentio/action-destinations pull request #1227
Opened 2023-05-02 23:02 UTC by zikaari

This is fix to deal with `j.php` script not always setting the `window.VWO` variable thus leading to `resolveWhen` freeze-up. This patch now checks if the execution of `j.php` immediately set `window.VWO` variable or it didn't. It resolves when it does, and rejects when it doesn't. Either way, preventing the freeze up of entire Analytics SDK.

2023-05-02 23:22 UTC, silesky approved these changes

2023-05-03 00:00 UTC, silesky commented on packages/browser-destinations/src/destinations/vwo/init-script.ts
> +    window._vwo_code ||= (function () {
just occurred to me that this promise will only resolve if vwo_code doesn't exist. I think we need to resolve immediately in that case.

2023-05-03 00:05 UTC, silesky requested changes
looks good, but q

2023-05-03 17:40 UTC, silesky commented
cc @prathamesh-88

2023-05-03 19:45 UTC, zikaari commented on packages/browser-destinations/src/destinations/vwo/init-script.ts
> +    window._vwo_code ||= (function () {
Good catch. Let me fix that

2023-05-05 08:44 UTC, prathamesh-88 commented
Hi @zikaari @silesky 
Thank you for bringing this issue to our attention and providing the necessary changes. We appreciate your contribution and attention. After testing the suggested changes, we have discovered some malfunctions in the `VWO.event` and `VWO.visitor` functions within the action-tester environment. Our team is actively investigating the root cause and working towards resolving this issue.

Furthermore, we have encountered some challenges when loading the SmartCode (init-script) with Segment, which has been a persistent concern for our team. We have included the necessary fixes to address this issue in this PR. https://github.com/segmentio/action-destinations/pull/1236

2023-05-10 06:57 UTC, silesky approved these changes

2023-05-10 20:37 UTC, chrisradek commented
@prathamesh-88 
The issues you mentioned around VWO.event and VWO.visitor - are those existing issues present without the changes in this PR? Or were they introduced by this PR? We're trying to understand if we can merge this change to unblock one issue we're seeing while you separately work on fixing the issues you mentioned.

2023-05-11 17:26 UTC, zikaari commented
@prathamesh-88 Please refer to [this comment](https://github.com/segmentio/action-destinations/pull/1236#issuecomment-1541080594)

2023-08-21 14:38 UTC, joe-ayoub-segment commented
Hi @zikaari - this looks like an old PR. Do you want to proceed with it or should it be closed?
Best regards,
Joe

2023-08-23 08:57 UTC, joe-ayoub-segment commented
Hi @zikaari , following up on this PR again. Is it something you'd like to proceed with?
Best regards,
Joe

2023-08-29 09:42 UTC, prathamesh-88 commented
Hi @joe-ayoub-segment 
The issue mentioned in this PR was resolved in the latest changes. Thus, these changes are no longer required as these changes posed certain functional issues while testing them.

I just noticed that the destination has been moved to private beta from public beta. Can you please look into it and let us know if anything needs to be done on our end?

2023-09-08 15:36 UTC, joe-ayoub-segment commented
hi @prathamesh-88 - quick clarification, can I close this PR?

2023-09-11 17:25 UTC, zikaari commented
@joe-ayoub-segment since the authors suggest that the changes in this patch might be problematic - we should close it out.

@prathamesh-88 It has been moved to private beta because it is still unstable, the `window.VWO` object never spawns sometimes, and holds up the entire AJS pipeline. We don't have repro steps since it happens at random.

2023-09-12 09:30 UTC, closed without merging