Sev-4480/fix sms subscription status and logging
segmentio/action-destinations pull request #1245
Opened 2023-05-10 15:42 UTC by pmunin

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-05-10 20:35 UTC, hocaho commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    const [firstMsg, ...rest] = msgs
Let's consider adding feature flag support to toggle info logs. I believe it's accessible via `payload.features`, here's an [example](https://github.com/segmentio/action-destinations/blob/13d69617b195102493629c3133504b326002935f/packages/destination-actions/src/destinations/facebook-conversions-api/utils.ts#L11). That way we can turn it on for specific sources as necessary.

2023-05-11 03:57 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/__tests__/send-sms.test.ts
> -    })
changed behavior of the scenario, making it less violent. so this test is no longer needed.
New behavior: is subStatus is not in the list of subscribedStatuses then we consider it unsubscribed. However we still check if subStatus does not fit any of supported status we log info about it and write it to new dd metric

2023-05-11 03:57 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/__tests__/send-whatsapp.test.ts
> -
Same here changed behavior of the scenario, making it less violent. so this test is no longer needed.
New behavior: is subStatus is not in the list of subscribedStatuses then we consider it unsubscribed. However we still check if subStatus does not fit any of supported status we log info about it and write it to new dd metric

2023-05-11 03:57 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/index.ts
> -    return new SmsMessageSender(request, payload, settings, statsClient, tags, logger, logDetails).send()
moved it to base class

2023-05-11 03:57 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/sms-sender.ts
> -  }
this constructor does not do anything, but passing through to the base class, so no point of having it

2023-05-11 03:57 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    const [firstMsg, ...rest] = msgs
I think we should have it by default for everything, and just filter logs by sourceId, no?

2023-05-11 03:57 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    } else{
discussed that adjustment in behavior with @alfrimpong. I tried to make code self explained, but summary of changes:
- we find the first subscribed extId even if it's not the first one
- we don't throw error on unrecognized subscription status, but just log it, stats it and treat it as Not Sendable.

2023-05-11 03:57 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/sms-sender.ts
> +
for sms sender we support undefined channelType for backward compatibility.
After @alfrimpong deploys the migration https://github.com/segmentio/control-plane/pull/3445 - this will be not needed and that method overload can be deleted from this class, so base implementation of MessageSender will be used.

2023-05-11 04:01 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +            )
wrap the error to support the status code for centrifuge

2023-05-11 15:06 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/index.ts
> +        },
lets add a default for channelType.
```
            channelType: {
              '@path': '$.channelType'
            },
```

2023-05-11 15:14 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/index.ts
> +        },
is it supposed to be like that:
```
 channelType: {
              ....
              default: { '@path': '$.channelType' }
            },

```
?

2023-05-11 18:32 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    const [firstMsg, ...rest] = msgs
got same request from @dlasky I am thinking for the interest of sev priority - merge this PR without feature flag to unblock single send team, and create next PR for feature flag. Does it make sense?

2023-05-11 18:32 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/index.ts
> +        },
done

2023-05-11 18:39 UTC, hocaho commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    const [firstMsg, ...rest] = msgs
Yep, makes sense. Thanks!

2023-05-11 18:40 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/sms-sender.ts
> +
With the change coming from this PR (default added), channelType should always be populated. I believe this can be removed now.

2023-05-11 18:41 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/sms-sender.ts
> +
@dlasky correct me if im mistaken here.

2023-05-11 18:43 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/sms-sender.ts
> +
just to be safe I suggest to deploy it with this fail-safety patch, and once single send test it, I'll include removing of it in the next logging-feature-flag pr

2023-05-11 18:46 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/sms-sender.ts
> +
also your migration is not yet deployed to Prod and we might have to deploy this PR before your migration

2023-05-11 18:55 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-sendgrid/__tests__/send-email.test.ts
> +            { id: userData.phone, type: 'phone', subscriptionStatus: 'subscribed', channelType:'sms' }
This file belongs to a different destination. Is this what you intended to do?

2023-05-11 18:57 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/__tests__/send-sms.test.ts
> +        expect.anything()
You are comparing against `anything`. That means that all things but `undefined` and `null` will satisfy this. How is the test valuable like that?

2023-05-11 18:58 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/__tests__/send-sms.test.ts
> +      debugger;
You should remove this before merging as it could impact the way tests run for others.

2023-05-11 18:59 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/__tests__/send-sms.test.ts
> +      // eslint-disable-next-line no-debugger
```suggestion
```

2023-05-11 18:59 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/__tests__/send-sms.test.ts
> +      // eslint-disable-next-line no-debugger
```suggestion
```

2023-05-11 18:59 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-sendgrid/__tests__/send-email.test.ts
> +            { id: userData.phone, type: 'phone', subscriptionStatus: 'subscribed', channelType:'sms' }
yes, channelType supposed to be provided everywhere, not sure why sendgrid unit test contained phone, but since it did - I added the proper field there too

2023-05-11 19:01 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/index.ts
> +  description: 'This is an Engage specific action to send an SMS and Whatsapp messages using Twilio API',
I think you need to run `generate types` so this change gets picked up by the types file and your updated description actually renders

2023-05-11 19:02 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/index.ts
> +
```suggestion
```

2023-05-11 19:03 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/sms-sender.ts
> +    if(externalId.type!=='phone') return false
Let's stay consistent with the style in this file and codebase.
```suggestion
    if(externalId.type !== 'phone') {
      return false
    }
```

2023-05-11 19:06 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/__tests__/send-sms.test.ts
> +        expect.anything()
With this I'm ignoring other arguments passed to that method and only assert the first argument of function matches the string. https://codewithhugo.com/jest-specific-argument-parameter-assert/

2023-05-11 19:06 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/sms-sender.ts
> +
sounds good. deploying the migration soon. first to production-sandbox

2023-05-11 19:06 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/__tests__/send-sms.test.ts
> +      debugger;
oh crap, good catch, thanks

2023-05-11 19:07 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +  redactPii(pii: string|undefined){
```suggestion js
  redactPii(pii: string | undefined) {
    if(!pii) {
      return pii
    }
    
    if(pii.length <= 8) {
      return '***'
     }
    return pii.substring(0, 3) + '***' + pii.substring(pii.length - 3)
  }
```

2023-05-11 19:07 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +      this.logger?.error("TE Messaging: "+ error, ...msgs, JSON.stringify(this.logDetails))
```suggestion
      this.logger?.error(`TE Messaging: ${error}`, ...msgs, JSON.stringify(this.logDetails))
```

2023-05-11 19:09 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +      this.logger?.error("TE Messaging: "+firstMsg, ...rest, error instanceof Error? error.message: error?.toString(), JSON.stringify(this.logDetails))
```suggestion
      this.logger?.error(`TE Messaging: ${firstMsg}`, ...rest, error instanceof Error? error.message: error?.toString(), JSON.stringify(this.logDetails))
```

2023-05-11 19:15 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendWhatsApp/whatsapp-sender.ts
> +    return 'whatsapp'
two channels https://github.com/segmentio/action-destinations/blob/f127542dca9c7a724a061055d926bffac8661759/packages/destination-actions/src/destinations/engage-messaging-twilio/sendSms/sms-sender.ts#L80-L82
And more may come later

2023-05-11 19:16 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
Don't you want to add a check instead? Just to be safer

2023-05-11 19:17 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +  static nonSendableStatuses = ['unsubscribed', 'did not subscribed', 'false'] // do we need that??
`// do we need that??` -> You tell me! 😄

2023-05-11 19:17 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +        this.logInfo("Message sent successfully")
You are already pushing successes to the stats client, is this log still valuable to you?

2023-05-11 19:19 UTC, marinhero requested changes
Please take a look at the comments I made. I'm aware of the urgency of the SEV but I'd discourage you from pushing code with `eslint-disable` statements as they could result in unpredictable behavior in the future.

2023-05-11 19:22 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
how is that making it more safer? hasInvalidStatuses guarantees that invalidStatuses is not null or undefined

2023-05-11 19:25 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +        this.logInfo("Message sent successfully")
yes: stats are not message specific. Logs are. we want to see exactly what happened with the message on all steps

2023-05-11 19:32 UTC, pmunin commented
@marinhero I replied to all your comments and applied most of your suggestions. 
RE:  I'd discourage you from pushing code with eslint-disable statements
I guess you're talking about --no-verify git flag? 
this was impossible, as there are tons of errors in other modules, so it does not let me commit until everything is fixed in entire repo

2023-05-11 19:46 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/index.ts
> +  description: 'This is an Engage specific action to send an SMS and Whatsapp messages using Twilio API',
Ran `yarn types` nothing was updated

2023-05-11 20:00 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/index.ts
> +  description: 'This is an Engage specific action to send an SMS and Whatsapp messages using Twilio API',
ah, I'm seeing this is the description of the destination and not an action. That makes sense. Thanks for reporting back on this!

2023-05-11 20:02 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +  logInfo(...msgs:string[])
```suggestion
  logInfo(...msgs:string[]) {
```

2023-05-11 20:02 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    this.logger?.info("TE Messaging: "+firstMsg, ...rest, JSON.stringify(this.logDetails))
```suggestion
    this.logger?.info(`TE Messaging: ${firstMsg}`, ...rest, JSON.stringify(this.logDetails))
```

2023-05-11 20:03 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +  logError(error?: any, ...msgs:string[])
```suggestion
  logError(error?: any, ...msgs:string[]) {
```

2023-05-11 20:03 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +  {
Remove this if you implement the suggestion above.
```suggestion
```

2023-05-11 20:11 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +  logError(error?: any, ...msgs:string[])
done

2023-05-11 20:11 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +  {
done

2023-05-11 20:11 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    this.logger?.info("TE Messaging: "+firstMsg, ...rest, JSON.stringify(this.logDetails))
done

2023-05-11 20:11 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +  logInfo(...msgs:string[])
done

2023-05-11 20:27 UTC, marinhero approved these changes
Looks good to me. I recommend keeping a log/ticket for cleaning up the logs when the issue is mitigated.

2023-05-11 20:27 UTC, marinhero commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +  {
Remove this if you implement the suggestion above.

```suggestion
```

2023-05-11 20:27 UTC, marinhero approved these changes
Looks good to me. I recommend keeping a log/ticket for cleaning up the logs when the issue is mitigated.

2023-05-11 20:29 UTC, merged