CONMAN-474 bypass subscription
segmentio/action-destinations pull request #1249
Opened 2023-05-11 14:46 UTC by sumitbhanwala

If a particular action destination have bypass subscription set to true than we should ignore the subscription of the user and send them the email.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x] [Segmenters] Tested in the staging environment

2023-05-11 18:58 UTC, sumitbhanwala commented on packages/destination-actions/package.json
> +    "testmy": "jest src/destinations/engage-messaging-sendgrid/__tests__/send-email.test.ts",
I will remove itl, had a hard time running the tests so had to do it.

2023-05-15 15:58 UTC, lew-gordon requested changes
GIven the nature of this change, can we verify it works e2e in stage?

2023-05-15 16:00 UTC, sumitbhanwala commented
> GIven the nature of this change, can we verify it works e2e in stage?

Yeahh merging my changes in staging now and will test e2e but apart from that does changes look good ?

2023-05-17 03:07 UTC, SyedWasiHaider approved these changes

2023-05-17 13:01 UTC, merged