Update Loops Action Destination
segmentio/action-destinations pull request #1250
Opened 2023-05-11 15:28 UTC by askkaz

_Updating the Loops action destination. Adding fields to `createOrUpdateContact` and creating `sendEvent`._

## Testing

- [X] Updated unit tests for `createOrUpdateContact`
- [X] Added unit tests for `sendEvent`
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-05-12 16:35 UTC, joe-ayoub-segment commented
Hi @askkaz , 
Thanks for raising this PR. I'll do a review next week. 
Best regards,
Joe

2023-05-17 12:42 UTC, joe-ayoub-segment requested changes
Hi @askkaz , 
Please find some feedback on the PR. 
The changes to your createOrUpdateContact Action look safe.
Couple of minor questions for the new Action.

2023-05-17 12:42 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/loops/createOrUpdateContact/index.ts
> +      description: 'Attributes maintained by your team.',
hi @askkaz , Is this description sufficient for the customer to understand what this field is for?

2023-05-17 12:42 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/loops/sendEvent/index.ts
> +      }
Hi @askkaz , for a track() event you need to check these 2 locations for the email address. See below. 

```suggestion
      default: {
        '@if': {
          exists: { '@path': '$.properties.email' },
          then: { '@path': '$.properties.email' },
          else: { '@path': '$.context.traits.email' }
        }
      }
```

2023-05-17 12:42 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/loops/sendEvent/index.ts
> +      json: {
hi @askkaz , do you also want/need to collect event properties as well? Most customers include a properties object in every track() call.

2023-05-17 14:40 UTC, askkaz commented on packages/destination-actions/src/destinations/loops/createOrUpdateContact/index.ts
> +      description: 'Attributes maintained by your team.',
@joe-ayoub-segment Our platform allows users to create custom attributes for their list. For example `favoriteColor` is not a default property on our platform but a user can create it for their list. On other platforms (Zapier for example), we use an API endpoint to fetch the available fields for the user when they set up the integration and then we display them. It seems that Segment does not support this, and based on earlier talks with Segment engineers, it was recommended we just dump these attributes into dictionary and then destructure it. I agree its not ideal, but I think its the best we can do with the way that Segment is set up. We will include specific examples of how to use this properly in our documentation.

Open to any suggestions here though :-)

2023-05-18 12:54 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/loops/createOrUpdateContact/index.ts
> +      description: 'Attributes maintained by your team.',
Thanks @askkaz this makes sense!

2023-05-18 13:08 UTC, joe-ayoub-segment approved these changes
Change looks safe. 
No new required fields. 
Local tests pass. 
yarn validate passes.

2023-05-18 14:31 UTC, merged

2023-05-23 21:25 UTC, joe-ayoub-segment commented
Hi @askkaz this PR been deployed. Please test and let me know if everything looks alright!