Push
segmentio/action-destinations pull request #1266
Opened 2023-05-17 07:17 UTC by alfrimpong

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-05-18 18:05 UTC, joe-ayoub-segment commented
Hi @alfrimpong thanks for the PR - I'll review tomorrow.

2023-05-19 16:44 UTC, joe-ayoub-segment requested changes

2023-05-19 16:44 UTC, joe-ayoub-segment requested changes
couple minor things I noticed. Didn't do full review.

2023-05-22 15:21 UTC, alfrimpong commented on packages/destination-actions/src/destinations/iterable/trackEvent/index.ts
> +    const trackEventRequest: TrackEventRequest = {
This was automatically added by `./bin/run generate:types` but i'll exclude it

2023-05-22 15:25 UTC, alfrimpong commented on packages/destination-actions/src/destinations/pinterest-conversions/reportConversionEvent/index.ts
> +  description:
I actually cant remove this. its a lint change. The content is the same.

2023-05-22 15:40 UTC, alfrimpong commented
@hocaho @pmunin can I get a review on this?

2023-05-24 07:51 UTC, joe-ayoub-segment commented
Hi @alfrimpong - just a reminder to let me know when you need me to review.

2023-05-25 19:01 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
>          }
Isn't this supposed to be in a phone-message-sender?

2023-05-25 19:01 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/phone-message.ts
I'd rename this class & file to TwilioMessageSender

2023-05-25 19:03 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
>          }
I'd expect messageSender.send to be very thin and mostly containing the log, stats, try catch logic, rather than hitting apis. Our plan is to share it across all channels - Email, Sms, Mms, whatsapp and Push right?

2023-05-25 19:10 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/push-sender.ts
> +    return this.logWrap([`Destination Action ${this.getChannelType().toUpperCase()}`], async () => {
e.g. this is copypasted, even though it is in the baseclass. In stead of copy pasting - consider creating new method in an abstract method in the base class, which will be overriden here and only containing Push-specific logic

2023-05-25 20:17 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
>          }
messageSender.send current doesnt exist in this pr. The send method is moved up one layer in what is currently called "phoneMessageSender".

2023-05-25 20:18 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/push-sender.ts
> +    return this.logWrap([`Destination Action ${this.getChannelType().toUpperCase()}`], async () => {
The base class actually doesnt have a `send` method anymore.
Adding an abstract method whose purpose is to wrap a method call could work, though i'd argue that a decorator could be more fitting.

I'll investigate.

2023-05-25 20:21 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/phone-message.ts
The thought here is that this class is sub-classed by all channels that require an external id of type `"phone"`. Those all have a similar workflow.
Calling it TwillioMessageSender is a little too broad because Push is technically also a twilio message, but has a completely different ethos in terms of actually sending a message.

2023-05-25 20:26 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
>          }
it'll probably be easier to look at this PR holistically in codespaces or an IDE. There are a lot of red and green here lol it can escape the eye

2023-05-25 20:31 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/push-sender.ts
> +    return this.logWrap([`Destination Action ${this.getChannelType().toUpperCase()}`], async () => {
I didn't notice you removed `send` method. I think MessageSender class should have such method and like I said just to have a thin functionality making logging/stats and error handling consistent across all our DAs

2023-05-25 23:19 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/push-sender.ts
> +    return this.logWrap([`Destination Action ${this.getChannelType().toUpperCase()}`], async () => {
Yea MessageSender has all of that. The decorator im talking about would be for this initLogDetails and logWrap. 
Otherwise i'll have to create the following:

```
MessageSender {
  abstract actuallyDoSending;

   send() {
    initLogs
    logWrap(this.actuallyDoSending) // idek what to call it
  }
}
```

As opposed to 
```
PhoneMessage {
  @InitLogging()
  send() {
    // actual send logic
  }
}
```

In the first approach, we end up with 2 methods seemingly both doing a send, in reality one is just a wrapper. But if you're 100% on that approach, then we can try it.

2023-05-26 03:22 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/push-sender.ts
> +    return this.logWrap([`Destination Action ${this.getChannelType().toUpperCase()}`], async () => {
decorators are still experimental, require changing tsconfig, don't know if it's worth it to say couple lines of code. so imho the first option is better for this situation. But besides what you mentioned above the base send method could/should include:
- statsClient.inc(attempt metric)
- root level try catch, preparing error (e.g. can handle request timeout errors, making it retryable) and rethrowing it

for method actuallyDoSending pattern - they usually `doSend`. You can name methods like that:
```js
MessageSender {
  abstract send();

   perform() {
    ...
    logWrap(()=>this.send()...)
    ...
  }
}
```

2023-05-30 01:58 UTC, alfrimpong commented
@joe-ayoub-segment it's ready for your review. 
Merge pending @pmunin 's approval.

2023-05-30 17:09 UTC, pmunin approved these changes
Thanks for addressing comments, sorry for delay with approval

2023-05-30 17:11 UTC, pmunin commented
@joe-ayoub-segment it needs your approval

2023-05-31 09:10 UTC, joe-ayoub-segment commented
Hi @alfrimpong and @pmunin I'll take a look now

2023-05-31 14:38 UTC, joe-ayoub-segment requested changes
Hi @alfrimpong and @pmunin , 

I spent some time reviewing. Only got a couple of questions / light suggestions. 
unit tests pass, and yarn validate passes. 

However given this is such a large refactor of the existing sendSms and sendWhatsApp Actions I'd like another member of my team to have a look. 

Edit: I think our best bet against having an incident based off of this change is to ensure that adequate testing has been done, with a sufficiently varied number of inputs and outputs. @alfrimpong said that this is something you do anyway. Do you feel that the depth and breadth of these tests are sufficient?

2023-05-31 14:41 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/index.ts
> +    contentSid: {
These don't have defaults values because they're unknown values. They're all customer provided.

2023-05-31 15:13 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/push-sender.ts
> +      }
sure i'll use that class

2023-05-31 16:25 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/push-sender.ts
> +      )
Yes we retry 500 and 429 errors. I believe centrifuge automatically does that depending on the the status. Which RetryableError sets to 500

2023-06-01 16:10 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
>  export type RequestFn = (url: string, options?: RequestOptions) => Promise<Response>
That RequestFn actually existed ages ago and got carried around. I'll add changing its usage in a follow up unit of work.

2023-06-01 23:47 UTC, NolanChan commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/index.ts
> +          description: 'Sets the noitfication click action/category',
typo!

2023-06-02 00:50 UTC, NolanChan commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/phone-message.ts
> +    if (webhookUrlWithParams) body.append('StatusCallback', webhookUrlWithParams)
small nit, but if we could keep the style of `if` statements with blocks that'd be great

2023-06-02 00:52 UTC, NolanChan approved these changes
No red flags from me, but there definitely are lots of changes here. I know we have a lot of (hopefully temporary) logging now, so if we could verify that logs are coming through on staging, that'd be great!

2023-06-02 08:37 UTC, joe-ayoub-segment approved these changes
Reviewed the code myself. Nolan also reviewed. Sayan also did a quick review.

2023-06-02 08:37 UTC, merged

2023-06-02 18:26 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush/push-sender.ts
> +    return JSON.parse(
I'll create an alternative for this in my next PR for this sendMobilePush action. I think json parse & stringify dont tend to get too expensive unless its working with large objects (tho they may block the thread), but in any case, the more performant the better, so i'll come up with something else. 

P.s. Lodash is [deprecating omit](https://levelup.gitconnected.com/omit-is-being-removed-in-lodash-5-c1db1de61eaf) in version 5 due to poor performance

2023-06-06 19:47 UTC, joe-ayoub-segment commented
Hi @alfrimpong this PR has been deployed.