Userpilot destination
segmentio/action-destinations pull request #1283
Opened 2023-05-22 18:25 UTC by ThabetIbrahim

_A summary of your pull request, including the what change you're making and why._

Adding support for Userpilot cloud action destination.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-05-23 10:23 UTC, joe-ayoub-segment commented
Hi again @ThabetIbrahim , 
If you grant me permission to your repo I can quickly make the changes myself. Let me know. 
Best regards,
Joe

2023-05-23 10:53 UTC, ThabetIbrahim commented
Thank you for the help @joe-ayoub-segment, I sent you an invite for the repo.

Based on my notes and the ones you shared, I believe the only missing thing I opted not to add is the `createdAt` field in the `identifyUser/index.ts` file. Do you know if we need anything else here?

2023-05-29 15:59 UTC, joe-ayoub-segment requested changes
Hi @Thabetlbrahim, 
Main comments are around making this Integration's fields be as similar to the Device Mode Integration's fields, if possible. 

Are you OK making these changes?
Best regards,
Joe

2023-05-29 15:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/userpilot/identifyUser/index.ts
> +    },
Hi @ThabetIbrahim , 

I'm thinking we should do the same as with the browser destination and just have a single field to collect the main identifier for the user. 

Something like this: 

    userId: {
      type: 'string',
      required: false,
      description: 'The ID of the logged-in user.',
      label: 'User ID',
      default: {
        '@if': {
          exists: { '@path': '$.userId' },
          then: { '@path': '$.userId' },
          else: { '@path': '$.anonymousId' }
        }
      }
    },

2023-05-29 15:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/userpilot/trackEvent/index.ts
> +    },
Hi again @ThabetIbrahim , as per the identifyUser Action and the web Destination, I think we should have a single identifier for the main user id. As below. 

    userId: {
      type: 'string',
      required: false,
      description: 'The ID of the logged-in user.',
      label: 'User ID',
      default: {
        '@if': {
          exists: { '@path': '$.userId' },
          then: { '@path': '$.userId' },
          else: { '@path': '$.anonymousId' }
        }
      }
    },

2023-05-29 15:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/userpilot/identifyUser/index.ts
> +  },
Hi @ThabetIbrahim , 
Could we add the createdAt field here as well? 
Should we not make the fields as similar between the Deivce Mode and Cloud Mode Destinations?
Keen to hear your thoughts.

2023-05-29 15:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/userpilot/index.ts
> +  name: 'Userpilot Cloud Mode (Actions)',
```suggestion
  name: 'Userpilot Cloud (Actions)',
```

2023-05-30 09:14 UTC, ThabetIbrahim commented on packages/destination-actions/src/destinations/userpilot/identifyUser/index.ts
> +      traits: { ...traits, created_at: createdAt || traits?.created_at },
Hi @joe-ayoub-segment, I noticed a behavior where the `created_at` property would be dropped if it's being passed directly without passing the `createdAt` as well.

2023-06-06 11:09 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/userpilot/identifyUser/index.ts
> +      required: false,
```suggestion
      required: true,
```

2023-06-06 11:23 UTC, joe-ayoub-segment approved these changes

2023-06-06 11:37 UTC, merged

2023-06-06 19:39 UTC, joe-ayoub-segment commented
Hi @ThabetIbrahim this PR has been deployed. I'll email you instructions for testing.