Canny functions destinatioon
segmentio/action-destinations pull request #1329
Opened 2023-06-07 09:10 UTC by BR4VE

_A summary of your pull request, including the what change you're making and why._

We are adding `canny-functions` destination to `action-destinations` which has two capabilities:
- Identify user on Canny side.
- Identify groups on Canny side.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

## Questions:

- I would appreciate if reviewers can answer the questions below:

1. We want users to be able to select `traits` to be registered as `customFields`. Right now users type the traits they want to  use and separate them with comma. How can we show a list of traits in a dropdown and allow users to multiselect?

2. Our destination is private beta and we don't want it to be released publicly for now. How can we do that?

3. We have an existing destination as `canny-functions` for old (deprecated) Developer Center. Can you please inform me how you migrate existing users? Having a new `clientID` and `clientSecret` will break the integration for our existing users.

2023-06-07 10:18 UTC, joe-ayoub-segment commented
Hi @BR4VE , thanks for raising this draft PR. When you are ready for review please let me know. 
Regards,
Joe

2023-06-08 07:07 UTC, BR4VE commented
> Hi @BR4VE , thanks for raising this draft PR. When you are ready for review please let me know. Regards, Joe

Hi @joe-ayoub-segment, thanks for the message. The PR is now ready to review. I would appreciate if you can answer my questions in PR description once you are done reviewing the PR. 

Thank you.

2023-06-09 12:41 UTC, joe-ayoub-segment requested changes
Hi @BR4VE , 
Please have a look at the recommendations from the review, and let me know if you have any questions or need assistance. 

I'll respond to your 3 questions here as well: 

Question 1. We want users to be able to select traits to be registered as [customFields](https://github.com/segmentio/action-destinations/pull/1329/files#diff-b5c7b7da1f0f493a13f2f48fb9681c6b7dd34379cf4853731f007c4cff7a88c3R22). Right now users type the traits they want to use and separate them with comma. How can we show a list of traits in a dropdown and allow users to multiselect?

Answer 1. I provided a potential approach for this in the review. Please test it out and see if it works for you. There may be other options for what you want to do, but I'd need to get a more detailed description of your use-cases before I could suggest any. 

Question 2. Our destination is private beta and we don't want it to be released publicly for now. How can we do that?

Answer 2. Once we deploy this new Integration it will be in Private Beta mode. No customers will be able to use it unless you provide them with a URL. You'll do testing ad create docs before we'll switch the Destination into Public Beta mode. (which is when customers can start using it properly). 


Question 3. We have an existing destination as canny-functions for old (deprecated) Developer Center. Can you please inform me how you migrate existing users? Having a new clientID and clientSecret will break the integration for our existing users.

Answer 3. There is no automated migration approach. Customers will be able to continue using your Legacy Integration or your new Integration. We can, if you like, prevent customers from creating new instances of your Legacy Integration. We'd then need to work on a communication plan to inform customers that the Legacy Integration will eventually stop working, and that they need to migrate to using the newer Integration. Does this make sense?

2023-06-09 12:41 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/index.ts
> +
Could we add a testAuthentication function here? 
This gets called after the customer types in the apiKey and hits the save button. It will ping a URL on your platform to validate that the apiKey is valid. 

Here's an example: 

```
    testAuthentication: (request, { settings }) => {
      return request(`https://yourapi.com/api/v1/checkapikey`)
    }
```

If we get a 200 response back then everything is good. If we don't get a 200 response back then the customer is notified.

2023-06-09 12:41 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/index.ts
> +  },
You might want to add some presets here, otherwise the customer will have an additional step when enabling your Integration. 

Here's an example of the presets you could define here: 

```
  presets: [
    {
      name: 'Create or update a group profile',
      subscribe: 'type = "group"',
      partnerAction: 'group',
      mapping: defaultValues(group.fields)
    },
    {
      name: 'Create or update a user profile',
      subscribe: 'type = "identify"',
      partnerAction: 'identify',
      mapping: defaultValues(identify.fields)
    }
  ]
```

2023-06-09 12:41 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/identify/index.ts
> +  description: 'Identify a user on Canny',
Maybe we should go with a more descriptive description here. 
For example: 

```suggestion
  description: 'Create or update a user profile in Canny',
```

2023-06-09 12:41 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/group/index.ts
> +  description: 'Updates or adds properties to a group. Group is created if it does not exist.',
Hi @BR4VE , 
Is the term 'group' something that Canny customers will understand? 
Or is a group the same an a company or organization?

2023-06-09 12:41 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/index.ts
> +      }
I think you should remove this setting. It's only used in your identify Action, and there's a better way to do this. 
I'll add a comment on the identify Action index.ts explaining more.

2023-06-09 12:41 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/identify/index.ts
> +    },
You could do something like this to help customers understand which user properties Canny accepts. 

The customer can always override these settings, or they can switch back to sending just a full object. 

```
    traits: {
      label: 'User Properties',
      type: 'object',
      description: 'Properties to set on the user profile',
      additionalProperties:true,
      defaultObjectUI: 'keyvalue',
      properties: {
        firstName: {
          label: 'First Name',
          description: 'The user\'s first name',
          type: 'string'
        },
        lastName: {
          label: 'Last Name',
          description: 'The user\'s last name',
          type: 'string'
        },
        birthday: {
          label: 'Birthday',
          description: 'The user\'s birthday date. in ISO 8601 string format. e.g. 1999-05-29T00:00:00.000Z',
          type: 'string'
        },
        phone: {
          label: 'Phone Number',
          description: 'The user\'s phone number, including country code',
          type: 'string'
        }
      },
      default: {
        firstName: {'@path': '$.traits.first_name'},
        lastName: {'@path': '$.traits.last_name'},
        birthday: {'@path': '$.traits.birthday'},
        phone: {'@path': '$.traits.phone'},
      }
    },
```

2023-06-09 12:41 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/identify/index.ts
> +    },
This setting  " defaultObjectUI: 'keyvalue', " sets the view for the field to look like this: 

![image](https://github.com/segmentio/action-destinations/assets/45374896/e1a20529-b8fe-4e0a-bf42-dc0a6244c3f4)

2023-06-09 12:41 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/utils/cloneWithDefinedProps.ts
> +}
You probably won't need this function if you change the way you have the traits field defined in your identify Action.

2023-06-12 07:49 UTC, BR4VE commented on packages/destination-actions/src/destinations/canny-functions/group/index.ts
> +  description: 'Updates or adds properties to a group. Group is created if it does not exist.',
Group refers to an company/organization in Canny. Canny customers using segment will understand what group means but I updated the description a little as you suggested 👍

2023-06-12 10:32 UTC, joe-ayoub-segment requested changes
hi @BR4VE , 

Few minor recommendations - suggestions. Keen to hear your thoughts. 

Best regards,
Joe

2023-06-12 10:32 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/identify/index.ts
> +        name: {
hi @BR4VE , 
I noticed that you have the following defined as default fields: 
['avatar', 'company', 'createdAt', 'email', 'id', 'name']

Why not have them defined in traits.properties as well, so that customers know about them?

For an example see below. I'm not sure it you should add the id field though as you already have a separate standalone field called 'userId'. Keen to hear your thoughts.  

```
        avatar: {
          label: 'Avatar',
          description: "URL to an avatar image for the user",
          type: 'string'
        }, 
        company: {
          label: 'Company',
          description: "Company the user represents. Optionally containing: name (String), id (String or Number), industry (String), employee_count (Number) or plan (String)",
          type: 'object'
        }, 
        createdAt: {
          label: 'Create At Date',
          description: "Date the user’s account was first created. Segment recommends using ISO-8601 date strings",
          type: 'string'
        }
```

2023-06-12 10:32 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/index.ts
> +      name: 'Create or update a group profile',
```suggestion
      name: 'Updates or update Company',
      description: 'Updates or adds properties to a company. Company is created if it does not exist.',
```

2023-06-12 10:32 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/index.ts
> +      name: 'Create or update a user profile',
```suggestion
      name: 'Create or update User',
      description: 'Create or update a user profile in Canny',
```

2023-06-12 10:32 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/canny-functions/identify/index.ts
> +        email: { '@path': '$.traits.email' }
If you decide to add avarat, company, and createdAt above, then you would use these defaults: 

avatar: {'@path': '$.traits.avatar'},
company: {'@path': '$.traits.company'},
createdAt: {'@path': '$.traits.createdAt'}

2023-06-12 11:01 UTC, BR4VE commented on packages/destination-actions/src/destinations/canny-functions/identify/index.ts
> +        name: {
Fields except `name` and `email` are not strictly required so I did not add them. But as you said adding all the fields makes it more explicit for users. Updated as you suggested 👍.

2023-06-12 11:01 UTC, BR4VE commented
@joe-ayoub-segment Thanks for the recommendations. Applied your suggestions 👍

2023-06-12 12:50 UTC, joe-ayoub-segment approved these changes
Only 1 query - What's the difference between the userId field and the traits.id field?
How will the customer know what to put in each?

I'll merge this now, so if you decide to change the userId or traits.id fields please raise another PR.

2023-06-12 13:05 UTC, BR4VE commented
> 

`userId` comes by default in segment event. `traits.id` can be set by end user. Canny has customers who has been using both ways. So we let them override/select which one to be used as the main `userID` on Canny side.

2023-06-12 13:07 UTC, BR4VE commented
> Only 1 query - What's the difference between the userId field and the traits.id field? How will the customer know what to put in each?
> 
> I'll merge this now, so if you decide to change the userId or traits.id fields please raise another PR.

Thank you for your feedback and time. We can merge. Also can you please let me know what is going to happen next? We've been told that we will gain access to new Developer Portal once our destination is merged. Will it happen immediately or will you notify us some time later? What is the ETA? @joe-ayoub-segment

2023-06-12 13:30 UTC, merged

2023-06-12 13:31 UTC, joe-ayoub-segment commented
Hi @BR4VE , 
I'll email you next steps. 
However you won't get access to the Dev Portal until the Destination code has been deployed, AFAIK. 
Best regards,
Joe

2023-06-15 13:15 UTC, joe-ayoub-segment commented
Hi @BR4VE , this PR has been deployed. The Integration is now in Private beta mode. 
I'll email you next steps. 
Best regards,
Joe