renaming destination and adding some validation
segmentio/action-destinations pull request #1331
Opened 2023-06-07 14:52 UTC by joe-ayoub-segment

Updating the TikTok Offline Conversions Destination
 - renaming it
 - adding checks for email and phone
 - adding tests for email and phone

## Testing

Destination is in Private Beta, not in use by customers. 
Unit tests added.

2023-06-08 18:14 UTC, sayan-das-in requested changes

2023-06-08 18:14 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/tiktok-offline-conversions/index.ts
> +  name: 'Tiktok Offline Conversions',
Hi Joe, I don't think it is a good idea to rename the destination in code. You can rename the destination in [Partner Portal](https://app.segment.com/partner-portal/integration/actions-tiktok-offline-conversions/profile) directly.

2023-06-09 04:59 UTC, sayan-das-in approved these changes
LGTM!

2023-06-09 07:39 UTC, joe-ayoub-segment commented
Thanks @sayan-das-in , I've updated the PR to change all references to Tiktok to TikTok.

2023-06-09 08:18 UTC, merged