Channels 633/messaging logging feature flag
segmentio/action-destinations pull request #1332
Opened 2023-06-07 15:35 UTC by pmunin

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-06-12 13:40 UTC, joe-ayoub-segment commented
Hi @pmunin , 
I'm still seeing commits coming in for this PR. Is it ready to be reviewed?

2023-06-12 13:41 UTC, pmunin commented
yes it's ready, I'm just cleaning some unit tests to minimize copy-pastes there, it does not change the production logic

2023-06-12 15:29 UTC, alfrimpong commented on packages/destination-actions/package.json
> +      "/*utils.*"
it'd also impart a convention on the entire destination-actions section of the repo that other developers are not aware of.

2023-06-12 16:40 UTC, pmunin commented on packages/destination-actions/package.json
> +      "/*utils.*"
> bunch of utils.test files in the repo
good catch, i'm switching it to *utils.ts

> convention on the entire destination-actions section of the repo that other developers are not aware of
I think it's worth it. Right now there are no files __tests__/*utils.ts that contain tests - if someone decides to add it later they will immediately notice that jest does not run it and they will have to find that config. but overall the convention that we should have for developers is naming the test files *.test?.ts - right now it's mostly followed, I found only two files that do not follow in packages/destination-actions:
```
./src/destinations/customerio/__tests__/deleteDevice.ts
./src/destinations/friendbuy/__tests__/cloudUtil.mock.ts
```

2023-06-12 17:02 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    if (!this.isFeatureActive(FLAGON_NAME_LOG_INFO, () => false)) return
where can I find that guide? my linter didn't complain. Besides I don't think that guide makes sense for this line, it will just make the code bulkier and harder to screen

2023-06-12 18:12 UTC, joe-ayoub-segment commented
Looks like some other folks ( e.g @alfrimpong ) are also reviewing. I'll wait until they are done.

2023-06-12 19:49 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    if (!this.isFeatureActive(FLAGON_NAME_LOG_INFO, () => false)) return
@NolanChan commented it on a previous PR :) im not sure why it's unlinted

2023-06-12 21:05 UTC, alfrimpong approved these changes

2023-06-12 21:05 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    metric = `actions_personas_messaging_twilio.${metric}`
nice

2023-06-12 21:34 UTC, NolanChan commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    if (!this.isFeatureActive(FLAGON_NAME_LOG_INFO, () => false)) return
ah yes, we should add a linter to catch one-line if statements :) I'll make a ticket for that

2023-06-12 21:35 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    if (!this.isFeatureActive(FLAGON_NAME_LOG_INFO, () => false)) return
for single return statement in the if - I'd recommend to keep a same line rule

2023-06-13 02:15 UTC, hocaho reviewed
Nice work consolidating stats and logging logic. Small comments regarding stats function.

2023-06-13 02:15 UTC, hocaho commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendWhatsApp/whatsapp-sender.ts
> +      this.stats('incr', 'error', 1)
Should we add an error type tag or update the metric name w/ the specific error type with a tag `error` here? eg `'wa_invalid_number'`? It'd be nice to be able to group the error stat by error type.

2023-06-13 18:56 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendWhatsApp/whatsapp-sender.ts
> +      this.stats('incr', 'error', 1)
it's done in this.tags - all those tags are applied to each stats push

2023-06-14 12:13 UTC, joe-ayoub-segment commented
Hi @pmunin , looks like the CI checks failed. 
I'm running them again. 

![image](https://github.com/segmentio/action-destinations/assets/45374896/061ae952-522a-4b47-9563-104545297ac8)

2023-06-14 12:16 UTC, joe-ayoub-segment commented
Hi @pmunin , I was out of office ill yesterday, so yesterday's deploy was cancelled. I'm doing a deploy now, but do not have time to review this PR first. Are you OK with this being deployed next Tuesday?

2023-06-14 13:20 UTC, pmunin commented
I guess we can deploy next Tuesday

2023-06-14 13:22 UTC, pmunin commented
> looks like the CI checks failed.

Oh man, I added local worktree to compare with the old code and it got into the remote somehow which screwed up the PR, I'll fix it

2023-06-20 09:00 UTC, sayan-das-in requested changes
All files under the `__test__` directory are considered as test files. Since the file `test-utils.ts` it doesn't contain any tests like `describe()` and `it()`, it is throwing an error. I would suggest you to move this file to another directory and not modify the `package.json`.

2023-06-20 10:29 UTC, joe-ayoub-segment commented on packages/destination-actions/package.json
> +      "/*utils.ts"
Hi @pmunin , can you explain why a change to this file is needed please?

2023-06-20 14:27 UTC, pmunin commented on packages/destination-actions/package.json
> +      "/*utils.ts"
hi, because we need some utils modules in __tests__ folder, that do not contain any tests, but used by *.test.ts files.
If you don't exclude those files with this change,  you'll get "no tests found in file" error from jest

2023-06-20 16:27 UTC, sayan-das-in commented
I have updated the `testPathIgnorePatterns` to `__tests__/__helpers__/` and moved your utils function inside the directory.

2023-06-20 16:32 UTC, sayan-das-in approved these changes

2023-06-21 03:07 UTC, pmunin commented on packages/destination-actions/src/destinations/engage-messaging-twilio/utils/message-sender.ts
> +    statsMethod: TStatsMethod,
done

2023-06-21 08:24 UTC, merged

2023-06-21 08:24 UTC, joe-ayoub-segment commented
Approved and merged only after tests were done in Staging as agreed with @pmunin and Albert Frimpong

2023-06-21 16:08 UTC, joe-ayoub-segment commented
hi @pmunin , @alfrimpong , this PR has been deployed.

2023-06-21 16:09 UTC, pmunin commented
thank you, will start testing now