[Stratconn-2149] - Add Update Support in UpsertCustomObjectRecord Action in Hubspot
segmentio/action-destinations pull request #1341
Opened 2023-06-15 13:15 UTC by Innovative-GauravKochar

This PR is to add an update Support in _upsertCustomObjectRecord_ action in **Hubspot Cloud Action Destination.**
[Jira Ticket](https://segment.atlassian.net/jira/software/c/projects/STRATCONN/boards/310?modal=detail&selectedIssue=STRATCONN-2769&assignee=63617339fc0cc7a600b03c6b)
Tested successfully in **Staging** environment ,Please have a look at [here](https://docs.google.com/document/d/1tKilYtBY_whxbccIWDRzzhub7pW5jnY92Z8Yt0Wxv9A/edit)
## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x] [Segmenters] Tested in the staging environment

2023-06-16 06:11 UTC, varadarajan-tw requested changes
This is a good draft. Left few comments that i would like to be addressed before i review further.

2023-06-16 06:11 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/index.ts
> +        return 'No record found to update and if create new custom record flag is false, will skip creation of new record'
```suggestion
        return 'There was no record found to update. If you want to create a new custom object record in such cases, enable the Create Custom Object Record if Not Found flag'
```

2023-06-16 08:58 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/index.ts
> +      default: true
createNewCustomRecord: This should be default to **true** as this will allow to create an record ,not update.
Updating an record only depends on Search Fields  , if we found an result then it will update else it will look for this property and will decide to create an record or skip it.

**NOTE :**- For an existing customers configurations ,
if it is default to true and custom search fields would be null then it will allow only to create not update

2023-06-21 05:33 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/hubspot/errors.ts
> +  'HubSpot returned 400 error while performing a custom search. Please check if Custom Search Fields’ contains valid properties defined in HubSpot.',
```suggestion
  'HubSpot returned 400 error while performing a custom object record search. Please check if Custom Object Record Search Fields’ contains valid properties defined in HubSpot.',
```

2023-06-21 05:33 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/hubspot/errors.ts
> +  `The search criteria defined by Custom Search Fields returned more than one records. The update request will be rejected.`,
```suggestion
  `The search criteria defined by Custom Object Record Search Fields returned more than one records. The update request will be rejected.`,
```

2023-06-21 05:33 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/hubspot/api/index.ts
> +    for (const [key, value] of Object.entries(searchFields)) {
Suggestion:
Instead of mutating searchPayload here - why can't this piece of code get `properties` and `sorts` array as paramters and build the searchPayload within this method?

2023-06-21 05:33 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/hubspot/upsertCompany/index.ts
> +    const hubspotApiClient: Hubspot = new Hubspot(request, objectType)
```suggestion
    const hubspotApiClient = new Hubspot(request, 'companies')
```

2023-06-21 05:33 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/index.ts
> +    customSearchFields: {
Should this be named customObjectSearchFields or just searchFields? 
```suggestion
    customObjectSearchFields: {
```

2023-06-21 05:33 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/__tests__/index.test.ts
> +  it('should throw an error when custom search field gives multiple records', async () => {
```suggestion
  it('should throw an error when custom object search returns multiple records', async () => {
```

2023-06-21 11:18 UTC, varadarajan-tw approved these changes

2023-06-21 11:18 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/index.ts
> +      if (!payload.createNewCustomRecord) {
nit: Don't think its a good idea to update the payload. 
Also [null coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) should do the job here for checking if the field is set if not defaulting to true.
```suggestion
      const createNewCustomRecord = payload?.createNewCustomRecord?? true
      // If Create New custom object record flag is set to false, skip creation
      if (!createNewCustomRecord) {
```

2023-06-26 10:44 UTC, varadarajan-tw approved these changes

2023-06-27 10:21 UTC, merged

2023-06-27 16:06 UTC, joe-ayoub-segment commented
Hi @Innovative-GauravKochar this PR has been deployed and pushed.