Stratconn 2684 dynamic field to select audience
segmentio/action-destinations pull request #1350
Opened 2023-06-21 18:51 UTC by hvardhan-unth

TikTok require users to input the audience_id that they want to sync to. In this PR the audience id in mapping is converted to dynamic  field. 

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] [Segmenters] Tested in the staging environment

Screenshot:- 
<img width="1505" alt="Screenshot 2023-06-22 at 12 16 12 AM" src="https://github.com/segmentio/action-destinations/assets/117922634/b69ddec4-d35b-4162-b6c8-0e0335a6c125">

2023-06-22 05:49 UTC, varadarajan-tw reviewed
Left few comments. Could you add tests for dynamic fields? [Example](https://github.com/segmentio/action-destinations/blob/70d93d3ccad42ffd8ac5d96b970a0e2d2866a214/packages/destination-actions/src/destinations/hubspot/upsertCustomObjectRecord/__tests__/index.test.ts#L149)

2023-06-22 05:49 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
> +        return tiktok.fetchAudiences(payload.selected_advertiser_id)
For the catch block to work, this statement needs to be awaited.
```suggestion
        return await tiktok.fetchAudiences(payload.selected_advertiser_id)
```

2023-06-22 05:49 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/tiktok-audiences/addUser/index.ts
> +        return tiktok.fetchAudiences(payload.selected_advertiser_id)
Another option is chaining catch and returning a value.
```suggestion
        return tiktok.fetchAudiences(payload.selected_advertiser_id).catch(err => { 
           return {
          choices: [],
          error: {
            message: JSON.stringify(err),
            code: '500'
          }
        }
        }
        })
```

2023-06-22 05:49 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/tiktok-audiences/removeUser/index.ts
> +      }
Pls read suggestions in addUser action and see if you can apply the same.

2023-06-22 05:49 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/tiktok-audiences/api/index.ts
> -  async getAudiences(page_number: number, page_size: number): Promise<GetAudienceAPIResponse> {
was getAudiences get renamed or removed?

2023-06-22 06:14 UTC, hvardhan-unth commented on packages/destination-actions/src/destinations/tiktok-audiences/api/index.ts
> -  async getAudiences(page_number: number, page_size: number): Promise<GetAudienceAPIResponse> {
It is renamed as `fetchAudiences`.

2023-06-22 17:30 UTC, maryamsharif requested changes
Can you include tests on the error messages to ensure they appear correctly? Also, I think this may break mappings customers already have. When I go into my staging destinations that I had set up before it now says that I am missing required fields and it is missing the audience_id I had previously inputed. Please do not merge until we ensure that it will not break customers current mappings.

2023-07-06 21:51 UTC, maryamsharif approved these changes
Based on the tests in here : https://docs.google.com/document/d/1mxw2sVoNlz2UrL1gZNYM-cvJzqS9EafP7WzFgHJL1t4/edit#heading=h.6qlwdta7t6ue changing the field does not cause any breaking changes.

2023-07-11 19:17 UTC, merged