New integration: Prodeology destination
segmentio/action-destinations pull request #1373
Opened 2023-07-03 07:07 UTC by NikolayProdeology

This PR adds [Prodeology](https://app.prodeology.com/) as a new destination.

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-07-03 13:16 UTC, varadarajan-tw commented
@NikolayProdeology - Thank you for raising the PR. This seems like a new action destination. Could you help with answers to the following questions to help me review the PR?
1. Who are the customers this destination intended for and why?
2. Could you give examples of top 3 use cases for the destinations?

2023-07-05 09:45 UTC, NikolayProdeology commented
@varadarajan-tw 

> 1. Who are the customers this destination intended for and why?
> 
Prodeology is a SaaS tool for product managers, therefore the customers using this destinations will be mostly product managers who are using prodeology for making informed decisions when prioritizing their feature backlog.

> 2. Could you give examples of use cases for the destination?
> 
When a customer connects Segment to Prodeology, they will be able to connect specific page events and user events to a feature backlog item. Once set, Prodeology will show a variety of pre-built reports for that feature backlog item.

Below you can see some screenshots of how it will look:

![image](https://github.com/segmentio/action-destinations/assets/134381757/0351ca3d-fc3c-4c92-a89a-4b05ee184be0)

![image](https://github.com/segmentio/action-destinations/assets/134381757/10323765-7675-47b1-a4a9-eebe0742a973)

![image](https://github.com/segmentio/action-destinations/assets/134381757/8365ddb2-8084-4664-929f-08244ada3704)

2023-07-14 19:46 UTC, rhall-twilio requested changes

2023-07-14 19:46 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/prodeology/index.ts
> +  slug: 'prodeology-actions',
this should be called `actions-prodeology` to be aligned with the other slug names.

2023-07-14 19:46 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/prodeology/index.ts
> +        type: 'string',
should likely be `password`

2023-07-14 19:46 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/prodeology/track/index.ts
> +    return request('https://api-dev.prodeology.com/api/v1/event-collection/track', {
How does Prodeology identify who the calling user is? From the API Key?

2023-07-24 13:50 UTC, sayan-das-in requested changes
In multiple places API calls points to `api-dev.prodeology.com` instead of `api.prodeology.com`, is this intended ?

2023-07-24 13:50 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/prodeology/index.ts
> +      return request('https://api-dev.prodeology.com/api/v1/event-collection/validate-api-key', { method: 'GET' })
Here's one more instance where it points to `api-dev.prodeology.com` instead of `api.prodeology.com`.

2023-07-24 13:50 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/prodeology/page/index.ts
> +    return request('https://api-dev.prodeology.com/api/v1/event-collection/page', {
Here's one more instance where it points to `api-dev.prodeology.com` instead of `api.prodeology.com`.

2023-07-25 07:35 UTC, NikolayProdeology commented on packages/destination-actions/src/destinations/prodeology/index.ts
> +      return request('https://api-dev.prodeology.com/api/v1/event-collection/validate-api-key', { method: 'GET' })
Hi @sayan-das-in 
The multiple API calls pointing to `api-dev.prodeology.com` instead of `api.prodeology.com` are intended for the time being. We would like to verify the functionality on `api-dev.prodeology.com` first, and after thorough testing and confirmation, we will update the calls to `api.prodeology.com`

2023-07-27 18:12 UTC, sayan-das-in approved these changes
LGTM!

**Follow up notes:**
All API call currently goes to `api-dev.prodeology.com` instead of `api.prodeology.com`. A follow up PR will be raised by Prodeology dev team to edit the endpoints after testing with the dev endpoint.

2023-07-27 18:12 UTC, merged

2023-08-02 15:39 UTC, joe-ayoub-segment commented
Hi @NikolayProdeology , this PR is now live.