Pre-commit hook to catch secrets
segmentio/action-destinations pull request #138
Opened 2021-09-07 19:00 UTC by nick-Ag

To prevent committing certain secrets this PR adds a pre commit hook which uses trufflehog to check for secrets that a user might have added.

<img width="1379" alt="Screen Shot 2021-09-07 at 11 36 46 AM" src="https://user-images.githubusercontent.com/27820201/132397013-95f793ba-12fd-4538-b56f-adfcf659526f.png">

2021-09-07 19:01 UTC, nick-Ag commented on .husky/pre-commit
> +git diff --name-only --cached > .husky/.included.txt
What would be a better way to do this?

2021-09-07 19:01 UTC, nick-Ag commented on .husky/trufflehog-rules.json
> +{
truffle uses this regex file to check for secrets

2021-09-07 19:05 UTC, nick-Ag commented on package.json
> +    "prepare": "husky install"
I'm using husky to manage the precommit hook because it looks like that's what is already being used in the `.git` folder on my machine. The folder is untracked however and I have some questions about where exactly I should add the script?

2021-09-07 22:02 UTC, lcampos commented on .husky/pre-commit
> +trufflehog .git --rules .husky/trufflehog-rules.json --include_paths .husky/.included.txt --regex --entropy=NO #entropy checks throw too many false positives
Have you looked at ways in which to kick off installing trufflehog when it's not available in the machine ?

2021-09-07 22:41 UTC, marinhero commented on .husky/pre-commit
> +#!/bin/sh
Also add this for safer execution of the script

`set -euo pipefail`

2021-09-07 23:00 UTC, marinhero commented on .husky/pre-commit
> +trufflehog .git --rules .husky/trufflehog-rules.json --include_paths .husky/.included.txt --regex --entropy=NO #entropy checks throw too many false positives
Add checks for python, pip, and trufflehog. If they are not available install them.

2021-09-07 23:04 UTC, marinhero commented on .husky/trufflehog-rules.json
> +{
Add a comment with the source of these regular expressions.

2021-09-07 23:05 UTC, marinhero requested changes
Thank you for taking the time to go thru this over a Zoom call. I left the comments as a reminder of the things we talked about. Let me know when I can take another look.

2021-09-08 02:15 UTC, nick-Ag commented
Trufflehog was unable to check files which were uncommitted and so wasn't well suited as a pre-commit hook. Fortunately gitleaks has this option with the `--unstaged` flag. It also allows for better custom rule extensions with the `--additional-config` flag. This commit switches from trufflehog to gitleaks for that reason and has output that looks like:
<img width="1593" alt="Screen Shot 2021-09-07 at 6 52 10 PM" src="https://user-images.githubusercontent.com/27820201/132434838-bda9aa3f-ebf2-4625-b14e-cac9cbb87e85.png">

2021-09-08 02:16 UTC, nick-Ag commented on .husky/pre-commit
> +gitleaks --repo-url=.git -v --additional-config=".husky/gitleaks-rules.toml" --branch=$BRANCH --unstaged || true
Do we want the commit to be canceled if a secret is detected?

2021-09-08 13:13 UTC, Whamo12 commented on .husky/pre-commit
> +gitleaks --repo-url=.git -v --additional-config=".husky/gitleaks-rules.toml" --branch=$BRANCH --unstaged || true
That would be a safe option.  If a secret is detected the commit should fail but it'll still be in staging.

2021-09-09 21:04 UTC, gpsamson commented on package.json
> +    "prepare": "husky install"
I don't quite follow here. Are you asking if we should use the default `.husky` directory or use some other directory?

2021-09-09 22:00 UTC, mshwery commented on package.json
> +    "prepare": "husky install"
I would add it to lint-staged.

2021-09-17 17:39 UTC, marinhero commented on .husky/gitleaks-rules.toml
> +  description = "Facebook System User Access Token"
You should include a section on the README that reminds other developers to include new regexes whenever they introduce a new token.

2021-09-17 17:40 UTC, marinhero commented on .husky/pre-commit
> +`#!/usr/bin/env bash`
Shouldn't this be 
```suggestion
#!/usr/bin/env bash
```
?

2021-09-17 17:46 UTC, marinhero commented on .husky/pre-commit
> +        if ! command -v brew -v &> /dev/null
Run this only on a mac
```suggestion
        if [ "$(uname)" == "Darwin" ]; then
            if ! command -v brew -v &> /dev/null
            then
                /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            fi
        brew install gitleaks
        else
             echo "Unable to automatically install gitleaks. Install it yourself"
        fi
```

2021-09-17 17:46 UTC, marinhero commented on .husky/pre-commit
> +        if ! command -v brew -v &> /dev/null
Sorry indentation is weird!

2021-09-17 17:47 UTC, marinhero commented on .husky/pre-commit
> +git diff --name-only --cached > .husky/.included.txt
I think this is ok 👍

2021-10-14 03:08 UTC, gpsamson commented
> @daltonscharff and I have been testing this out locally for a couple weeks now and the main functionality is working as expected. Users would be able to install the husky and lint-staged dependencies with a `yarn install` and if they don't have gitleaks installed the husky pre-commit hook will install it. @gpsamson Do you think there are additional first-time setup steps this script should do?

Chatted about this out of band in Slack. In short, I think all looks fine but I would caution against the assumption that every developer will be on MacOS and have `brew` installed. This is usually the case for Segmenters (majority of devs in this repo) but we should still catch a failure and notify the user.

I am not sure if we want to fail the commit if `gitleaks` can't be installed and ran. This might be a question to pose in a Github Discussion post and share in our actions-collab Slack channel.

2021-10-14 03:23 UTC, mericsson commented
> > @daltonscharff and I have been testing this out locally for a couple weeks now and the main functionality is working as expected. Users would be able to install the husky and lint-staged dependencies with a `yarn install` and if they don't have gitleaks installed the husky pre-commit hook will install it. @gpsamson Do you think there are additional first-time setup steps this script should do?
> 
> Chatted about this out of band in Slack. I think all looks fine but I would caution against the assumption that every developer will be on MacOS and have `brew` installed. This is usually the case for Segmenters (majority of devs in this repo) but we should still catch a failure and notify the user.
> 
> I am not sure if we want to fail the commit if `gitleaks` can't be installed and ran. This might be a question to pose in a Github Discussion post and share in our actions-collab Slack channel.

Perhaps we update to only run if `OS == MacOS and brew is installed`? Then we can potentially add a follow-up to consider platform independent implementation?

2021-10-15 22:22 UTC, nick-Ag commented
> > > > @daltonscharff and I have been testing this out locally for a couple weeks now and the main functionality is working as expected. Users would be able to install the husky and lint-staged dependencies with a `yarn install` and if they don't have gitleaks installed the husky pre-commit hook will install it. @gpsamson Do you think there are additional first-time setup steps this script should do?
> > > 
> > > 
> > > Chatted about this out of band in Slack. I think all looks fine but I would caution against the assumption that every developer will be on MacOS and have `brew` installed. This is usually the case for Segmenters (majority of devs in this repo) but we should still catch a failure and notify the user.
> > > I am not sure if we want to fail the commit if `gitleaks` can't be installed and ran. This might be a question to pose in a Github Discussion post and share in our actions-collab Slack channel.
> > 
> > 
> > Perhaps we update to only run if `OS == MacOS and brew is installed`? Then we can potentially add a follow-up to consider platform independent implementation?
> 
> Ahh :nice: -- this works for me. It'll solve for the common case :)

Implemented this suggestion of running only on MacOS. I successfully tested on an Ubuntu machine, my local (Segment) machine, and my personal laptop (MacOS) to check if open-source users can install fine. This is ready to merge in after a review.

2021-10-21 19:31 UTC, merged