pushwoosh integration
segmentio/action-destinations pull request #1385
Opened 2023-07-07 08:15 UTC by shaders

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-07-07 17:37 UTC, maryamsharif commented
@shaders - Thank you for the PR.

This seems like a new destination. Could you help me with answers to the following questions? This will help us understand and give you feedback appropriate for the destination.

What type of customers would want to use this destination?
Could you provide top 3 scenarios on how they would want to use it?

2023-07-31 13:40 UTC, joe-ayoub-segment commented
Hi @shaders , 

@maryamsharif was helping review PRs while I was out, however I'm back now so I'll be picking this up. Apologies for any delays to getting this review. I do have a large backlog to get through but I'll provide feedback as soon as I can. 

Kind regards,
Joe

2023-08-03 12:36 UTC, joe-ayoub-segment requested changes
Hi @shaders , 
Thanks for raising this PR. 
I've done a cursory review and would like to chat with you regarding a couple of topics (IS resolution and batching). 

Would you be OK scheduling a call with me please?
Here's my Calendly link: http://calendly.com/joe_ayoub/integration-workshop

Best regards,
Joe

2023-08-03 12:36 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/pushwoosh/index.ts
> +      name: 'Update User Profile',
Does this create and/or update a user profile?

2023-08-03 12:36 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/pushwoosh/updateUserProfile/index.ts
> +  title: 'Update User Profile',
Does this create and/or update a user profile?

2023-08-03 12:36 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/pushwoosh/updateUserProfile/index.ts
> +    },
Given this is a new Integration I think it would be worth having a face to face conversation about the identifiers PushWoosh needs in each API call. 
Right now it looks like you'll only be expecting events from users who are logged in (Segment calls these "Known Users"). You will not be collecting events from anonymous users unless a change is made.

2023-08-03 12:36 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/pushwoosh/updateUserProfile/index.ts
> +        '@path': '$.email'
```suggestion
        '@path': '$.traits.email'
```

2023-08-03 12:36 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/pushwoosh/updateUserProfile/index.ts
> +      }
You'll rarely see any of this data sent by customers.

2023-08-03 12:36 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/pushwoosh/utilities.ts
> +}
Let's have a chat about the benefits, drawbacks and considerations to keep in mind if you are sending batches to your platform. 

- what's the max payload size your platform will accept?
- what type of response will your API send if there are some failures and some successes from a batch event?
- etc...

2023-08-14 11:40 UTC, joe-ayoub-segment commented
Hi @shaders , 

I'm following up regarding a PR which was raised a few weeks ago. 

https://github.com/segmentio/action-destinations/pull/1385 

I was not able to approve the PR as I'm lacking some context. 

Would you be available to meet with me to discuss the PR please?

You can schedule a call with me using this link: http://calendly.com/joe_ayoub/integration-workshop

Kind regards,
Joe

2023-08-17 15:38 UTC, joe-ayoub-segment approved these changes

2023-08-24 09:23 UTC, merged