Hilo destination
segmentio/action-destinations pull request #1390
Opened 2023-07-11 16:14 UTC by sorich87

_A summary of your pull request, including the what change you're making and why._

This is a new Segment destination.

**Type of customers who would want to use this destination**

Hilo is a data activation platform that helps customers find qualified leads from all their data sources, whether that’s product, marketing, community, support, and more. This destination will be used by current and future Hilo customers, who are marketers or sales people in B2B SaaS and ecommerce companies.

**How they would want to use it**

Hilo customers may already have usage events in Segment. If they don't, we recommend Segment as a way to quickly connect product usage and marketing data to Hilo.

Once the integration is connected, Hilo uses the data, in combination with other data sources, like Apollo, Salesforce and Hubspot, to generate a list of leads who have done specific actions within specific time frames, indicating that they might be potential buyers. It helps Hilo customers to reach out to the right person at the right time.

**Please let me know if there's anything else to clarify.**

**Also, this destination uses OAuth2. Let me know if there's anything else we need to do, as I've seen in the documentation that it's experimental.**

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-07-12 21:27 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/hilo/index.ts
> +          client_id: auth.clientId,
Are these client_id, client_secret global for all customers and owned by Hilo's team?

2023-07-13 07:12 UTC, sorich87 commented on packages/destination-actions/src/destinations/hilo/index.ts
> +          client_id: auth.clientId,
Thanks for the review, @rhall-twilio. Yes, they're global for all customers and owned by Hilo's team.

Thomas from your partner support team told me we'll be able to enter them in the developer portal, as shown in the below screenshot, after this PR is merged.

Let me know if there's anything else we need to do.

![unnamed](https://github.com/segmentio/action-destinations/assets/230367/970653fe-3707-4ebd-90fd-7f4c809c8444)

2023-07-14 16:35 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/hilo/index.ts
> +          client_id: auth.clientId,
In that case, you will want to change your authentication scheme from `oauth2` to `oauth-managed` so that the service knows to read the credentials from this portal.

2023-07-14 19:11 UTC, sorich87 commented on packages/destination-actions/src/destinations/hilo/index.ts
> +          client_id: auth.clientId,
Thanks @rhall-twilio. I just changed it.

2023-07-18 00:27 UTC, rhall-twilio commented
hey @sorich87 it looks like some testcases are failing, the timestamps seem to be off by an hour or two.

2023-07-18 06:57 UTC, sorich87 commented
@rhall-twilio Thanks! It seems I didn't have the proper timezone set in my development environment. I updated the test snapshots after setting TZ=UTC. The test cases should pass now.

2023-07-24 04:46 UTC, sayan-das-in commented
Hi @sorich87, there's still TZ related issues in test cases, it is still failing with an offset of +5:30 hours (I am from IST TZ).

2023-07-24 04:51 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/hilo/group/index.ts
> +  fields: {
```suggestion
  description: 'Create or update an account in Hilo',
  defaultSubscription: 'type = "group"',
  fields: {
```

2023-07-24 04:51 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/hilo/identify/index.ts
> +  fields: {
```suggestion
  defaultSubscription: 'type = "identify"',
    defaultSubscription: 'type = "identify"',
  fields: {
```

2023-07-24 04:52 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/hilo/page/index.ts
> +      description: 'An anonymous identifier',
```suggestion
      type: 'string',
        defaultSubscription: 'type = "page"',
      description: 'An anonymous identifier',
```

2023-07-24 04:52 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/hilo/screen/index.ts
> +  fields: {
```suggestion
  description: 'Track mobile screen view in Hilo',
  defaultSubscription: 'type = "screen"',
  fields: {
```

2023-07-24 04:53 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/hilo/track/index.ts
> +  fields: {
```suggestion
  description: 'Track event in Hilo',
  defaultSubscription: 'type = "page"',
  fields: {
```

2023-07-24 04:56 UTC, sayan-das-in requested changes
Hi @sorich87, This PR looks mostly okay to me, just a couple of changes required as suggested above.

2023-07-24 08:03 UTC, sorich87 commented
Thanks, @sayan-das-in! I made the changes to the defaultSubscription.

Please can you point me to the remaining TZ issues? I don't see any TZ issue in the last CI run: https://github.com/segmentio/action-destinations/actions/runs/5584271221

2023-07-24 11:02 UTC, sayan-das-in commented
Hi @sorich87, the test cases and snapshots are timezone sensitive. I got a total of 6 failed test cases when I tried to run the tests locally using `yarn cloud test`. The following screenshot is from one of the failed tests, other failed tests gives similar output. Even though this may not appear to fail in CI/CD pipeline this will fail for all local development.

![image](https://github.com/segmentio/action-destinations/assets/109198085/b32b6a5e-6bbc-4da3-afda-5eb0804be8ba)

![image](https://github.com/segmentio/action-destinations/assets/109198085/647154a6-fe2f-44b3-9426-3d0e6431f02f)

2023-07-24 12:06 UTC, sayan-das-in commented
Follow the steps to reproduce the issue

- Delete all snapshots in `__tests__/__shapshots__`, repeat the same for snapshots in each actions directory.
- Run `yarn cloud test` from the project's root directory, this would create re-create the snapshots
- Change your dev system's time zone to anything other than your current TZ
- Run `yarn cloud test` again

2023-07-24 12:27 UTC, sorich87 commented
Thanks, @sayan-das-in! I was able to reproduce and it should be fixed now.

Doing it the same way as the qualtrics destination didn't work, but I was able to find that the june and ripe destination have a way to handle it, so I did the same.

Let me know if it works for you now.

2023-07-24 13:55 UTC, sayan-das-in approved these changes
Thanks @sorich87 for making the changed. This looks good to me.

2023-07-24 13:56 UTC, merged

2023-07-24 16:43 UTC, sorich87 commented
Thanks @sayan-das-in! I really appreciate your help.

2023-07-26 07:02 UTC, sorich87 commented
@sayan-das-in quick question: what's the next step now? Will I receive an email or something to set up the OAuth information?

2023-07-31 14:56 UTC, joe-ayoub-segment commented
Hi @sorich87 . 

My colleagues @sayan-das-in and @rhall-twilio were filling in for me while I was on leave. I'm back now, so I'll be your main point of contact regarding the code for your Integration. 

There's a few next steps which I'd like to send you via email. This will include details of where you'll supply your oauth details. 

Could you reach out to me by email please? jayoub@twilio.com 

Kind regards,
Joe

2023-08-08 10:59 UTC, sorich87 commented
Thanks for offering to help @joe-ayoub-segment ! I contacted Thomas from the Partner Support team who was able to help.

We found an issue when testing the destination, and I just submitted another PR to fix it. https://github.com/segmentio/action-destinations/pull/1476