Sdk 3485/segment subscription groups
segmentio/action-destinations pull request #1400
Opened 2023-07-14 12:28 UTC by davidbielik

Adds a new Action to Set Subscription Groups.

The expected use is a customer calling:
```
analytics.identify("id", {
  braze_subscription_groups: [{
          "subscription_group_id": "5ertykiuyfjyttgkf",
          "subscription_state": "unsubscribed"
      }, {
          "subscription_group_id": "ytghkuguymjghb",
          "subscription_state": "unsubscribed"
    }]
})
```

We would loop through each group and call the `addToSubscriptionGroup`/`removeFromSubscriptionGroup` methods.

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-07-16 16:18 UTC, davidbielik commented
@spvismaya @wesleyorbin FYI

2023-07-17 16:23 UTC, davidbielik commented on packages/browser-destinations/destinations/braze/src/__tests__/updateUserProfile.test.ts
> +          changeUser: expect.any(Function)
@pooyaj question for your team - this doesn't actually test that the method was called, i think it just checks that the Braze SDK loaded has that method in its JSON. 

Is there a way to check that a given braze sdk method was called? I'm not sure how valuable this test assertion is.

2023-08-01 11:22 UTC, joe-ayoub-segment commented
hi @pooyaj - I'm just back from leave and am catching up on everything. Will you be completing this PR review?

2023-08-01 16:22 UTC, davidbielik commented
Tested it via the actions tester and looks good on my end!

2023-08-11 14:57 UTC, joe-ayoub-segment commented
Hi @pooyaj , 
I just had a call with @davidbielik where we discussed options for testing this Integration. 
Would it be possible to deploy this so that it's only available for David's Workspace?
David's Workspace slug is braze-sdks 

Thanks,
Joe

2023-08-11 15:06 UTC, joe-ayoub-segment requested changes

2023-08-11 15:06 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/braze/src/updateUserProfile/index.ts
> +    if (payload.external_id && typeof payload.external_id === 'string') {
This change isn't needed.

2023-08-11 15:06 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/braze/src/updateUserProfile/index.ts
> +    if (payload.custom_attributes && typeof payload.custom_attributes === 'object') {
The change on this line isn't necessary

2023-08-11 15:09 UTC, joe-ayoub-segment commented
Hi @pooyaj , 
I just had a call with @davidbielik where we discussed options for testing this Integration. 
Would it be possible to deploy this so that it's only available for David's Workspace?
David's Workspace slug is braze-sdks 

Also @davidbielik , can you please attach some testing screenshots? Other than that the PR looks good to me! 

Thanks,
Joe

2023-08-11 16:25 UTC, davidbielik commented
Braze /v3/data payload shows correct custom attributes (excluding sub groups) and correct "events" to add subscription groups (excluding the "bad" one)
<img width="871" alt="image" src="https://github.com/segmentio/action-destinations/assets/7410770/5dfc6154-8c51-4530-be4a-476e85ff756f">

<img width="1512" alt="image" src="https://github.com/segmentio/action-destinations/assets/7410770/eb39b469-18c2-45c2-abbd-8be80891de85">

2023-08-14 10:12 UTC, joe-ayoub-segment approved these changes
Looks good, thanks for adding the test payloads.

2023-08-14 10:12 UTC, joe-ayoub-segment commented
Hi @pooyaj can this go out with the next web deploy?

2023-08-16 16:29 UTC, pooyaj commented on packages/browser-destinations/destinations/braze/src/__tests__/updateUserProfile.test.ts
> +          changeUser: expect.any(Function)
@davidbielik That's right, the test is not valuable because it just tests the perform method, rather than what the braze SDK is being called with. Not a blocker, but we can improve the tests using examples from other destinations: https://github.com/segmentio/action-destinations/blob/main/packages/browser-destinations/destinations/hubspot-web/src/trackPageView/__tests__/index.test.ts

2023-08-22 15:55 UTC, davidbielik commented
Hi @joe-ayoub-segment @pooyaj any update on this one?

2023-08-22 16:09 UTC, joe-ayoub-segment commented
Hi @davidbielik this is ready to deploy. We're in a deploy freeze at the moment. 
@pooyaj , when can we schedule a Web deploy? Would we do it Monday 28th?

2023-08-23 16:08 UTC, merged