Feature/sSD-91672
segmentio/action-destinations pull request #1433
Opened 2023-07-24 08:14 UTC by esezerguven

We added optin information

## Testing

we have tested on our side

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-07-25 17:17 UTC, marinhero commented on packages/destination-actions/src/destinations/insider-audiences/insiderAudiences/index.ts
> +      label: 'GDPR Optin',
I believe "optin" is instead "opt in". Since these are labels and descriptions, consider changing it for better readability and correctness.

2023-07-25 17:22 UTC, marinhero requested changes
I need more information regarding the use of `undefined` before approving. We have a type system and I think it's better if we lean into it.

Also, consider changing "optin" for "opt-in". 

Thank you for your help and patience!

2023-07-26 15:12 UTC, esezerguven commented on packages/destination-actions/src/destinations/insider-audiences/insiderAudiences/index.ts
> +      default: undefined,
This field shows user email optin which means that can we send email to user. If it is false we set user optin field as false and on our side is user is not reachable. If we get undefined we dont change user and keep optin information as previous.

2023-07-27 07:09 UTC, esezerguven commented
Hello @marinhero can you please check and update. As I know you have deployment today. If it is possible we want to be ready and live today. Thanks

2023-08-01 15:21 UTC, emreisik95 commented
> Hi @esezerguven ,
> 
> @marinhero was filling in for me while I was on leave, but I'm back now and will pick up this PR. I have a sizable backlog to get through so please bear with me!
> 
> In the meantime, would it be possible to split this PR into 2 separate PRs, one for each Destination? This is in case we need to roll back for some reason.
> 
> Best regads, Joe

Hello Joe,

It is a bit urgent for us. Can we keep it like that and merge? Next time if we change or add something we will open seperate PRs for each destination.

Best regards, Emre

2023-08-02 08:34 UTC, joe-ayoub-segment commented
Hi @emreisik95 , 

I'm very sorry but it's a hard rule we have after some incidents which happened in the past. We can't allow a PR with changes to multiple Destinations. 

This PR won't be going out this week anyway, so the earliest it will go out is Tuesday next week (8th August). 

Kind regards,
Joe

2023-08-02 10:54 UTC, emreisik95 commented
> Hi @emreisik95 ,
> 
> I'm very sorry but it's a hard rule we have after some incidents which happened in the past. We can't allow a PR with changes to multiple Destinations.
> 
> This PR won't be going out this week anyway, so the earliest it will go out is Tuesday next week (8th August).
> 
> Kind regards, Joe

Hello @joe-ayoub-segment,

Thank you for your update.

We will separate the tasks ASAP. Thank you for your help!

Best regards,
Emre

2023-08-03 17:42 UTC, emreisik95 commented
Hello again @joe-ayoub-segment,

I separated destinations. You can find insider destination at #1465 PR.

If you have any additional comments I am here.

Regards, 
Emre

2023-08-08 11:35 UTC, joe-ayoub-segment commented
Hi @emreisik95 , just following up on this to see if you've seen my comments?

2023-08-08 12:06 UTC, emreisik95 commented
> Hi @emreisik95 , just following up on this to see if you've seen my comments?

Hello,

Yes, I saw your comment but I need to align with our side, after that I'll write here. We can postpone to merge this.

2023-08-08 12:11 UTC, joe-ayoub-segment commented
Thanks @esezerguven , could we convert this to a draft PR for now please?

2023-08-08 13:00 UTC, closed without merging