Sc 25493 add all new endpoints to segment
segmentio/action-destinations pull request #1459
Opened 2023-08-01 07:36 UTC by rubyjohn93

We have added 3 new endpoints to talon-integration. This PR aims at adding these 3 endpoints to segment.

The new endpoints mainly support a new query param `skipNonExistingAttributes` compared to their previous versions.

This flag indicates whether to skip non-existing attributes.
If `true`, the non-existing attributes are skipped and a 400 error is not returned.
If `false`, a 400 error is returned in case of non-existing attributes.
## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-08-03 15:16 UTC, joe-ayoub-segment commented
Hi @rubyjohn93 thanks for raising this PR. I'll schedule for review.

2023-08-08 12:26 UTC, joe-ayoub-segment commented
Thanks for raising this PR @rubyjohn93 , 

I'd like to have a little more context about these changes so I can be more informed when reviewing the PR. 
Would you be OK scheduling a call with me via this Calendly link please?
http://calendly.com/joe_ayoub/integration-workshop

Best regads,
Joe

2023-08-14 11:47 UTC, joe-ayoub-segment commented
Hi @rubyjohn93 , Alex and Krishna, 

Please let me know once you've updated the PR based on our discussion, and that you are happy for me to rereview. 

Best regards,
Joe

2023-08-14 15:27 UTC, rubyjohn93 commented
> Hi @rubyjohn93 , Alex and Krishna,
> 
> Please let me know once you've updated the PR based on our discussion, and that you are happy for me to rereview.
> 
> Best regards, Joe

Hi @joe-ayoub-segment 
We will make these changes and get back to you.
Sorry about the delay.

2023-08-17 14:43 UTC, kkupreeva commented on packages/destination-actions/src/destinations/talon-one/updateCustomerProfileV2/index.ts
> +  title: '[Deprecated] Update Customer Profile V2',
Maybe have just `[Deprecated] Update Customer Profile`  as a title? without V2. This action is about updating customer profile, but the version is not an important info for clients

2023-08-17 14:48 UTC, kkupreeva commented on packages/destination-actions/src/destinations/talon-one/updateCustomerSession/index.ts
> +  title: '[Deprecated] Update Customer Sessions',
maybe `[Deprecated] Update Customer Session`? Without `s` at the end? Because we update only one session

2023-08-17 15:09 UTC, kkupreeva approved these changes
LGTM 👍

2023-08-18 10:19 UTC, vignesh-giridharan commented on packages/destination-actions/src/destinations/talon-one/updateCustomerProfile/index.ts
> +  title: '[Deprecated] Update Customer Profile',
Can we match the name from [docs](https://docs.talon.one/third-party-api#tag/Segment/operation/segment/)?
```
[Deprecated] Upsert customer profile
```

2023-08-18 11:09 UTC, rubyjohn93 commented
> Hi @vignesh-giridharan and @rubyjohn93 , I can see that you're still working on this so I'll hold off on approving it. Please message me directly here to let me know when you are done :)

@joe-ayoub-segment Yes, @vignesh-giridharan is from our docs team and we are working on making the mappings name in segment and our docs the same, so that the customers can easily relate both. I'll make the proposed changes and once everything is finalised I'll ping you here.

2023-08-21 09:19 UTC, rubyjohn93 commented
@joe-ayoub-segment 
A small update on this PR. 

I have completed the changes you proposed, in the scope of this repo. I incorporated a few suggestion from our docs team as well. 
But regarding your other comment for docs repo
```
We agreed that we'd add a new paragraph to the Segment docs to explain which Actions are deprecated, and which ones should be used going forward.
```
This change will be picked up by our docs team later in their pipeline and hopefully they will raise a PR by next week.

I would like to request you to wait till then so that we can make avail both PRs ready for your review.
Thank you!
cc: @vignesh-giridharan @kkupreeva @gotgelf

2023-08-21 14:20 UTC, joe-ayoub-segment requested changes
Hi @rubyjohn93 , few more minor changes.

2023-08-21 14:20 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/talon-one/updateCustomerProfileV2/index.ts
> +  **Important:** This endpoint is deprecated. Use the current **Update customer profile** endpoint instead.`,
```suggestion
  description: `You do not have to create attributes or audiences before using this Action. **Important:** This Action is deprecated. Use the **Update customer profile** Action instead.`,
```

2023-08-21 14:20 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/talon-one/updateCustomerSession/index.ts
> +  **Important:** This endpoint is deprecated. Use the current **Update customer session** endpoint instead.`,
```suggestion
  description: `This updates a customer session. **Important:** This Action is deprecated. Use the **Update customer session** Action instead.`,
```

2023-08-21 14:20 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/talon-one/updateCustomerProfileV3/index.ts
> +    'This updates attributes and audiences for a single customer profile. Create all the required attributes and audiences before using this endpoint.',
```suggestion
    'This updates attributes and audiences for a single customer profile. Create all the required attributes and audiences before using this Action.',
```

2023-08-21 14:20 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/talon-one/updateCustomerSessionV2/index.ts
> +  description: 'This updates a customer session. Create all the required attributes before using this endpoint.',
```suggestion
  description: 'This updates a customer session. Create all the required attributes before using this Action.',
```

2023-08-22 07:52 UTC, rubyjohn93 commented
> Hi @rubyjohn93 , few more minor changes.

Hi @joe-ayoub-segment,

Thank you for the review. Made these changes.
Now all the descriptions are in single line and changed `endpoint` to `Action`.

2023-08-22 08:56 UTC, joe-ayoub-segment approved these changes

2023-08-22 08:58 UTC, joe-ayoub-segment commented
hi @rubyjohn93 thanks for making the changes. I've approved the PR. Waiting on CI checks to pass. If they do, we plan to deploy Thursday 24th August.

2023-08-22 11:15 UTC, rubyjohn93 commented
Hi @joe-ayoub-segment 
Thank you!
Seems like one [test](https://github.com/segmentio/action-destinations/actions/runs/5935960260/job/16097468262?pr=1459) failed due to some authentication issue. Can you please check when you have time.

2023-08-22 16:01 UTC, joe-ayoub-segment commented
hi @rubyjohn93 , nope we're good. The Synk test fails unless it's an internal PR. We're good to deploy Thursday.

2023-08-22 16:14 UTC, rubyjohn93 commented
> hi @rubyjohn93 , nope we're good. The Synk test fails unless it's an internal PR. We're good to deploy Thursday.

Thank you 👍  
As I mentioned earlier, the docs PR will be raised by next week.
Thanks again for your support throughout the process 🙇‍♀️

2023-08-24 09:24 UTC, merged

2023-08-24 14:29 UTC, joe-ayoub-segment commented
Hi @rubyjohn93 this PR has been deployed.