Extra context fields requested by client.
segmentio/action-destinations pull request #1462
Opened 2023-08-02 21:45 UTC by seg-leonelsanches

Client requested optional mappings for context fields to be sent to Mixpanel (all supported events).

## Testing

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [X] [Segmenters] Tested in the staging environment

2023-08-02 21:48 UTC, shouri-thangellapalli commented on packages/destination-actions/src/destinations/mixpanel/mixpanel-properties.ts
> +      '@path': '$.context.timezone'
$.context.app.platform?

2023-08-02 21:50 UTC, seg-leonelsanches commented on packages/destination-actions/src/destinations/mixpanel/mixpanel-properties.ts
> +      '@path': '$.context.timezone'
Fixed.

2023-08-09 23:50 UTC, marinhero reviewed
This looks good to me. Letting @joe-ayoub-segment have the final say.

2023-08-11 12:34 UTC, joe-ayoub-segment requested changes
Hi @seg-leonelsanches , 
Just one question about a field description. 
Other than that it looks fine to me. 

Note that this change will affect all customers who configure a new instance of a Mixpanel Destination going forward. 

Customers with Mixpanel already configured as a Destination will need to open the Destination configuration, ensure that there are paths configured for the new fields, then save the Destination configuration. 

Regards.
Joe

2023-08-11 12:34 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/mixpanel/mixpanel-properties.ts
> +    description: 'The Event Original Name, if applicable',
Hi @seg-leonelsanches , 

screen() and page() events might contain a value at the `$.name` path. They will never contain any value at the `$.event` path. 

track() events never contain a value at the `$.name` path, but always contain a value at the `$.event` path. 

So I'm not sure if your description for this field is accurate, or if you are configuring it to collect the information you think will be at that path. 

Maybe the description just needs to read "The name of the page or screen, if applicable", or something like that?

Happy to discuss if you can explain a little more about what the customer wants to collect with this field.

2023-08-11 16:11 UTC, seg-leonelsanches commented on packages/destination-actions/src/destinations/mixpanel/mixpanel-properties.ts
> +    description: 'The Event Original Name, if applicable',
Hi @joe-ayoub-segment, 

In fact this is something that the client asked to send downstream. They want to pass two names: one for the mapped event, another one for the event original name. I believe this can be used also for page() and screen(), and I can improve the description.

2023-08-14 10:06 UTC, joe-ayoub-segment commented
Approved - will merge prior to deploy. scheduled for 15-August-23

2023-08-15 09:16 UTC, merged