Added CDP Resolution Browser Action
segmentio/action-destinations pull request #1488
Opened 2023-08-09 17:42 UTC by ajaysikri

_A summary of your pull request, including the what change you're making and why._

Adding CDP Resolution browser action. On load of the page, the browser will "fetch" an endpoint on the browser passing in the customer identifier (provided to segment.io customers) and the anonymous ID for the session.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

TESTING NOTE: Used the action tester to "send page load" test event.  In the network traffic, the expected call and the parameter values are sent to the endpoint.  Ensured the endpoint was receiving the call and the values in the expected format.

2023-08-21 15:15 UTC, joe-ayoub-segment requested changes
Hi @ajaysikri , 

Thanks for raising this PR and apologies we're only getting to it now. 

Given your PR is for a new Destination I'd like to sync with you to discuss the use-cases for it, and to review the code together. 

The code you've submitted doesn't load a 3rd party library, and only seems to collect the end user's anonymousId, which is unusual. 

Having a discussion should help me better understand what you'd like to accomplish. 

Would you be available to meet? You can schedule a call with me using this Calendly link: 

http://calendly.com/joe_ayoub/integration-workshop

I look forward to hearing from you. 
Regards,
Joe

2023-08-23 08:56 UTC, joe-ayoub-segment commented
hi @ajaysikri , just following up on this PR again. Is it something you'd like to proceed with?
Best regards,
Joe

2023-08-29 19:26 UTC, ajaysikri commented
Hi Joe,

I have update the code to reflect the changes we discussed.

Thanks, Ajay

2023-08-30 16:12 UTC, joe-ayoub-segment requested changes

2023-08-30 16:12 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/cdpresolution/package.json
> +    "@segment/browser-destination-runtime": "^1.4.0"
```suggestion
    "@segment/browser-destination-runtime": "^1.12.2"
```

Hi @ajaysikri , could you update the version as specified please?

2023-09-01 12:29 UTC, ajaysikri commented on packages/browser-destinations/destinations/cdpresolution/package.json
> +    "@segment/browser-destination-runtime": "^1.4.0"
Hi Joe,

I have updated the version as requested.

Thanks, Ajay

2023-09-07 21:42 UTC, ajaysikri commented
Hi @joe-ayoub-segment.  I have committed the suggested change.  Looking forward to any next steps.  Thanks, Ajay

2023-09-08 09:43 UTC, joe-ayoub-segment commented
hi @ajaysikri apologies for the delay with this, I was out ill. 

There are still a few minor things which will need to be fixed before I can merge. 

The linter is complaining about the initialize function having unused params and variables. 

Also, a valid unit test will need to be added. 

Finally, could you add a description to the Destination please? 
Something like this: 

export const destination: BrowserDestinationDefinition<Settings, unknown> = {
  name: 'Cdpresolution',
  slug: 'actions-cdpresolution',
  `description: 'Sync Segment anonymousId to CDP Resolution',  `
  mode: 'device',

2023-09-14 10:07 UTC, joe-ayoub-segment commented
Hi @ajaysikri just following up on this. Did you see my earlier comment above?
Best regards,
Joe

2023-09-14 12:46 UTC, ajaysikri commented on packages/browser-destinations/destinations/cdpresolution/src/index.ts
> +    const baseURL = settings.endpoint
Added an empty return.  As per our last conversation we have no object to initialize.

2023-09-20 17:09 UTC, joe-ayoub-segment approved these changes

2023-09-21 14:20 UTC, merged