[PINT-1852a]
segmentio/action-destinations pull request #1490
Opened 2023-08-09 21:20 UTC by jumpingGrendel

Adding an Action that allows for registering an email address with Airship and associating it with a Named User ID. Also allows for replacing an email address with a new one.

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-08-11 12:38 UTC, joe-ayoub-segment commented
Thanks for the PR @jumpingGrendel - I'll schedule for review.

2023-08-15 13:39 UTC, joe-ayoub-segment requested changes
Hi @jumpingGrendel , 
Would you have time to catch up and review this together? I've provided some comments/feedback, but I've some questions about the new Action which would be best discussed in person. 

Could we catch up Thursday or Friday this week?

2023-08-15 13:39 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +      throw new Error(`Registration Failed, didn't create channel_id for ${payload.channel_object.address}`)
We can't allow regular JS Error objects to be thrown. We need to use one of the error types defined in the framework. See docs https://github.com/segmentio/action-destinations/blob/main/docs/error-handling.md 

In this case will we be throwing a non retryable error? If so then I think you should throw a IntegrationError. 

Make sure you provide an error message, an error code, and an error status number. For example: 

   ```
 throw new IntegrationError(
      'Empty Salesforce instance URL. Please login through OAuth.',
      'INVALID_INSTANCE_URL',
      400
    )
```

2023-08-15 13:39 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +        throw new Error(`Associate Failed for named user ${payload.named_user_id}`)
Same as above - we can't throw a regular JS Error object.

2023-08-15 13:39 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +  const country_language = _extract_country_language(payload.locale)
If we change payload.locale to be optional, this code may need to check for null/undefined values.

2023-08-15 13:39 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/fullstory/generated-types.ts
> +   * [FullStory API key](https://help.fullstory.com/hc/en-us/articles/360052021773-Managing-API-Keys)
We need to remove this change from the PR. It's for a different Destination.

2023-08-15 18:10 UTC, jumpingGrendel commented
> Hi @jumpingGrendel , Would you have time to catch up and review this together? I've provided some comments/feedback, but I've some questions about the new Action which would be best discussed in person.
> 
> Could we catch up Thursday or Friday this week?

Hi @joe-ayoub-segment I can give you 8am Friday (PST) if that works...

2023-08-18 17:07 UTC, joe-ayoub-segment requested changes

2023-08-18 17:07 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +    }
You might not need to handle errors, as Segment will do it. 
If Airship's API responds with 200 for success and some failure code when a failure happens, there's no need to throw errors yourself.

2023-08-18 20:47 UTC, jumpingGrendel commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +    const register_response = await register(request, settings, payload, null)
In retrospect, I think this update is unneeded. The logic above it (do an email replacement if there's a new email address) actually does `return await` so it won't execute anything  further.

2023-08-18 20:49 UTC, jumpingGrendel commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +    }
removed

2023-08-18 20:49 UTC, jumpingGrendel commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +    if (payload.channel_object.new_address) {
added

2023-08-18 20:56 UTC, jumpingGrendel commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +    const register_response = await register(request, settings, payload, null)
If you review and agree,  I believe  I've  resolved all the  rest of your comments @joe-ayoub-segment . Thanks!

2023-08-21 12:14 UTC, joe-ayoub-segment requested changes

2023-08-21 12:14 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +    const register_response = await register(request, settings, payload, null)
Hi John, I still think there are a couple of issues with the logic and return types in the perform() function. 
I recorded a [video](https://drive.google.com/file/d/1mIZ0Wwc71FuEB4iL8JHBX5YFxdKgT7I_/view?usp=sharing) to explain. 

Happy to pair on this if you like. Please let me know. 
Joe

2023-08-22 14:41 UTC, jumpingGrendel commented on packages/destination-actions/src/destinations/fullstory/generated-types.ts
> +   * [FullStory API key](https://help.fullstory.com/hc/en-us/articles/360052021773-Managing-API-Keys)
idk why this file keeps sneaking back in! removed.

2023-08-25 09:53 UTC, joe-ayoub-segment requested changes
Hi @jumpingGrendel I think that looks good! makes sense to me. 

One super minor thing and we're done. 

updating country_language check to make it a little more defensive.

2023-08-25 09:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +  if (country_language) {
```suggestion
  if (Array.isArray(country_language) && country_language.length === 2) {
```

2023-08-29 10:46 UTC, joe-ayoub-segment approved these changes

2023-08-29 11:59 UTC, merged

2023-08-29 16:24 UTC, jumpingGrendel commented
thanks for the heads-up @joe-ayoub-segment !

2023-08-30 17:15 UTC, joe-ayoub-segment commented
Hi @jumpingGrendel this PR has been deployed! Please let me know how everything looks. 
Shall we sync up to do some testing?

2023-08-30 17:46 UTC, jumpingGrendel commented
@joe-ayoub-segment I went ahead and put time on your calendar for 4 Sept. Thanks!