Acoustic S3TC Aug14 main - Clean
segmentio/action-destinations pull request #1499
Opened 2023-08-14 17:47 UTC by KWLandry-acoustic

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

Hi Joe, 
This is a fresh repository without extraneous files, replacing PR - S3TC main #1495
This is to establish a New Acoustic S3 Action-Destination Endpoint - With Completed S3 Caching Support
Acoustic-S3TC

2023-08-15 08:42 UTC, joe-ayoub-segment commented
Hi @KWLandry-acoustic thanks for raising this PR. I'll schedule for review.

2023-08-17 11:24 UTC, joe-ayoub-segment requested changes
hi @KWLandry-acoustic , 

This is generally looking good. 

1. Can we remove all unnecessary comments, specially if they contain code? 
2. The putS3 function isn't used. Maybe we can remove that file?
3. I checked with another Engineer and you are OK to use generateS3RequestOptions 
4. I think we need to tweak the fields you have set up, and tweak the addUpdateEvents function. See inline comments. This is probably worth a face to face call. 
5. It looks like you are offering both S3 and SFTP, however I don't see any code for the SFTP option. Can you remove any reference to SFTP until you decide to implement it please?

Thanks,
Joe

2023-08-17 11:24 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/fullstory/generated-types.ts
Hi @KWLandry-acoustic please undo the change for this Fullstory file.

2023-08-18 00:43 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic-s3tc/index.ts
> +      }
Done,

2023-08-18 00:44 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic-s3tc/index.ts
> +  slug: 'actions-acoustic-s3tc',
Done,

2023-08-18 00:46 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic-s3tc/index.ts
> +      },
Hi Joe, these are not sensitive and are string so that each Customer can confirm correct configuration with their access definition, not that the RefreshToken is marked as password, and that does remain protected as it ties directly to the account that permits access,

2023-08-18 00:48 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic-s3tc/index.ts
> +        default: 's3://arn:aws:s3:us-east-1:777957353822:accesspoint/tricklercache-access',
Initially no, this is the access point provided for this Customer, going forward each Customer will be provided a specific S3 "Access Point" which is what this resource string represents,

2023-08-18 00:51 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/fullstory/generated-types.ts
How the ever-living hell is this getting in??? I've specifically killed it more than once and reviewed this commit very-closely to assure nothing but the files of the Acoustic folder are included, 
I'll get this done,

2023-08-18 00:52 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic/generated-types.ts
>     */
Another bit of ...stuff.... that should not be here, I'll get it out,

2023-08-18 00:54 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/index.ts
> +    // console.log(method, '\n', `https://${opts.host}/${opts.path}`, '\n', fileName, '\n', settings.s3_bucket, '\n', settings.s3_access_key, '\n', settings.s3_secret)
Done,

2023-08-18 00:54 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/acoustic-s3tc/receiveEvents/index.ts
> +    // }
Done,

2023-08-22 13:05 UTC, KWLandry-acoustic commented
<!-- Hello and thank you for contributing to Segment action-destinations! -->

<!-- Before opening your pull request, make sure you have added and ran unit
     tests and tested your change locally. Refer to our testing
     documentation for more information: https://github.com/segmentio/action-destinations/blob/main/docs/testing.md -->

<!-- If you have questions or issues please open a new issue or create a new discussion
     post in Github. -->

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-08-22 13:07 UTC, KWLandry-acoustic commented
Hi Joe, all changes should be reflected now,
Explanatory field removed
Action Description updated, 
Throw integration error if no mapping provided, 
Thanks,
KWL

2023-08-22 16:16 UTC, joe-ayoub-segment commented
Hi @KWLandry-acoustic , 

Still seeing the Fullstory file. Also did you mean to add a gitignore?

![image](https://github.com/segmentio/action-destinations/assets/45374896/86c40293-a567-4c9c-9343-e54aff397883)

2023-08-23 20:34 UTC, KWLandry-acoustic commented on packages/destination-actions/src/destinations/fullstory/generated-types.ts
Should be done, again,

2023-08-25 10:51 UTC, joe-ayoub-segment commented
Hi @KWLandry-acoustic , I've raised a new PR for your Integration. https://github.com/segmentio/action-destinations/pull/1525 

The code is the same, with some minor changes which I'm sure. you'll be fine with. 

1. Fix broken test
2. remove gitignore file and scratch file
3. minor changes to field descriptions, and Action description
4. Renamed the Integration to "Acoustic (Actions)"
5. Renamed the slug to "actions-acoustic"

Apart from that there is no change in the logic of the code. 

Thanks,
Joe

2023-08-25 10:51 UTC, closed without merging