[TTD] Add Native Audience Support
segmentio/action-destinations pull request #1501
Opened 2023-08-15 16:18 UTC by maryamsharif

This PR addresses S[TRATCONN-2990](https://segment.atlassian.net/jira/software/c/projects/STRATCONN/boards/310?modal=detail&selectedIssue=STRATCONN-2990&assignee=620ae2beef2bd5006ae88efb) to add native audience methods to The Trade Desk Crm.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)

Local Test Create Audience
```
curl --location 'http://localhost:3000/createAudience' \
--header 'Content-Type: application/json' \
--data '{
        "settings": {
                "authToken": "REDACTED",
                "advertiser_id": "REDACTED"
        },
        "audienceSettings": {
                "region": "US"
        },
        "audienceName": "Testing NEW Create Audience Method"     
}'

{"externalId":"tnlsw2x"}%
```

Local Test Get Audience
```
curl --location 'http://localhost:3000/getAudience' \
--header 'Content-Type: application/json' \
--data '{
        "settings": {
                "auth_token": "REDACTED",
                "advertiser_id": "REDACTED"
        },
        "externalId": "tnlsw2x"
}'

{"externalId":"tnlsw2x"}%       
```
- [x] [Segmenters] Tested in the staging environment

2023-09-18 22:13 UTC, nick-Ag commented on packages/destination-actions/src/destinations/the-trade-desk-crm/functions.ts
> +        `received payload count below The Trade Desk's ingestion limits. Expected: >=${TTD_MIN_RECORD_COUNT} actual: ${input.payloads.length}`
Nit:
```suggestion
        `received payload count below The Trade Desk's ingestion minimum. Expected: >=${TTD_MIN_RECORD_COUNT} actual: ${input.payloads.length}`
```

2023-09-18 22:13 UTC, nick-Ag commented on packages/destination-actions/src/destinations/the-trade-desk-crm/index.ts
> +  name: 'The Trade Desk Crm',
Should CRM be capitalized?

2023-09-20 18:02 UTC, marinhero requested changes
Left a few comments and questions. Overall structure of the audience destination looks good, we just gotta tighten some nuts and bolts. Good job!

2023-09-20 18:02 UTC, marinhero commented on packages/destination-actions/src/destinations/the-trade-desk-crm/properties.ts
> +  description: 'The CRM Data ID for The Trade Desk Segment. ',
```suggestion
  description: 'The CRM Data ID for The Trade Desk Segment.',
```

2023-09-20 19:28 UTC, maryamsharif commented on packages/destination-actions/src/destinations/the-trade-desk-crm/syncAudience/__tests__/index.test.ts
> +  it('should fail if batch has less than 1500 and old flow', async () => {
We moved the error message so it only errors out if we are using the legacy flow which sends events straight to TTD.

2023-09-20 19:28 UTC, maryamsharif commented on packages/destination-actions/src/destinations/the-trade-desk-crm/index.ts
> +      const authToken = getAudienceInput.settings.auth_token
No oauth, it is stored as a setting.

2023-09-20 19:29 UTC, maryamsharif commented on packages/destination-actions/src/destinations/the-trade-desk-crm/index.ts
> +          'TTD-Auth': authToken
Moved to `extendRequest`.

2023-09-21 17:55 UTC, marinhero approved these changes

2023-09-22 00:54 UTC, merged