Conman 627
segmentio/action-destinations pull request #1506
Opened 2023-08-16 20:59 UTC by vikramkumar19

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-08-18 23:11 UTC, pmunin commented
I do have some questions about this, but not sure if I'm able to finish review by EOD

2023-08-18 23:40 UTC, pmunin requested changes
plz see suggestions

2023-08-18 23:40 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
this does not make sense how `did not subscribe` is sendable status for optOut? Changing for optout model introduces confusion. I suggest to remove that and change the logic of methods that use it

```suggestion
```

2023-08-18 23:40 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +
Instead of creating this separate method. I suggest to change the existing method in a very simple way:

```
  isExternalIdSubscribed(extId: ExtId<TPayload>): boolean | undefined {
    const staticMems = this.getStaticMembersOfThisClass()
    const subStatus = extId.subscriptionStatus?.toString()?.toLowerCase()

    + const isOptOutModel = this.payload.sendBasedOnOptOut

    + if(isOptOutModel) 
    + {
    +   if (!subStatus) return true //falsy status considered to be subscribed for opt-out model
    +   // allow sending messages to all subscription state apart from unsubscribed
    +   // so if subStatus is not in any of the lists of unsubscribed, return true, otherwise false
    +   return (!staticMems.nonSendableStatuses.includes(subStatus)) 
    + }
    if (!subStatus) return false // falsy status is valid and considered to be Not Subscribed, so return false
    // if subStatus is not in any of the lists of valid statuses, then return true
    if (staticMems.sendableStatuses.includes(subStatus)) return true
    if (staticMems.nonSendableStatuses.includes(subStatus)) return false
    return undefined //Invalid subscriptionStatus
  }

```

2023-08-18 23:40 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
>      if (!supportedExtIdsWithSub || !supportedExtIdsWithSub.length)
according to suggested logic above I suggest to revert this change

2023-08-18 23:40 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
>      if (!isSubscribed) return isSubscribed // may be undefined => as invalid
Having those suggestions in the MessageSendPerformer - you don't need that change here. If you do need that extra log message here - you should put it in the super.isExternalIdSubscribed in MessageSendPerformer

```suggestion
```

2023-08-18 23:43 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
>      if (!isSubscribed) return isSubscribed // may be undefined => as invalid
not sure why it captured line 48 in that suggestion above, so make sure you don't apply it as it

2023-08-18 23:56 UTC, pmunin requested changes

2023-08-18 23:56 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +  ShouldNotSend = 'should_not_send',
Seems like you are replacing `NotSubscribed` with `ShouldNotSend` - which does not look right, as the purpose of this status is to explain the reason why it's not being sent (if it's not ShouldSend) just by looking at it. I suggest to revert that replacement

2023-08-18 23:56 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +            sendabilityStatus: SendabilityStatus.ShouldNotSend
See the comment above. I suggest to revert it

2023-08-18 23:56 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +    const supportedExtIdsBasedOnSendType = this.payload.externalIds
this name is confusing, what is send type? it looks like the behavior is still defined based on the subscription status.  So I suggest to keep the old name `supportedExtIdsWithSub`

2023-08-18 23:56 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +    const shouldSendExtIds = supportedExtIdsBasedOnSendType.filter((e) => e.isSubscribed === true).map((e) => e.extId)
same here

2023-08-21 10:37 UTC, joe-ayoub-segment commented
hi @vikramkumar19 and @pmunin please let me know when the PR is ready for me to review / deploy.

2023-08-21 17:09 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> The main idea behind this PR

Yep, I was reviewing it based on this exact understanding, I read the jira ticket.

2023-08-21 17:13 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
if the status is `did not subscribe` it should be noSendableStatus, same as of optIn model

also make sure you read the other comments I posted below.

2023-08-21 17:35 UTC, VenkataNeeharikaKondipati commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +  ShouldNotSend = 'should_not_send',
Based on customer chosen send type i.e bypass, opt-out / opt-in we decide if we 'should send' or 'should not send'. 
The subscription state of the user could be unsubscribed or did-not-subscribe but we still send the email if the customer has chosen 'bypass'. In this case, it confusing to have it 'NotSubscribed' as the reason here

2023-08-21 21:45 UTC, pmunin requested changes

2023-08-21 21:45 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +  //  */
I guess you're unintentionally commented it
```suggestion
  /**
   * check if extId is (un)subscribed (returns true|false) or if subscription status is invalid (returns undefined)
   */
```

2023-08-21 21:45 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +  static readonly sendableStatuses = ['true']
should we just in case also leave `unsubscribed` and `subscribed` in those arrays or you're absolutely sure those value will never come here? because if they will - nothing will be sent.  keep in mind test message scenario (destination-actions-service)

2023-08-21 21:45 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +    const isOptOutModel = this.payload.sendBasedOnOptOut ? true : false
what about that `if(subStatus=='null')? subStatus = null`?

2023-08-21 21:45 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +          this.currentOperation?.tags.push('unknown_subscription_state:')
You are not passing value to those tags. `tags` is the array. In your code you will just have a lot of `{tagName}:` items here with empty value. that does not look right. consider using some aggregate or `Array.reduce`

2023-08-21 22:28 UTC, vikramkumar19 commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +    const isOptOutModel = this.payload.sendBasedOnOptOut ? true : false
As we walked through the scenarios this should not happen.

2023-08-21 22:29 UTC, vikramkumar19 commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +  static readonly sendableStatuses = ['true']
I am mostly sure about this. However, for keeping this more flexible shall add `unsubscribed ` and `subscribed ` back

2023-08-21 22:38 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +  static readonly sendableStatuses = ['true']
yeah I'd add it back just to be safe

2023-08-22 00:22 UTC, pmunin approved these changes
Thanks for all the changes

2023-08-22 09:48 UTC, joe-ayoub-segment commented
hi @vikramkumar19 the change looks fine to me - however I'm only looking for basic syntax issues, and other potential issues which might cause problems (such as adding a new required field for example). 

Usually we don't allow PRs containing changes to more than one Destination at a time, however in this case it makes sense. 

I see you did some testing. Did you do some regression testing as well?

My main question from the PR relates to how you are accessing the new field. 

Remember that for customers who already have the Integration configured prior to your deploy, `payload.sendBasedOnOptOut` will always return `undefined`. So you need to write your code to handle the 3 states for this optional boolean flag. 

If you can confirm that this is what you've done then I'm good to approve!

2023-08-22 16:15 UTC, vikramkumar19 commented
> hi @vikramkumar19 the change looks fine to me - however I'm only looking for basic syntax issues, and other potential issues which might cause problems (such as adding a new required field for example).
> 
> Usually we don't allow PRs containing changes to more than one Destination at a time, however in this case it makes sense.
> 
> I see you did some testing. Did you do some regression testing as well?
> 
> My main question from the PR relates to how you are accessing the new field.
> 
> Remember that for customers who already have the Integration configured prior to your deploy, `payload.sendBasedOnOptOut` will always return `undefined`. So you need to write your code to handle the 3 states for this optional boolean flag.
> 
> If you can confirm that this is what you've done then I'm good to approve!

Hey @joe-ayoub-segment !
All these are good questions.
> I see you did some testing. Did you do some regression testing as well?
 Tested these changes in stage and all looked good. 
I have added couple more test cases here for all three states true, false and undefined.
Agreed on the backward compatibility we have added few fields in past and had success going forward.

2023-08-22 16:42 UTC, pmunin commented
@joe-ayoub-segment 

> for customers who already have the Integration configured prior to your deploy, `payload.sendBasedOnOptOut` will always return undefined

Wouldn't the old integrations fallback to default=false instead of undefined according to [the mappings](https://github.com/segmentio/action-destinations/pull/1506/files#diff-24cb4244068776ed36ee2fe097e6f31bc60868dc2acf9251e00d094cac45839bR126)? the code will handle both undefined and false equally, but i'm just currious

2023-08-22 20:13 UTC, VenkataNeeharikaKondipati approved these changes
LGTM! Thanks for all the additional stats

2023-08-23 08:06 UTC, joe-ayoub-segment commented
> 

Hi @pmunin , no, pre-existing Integrations won't default to false as there won't be an entry in the control plane DB for that instance of the Destination. This is one of the gotchas I need to look out for when approving PRs. 

The background on this is as follows: 

1. When an instance of an Integration is created by a customer the mappings for each field for that specific instance are saved to the database. So for that particular instance of the Destination, the database only contains mapping details for fields which existing when the instance of the Destination was created

2. When we deploy a new version of the Integration which has added fields, the new field mapping data in not present for pre existing instances. So the new field value will always result in undefined for those old instances.

2023-08-24 09:04 UTC, joe-ayoub-segment approved these changes

2023-08-24 09:23 UTC, merged

2023-08-24 14:30 UTC, joe-ayoub-segment commented
hi @vikramkumar19 this PR has been deployed.