Conman 615
segmentio/action-destinations pull request #1521
Opened 2023-08-23 23:20 UTC by Swaty-G

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-08-24 08:44 UTC, joe-ayoub-segment commented
hi @Swaty-G - please ping me directly when you are ready for me to review your PR.

2023-09-16 14:30 UTC, vikramkumar19 requested changes
Overall LGTM! Missing push tokens externalId's and validations.

2023-09-16 14:30 UTC, vikramkumar19 commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +        !(payload.email_subscription_status || payload.whatsapp_subscription_status || payload.sms_subscription_status)
We  should also throw push token errors as well

2023-09-16 14:30 UTC, vikramkumar19 commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +        throw MissingEmailSmsOrWhatsappSubscriptionIfEmailPhoneIsPresentThrowableError
Same here for push tokens

2023-09-16 14:30 UTC, vikramkumar19 commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +    if (payload?.phone) {
Lets make this for push tokens as well.

2023-09-18 11:03 UTC, joe-ayoub-segment commented
hi @Swaty-G , 
There are some failing tests introduced with this PR. Could you take a look please?
![image](https://github.com/segmentio/action-destinations/assets/45374896/60137ff6-5ccb-4399-952d-1aa94d21f834)

Thank you!
Joe

2023-09-18 13:33 UTC, joe-ayoub-segment commented
Hi @Swaty-G , 
Thanks again for raising the PR. 
I added some comments and suggestions, but I think it would be best to catch up force to face to review them together. 
Overall I think there is scope to simplify the field design and remove a lot of the validation code. 
I also am unclear if the subscription groups field will get passed a JSON object or string from RETL. Maybe you know the answer to this?

Are you OK scheduling a call with me here? http://calendly.com/joe_ayoub/integration-workshop

Hopefully chat soon!
Joe

2023-09-18 20:03 UTC, Swaty-G commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +      }
discussed and made the changes.

2023-09-18 23:10 UTC, vikramkumar19 approved these changes

2023-09-19 12:25 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/errors.ts
> +export const MissingPhoneIfSmsOrWhatsappSubscriptionIsPresentThrowableError = new PayloadValidationError(
Can you please come with some better names. They are just too too long

2023-09-19 12:29 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +  if (
Please follow the common indentation style
`  if (!(
    payload.email_subscription_status ||
    payload.whatsapp_subscription_status ||
    payload.sms_subscription_status ||
    payload.android_push_subscription_status ||
    payload.ios_push_subscription_status
  )) {
    throw MissingSubscriptionStatusesThrowableError
  }`

2023-09-19 12:30 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +  if (
Same here.

2023-09-19 12:32 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +  const validStatuses = ['true', 'subscribed', 'false', 'unsubscribed', 'did_not_subscribe']
Use a map and declare it outside this method. This object doesn't need to be redeclared for each validation call.

2023-09-19 12:33 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +    //TODO: Add email format and phone validations
There is a pending TODO.If something still needs to be done than please add those changes otherwise remove the TODO or update it to reflect reality

2023-09-19 12:34 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +    const messaging_subscriptions_retl = true
mix of snake_case vs camelCase. Please follow one convention.

2023-09-19 12:37 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +        return 'subscribed'
Declare these strings as constants. We don't want same strings flowing around in the code.

2023-09-19 12:42 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +    payload?.phone &&
From line 195 to 207 are doing the same thing again and again.You can easily make a function call it with appropriate parameters and perform the same validation inside that function. That will make it more readable.

2023-09-19 12:44 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +    if (payload?.email) {
You can do an && operator here rather than doing it on 2 seperate if statements.

2023-09-19 12:46 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +    const getStatus = (subscriptionStatus: string | null | undefined): string => {
Same goes for this method. Not fully sure why methods are declared inside the perform method.

2023-09-19 12:48 UTC, sumitbhanwala commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +              status: getStatus(String(status).trim().toLowerCase())
Move the logic of lowercasing in the getStatus method, that will make the like of the caller simple and API more usable.

2023-09-19 14:01 UTC, joe-ayoub-segment approved these changes
Agreed to approve this PR even though there are recommended code improvements, because: 
1. deployment for new Action is behind a feature flag to prevent it being used by customers. 
2. team intends to continue development of this Action and to improve code quality. They might refine the field design also. This will be done post initial deploy. 

cc @vikramkumar19 , @Swaty-G , @sumitbhanwala

2023-09-19 14:01 UTC, merged

2023-09-19 15:55 UTC, Swaty-G commented on packages/destination-actions/src/destinations/segment-profiles/segment-properties.ts
> +    'Global status of the ios push subscription. True is subscribed, false is unsubscribed and null is did-not-subscribe.',
Not sure if we want  to add choices, as we have thought initially to allow users to true or subscribed, false or unsubscribed, did-not-subscribed.
cc: @vikramkumar19

2023-09-19 15:56 UTC, Swaty-G commented on packages/destination-actions/src/destinations/segment-profiles/sendSubscription/index.ts
> +      if (payload.subscription_groups && typeof payload.subscription_groups === 'object') {
@joe-ayoub-segment will test this one out.

2023-09-19 17:47 UTC, joe-ayoub-segment commented
hi @Swaty-G , PR deployed. cc @vikramkumar19 , @sumitbhanwala