Add Rupt integration (prev. Sabil)
segmentio/action-destinations pull request #1527
Opened 2023-08-27 22:03 UTC by ahmedmawiri

Added Rupt integration [https://rupt.dev](https://rupt.dev). Already had a valid integration under Sabil. But took that down because of a name and domain change.

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-08-29 10:17 UTC, joe-ayoub-segment commented
Hi @ahmedmawiri , thanks for raising this PR. 

Given that it's for a new Integration - would you be OK meeting with me to discuss the use-cases? I'd like to have some more context around how customers will use this Integration, which types of events they will send to it, and which identifiers will be used. 

You can schedule a call with me via this URL: http://calendly.com/joe_ayoub/integration-workshop 

I look forward to catching up, 
Best regards,
Joe

2023-08-29 15:43 UTC, ahmedmawiri commented
Hey @joe-ayoub-segment, thank you for taking a look.

This is not a new integration. 
>  Already had a valid integration under Sabil. But took that down because of a name and domain change.

@pooyaj, was our point of contact, and we already had a published integration called Sabil. But we took the company through a rename, and that's why we're resubmitting the integration.

Also, the time zones are quite different. The available times on your calendar are around 4 a.m. my time. But it isn't necessary, given that this is mostly a rename of our existing integration. 🙌

Thank you so much 🙏

2023-08-30 16:06 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/rupt/package.json
> +    "@segment/browser-destination-runtime": "^1.4.0"
```suggestion
    "@segment/browser-destination-runtime": "^1.12.2"
```

hi @ahmedmawiri , could you update the version as specified please?

2023-08-30 16:11 UTC, ahmedmawiri commented
Thank you, @joe-ayoub-segment 🙏!

Yes, here's the chronological code change for Rupt (prev. Sabil)
1. The original Sabil integration PR: https://github.com/segmentio/action-destinations/pull/871
2. The deletion PR: https://github.com/segmentio/action-destinations/pull/871
3. Now, this PR.

@pooyaj was kind enough to be with us throughout the whole process. The biggest change, really, is the CDN: `cdn.rupt.dev` and adding types.

2023-08-31 12:21 UTC, joe-ayoub-segment requested changes
hi @ahmedmawiri , 
Thanks for sharing the Sibil code. 
Looks like a few changes - but nothing major. 
Got some minor recommendations and a couple of questions. 
Cheers,
Joe

2023-08-31 12:21 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/rupt/src/index.ts
> +        'A URL to redirect the user to if they choose to logout or if they are kicked out by a verified owner.',
```suggestion
        'A URL to redirect the user to if they choose to logout or if they are kicked out by a verified owner.',
```

Can we use a friendlier term other than 'kicked out', or is that a term used by the Rupt platform/product?

2023-08-31 12:21 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/rupt/src/attach/index.ts
> +  defaultSubscription: 'type = "page"',
hi @ahmedmawiri , in the Sabil Integration you were subscribing to identify() events. Why the change to page() events?

2023-08-31 12:21 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/rupt/src/attach/index.ts
> +    account: {
Is the account field intended to collect the end user's main identifier?

2023-08-31 12:21 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/rupt/src/attach/index.ts
> +      }
```suggestion
      default: {
        '@if': {
          exists: { '@path': '$.context.traits.email' },
          then: { '@path': '$.context.traits.email' },
          else: { '@path': '$.properties.email' }
        }
      }
```

If you decide to keep the defaultSubscription as "type = 'page'", then you will only really see email addresses being send via context.traits.email or properties.email. 

traits.email is only really used in identify() payloads.

2023-08-31 12:21 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/rupt/src/attach/index.ts
> +      }
```suggestion
      default: {
        '@if': {
          exists: { '@path': '$.context.traits.phone' },
          then: { '@path': '$.context.traits.phone' },
          else: { '@path': '$.properties.phone' }
        }
      }
```

Same as per the email field comment above.

2023-08-31 12:21 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/rupt/src/attach/index.ts
> +    console.log('attach', data)
Can we remove the console.log please?

2023-08-31 12:25 UTC, joe-ayoub-segment commented
Also there are some failing tests: 

![image](https://github.com/segmentio/action-destinations/assets/45374896/db3473da-c731-4ae4-a510-b92d28dda881)

2023-08-31 15:47 UTC, ahmedmawiri commented on packages/browser-destinations/destinations/rupt/src/attach/index.ts
> +  defaultSubscription: 'type = "page"',
Subscribing to page events increases accuracy and protects all pages. Our previous recommendation to customers was on login. Now it's on every page. [See our docs here](https://www.rupt.dev/docs/advanced/when-to-call-the-attach-function#:~:text=and%20and%20on%20every%20logged%2Din%20page%20once)

2023-08-31 15:48 UTC, ahmedmawiri commented on packages/browser-destinations/destinations/rupt/src/attach/index.ts
> +    account: {
Yes. It should collect the user ID.

2023-08-31 16:28 UTC, ahmedmawiri commented
Thank you @joe-ayoub-segment! Suggestions and feedback are welcome! Updated the code as requested.

2023-09-01 10:20 UTC, joe-ayoub-segment approved these changes

2023-09-05 17:31 UTC, ahmedmawiri commented
Hey @joe-ayoub-segment, thanks again for the review. Just pinging to see if there's anything else needed from us or if the PR is ready to be merged.

Thank you 🙏

2023-09-08 16:19 UTC, ahmedmawiri commented
Pinging @joe-ayoub-segment & @pooyaj for this PR ✋. Please let me know if there's anything we need to do to move this forward. Thank you.

2023-09-11 11:40 UTC, joe-ayoub-segment commented
Hi @ahmedmawiri , the PR has been approved. We're planning to deploy this Wednesday.

2023-09-11 11:41 UTC, merged

2023-09-13 12:08 UTC, joe-ayoub-segment commented
Hi @ahmedmawiri , I'm registering the Rupt Destination prior to deploy. Can I have your email address please? You can share it via joe.ayoub@segment.com. 

Thank you!