Add ABsmartly first actions implementation
segmentio/action-destinations pull request #1533
Opened 2023-08-29 08:38 UTC by marcio-absmartly

This PR adds an destination action integration with ABsmartly.
This initial implementation converts track, page and screen calls and sends the events as goals to the ABsmartly collector.
It may also allow sending custom exposure events through Segment.

This is a refactoring of our destination function at https://github.com/absmartly/segment to fit the actions framework (currently deployed).

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-08-29 10:11 UTC, joe-ayoub-segment commented
Thank you @marcio-absmartly - I'll schedule for review!

2023-09-01 15:49 UTC, joe-ayoub-segment requested changes
Hi @marcio-absmartly , 

Thanks for raising this PR - shall we schedule a call to review together. I've a few questions which would be best discussed in person. Hopefully we can get it all fixed up and approved during the call. 

You can schedule a call with me here http://calendly.com/joe_ayoub/integration-workshop

Best regards,
Joe

2023-09-01 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/index.ts
> +
Let's put a description in here. 
For example: 
description: 'Send analytics events and user profile data to events to ABsmartly...'

2023-09-01 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/index.ts
> +  // },
OnDelete just passes the userId and nothing else. Customers generally aren't so concerned about anonymous data.

2023-09-01 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/goal.ts
> +      '@path': '$.originalTimestamp'
```suggestion
      '@path': '$.timestamp'
```

2023-09-01 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/goal.ts
> +    default: {
Do you need to specify if userId or anonymousId is required?

2023-09-01 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/event.ts
> +      '@path': '$.sentAt'
Not sure why you want to collect the sentAt timestamp, but of course you can if you like! 

I'll explain what the 4 different Segment timestamps are: 

**originalTimestamp** - this is the time on the client when the event was generated. Note the time can be inacurate if the client's clock is incorrect. 
**sentAt** - this is the time on the client when the event was actually sent from the client. Note the time can be inacurate if the client's clock is incorrect. 
**receivedAt** - this is the time on Segment's servers when the event was received by Segment's servers. We guarantee that the time is correct. 
**timestamp** - If Segment detect that there's a difference between the **sentAt** and **receivedAt** timestamps, we infer that the Client's clock is off by that amount of time. We then correct the **originalTimestamp** value by that difference to arrive at the **timestamp** value.

2023-09-01 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/event.ts
> +    default: 'segment'
```suggestion
    default: {'@path': '$.context.library.name'}
```

This will pull the actual name of the Segment library which was used to send the event. e.g. analytics.js for Web

2023-09-01 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/event.ts
> +    default: ''
If you are not setting a default then just remove this line.

2023-09-01 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/exposure.ts
> +}
To help me understand, could you paste in a JSON object for a valid Exposure payload please?

2023-09-01 15:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/exposure.ts
> +    payload.application
Hi @marcio-absmartly you don't seem to be sending the other fields from defaultEventFields here. Is that intentional?

Which user identifier are you sending?

2023-09-02 09:29 UTC, marcio-absmartly commented on packages/destination-actions/src/destinations/absmartly/index.ts
> +  // },
Sure, but we still the mapping, just like in other events. We need to know what corresponds to Segment's userId on our platform.

2023-09-02 09:35 UTC, marcio-absmartly commented on packages/destination-actions/src/destinations/absmartly/goal.ts
> +    default: {
Yes, we should specify that at least one is required. How can we do this?

2023-09-02 09:37 UTC, marcio-absmartly commented on packages/destination-actions/src/destinations/absmartly/event.ts
> +      '@path': '$.sentAt'
It's because we do the same calculation that you do to get the final timestamp. So if we send the originals we get a little extra information and we just treat Segment as another SDK.

2023-09-02 09:46 UTC, marcio-absmartly commented on packages/destination-actions/src/destinations/absmartly/exposure.ts
> +}
The idea is that we don't want the user to mess with this data in Segment - we want the payload generated by the SDK to be an atomic piece of data that gets passed directly here - because it's subject to change with different versions of the SDK, etc...

This code is just a safety measure to loosely validate that that is the case.

What this code is trying to do is saying that, for example, we cannot have any goals in this payload. For that to be true either there is no "goals" field, or the field is an empty array. Depending on the SDK, language, and Json encoding library used, sometimes they omit the field, sometimes the field is encoded as null, or sometimes it is an empty array, all valid cases of having no goals.

2023-09-02 09:49 UTC, marcio-absmartly commented on packages/destination-actions/src/destinations/absmartly/exposure.ts
> +}
Here is an example payload from our Javascript SDK's tests.

```
{
  publishedAt: 1611141535829,
  units: publishUnits,
  hashed: true,
  exposures: [
    {
      id: 1,
      name: "exp_test_ab",
      unit: "session_id",
      exposedAt: 1611141535729,
      variant: 1,
      assigned: true,
      eligible: true,
      overridden: false,
      fullOn: false,
      custom: false,
      audienceMismatch: false,
    },
  ],
  attributes: [
    {
      name: "attr1",
      setAt: 1611141535729,
      value: "value1",
    },
    {
      name: "attr2",
      setAt: 1611141535729,
      value: "value2",
    },
    {
      name: "attr3",
      setAt: 1611141535729,
      value: 3,
    },
  ],
},
```

2023-09-02 10:00 UTC, marcio-absmartly commented on packages/destination-actions/src/destinations/absmartly/exposure.ts
> +    payload.application
Yes, so for these, we are sending the "atomic" payload directly from our SDK in that "exposure" property, which is already correctly formatted by definition.

Our exposure events are constantly evolving, so I thought it better to pass the payload directly and verbatim, instead of having us update the integration, and customers manage this mapping with each change to the exposure Schema.

This usage is not your typical Segment usage. We don't expect many customers to use this, and currently only one customer is going down this route. This is basically to support using Segment to publish our exposures, instead of sending them directly to us, and also send "dumber" 'Experiment Viewed' events to Segment to process by other destinations.

I am expecting this to also be useful if/when we build an ABsmartly Source, but must admit haven't done any research on that yet.

2023-09-04 11:13 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/index.ts
> +  // },
Hi @marcio-absmartly , 

Here's an example delete function from another Integration: 

  onDelete: async (request, { payload }) => {
    return request(`https://api.hilohq.com/v1/events/delete`, {
      method: 'POST',
      json: {
        event: {
          contact_id: payload.userId
        }
      }
    })
  }

Does that make sense?

2023-09-04 13:38 UTC, joe-ayoub-segment requested changes

2023-09-04 13:38 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/index.ts
> +        description: 'ABsmartly Collector endpoint, for example: https://you-subdomain.absmartly.io/v1',
```suggestion
        description: 'ABsmartly Collector endpoint, for example: https://your-subdomain.absmartly.io/v1. Contact ABsmartly Support if you don\'t know your Collector Endpoint',
```

2023-09-04 13:38 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/index.ts
> +          'Environment name. Create Environments in the Settings > Environments section of the ABsmartly Web Console',
```suggestion
          'Environment name. Create Environments in the Settings > Environments section of the ABsmartly Web Console'. Environment name needs to match what\'s in the console. ,
```

2023-09-04 13:38 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/event.ts
> +    default: {'@path': '$.context.library.name'}
```suggestion
        default: {
      '@if': {
        exists: { '@path': '$.context.library.name' },
        then: { '@path': '$.context.library.name' },
        else: 'segment'
      }
    }
```

2023-09-04 13:38 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/trackGoal/index.ts
> +  fields: fields,
Add this line: 

  defaultSubscription: 'type = "track" and event != "Experiment Viewed"',

2023-09-04 13:38 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/absmartly/trackExposure/index.ts
> +  fields: fields,
Please add this line: 

defaultSubscription: 'type = "track" and event = "Experiment Viewed"',

2023-09-04 13:53 UTC, joe-ayoub-segment approved these changes

2023-09-05 10:09 UTC, merged