Added more optional parameters to Snap Conversions API destination
segmentio/action-destinations pull request #1546
Opened 2023-09-04 15:35 UTC by sebashine-branly

Following the work that has been done in this other [PR](https://github.com/segmentio/action-destinations/pull/833), this new PR adds more optional fields for the following Destination: [Snapchat Conversions API (Actions)](https://segment.com/docs/connections/destinations/catalog/actions-snap-conversions/).

It is based on the official documentation from Snapchat: https://marketingapi.snapchat.com/docs/conversion.html#conversion-parameters

More specifically, it adds the following parameters:
- `hashed_first_name_sha`
- `hashed_middle_name_sha`
- `hashed_last_name_sha`
- `hashed_city_sha`
- `hashed_state_sha`
- `hashed_zip`
- `hashed_dob_month`
- `hashed_dob_day`
- `country`
- `region`

(Command `yarn types` has been run)

This PR adds checks around the usage of `country` and/or `region` based on the rules given by Snapchat.

🐛 This PR also fixes a bug around the usage of `idfv` being turned into `hashed_idfv`, as it should be normalized (lowercased) before being hashed (like it's the case for `hashed_mobile_ad_id`).

Given that the Destination is currently active in Production, the following guide has been followed: https://github.com/segmentio/action-destinations/blob/main/CONTRIBUTING.md#submitting-changes-after-your-integration-is-already-live

## Documentation

For quick documentation through test purposes, the hash values in the unit tests correspond to those present in the [Snapchat documentation](https://marketingapi.snapchat.com/docs/conversion.html#conversion-parameters)

|Name of param|Raw string value|Hashed value|
|-|-|-|
|`hashed_first_name_sha`|`John`|`a8cfcd74832004951b4408cdb0a5dbcd8c7e52d43f7fe244bf720582e05241da`|
|`hashed_middle_name_sha`|`Middle`|`d93006ec2e4339d770a7afd068c1f1e789a52df12f595e529fd0f302fc1e5ec7`|
|`hashed_last_name_sha`|`Doe`|`fd53ef835b15485572a6e82cf470dcb41fd218ae5751ab7531c956a2a6bcd3c7`|
|`hashed_city_sha`|`Santa Monica`|`ced2e77f732fbf327f53e1f9748078c778b190ed9cf376a7df469a92d2ad62d3`|
|`hashed_state_sha`|`CA`|`4b650e5c4785025dee7bd65e3c5c527356717d7a1c0bfef5b4ada8ca1e9cbe17`|
|`hashed_zip`|`90405`|`e222c384dd83ac669bcd1da281ffea2e60bab298f8c0673d35bc0b704e345282`|
|`hashed_dob_month`|`January`|`37082e68df858e0ba76442174128811135890ae4c2c5df8b6f31aef5885d0be7`|
|`hashed_dob_day`|`26`|`5f9c4ab08cac7457e9111a30e4664920607ea2c115a1433d7be98e97e64244ca`|

## Limitations

This PR does not implement the five parameters finishing with `_sdx` suffix (Soundex). In the future, if a PR does so, it will have to check for the existence of one parameter (`_sha` suffix) or the other (`_sdx`), but not both. For instance, if a PR implements `hashed_first_name_sdx` in the future, said PR will have to make sure it is not being used at the same time as `hashed_first_name_sha`.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

For unit tests the following commands have been run:
- `yarn cloud test --testPathPattern=src/destinations/snap-conversions-api`
- `yarn cloud test --testPathPattern=src/destinations/snap-conversions-api -u` (for updating the snapshots)

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-09-04 16:12 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
>      if (data.payload.currency && !CURRENCY_ISO_4217_CODES.has(data.payload.currency.toUpperCase())) {
I wonder if for this message, we should send `Misconfigured optional field` rather than `Misconfigured required field`, as I think `currency` isn't mandatory.

2023-09-05 10:02 UTC, joe-ayoub-segment commented
hi @sebashine-branly I see this is no longer a draft - are you ready for me to review it?

2023-09-05 10:25 UTC, sebashine-branly commented
Hi @joe-ayoub-segment , thank you for your quick reply. Yes, this PR is ready for a review when you get a chance. Thank you for your help.

2023-09-08 11:27 UTC, joe-ayoub-segment commented
hi @sebashine-branly I'm about to review your PR. Can you please provide proof that you are from Snap please, or that you have authorization for this change? you can email me at joe.ayoub@segment.com .

2023-09-08 11:53 UTC, joe-ayoub-segment requested changes
hi @sebashine-branly , PR looks really good! Few minor additions needed.

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
>      if (data.payload.currency && !CURRENCY_ISO_4217_CODES.has(data.payload.currency.toUpperCase())) {
hi @sebashine-branly , yes I agree. The error can better be explained as "Misconfigured optional field". 

However, could we throw a PayloadValidationError instead please?

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
> +      throw new IntegrationError(
Hi @sebashine-branly can we throw a PayloadValidationError error instead please?

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
> +    if (data.payload.country === 'US' && data.payload.region && data.payload.region.length !== 2) {
Can this be a PayloadValidationError please?

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Can we add a default mapping?

      default: {
        '@if': {
          exists: { '@path': '$.context.traits.first_name' },
          then: { '@path': '$.context.traits.first_name' },
          else: { '@path': '$.properties.first_name' }
        }
      }

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Can we add a default mapping?

  default: {
    '@if': {
      exists: { '@path': '$.context.traits.middle_name' },
      then: { '@path': '$.context.traits.middle_name' },
      else: { '@path': '$.properties.middle_name' }
    }
  }

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Can we add a default mapping?

  default: {
    '@if': {
      exists: { '@path': '$.context.traits.last_name' },
      then: { '@path': '$.context.traits.last_name' },
      else: { '@path': '$.properties.last_name' }
    }
  }

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Can we add a default mapping?

default: { '@path': '$.address.city' }

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Can we add a default mapping?

default: { '@path': '$.address.state' }

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Can we add a default mapping?

default: { '@path': '$.address.postalCode' }

2023-09-08 11:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Can we add a default mapping?

default: { '@path': '$.address.region' }

2023-09-08 13:38 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
>      if (data.payload.currency && !CURRENCY_ISO_4217_CODES.has(data.payload.currency.toUpperCase())) {
I am happy to make the change but I have some concerns about the comment above the definition of `PayloadValidationError`: https://github.com/segmentio/action-destinations/blob/main/packages/core/src/errors.ts#L76

> Error to indicate the payload is missing fields that are required.

The field here is not required so I am not sure whether the new error type is fitting. I don't know if the comment should be updated instead, to also include the case of wrongly formatted optional parameters, but if needed I would prefer to have it in a separate PR as the contribution would be outside of the `snap-conversions-api` folder.

https://github.com/segmentio/action-destinations/blob/main/CONTRIBUTING.md#submitting-changes-after-your-integration-is-already-live

> Do not raise a PR containing changes for more than 1 Integration. For example if you need to make changes to a Cloud Mode and Device Mode Integration you should raise separate PRs.

2023-09-08 13:41 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
>      if (data.payload.currency && !CURRENCY_ISO_4217_CODES.has(data.payload.currency.toUpperCase())) {
I also noticed that `PayloadValidationError` uses `ErrorCodes.PAYLOAD_VALIDATION_FAILED` behind the scenes but it seems like `ErrorCodes.INVALID_CURRENCY_CODE` would be more fitting.

2023-09-08 13:41 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
> +      throw new IntegrationError(
Same concern regarding the fact this field is not required, contrary to what is assumed by the comment above `PayloadValidationError` definition.

2023-09-08 13:42 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
> +    if (data.payload.country === 'US' && data.payload.region && data.payload.region.length !== 2) {
Same concern regarding the fact this field is not required, contrary to what is assumed by the comment above `PayloadValidationError` definition.

2023-09-08 13:50 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Looking at the existing codebase, unless it's intended, I'd like to suggest either one of these two solutions:

1.

```ts
      default: {
        '@path': '$.traits.address.city'
      }
```

2.

```ts
      default: {
        '@if': {
          exists: { '@path': '$.traits.address.city' },
          then: { '@path': '$.traits.address.city' },
          else: { '@path': '$.properties.address.city' }
        }
      }
```

2023-09-08 13:51 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Similarly, I would suggest:

1.

```ts
      default: {
        '@path': '$.traits.address.state'
      }
```

2.
```ts
      default: {
        '@if': {
          exists: { '@path': '$.traits.address.state' },
          then: { '@path': '$.traits.address.state' },
          else: { '@path': '$.properties.address.state' }
        }
      }

2023-09-08 13:52 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
1.

```ts
default: { '@path': '$.traits.address.postalCode' }
```

2.
```ts
      default: {
        '@if': {
          exists: { '@path': '$.traits.address.postalCode' },
          then: { '@path': '$.traits.address.postalCode' },
          else: { '@path': '$.traits.address.postal_code' }
        }
      }
```

2023-09-08 13:53 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Even though it doesn't exist in the codebase, I would recommend:
```ts
default: { '@path': '$.traits.address.region' }
```

2023-09-08 13:57 UTC, sebashine-branly commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +}
ℹ️ We didn't include a `default` value here but I think this is actually very valid because of the newly created rule about `country` validation. Because the integration is live (https://github.com/segmentio/action-destinations/blob/main/CONTRIBUTING.md#submitting-changes-after-your-integration-is-already-live), I wouldn't want to have a default mapping leading to a non-ISO 3166 alpha-2 country code (e.g. the value retrieved is `United States of America` when it should be `US`) and the existing integration of the Snap CAPI Destinations return an error because of the invalid payload.

2023-09-08 14:02 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +}
Hi @sebashine-branly , yes I thought the same thing!

2023-09-08 14:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Hi @sebashine-branly yes good catch! I'd go with the following. Note that customers don't send any data at the '$.traits' part of the payload for track() events. This only happens for identify() events. So we generally suggest to customers who want to capture user profile details in a track event to either put it in the '$.context.traits' object or the '$.properties' object. 

  ```
default: {
        '@if': {
          exists: { '@path': '$.context.traits.address.city' },
          then: { '@path': '$.context.traits.address.city' },
          else: { '@path': '$.properties.address.city' }
        }
      }
```

2023-09-08 14:07 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Hi @sebashine-branly yes good catch! I'd go with the following. Note that customers don't send any data at the '$.traits' part of the payload for track() events. This only happens for identify() events. So we generally suggest to customers who want to capture user profile details in a track event to either put it in the '$.context.traits' object or the '$.properties' object. 

  ```
default: {
        '@if': {
          exists: { '@path': '$.context.traits.address.state' },
          then: { '@path': '$.context.traits.address.state' },
          else: { '@path': '$.properties.address.state' }
        }
      }
```

2023-09-08 14:07 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  type: 'string'
Hi @sebashine-branly , 

Can we do this?

default: {
      '@if': {
        exists: { '@path': '$.context.traits.address. postalCode' },
        then: { '@path': '$.context.traits.address. postalCode' },
        else: { '@path': '$.properties.address. postalCode' }
      }
    }

2023-09-08 14:08 UTC, joe-ayoub-segment commented
Thanks for implementing the feedback @sebashine-branly , and for pointing out the incorrect mapping suggestions!

2023-10-03 10:52 UTC, joe-ayoub-segment commented
Hi @dcasey-sc, cc @sebashine-branly , 

Now that we have https://github.com/segmentio/action-destinations/pull/1557 out of the way, would you be interested in getting this PR approved?

2023-10-10 12:42 UTC, joe-ayoub-segment commented
hi @sebashine-branly and @dcasey-sc, checking in on this again to see if you are interested in progressing with this change?

2023-10-13 09:36 UTC, sebashine-branly commented
Hi @joe-ayoub-segment and @dcasey-sc, thanks for the follow-up.
From what I can see, https://github.com/segmentio/action-destinations/pull/1557 is complimentary with this PR as they add more properties but in a different scope: array of products for https://github.com/segmentio/action-destinations/pull/1557 whereas this PR adds more customer information.
For this reason I'd still be interested in getting this PR approved. I'm planning to solve the code conflict either today or early next week.
Thank you!

2023-10-13 13:51 UTC, sebashine-branly commented
ℹ️ Fixed the code conflict and verified that test suite is still ✅

2024-07-16 09:36 UTC, joe-ayoub-segment commented
Tidy up: closing this PR for now due to lack of progress.

2024-07-16 09:36 UTC, closed without merging