feat: hubble-web browser-destination
segmentio/action-destinations pull request #1566
Opened 2023-09-08 11:12 UTC by bombamong

_A summary of your pull request, including the what change you're making and why._

Added code for a new browser destination, Hubble (hubble-web).

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-09-08 14:33 UTC, joe-ayoub-segment commented
hi @bombamong thanks for raising this PR. 
Given that it's for a new Integration would you be OK meeting with me to discuss it please?
I'd like to understand the use-cases as well as get an understanding of the data and identifiers to be sent to your platform. 

You can schedule a call with me here: http://calendly.com/joe_ayoub/integration-workshop

Kind regards,
Joe

2023-09-11 07:07 UTC, bombamong commented
Hi @joe-ayoub-segments

I requested a meeting via your Calendly link!

Regards,
David

2023-09-13 06:10 UTC, bombamong commented
> > Hi @joe-ayoub-segments
> > I requested a meeting via your Calendly link!
> > Regards, David
> 
> Hi David, I didn't receive any invite. Could you mail me directly please (or share your email address with me)? [joe.ayoub@segment.com](mailto:joe.ayoub@segment.com)
> 
> Best regards, Joe

Hi Joe,

Just sent an email (david@hubble.team) to [joe.ayoub@segment.com](mailto:joe.ayoub%40segment.com).
I think Calendly sent the invite to jayoub@twilio.com <jayoub@twilio.com>. 

Best, 
David

2023-09-13 09:55 UTC, joe-ayoub-segment commented
Hi David,

I was able to find the meeting invite in my calendar, but there was no
Calendly email and no email from your email address which is strange.
Either way, see you later today!

Best regards,
Joe

On Wed, Sep 13, 2023 at 7:10 AM M.Byun ***@***.***> wrote:

> Hi @joe-ayoub-segments
> I requested a meeting via your Calendly link!
> Regards, David
>
> Hi David, I didn't receive any invite. Could you mail me directly please
> (or share your email address with me)? ***@***.***
>
> Best regards, Joe
>
> Hi Joe,
>
> Just sent an email ***@***.***) to ***@***.***
> I think Calendly sent the invite to ***@***.*** ***@***.***
>
> Best,
> David
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/segmentio/action-destinations/pull/1566*issuecomment-1717004061__;Iw!!NCc8flgU!dn1L7Ubp4e9ZCBhiSno9GHTLqXNoT3j-KLLp7UqXRi-XXsQmLQlXAXt5imIAzNXQK_VLTC2Yec5rkY990d4_40MvEg$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AK2F3MEUIYPC4PRD32DYOSLX2FE4RANCNFSM6AAAAAA4QHGO6I__;!!NCc8flgU!dn1L7Ubp4e9ZCBhiSno9GHTLqXNoT3j-KLLp7UqXRi-XXsQmLQlXAXt5imIAzNXQK_VLTC2Yec5rkY990d74Cr6xZw$>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-09-13 15:30 UTC, joe-ayoub-segment requested changes

2023-09-13 15:30 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/hubble-web/src/index.ts
> +      mapping: defaultValues(identify.fields)
please add this line to each preset 

      type: 'automatic'

2023-09-13 15:30 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/hubble-web/src/index.ts
> +      subscribe: 'type = "track"',
type: 'automatic'

2023-09-13 15:30 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/hubble-web/src/track/index.ts
> +  description: 'Track event',
```suggestion
  description: 'Sync Segment track() events to Hubble',
```

2023-09-13 15:49 UTC, joe-ayoub-segment requested changes

2023-09-20 09:49 UTC, joe-ayoub-segment commented
hi @bombamong , following up on this as I've noticed that there's still some outstanding items which need to be addressed before I can merge and deploy. 

Are you clear on what needs to be done?

2023-09-20 16:41 UTC, bombamong commented
Hi @joe-ayoub-segment, 
we are working on some internal improvements, but everything is clear!

2023-09-26 05:56 UTC, bombamong commented
@joe-ayoub-segment I think we are ready to proceed!

2023-09-26 09:41 UTC, joe-ayoub-segment commented
Thanks @bombamong I'll take a look shortly.

2023-09-27 17:54 UTC, joe-ayoub-segment requested changes

2023-09-27 17:54 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/hubble-web/src/index.ts
> +  mode: 'device',
Please add a description to the Destination object. This will display in the Segment UI

2023-09-27 17:54 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/hubble-web/src/__tests__/index.test.ts
> +describe('Hubble', () => {
Hi @bombamong I believe that this test fails. I ran the tests locally and it didn't pass. 

![image](https://github.com/segmentio/action-destinations/assets/45374896/e70cf476-6370-48e3-980d-f4a2538a9325)

2023-09-27 17:54 UTC, joe-ayoub-segment commented
Hi @bombamong thanks for making those changes. 
Few items blocking me from merging this. Please see the comments. 

I'm going to be running a deploy tomorrow, so if you are able to get everything fixed by then we can get this live soon. 

Best regads,
Joe

2023-09-27 18:19 UTC, bombamong commented on packages/browser-destinations/destinations/hubble-web/src/__tests__/index.test.ts
> +describe('Hubble', () => {
@joe-ayoub-segment Noted, and sorry about that. Will make the fix shortly.

2023-09-27 18:33 UTC, bombamong commented
Hi @joe-ayoub-segment
Made changes for the requests

2023-09-27 18:34 UTC, bombamong commented on packages/browser-destinations/destinations/hubble-web/src/index.ts
> +      description: 'id',
added
```
  description:
    'From design to production, monitor, measure and enhance your user experience with seamless integration with Segment',

```

2023-09-27 18:35 UTC, bombamong commented on packages/browser-destinations/destinations/hubble-web/src/index.ts
> +    await deps.resolveWhen(() => window.Hubble.initialized, 250)
Added optional chaining for resolving condition

2023-09-27 18:35 UTC, bombamong commented on packages/browser-destinations/destinations/hubble-web/src/track/index.ts
> +    }
Removed unnecessary code

2023-09-27 18:37 UTC, bombamong commented on packages/browser-destinations/destinations/hubble-web/src/identify/index.ts
> +      required: true,
Changed `userId` to not be a requirement as suggested, and will. handle empty values on our end.

2023-09-27 18:37 UTC, bombamong commented on packages/browser-destinations/destinations/hubble-web/src/identify/index.ts
> +    }
Removed unnecessary code

2023-09-27 18:39 UTC, bombamong commented on packages/browser-destinations/destinations/hubble-web/src/index.ts
> +  mode: 'device',
Added a description as below
```
  description:
    'From design to production, monitor, measure and enhance your user experience with seamless integration with Segment',
```

2023-09-27 18:40 UTC, bombamong commented on packages/browser-destinations/destinations/hubble-web/src/index.ts
> +      description: 'id',
Added a better description as below
```
'Unique identifier for your team (given in Hubble app)'
```

2023-09-28 09:04 UTC, joe-ayoub-segment approved these changes

2023-09-29 12:09 UTC, bombamong commented
hi @joe-ayoub-segment 
It seems like one of the CI checks failed. 
Would there be anything that I need to do on my end.

2023-10-02 11:01 UTC, joe-ayoub-segment commented
> hi @joe-ayoub-segment It seems like one of the CI checks failed. Would there be anything that I need to do on my end.

Hi @bombamong , all good. That check always fails if the PR was raised externally. We're good to deploy. 

I'm planning a deploy to run across today / tomorrow. 
Best regards,
Joe

2023-10-02 11:16 UTC, merged

2023-10-04 10:23 UTC, joe-ayoub-segment commented
Hi @bombamong just a quick update - we expect the rollout to be complete later today. I'll message you with instructions via email.

2023-10-04 10:26 UTC, bombamong commented
> Hi @bombamong just a quick update - we expect the rollout to be complete later today. I'll message you with instructions via email.

Hi @joe-ayoub-segment, 
Thanks for letting me know!

2023-10-05 09:14 UTC, joe-ayoub-segment commented
Hi @bombamong this PR is now live. I've shared next step instructions with you via email. 
Best regards,
Joe

2023-10-16 01:48 UTC, bombamong commented
Hi @joe-ayoub-segment, 
We are having a bit of trouble on our private beta stage, and were hoping that you could help us out.
Tried reaching out via e-mail a few times, but I think our emails are not reaching you.
I sent a request to schedule a call via Calendly, but wasn't sure if you got the request.

2023-10-16 09:57 UTC, joe-ayoub-segment commented
Hi @bombamong , 
I didn't receive an email - but am happy to help out. I have the Calendly invite and will chat to you later today. 
Best regards,
Joe