[DevRev]: Add new browser destination with action identifyRevUser
segmentio/action-destinations pull request #1582
Opened 2023-09-15 07:50 UTC by Nandy-006

This PR adds a new browser destination for DevRev with action `identifyRevUser`.  This change is being made to obtain two user traits `accountRef` and `workspaceRef` (which get passed during an `identify` call) in `streamEvent` action destination. To solve this we enrich the integrations object during `identify` and use that in the `streamEvent` action.

## Testing
Tested browser destination and action destination for DevRev independently

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-09-18 09:40 UTC, joe-ayoub-segment commented
hi @Nandy-006 thanks for raising this PR! 
As it's for a new Integration - could we schedule a call to discuss the use-cases, etc please?

You can schedule a call with me here: http://calendly.com/joe_ayoub/integration-workshop 

I look forward to catching up, 
Best regards,
Joe

2023-09-18 09:42 UTC, joe-ayoub-segment commented
hi @Nandy-006 , 
Would you be OK separating this PR so that the changes to the server side Integration are raised separately please?
Kind regards,
Joe

2023-09-20 05:44 UTC, Nandy-006 reviewed
Hey @joe-ayoub-segment,
I have moved the changes related to the server side integration to #1593

2023-09-20 10:17 UTC, joe-ayoub-segment requested changes

2023-09-20 10:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/src/identifyRevUser/index.ts
> +      description: 'User Ref, ideally mappable to external ref of a Rev User.',
```suggestion
      description: 'User Ref trait field name, ideally mappable to external ref of a Rev User.',
```

2023-09-20 10:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/src/identifyRevUser/index.ts
> +      description: 'Account Ref, ideally mappable to external ref of a Rev Account.',
```suggestion
      description: 'Account Ref trait field name, ideally mappable to external ref of a Rev Account.',
```

2023-09-20 10:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/src/identifyRevUser/index.ts
> +      description: 'Workspace Ref, ideally mappable to external ref of a Rev Workspace.',
```suggestion
      description: 'Workspace Ref trait field name, ideally mappable to external ref of a Rev Workspace.',
```

2023-09-20 10:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/src/identifyRevUser/index.ts
> +  defaultSubscription: 'type = "identify"',
We might as well update all Segment events sent from the browser, rather than just identify() calls.

2023-09-20 10:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/src/identifyRevUser/index.ts
> +  title: 'Identify Rev User',
```suggestion
  title: 'DevRev Web Plugin',
```

2023-09-20 10:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/src/index.ts
> +    identifyRevUser
```suggestion
    devrevPlugin
```

2023-09-20 10:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/src/index.ts
> +  slug: 'actions-devrev-web',
Please remove this line

2023-09-20 10:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/src/identifyRevUser/index.ts
> +  description: 'Looks up User, Account and Workspace Refs from user traits and adds it to context.',
```suggestion
  description: 'Looks up User, Account and Workspace Refs from user traits on the browser, and adds it to context.',
```

2023-09-20 10:18 UTC, joe-ayoub-segment commented
Hi @Nandy-006 thanks for raising this PR. 
Few minor but important changes to make. 
Are you OK renaming the Action to be something like devrevPlugin? 

Note: I recommend that we run this code in the browser when any browser event is triggered. We want the traits enriched into the payload every time. Does that make sense?

2023-09-20 10:37 UTC, joe-ayoub-segment requested changes

2023-09-20 10:37 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/package.json
> +  },
```suggestion
    "publishConfig": {
    "access": "public",
    "registry": "https://registry.npmjs.org"
  },
```

2023-09-20 10:37 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/package.json
> +  },
Can you replace that block of config with that I provided please?

2023-09-20 10:37 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/devrev/package.json
> +    "@segment/browser-destination-runtime": "^1.4.0"
```suggestion
    "@segment/browser-destination-runtime": "^1.3.0"
```

2023-09-21 05:23 UTC, Nandy-006 commented on packages/browser-destinations/destinations/devrev/src/identifyRevUser/index.ts
> +  title: 'Identify Rev User',
I changed it to `Rev User Enrichment Plugin` so that in the future if we need to add more plugins, we can. Hope it is fine?

2023-09-21 11:24 UTC, joe-ayoub-segment approved these changes

2023-09-21 11:34 UTC, Nandy-006 reviewed
Hi @joe-ayoub-segment,
Thanks for the review and approval.

Is there any way to test both the browser and cloud destination together locally?

2023-09-21 14:21 UTC, merged