Update Attio Actions destination to use IDs as unique lookup field
segmentio/action-destinations pull request #1589
Opened 2023-09-19 15:45 UTC by nickcampbell18

Hi team 👋 ,

This is a relatively small change based on some feedback with our early beta testers. We've changed the data model slightly in Attio, so that with the suggested "identify User" and "group Workspace" mappings you need to specify an additional `user_id` or `workspace_id` attribute (that is likely part of your Segment event already).

While it's technically a breaking change, none of our existing testers are actually sending production data through this Action yet, so we thought it a good time to make the change, and we'll coordinate with them as it's released.

## Testing

I've updated the unit tests and run through some manual end-to-end tests locally, this should still work great like before.

2023-09-22 08:48 UTC, nickcampbell18 commented
Hi @joe-ayoub-segment, can I provide any additional context to help get this over the line? Thanks!

2023-09-22 11:03 UTC, joe-ayoub-segment commented
Hi @nickcampbell18 , thanks for raising this PR. 
I usually review code for all new Integrations but was on leave when your initial PR to add a new Integration was raised. 

Given that you are open to making a breaking change - there's a few things in the Integration which I have questions about. Could we have a quick sync to run through them please?

http://calendly.com/joe_ayoub/integration-workshop 

I look forward to catching up. 
Best regards,
Joe

2023-09-26 10:33 UTC, joe-ayoub-segment requested changes

2023-09-26 10:33 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/groupWorkspace/index.ts
> +      else: { '@path': '$.id' }
```suggestion
      exists: { '@path': '$.groupId' },
      then: { '@path': '$.groupId' },
      else: { '@path': '$.context.group_id' }
```

2023-09-26 10:33 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/groupWorkspace/generated-types.ts
> +  workspace_id: string
Note: adding a new required field will break the Action for any customer who is already using it. 
Discussed with Nick and he is aware of this - no customer using this Action currently.

2023-09-26 10:33 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/identifyUser/generated-types.ts
> +  user_id: string
Another required field. This will break the experience for existing customers.

2023-09-26 10:33 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/identifyUser/index.ts
> +  }
```suggestion
  default: { '@path': '$.userId' }
```

2023-09-26 11:52 UTC, joe-ayoub-segment approved these changes

2023-09-26 12:21 UTC, merged