CHANNELS-850: Twilio/Sendgrid stats showing N/A error_code for error in datadog
segmentio/action-destinations pull request #1596
Opened 2023-09-20 14:42 UTC by miguelpdiaz8

This issue was caused by calling .toLowercase() function on a number (since sometimes the code is a number) in EngageActionPerformer --> request --> onFinally

We extended the code to be string or number now and always calling toString() first

## Testing

Tested it locally

2023-09-20 19:37 UTC, CesarAyuso approved these changes
Changes look good to me 👍

2023-09-20 20:43 UTC, pmunin requested changes
I don't really see what the actual behavioral change you're adding with this PR.
I only see some extra questionable typing and returning some status extraction paths from what was commented before. Am I missing something? Did you actually test it locally?

2023-09-20 20:43 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/ResponseError.ts
> +    respError.response?.data?.statusCode
what's the motivation of adding this back (from commented state)? and also removing all those comments above?

2023-09-20 20:43 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/ResponseError.ts
> +      code: string | number
is there an evidence where this is number?

2023-09-20 20:43 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/EngageStats.ts
> +    const errDetails: ErrorDetails = getErrorDetails(error)
what's the value of explicit typing here?

2023-09-20 20:43 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/EngageLogger.ts
> +    const errorDetails: ErrorDetails = getErrorDetails(error)
what's the value of explicit typing here?

2023-09-20 21:55 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/utils/ResponseError.ts
> +      code: string | number
Hi Philipp, I tested this locally using this doc https://segment.atlassian.net/wiki/spaces/ONCON/pages/2456289553/Testing+and+Running+Integrations+Repo+Locally+Stage adding a breakpoint in the ResponseError and the code was actually a number, for that reason when we call toLowercase() with that number I was getting an exception saying toLowercase function does not exist

2023-09-20 22:02 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/utils/ResponseError.ts
> +    respError.response?.data?.statusCode
In the previous PR the function extractTagsFromError function was checking the status with this code: `respError?.response?.data?.status || respError?.status` and it was replaced by calling the function getErrorDetails that now only was checking for `respError.status || respError.response?.status` so we were missing the case the data comes in `respError?.response?.data?.status`

2023-09-20 22:08 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/utils/EngageStats.ts
> +    const errDetails: ErrorDetails = getErrorDetails(error)
If we have a type now, it is safer to use it, we'll get an error if we try in the future in that code to do: `errDetails.propertythatdoesnotexist` or `errDetails.status?.toLowercase()`

2023-09-20 22:08 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/utils/EngageLogger.ts
> +    const errorDetails: ErrorDetails = getErrorDetails(error)
same

2023-10-03 10:45 UTC, joe-ayoub-segment commented
Hi @miguelpdiaz8 @pmunin @CesarAyuso is this PR ready to be reviewed and then deployed?

2023-10-03 13:51 UTC, miguelpdiaz8 commented
> Hi @miguelpdiaz8 @pmunin @CesarAyuso is this PR ready to be reviewed and then deployed? I see that @pmunin asked a question which hasn't been responded to. Have you all agreed the status for this PR?

Talked with Philipp offline, we found out there were still issues unresolved, then I made some changes and asked for reviews again

2023-10-10 14:05 UTC, joe-ayoub-segment commented
Hi @miguelpdiaz8 is this PR ready to go out?

2023-10-10 14:36 UTC, joe-ayoub-segment commented
![image](https://github.com/segmentio/action-destinations/assets/45374896/62d11b77-1c39-447c-b586-c81fe32e0210)

2023-10-10 14:45 UTC, pmunin approved these changes
few code cleaning suggestions

2023-10-10 14:45 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/EngageActionPerformer.ts
> +          }
```suggestion
          const status = errorDetails.status ?? respError.status ?? 408
          respError.status = status
          erroDetails.status = status
```

2023-10-10 14:45 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/EngageActionPerformer.ts
> +          }
```suggestion
          const errorCode = errorDetails.code ?? respError.code ?? 'etimedout'
          respError.code = errorCode
          errorDetails.code = errorCode
```

2023-10-10 14:53 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/utils/EngageActionPerformer.ts
> +          }
done

2023-10-10 14:54 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/utils/EngageActionPerformer.ts
> +          }
done

2023-10-17 10:41 UTC, merged

2023-10-17 18:39 UTC, joe-ayoub-segment commented
Hi @miguelpdiaz8 this PR has been deployed