Remove flagon check for event streams
segmentio/action-destinations pull request #1616
Opened 2023-09-26 17:55 UTC by Sneha-Uppalapati

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-09-26 18:11 UTC, nick-Ag approved these changes

2023-09-26 20:53 UTC, joelbandi requested changes
This will cause dupes - we havent done investigation yet.

2023-09-27 01:52 UTC, hocaho commented
> This will cause dupes - we havent done investigation yet.

Tested in staging with webhooks and event streams no dupes observed.

2023-09-27 01:54 UTC, joelbandi approved these changes

2023-09-27 02:18 UTC, merged