[Hyperengage] Destination
segmentio/action-destinations pull request #1621
Opened 2023-09-28 14:58 UTC by zhadier39

### Hyperengage Integration
Smart alerting for startup GTM teams, Hyperengage tracks thousands of data points to trigger smart alerts on hidden opportunities when the accounts are ready for upsell, or likely to churn. Our customers are sales, customer success, and Revops teams at B2B SaaS companies. 

### How our customers want to use Segment
Hyperengage customers may already have usage events in Segment. If they don't, we recommend Segment as a way to quickly connect product usage data to Hyperengage.

Once the integration is connected, Hyperengage uses the data, in combination with other data sources to provide actionable insights which would help Hyperengage customers to reach out to the right people at the right time.

![image](https://github.com/segmentio/action-destinations/assets/113626827/3134295e-be45-4ae6-9689-cb4d0eeba5ab)

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-09-28 15:59 UTC, joe-ayoub-segment commented
hi @zhadier39 , thanks for raising this PR for a new Integration. 
Because this is for a new Integration I'd like to meet with you to get an understanding of the use-cases involved, events  and user identifiers to be sent to your platform. 

Would you be OK meeting with me to run through this? 

You can schedule a call with me here: 

http://calendly.com/joe_ayoub/integration-workshop 

Best regards,
Joe

2023-09-28 16:27 UTC, saadhypng commented
hey @joe-ayoub-segment , 

We have booked a time for tomorrow. 

Thanks

2023-09-29 17:03 UTC, joe-ayoub-segment requested changes
Hi @zhadier39 , 

Here's the complete PR review. 

Best regards,
Joe

2023-09-29 17:03 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/identify/index.ts
> +      description: 'The timestamp when the user was created',
Maybe explain the format for the timestamp. e.g. ISO 8601, and give an example.

2023-10-02 10:59 UTC, joe-ayoub-segment commented
hi @zhadier39 , just checking that you are OK with the feedback on this PR? 
Best regards,
Joe

2023-10-02 11:03 UTC, zhadier39 commented
Hi @joe-ayoub-segment ,

Thanks for reaching out. Yes the feedback is perfect, I've reviewed them and I'm currently addressing the comments. I'll push the updates shortly and will let you know if I have any questions.

Best regards,
@zhadier39

2023-10-02 12:29 UTC, joe-ayoub-segment requested changes

2023-10-02 12:29 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/identify/index.ts
> +          else: { '@path': '$.properties.firstName' }
```suggestion
          exists: { '@path': '$.traits.first_name' },
          then: { '@path': '$.traits.first_name' },
          else: { '@path': '$.properties.first_name' }
```

2023-10-02 12:29 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/identify/index.ts
> +          else: { '@path': '$.properties.lastName' }
```suggestion
          exists: { '@path': '$.traits.last_name' },
          then: { '@path': '$.traits.last_name' },
          else: { '@path': '$.properties.last_name' }
```

2023-10-02 12:29 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/identify/index.ts
> +      }
```suggestion
      default: {
        '@if': {
          exists: { '@path': '$.context.group_id' },
          then: { '@path': '$.context.group_id' },
          else: { '@path': '$.groupId' }
        }
      }
```

2023-10-02 12:29 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/group/index.ts
> +      }
```suggestion
      default: {
        '@if': {
          exists: { '@path': '$.context.group_id' },
          then: { '@path': '$.context.group_id' },
          else: { '@path': '$.groupId' }
        }
      }
```

2023-10-02 12:29 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/track/index.ts
> +      }
```suggestion
      default: {
        '@if': {
          exists: { '@path': '$.context.group_id' },
          then: { '@path': '$.context.group_id' },
          else: { '@path': '$.groupId' }
        }
      }
```

2023-10-02 12:29 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/validateInput.ts
> +  console.log(properties)
please remove the console.log

2023-10-02 12:29 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/validateInput.ts
> +      }
Should we throw an error if input.name and input.first_name and input.last_name are all empty?

2023-10-02 12:32 UTC, zhadier39 commented on packages/destination-actions/src/destinations/hyperengage/validateInput.ts
> +      }
Yes, I think throwing an error for mandatory field missing should be the way to go here. Lemme see what I can do.

2023-10-02 12:55 UTC, zhadier39 commented on packages/destination-actions/src/destinations/hyperengage/validateInput.ts
> +      }
Hey @joe-ayoub-segment , I've resolved the default path issues and added an error incase none of the first_name and last_name or name fields are provided. Sorry for the inconvenience and thank you so much for your time

2023-10-03 10:05 UTC, joe-ayoub-segment requested changes
hi @zhadier39 , couple more things. 
Also the unit tests are failing. Can you make sure they pass please?

You can run them using this command: 

yarn jest --testPathPattern='./packages/destination-actions/src/destinations/hyperengage'

Also please make sure this command passes: 

yarn validate

2023-10-03 10:05 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/commonFields.ts
> +        exists: { '@path': 'context.timezone' },
```suggestion
        exists: { '@path': '$.context.timezone' },
```

2023-10-03 10:05 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/validateInput.ts
> +import { Settings } from './generated-types'
There are linting errors because of the use of 'any'. You can either fix them or add the following line: 

/* eslint-disable @typescript-eslint/no-explicit-any */

Also, you shouldn't throw a regular Error object. Please throw a PayloadValidationError object. You can include it here: 

import { PayloadValidationError } from '@segment/actions-core'

2023-10-03 10:05 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/hyperengage/validateInput.ts
> +      throw new Error('Either name, or first_name and last_name must be provided.')
```suggestion
      throw new PayloadValidationError('Either name, or first_name and last_name must be provided.')
```

2023-10-03 10:33 UTC, zhadier39 commented
> yarn validate

Hey @joe-ayoub-segment ,
When I run yarn validate, there's only a single error in someone else's action destination

![image](https://github.com/segmentio/action-destinations/assets/113626827/71bba51b-8f53-49c1-9763-b5d1bc62c75c)

I haven't meddled with any other action destinations as you can see in the PR.

2023-10-03 10:40 UTC, joe-ayoub-segment commented
> > yarn validate
> 
> Hey @joe-ayoub-segment , When I run yarn validate, there's only a single error in someone else's action destination
> 
> ![image](https://user-images.githubusercontent.com/113626827/272231574-71bba51b-8f53-49c1-9763-b5d1bc62c75c.png)
> 
> I haven't meddled with any other action destinations as you can see in the PR. What am I expected to do here?

Hi @zhadier39 if yarn validate passes that's great, nothing to do. 

Do the unit tests pass when you run this?

yarn jest --testPathPattern='./packages/destination-actions/src/destinations/hyperengage'

2023-10-03 10:41 UTC, joe-ayoub-segment approved these changes

2023-10-03 10:42 UTC, joe-ayoub-segment commented
Looks like you probably fixed the tests. I'll run CI now.

2023-10-03 12:48 UTC, merged