Jimo Browser Destination
segmentio/action-destinations pull request #1626
Opened 2023-10-02 16:19 UTC by imsamdez

Jimo enables product teams to create engaging in-app interactions (modal, snippet, product tours, etc). To do so, our customers inject a javascript code into their app.

This PR provide add a Browser Destination for Jimo. It's responsible for : 
- Injecting the script
- Enrich Jimo user's profile using segment.identify
 
## Testing

We are currently unable to provide test as we are having typescript errors while running test. One of our 3rd party lib, Lottie, make the test crash. Tried different options like disabling all code execution but I'm still having the issue. Seems to happen at build time or something. Everything is working fine in the e2e env.

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-10-03 00:04 UTC, zikaari requested changes

2023-10-03 00:04 UTC, zikaari commented on packages/browser-destinations/destinations/jimo/package.json
> +    "@segment/browser-destination-runtime": "^1.4.0"
```suggestion
    "@segment/browser-destination-runtime": "^1.14.0"
```

This version needs to pinned to latest runtime version. There's an open PR that'll make sure that every new scaffolded destination will have the latest version to begin with.

https://github.com/segmentio/action-destinations/blob/main/packages/browser-destination-runtime/package.json#L3

2023-10-03 00:04 UTC, zikaari commented on packages/browser-destinations/destinations/jimo/src/index.ts
> +    console.log('Jimo added to window')
Remnants of development aid?

2023-10-03 00:04 UTC, zikaari commented on packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
> +      console.debug('user id sent to jimo')
More remnants

2023-10-03 11:20 UTC, imsamdez commented
Cleaned up 👍

2023-10-09 15:09 UTC, joe-ayoub-segment requested changes
Hi @imsamdez , 

Thanks for raising this PR. 

I've emailed you to request a meeting, which you can schedule via this link: http://calendly.com/joe_ayoub/integration-workshop

Items to discuss: 
1. Let's clarify which events you need sent to Jimo. When we met last you indicated that you wanted user profile data and user analytics events sent to Jimo. The code doesn't really cover these use-cases at the moment. 
2. We need to include unit tests or the PR will not pass CI. When you scaffold a new Integration the tests get create automatically, so you should have a starting point to build on. You can always look at the tests written by other Partners to see how they do it. 
3. Let's also discuss how you are connecting the client library, and if we should be throwing an error if the loadScript function call fails. 
4. We should also add presets and defaultSubscriptions. We can discuss this when we meet. 
5. Field descriptions should be a little more helpful for the customer. 

I look forward to catching up soon,
Kind regards,
Joe

2023-10-09 15:09 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
> +      description: 'The unique user id provided to segment that will be reuse in Jimo',
Hi @imsamdez can we reword this to make it clearer please?

2023-10-09 15:09 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
> +      allowNull: true,
Should this field be required or not?
You can set this using the 'required' attribute

2023-10-09 15:09 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
> +      allowNull: true,
Should this field be required or not?
You can set this using the 'required' attribute.

2023-10-09 15:09 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/jimo/src/sendUserData/index.ts
> +  description: 'Set Jimo identify data from segment.io data',
Can this be reworded to explain a little more about what this Action does please?

2023-10-11 18:50 UTC, imsamdez commented
Tests has been added, let me know if I can help with anything else!

2023-10-16 12:27 UTC, joe-ayoub-segment approved these changes

2023-10-16 12:58 UTC, merged

2023-10-18 10:58 UTC, joe-ayoub-segment commented
hi @imsamdez this PR has been deployed.