ReplayBird Web Browser  Destination
segmentio/action-destinations pull request #1687
Opened 2023-10-25 13:18 UTC by fizerkhan

This PR is for the [ReplayBird](https://www.replaybird.com/) web browser destination

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-10-25 14:31 UTC, joe-ayoub-segment commented
Hi @fizerkhan thanks for raising this PR. 

Since it's for a new Integration would you be able to schedule a call with me to discuss the use-cases and data to be sent to your platform please?

Here's my Calendly link: http://calendly.com/joe_ayoub/integration-workshop

I look forward to hearing from you! 

Best regards,
Joe

2023-10-25 16:37 UTC, joe-ayoub-segment reviewed
Hi @fizerkhan and @prakashatatus , 

Providing some initial feedback. Let's chat some more when we meet!

Kind regards,
Joe

2023-10-25 16:37 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/replaybird/src/types.ts
> +  capture: (eventName: string, eventProperties: EventProperties, library?: string) => void
Should capture also include the ability to include the user ID?

2023-10-25 16:37 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/replaybird/src/__tests__/index.test.ts
> +    const [event] = await replaybird({
Hi @fizerkhan @prakashatatus, 
In the unit tests we need to ensure we don't make any outbound HTTP/HTTPS calls. You can use nock for this. 

The idea of these tests is mostly to check that the correct functions in your replaybird SDK are called locally, with the correct params. 

If we allowed real HTTP/HTTPS requests it would make our CI tests super flakey.

2023-10-26 06:37 UTC, fizerkhan commented on packages/browser-destinations/destinations/replaybird/src/types.ts
> +  capture: (eventName: string, eventProperties: EventProperties, library?: string) => void
We dont have userId in the capture method.

2023-10-26 12:49 UTC, fizerkhan commented on packages/browser-destinations/destinations/replaybird/src/__tests__/index.test.ts
> +    const [event] = await replaybird({
Hi @joe-ayoub-segment 

Thanks for the feedback.
We fixed the test with nock. Could you please check and let me know?

2023-10-30 14:41 UTC, joe-ayoub-segment commented
Thanks @fizerkhan , chat to you Wednesday. 
I just noticed that the CI checks are failing. I don't have time to look into it now, so if you don't get to it before we meet we can look at it during our call. 

Best regards,
Joe

2023-10-31 06:26 UTC, fizerkhan commented
Thanks @joe-ayoub-segment. We fixed the CI checks issues.

2023-11-01 14:09 UTC, joe-ayoub-segment approved these changes

2023-11-09 17:47 UTC, joe-ayoub-segment requested changes

2023-11-09 17:47 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/replaybird/src/trackEvent/index.ts
> +  title: 'Track Event',
```suggestion
  title: 'Send Track Events',
```

2023-11-09 17:47 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/replaybird/src/trackEvent/index.ts
> +  description: 'Track events',
```suggestion
  description: 'Send Segment track() events and / or Segment page() events to ReplayBird',
```

2023-11-09 17:47 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/replaybird/src/trackEvent/index.ts
> +  defaultSubscription: 'type = "track" || type = "page"',
```suggestion
  defaultSubscription: 'type = "track" or type = "page"',
```

2023-11-09 17:47 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/replaybird/src/identifyUser/index.ts
> +  description: 'Sets user identity',
```suggestion
  description: 'Sets user identifier and user profile details',
```

2023-11-09 17:47 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/replaybird/src/identifyUser/index.ts
> +      description: 'The Segment traits to be forwarded to replaybird',
```suggestion
      description: 'The Segment traits to be forwarded to ReplayBird',
```

2023-11-09 17:47 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/replaybird/src/index.ts
> +      subscribe: 'type = "track"',
```suggestion
      subscribe: 'type = "track" or type = "page"',
```

2023-11-09 17:48 UTC, joe-ayoub-segment commented
Hi @fizerkhan thanks for making the updates. 
Few more minor things to look at. Please see comments. 

I noticed that CI didn't pass, so I have rerun it.

2023-11-14 08:45 UTC, fizerkhan commented
@joe-ayoub-segment Thank you for the suggestions. We have made the changes. Please review it again.

2023-11-14 10:26 UTC, joe-ayoub-segment approved these changes

2023-11-14 10:27 UTC, joe-ayoub-segment commented
Looks good! Just running CI. I'll merge prior to deploy tomorrow.

2023-11-15 13:18 UTC, merged

2023-11-17 13:45 UTC, joe-ayoub-segment commented
Hi @fizerkhan this PR has been deployed. I'll share next steps via email.