[Marketo Static Lists] Add audience functions
segmentio/action-destinations pull request #1699
Opened 2023-10-31 00:09 UTC by maryamsharif

This PR adds the audience functions and authorization for Marketo Static Lists. 

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment
![Screenshot 2023-10-30 at 12 53 53 PM](https://github.com/segmentio/action-destinations/assets/99763167/0f03cff2-4a72-4a2c-99c8-a704bbe2b5ab)
![Screenshot 2023-10-30 at 12 54 01 PM](https://github.com/segmentio/action-destinations/assets/99763167/e14b12c5-c0d3-479f-b0ee-f247e8dd6e5b)
![Screenshot 2023-10-30 at 12 54 23 PM](https://github.com/segmentio/action-destinations/assets/99763167/5f9117f7-3fe6-4585-963a-32446c263261)

2023-10-31 00:27 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/marketo-static-lists/index.ts
> +import { MarketoResonse, getAccessToken } from './constants'
nit, spelling

2023-10-31 00:29 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/marketo-static-lists/index.ts
> +      const audience_name = createAudienceInput.audienceName
style, it's better to be consistent in using either camelCasing or snake_casing.
i think in TypeScript the pattern has generally been camelCasing.

2023-10-31 00:47 UTC, marinhero commented on packages/destination-actions/src/destinations/marketo-static-lists/index.ts
> +import { MarketoResonse, getAccessToken } from './constants'
No nit, fix it 😄

2023-10-31 00:51 UTC, marinhero commented on packages/destination-actions/src/destinations/marketo-static-lists/index.ts
> +      return { accessToken: await getAccessToken(request, settings) }
What happens to this call if it fails? is it retried automatically?

2023-10-31 00:59 UTC, marinhero requested changes
There's a few things that I would like you to address but overall this looks pretty good! Nice job!

2023-10-31 00:59 UTC, marinhero commented on packages/destination-actions/src/destinations/marketo-static-lists/constants.ts
> +export interface MarketoResonse {
```suggestion
export interface MarketoResponse {
```

2023-10-31 23:54 UTC, maryamsharif commented on packages/destination-actions/src/destinations/marketo-static-lists/index.ts
> +      return { accessToken: await getAccessToken(request, settings) }
The event will not pass and eventually get retried.

2023-11-01 03:12 UTC, marinhero approved these changes

2023-11-01 11:56 UTC, merged

2023-11-01 18:16 UTC, joe-ayoub-segment commented
Hi @maryamsharif this PR has been deployed