create trackEvent and identifyUser browser-destinations for 1flow
segmentio/action-destinations pull request #1703
Opened 2023-11-01 07:08 UTC by namit1Flow

**1Flow web**
- 1Flow can use this information to trackEvent and identify users.
- In this repo we are targeting trackEvent and identifyUser.
- Initialize 1Flow and fire trackEvent(track) and idenfiyUser(identifyUser)

2023-11-01 07:16 UTC, namit1Flow commented
please let me know if any changes you want.
Thanks

2023-11-01 09:51 UTC, joe-ayoub-segment commented
hi @namit1Flow - thanks for raising this PR. 

As this is for a new Integration would you be available to meet with me to help me understand the use-cases for the Integration, as well as the types of data you want to send to the 1Flow platform?

You can schedule a call with me here: http://calendly.com/joe_ayoub/integration-workshop

I look forward to hearing from you!

Best regards,
Joe

2023-11-06 04:41 UTC, namit1Flow commented
Hi Joe,

We have a meeting today at 10:00 PM IST to discuss the integration.

2023-11-08 13:44 UTC, joe-ayoub-segment commented
Hi Namit, 

Thanks for taking the time to catch up. 
Please see the diff file for recommended changes, and please add unit tests. 

Kind regards,
Joe

2023-11-14 13:10 UTC, joe-ayoub-segment commented
Hi @namit1Flow , just following up on this PR since our meeting on 8-Nov. Are you still interested in getting this PR live?
Are you clear on the changes we discussing during the call (which were shared via the diff file)?

Best regards,
Joe

2023-11-17 13:30 UTC, joe-ayoub-segment requested changes

2023-11-17 13:30 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/1flow/src/index.ts
> +      description: 'The app_id of your 1Flow app which will indicate where to store any data.',
```suggestion
      description: 'Your 1Flow app_id - indicates where in 1Flow send Segment events to.',
```

2023-11-17 13:30 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/1flow/src/identifyUser/index.ts
> +      traits: traits,
note: you might want to dedupe first_name, last_name, email and phone from the traits object.

2023-11-17 13:30 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/1flow/src/trackEvent/generated-types.ts
> +export interface Payload {
please run this command to auto generate the types files: 

./bin/run generate:types

2023-11-17 17:15 UTC, namit1Flow commented
Hi, @joe-ayoub-segment  suggested issues I fixed. Please check.

2023-11-22 11:45 UTC, joe-ayoub-segment requested changes

2023-11-22 11:45 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/1flow/src/index.ts
> +
please add description here: 

description: 'Send user analytics events and user profile data from Segment to 1Flow',

2023-11-22 11:51 UTC, joe-ayoub-segment approved these changes

2023-11-22 12:09 UTC, joe-ayoub-segment commented
Hi @namit1Flow - looks like the tests are failing. Can you take a look please?

![image](https://github.com/segmentio/action-destinations/assets/45374896/d8c4be88-0970-4164-bcd1-f2e09b7695f4)

2023-11-23 13:12 UTC, namit1Flow commented
Hi @joe-ayoub-segment ,

Please check my latest commit and let me know if any action is needed.

2023-11-24 12:08 UTC, joe-ayoub-segment approved these changes

2023-11-29 12:42 UTC, merged

2023-12-06 11:59 UTC, joe-ayoub-segment commented
hi @namit1Flow - this PR has been deployed. Can you please let me know if you are happy with the change?

Kind regards,
Joe