[STRATCONN] Klaviyo AddToProfileList and RemoveFromProfileList actions with engage setup
segmentio/action-destinations pull request #1723
Opened 2023-11-14 23:23 UTC by AnkitSegment

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [X] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [X] [Segmenters] Tested in the staging environment

2023-11-14 23:27 UTC, marinhero commented on packages/destination-actions/src/destinations/klaviyo/index.ts
>        headers: {
Is this working? We thought extendRequest wasn't working for audience destinations.

2023-11-14 23:33 UTC, maryamsharif commented on packages/destination-actions/src/destinations/klaviyo/index.ts
> +      return {
What if this response fails? We should probably check that it returns successfully first.

2023-11-14 23:35 UTC, AnkitSegment commented on packages/destination-actions/src/destinations/klaviyo/index.ts
>        headers: {
Yes it is working, Isn't is right way to declare here ?

<img width="1089" alt="Screenshot 2023-11-15 at 5 05 36 AM" src="https://github.com/segmentio/action-destinations/assets/139338151/709c41b3-ac8e-4bed-8710-7d5114281104">

2023-11-14 23:36 UTC, maryamsharif commented on packages/destination-actions/src/destinations/klaviyo/properties.ts
> +  description: 'Email of User',
```suggestion
  description: 'The user's email to send to Klavio.',
```

2023-11-14 23:39 UTC, maryamsharif commented on packages/destination-actions/src/destinations/klaviyo/properties.ts
> +  description: 'Email of User',
Also do we want to allow users to update this field? Maybe we use readOnly here?

2023-11-14 23:49 UTC, maryamsharif commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +      throw new IntegrationError('Missing List Id', 'Missing required fields', 400)
```suggestion
      throw new IntegrationError('Missing list ID or email', 'MISSING_REQUIRED_FIELD', 400)
```

2023-11-14 23:52 UTC, maryamsharif commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +  perform: async (request, { payload }) => {
Are we not implementing batching for this destination?

2023-11-14 23:52 UTC, maryamsharif commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +      throw new Error('An error occurred while processing the request')
Can we add a more specific error here?

2023-11-14 23:53 UTC, maryamsharif commented on packages/destination-actions/src/destinations/klaviyo/index.ts
>        headers: {
Have you also verified that it worked in staging? IIRC when I was testing this for TTD it worked locally but not in staging.

2023-11-14 23:56 UTC, maryamsharif reviewed
Good work, left a few comments with suggestions and questions. Can you also add more information about testing in the description?

2023-11-14 23:59 UTC, maryamsharif commented on packages/destination-actions/src/destinations/klaviyo/index.ts
>        headers: {
It looks like the Authorization header is defined in the individual create/getAudience requests so I don't think they are using the extendRequest?

2023-11-15 04:58 UTC, AnkitSegment commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +  perform: async (request, { payload }) => {
@maryamsharif Yes, we are not implementing batching for this destination now.  But we will implement it later.

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +    const listData: listData = {
Consider moving this inside `executeProfileList` as that is the only place this is required.

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +      const id = JSON.parse(profileData?.content)?.data?.id
Consider returning json/object from `createProfile` method instead of parsing here.

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +        return await executeProfileList(request, 'POST', listData, external_id)
A better name could be `addProfileToList`

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +      if (response?.status === 409) {
In what scenarios do we get 409 here? 
If this is for createProfile, it will be better if the try catch is around `createProfile ` to ensure we are handling error response for the appropriate API.

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +        const id = content?.errors[0]?.meta?.duplicate_profile_id
Would duplicate_profile_id be 100% present as the first element of the errors array?

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +          return await executeProfileList(request, 'POST', listData, external_id)
Like the comment before, consider passing profile_id and external_id as params and build the payload `listData` inside the executeProfileList.

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +      throw new Error('An error occurred while processing the request')
Please avoid throwing Error. Use one of the predefined error classes as per the error-handling guide.

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +    return list
```suggestion
    return list.json()
```

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +    throw new Error('An error occurred while processing the request')
I don't think a catch is required here. This catch overrides the default HTTPError exception which is not desirable in this case.

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +    throw new Error('An error occurred while processing the request')
I don't think a catch is required here. This catch overrides the default HTTPError exception which is not desirable in this case. Also, throwing new Error will result in Sentry errors. Always use one of the predefined Error classes.

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/index.ts
> +    async createAudience(request, createAudienceInput) {
Could you write unit tests for create and getAudience?

2023-11-15 09:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/index.ts
> +      if (response.status !== 200) {
If response is not 200, `request` will throw an HttpError by default. I don't think this statement will get executed. Could you write some unit tests?

2023-11-20 18:00 UTC, marinhero commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +// export async function addProfileToList(request: RequestClient, profileId: string, listId: string) {
is this supposed to be here?

2023-11-20 18:04 UTC, marinhero commented on packages/destination-actions/src/destinations/klaviyo/index.ts
>        headers: {
Good 👁️ Maryam! Ankit, please assume it doesn't work and move these headers into a `buildHeaders()` function that you call within the arguments of the `request` call. Thanks!

2023-11-20 18:05 UTC, marinhero commented on packages/destination-actions/src/destinations/klaviyo/types.ts
> +  data: {
consider moving data into its own type to facilitate reading

2023-11-20 18:06 UTC, marinhero reviewed
This is getting better but we need to make a few adjustments before shipping.

2023-11-21 07:18 UTC, varadarajan-tw reviewed
The change looks better. Left few more comments!

2023-11-21 07:18 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +      throw new APIError('An error occured while adding profile to list', 400)
I don't think we should capture and override status codes to 400 always. This will affect retries in case APIs return 429.

2023-11-21 07:18 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +    throw new APIError('An error occured while adding profile to list', 400)
Same as above - Lets retain status code or even rethrow the error if status is not 409

2023-11-21 07:18 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +      listData.data[0].id = id
Is parsing this response necessary?

2023-11-21 07:18 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +    'Content-Type': 'application/x-www-form-urlencoded'
Why is the`Content-Type` set to 'application/x-www-form-urlencoded'?

2023-11-21 07:18 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/properties.ts
> +  unsafe_hidden: true
Should we mark this as required?

2023-11-21 07:18 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
> +    if (!email || !external_id) {
Does it make sense to mark external_id as required?  If so, you can remove external_id validation here.

2023-11-21 07:18 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
> +      throw new Error('An error occurred while processing the request')
Pls evaluate if handling of the error here is needed because request client throws HttpError which is handled automatically by the framework.

2023-11-22 12:38 UTC, varadarajan-tw approved these changes
Thanks for applying the changes. Left final few comments. Approving the PR.

We still have to update AddProfileToList and RemoveProfileFromList destinations to work with phone_number and external_id. I believe that'll be addressed in a followup PR next week.

2023-11-22 12:38 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/removeProfileFromList/index.ts
> +  description: 'Remove profile from list',
```suggestion
  description: 'Remove profile from list',
  defaultSubscription: 'event = "Audience Exited"',
```

2023-11-22 12:38 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +  description: 'Add to list',
```suggestion
  description: 'Add to list',
  defaultSubscription: 'event = "Audience Entered"',
```

2023-11-22 12:49 UTC, varadarajan-tw requested changes
Missed couple of key points in the earlier review.  Could you help answer the questions?

2023-11-22 12:49 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +    const profileData = await createProfile(request, email)
I missed this line. What if a profile already exists? Won't we get an error?

2023-11-22 12:49 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +    if (response?.status === 409) {
When do we get 409? I thought we get 409 when we try to add a profile that doesn't exist to a list?

2023-11-23 04:05 UTC, AnkitSegment commented on packages/destination-actions/src/destinations/klaviyo/addProfileToList/index.ts
> +    const profileData = await createProfile(request, email)
yes right and If profile is already created or exist then we will get 409 status with profile id.

2023-11-27 07:59 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/properties.ts
> +export const email: InputField = {
Spoke with @AnkitSegment . This is going to be addressed in a followup PR.

2023-11-27 12:41 UTC, AnkitSegment commented on packages/destination-actions/src/destinations/klaviyo/types.ts
> +  data: {
Going to address this in following PR of JIRA STRATCONN-3413

2023-11-29 11:55 UTC, merged

2023-11-29 17:00 UTC, joe-ayoub-segment commented
Hi @AnkitSegment this PR has been deployed