[Hyperengage] Resolved issue with Timezone Offset and Added Missing user_id field in group call
segmentio/action-destinations pull request #1733
Opened 2023-11-18 12:05 UTC by zhadier39

This PR has no breaking changes. In this PR, we updated fallback mappings for created at  and plan fields, fixed function that returned local timezone offset and added user_id field in group events.

Release in the upcoming deployment would be great. Thanks!

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [X] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-11-19 17:02 UTC, saadhypng commented
@joe-ayoub-segment Please review this PR and it would be great if it can be merged soon. Also, no segmenter is actively using this integration right now, so there shouldn't be any breaking changes. 

Thank you

2023-11-21 12:05 UTC, saadhypng commented
hey @joe-ayoub-segment Is it possible to get this deployed in tomorrow's release we are waiting on this fix to onboard some customers. 

Thank you

2023-11-22 12:18 UTC, joe-ayoub-segment requested changes

2023-11-22 12:18 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSFTP.types.ts
> +
Hi @zhadier39 and @saadhypng the PR looks good. Can you just remove the change to this file from the PR pleaese?

It was likely automatically added when you ran the `./bin/run generate:types` command. 

Next steps are: 
- We're planning a deploy next Wednesday. The deploy rolls out across 2 days, so the code will be live for all customers by the end of Thursday.

2023-11-22 12:31 UTC, saadhypng commented on packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSFTP.types.ts
> +
@zhadier39 Will get this updated. 

Also @joe-ayoub-segment On the deployment we will convert to our customers to install on next Thursday. 

Thanks

2023-11-22 12:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSFTP.types.ts
> +
Thanks @zhadier39 and @saadhypng . 

Just to clarify: We don't have a deploy happening this week. If we did we would push this change out. 
The next deploy is next Wednesday/Thursday. 

Best regards,
Joe

2023-11-22 12:46 UTC, saadhypng commented on packages/destination-actions/src/destinations/liveramp-audiences/audienceEnteredSFTP.types.ts
> +
Yes got it, next Thursday it will be live. 30th November.

2023-11-22 12:58 UTC, joe-ayoub-segment approved these changes

2023-11-22 13:12 UTC, joe-ayoub-segment commented
Hi @zhadier39 and @saadhypng , 

Looks like some CI issues. Can you take a look please?

![image](https://github.com/segmentio/action-destinations/assets/45374896/a07f881c-d29b-471f-8538-505a08a35bc5)

Thanks
Joe

2023-11-22 14:33 UTC, saadhypng commented
@joe-ayoub-segment I think the issue is resolved now.

2023-11-22 15:09 UTC, joe-ayoub-segment commented
> @joe-ayoub-segment I think the issue is resolved now.

Thank you @saadhypng , looks good! I'll merge prior to deploy.

2023-11-29 11:41 UTC, merged