[PINT-2052_2] - Add SMS registration and named user association
segmentio/action-destinations pull request #1786
Opened 2024-01-03 17:18 UTC by jumpingGrendel

This adds the SMS channel to the existing Register and Associate endpoint.

## Testing

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-01-07 14:37 UTC, joe-ayoub-segment requested changes
Hi @jumpingGrendel , thanks for raising this PR. 

Got an important change to request to the PR, as well as some minor changes. Please see the inline comments. 

Any chance you could attach some screenshots from testing you have done? If you haven't done any I'd be happy to assist if you want to schedule a call with me?

http://calendly.com/joe_ayoub/integration-workshop

Best regards,
Joe

2024-01-07 14:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +      required: true
hi @jumpingGrendel , we can't add a new required field as it will break data collection for all customers who are already using the Integration. What will happen is that the field value will be 'undefined' for those customers. 

Instead, let's make it an optional field. We can keep the default value = 'Email' in the field definition, but also do a check in the perform() function to see if the field is undefined. If it is undefined we should default to 'Email'.

2024-01-07 14:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +    const channel_type = payload.channel_type.toLowerCase()
This is where we should do the check for the field being undefined. 

e.g. 

const channel_type = (payload.channel_type ? payload.channel_type.toLowerCase() : 'email');

2024-01-07 14:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +  const channel_type = payload.channel_type
We'd also need to do the check for undefined here. Something like this: 

const channel_type = payload.channel_type ?? 'email'.

2024-01-07 14:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +  if (channel_type == 'Email') {
Can we make the string value 'Email' a const, and use that const throughout the code when need need to reference the string?

2024-01-07 14:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +  if (channel_type == 'Email') {
probably best to do the same for SMS / sms

2024-01-07 14:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/registerAndAssociate/index.ts
> +        { label: 'SMS', value: 'SMS' }
Can we make the values being passed into const values which will be referenced throughout the rest of the code base please?

2024-01-07 14:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +  } else if (channel_type == 'SMS') {
Let's make the string 'SMS' into a const.

2024-01-07 14:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/airship/utilities.ts
> +  return do_request(request, register_uri, email_register_payload)
Should we move this second do_request function call into the (channel_type == 'Email') conditional statement?

2024-01-12 20:22 UTC, jumpingGrendel commented
@joe-ayoub-segment as discussed, I tested these changes and everything works as expected. Feel free to merge/deploy.

2024-01-15 17:51 UTC, joe-ayoub-segment approved these changes
Reviewed in meeting with John - John tested with Actions Tester.

2024-01-16 12:22 UTC, merged

2024-01-16 14:49 UTC, joe-ayoub-segment commented
Hi @jumpingGrendel this PR has been deployed. 
Can you confirm that the change looks good from your perspective please?