Add Aggregations.io Destination
segmentio/action-destinations pull request #1789
Opened 2024-01-04 17:01 UTC by jsneedles

Added new destination for [Aggregations.io](https://aggregations.io).  

Aggregations.io doesn't require any special mapping or modifications to events, so the action is a pretty simple "Send Events" action.  User needs to provide their API Key as well as the `Ingest Id` they retrieve from their Aggregations.io dashboard. 

Batching is encouraged, so I defaulted that on with a default batch size of 300 (our max request size is 1MB so with Segment's event size limit of 32KB, seems sensible).

Please let me know if there are any questions or issues! 

## Testing

- Added basic tests for success & failure scenarios for `Send` method.
- Added basic test for auth 
- Ran unit tests locally, worked
- Used actions tester tool, worked
- Tested requests via postman as well, all worked as expected

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-01-07 11:37 UTC, joe-ayoub-segment commented
agreed with @tcgilbert that he will review this PR

2024-01-09 16:11 UTC, tcgilbert requested changes

2024-01-09 16:11 UTC, tcgilbert commented on packages/destination-actions/src/destinations/aggregations-io/index.ts
> +  slug: 'aggregations-io',
```suggestion
  slug: 'actions-aggregations-io',
```

2024-01-09 16:11 UTC, tcgilbert commented on packages/destination-actions/src/destinations/aggregations-io/index.ts
> +  name: 'Aggregations Io',
```suggestion
  name: 'Aggregations IO',
```

2024-01-09 16:11 UTC, tcgilbert commented on packages/destination-actions/src/destinations/aggregations-io/send/index.ts
> +  description: '',
```suggestion
  description: '',
```

need description

2024-01-09 16:11 UTC, tcgilbert commented on packages/destination-actions/src/destinations/aggregations-io/send/index.ts
> +      default: 300
```suggestion
      default: 300
      unsafe_hidden: true
```

2024-01-09 16:20 UTC, jsneedles commented on packages/destination-actions/src/destinations/aggregations-io/send/index.ts
> +  defaultSubscription: 'type = "track" or type = "page" or type = "screen"',
👍

2024-01-09 16:20 UTC, jsneedles commented on packages/destination-actions/src/destinations/aggregations-io/send/index.ts
> +      default: 300
👍

2024-01-09 16:21 UTC, jsneedles commented on packages/destination-actions/src/destinations/aggregations-io/send/index.ts
> +  description: '',
👍

2024-01-09 16:21 UTC, jsneedles commented on packages/destination-actions/src/destinations/aggregations-io/index.ts
> +  name: 'Aggregations Io',
went with `Aggregations.io` - assuming the `.` won't cause any issues?

2024-01-09 16:44 UTC, tcgilbert approved these changes

2024-01-10 13:24 UTC, joe-ayoub-segment approved these changes

2024-01-10 13:24 UTC, merged

2024-01-10 19:07 UTC, joe-ayoub-segment commented
hi @jsneedles this PR has been deployed. Thomas will send instructions for next steps via email.