[STRATCONN] [GA4] Added send_to key in all events
segmentio/action-destinations pull request #1803
Opened 2024-01-12 06:03 UTC by AnkitSegment

In this ticket added send_to key in all events of GA4. Now events are routed to specific group.

JIRA TICKET: https://segment.atlassian.net/browse/STRATCONN-3325

<img width="689" alt="Screenshot 2024-01-08 at 10 28 20 PM" src="https://github.com/segmentio/action-destinations/assets/139338151/9d3fd9c3-6159-410b-b34d-c581d54679c9">

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [X] [Segmenters] Tested in the staging environment

2024-01-12 09:37 UTC, varadarajan-tw reviewed
LGTM! Should the tests be updated for this change?

2024-01-12 09:55 UTC, AnkitSegment commented
> LGTM! Should the tests be updated for this change?

yes, this changes are deployed on stage and tested.

2024-01-13 19:07 UTC, dossy commented
Before this PR, events are sent to the `default` group which is the behavior when `send_to` is not specified.

https://developers.google.com/tag-platform/gtagjs/routing#default_group

This PR breaks this, and makes it impossible for someone using the GA4 Web destination to do so, as `send_to: settings.measurementID` is now hard-coded into the event params.

It would be better if someone who wants to use an explicit `send_to` event parameter for a mapped event to specify it in their `payload.params` and not force this on everyone.

2024-01-16 17:09 UTC, jsabor commented
Yes, the config does set the measurement id for all events; however, if there are multiple configs, or (1) config with multiple tag ids, if you don't limit the event with the `send_to` parameter, the event will broadcast to all tag ids.  Specifically, there is a issue where some GA4 event would broadcast to GAds since they share similar events, and it would cause (and has caused) a conflict.  If you look at how Google handles this in GTM, all events sent via a GTM GA4 Event tag include a send_to param so it sends specifically to the GA4 measurement id indicated in the tag.

Backwards compatibility will be updated, as well as documentation.

2024-01-16 18:04 UTC, dossy requested changes

2024-01-16 18:04 UTC, dossy commented on packages/browser-destinations/destinations/google-analytics-4-web/src/customEvent/index.ts
> +    gtag('event', event_name, { params: payload.params, send_to: settings.measurementID })
I think this needs to be:

```
gtag('event', event_name, {
  send_to: settings.measurementID,
  ...payload.params
})
```

2024-01-16 18:06 UTC, dossy commented
> Backwards compatibility will be updated, as well as documentation.

Okay.  This is definitely going to be a big gotcha for anyone who's currently using the GA4 Web destination.  Is there a way to version the destinations and pin your Segment configuration to a particular version?

2024-01-16 18:09 UTC, dossy commented on packages/browser-destinations/destinations/google-analytics-4-web/src/customEvent/index.ts
> +    gtag('event', event_name, { params: payload.params, send_to: settings.measurementID })
@varadarajan-tw what do you think?

2024-01-25 18:45 UTC, jsabor commented
The changes do support backwards capability.  If you want to run the event like it has in the past, it is equivalent to `send_to: default`  If the the user wants to add guardrails to the event, the user has to make the selection of `Yes` and that gives the output of `send_to: G-xxxx`

2024-01-25 18:58 UTC, jsabor commented
Backwards capability is applied to the update.  If you have a mapping created, there will be no selection and it will output `send_to: default` .  If you create a new mapping, it will pre-select yes, but the user can flip to no.

2024-01-26 15:57 UTC, dossy commented on packages/browser-destinations/destinations/google-analytics-4-web/src/ga4-properties.ts
> +  description: 'If a send_to parameter is not set, events are routed to the default target group.'
This is not true.  If the `send_to` parameter is not set, events are routed to `settings.measurementID`, not the `default` target group:

```
send_to: payload.send_to == undefined || payload.send_to == true ? settings.measurementID : 'default',
```

In order to not break backwards-compatibility, if `send_to` is not set, events SHOULD be routed to the `default` target group, which is what the current behavior is before this change.  But, this PR does not implement this, as of this moment.

2024-01-26 15:58 UTC, dossy commented on packages/browser-destinations/destinations/google-analytics-4-web/src/ga4-properties.ts
> +  description: 'If a send_to parameter is not set, events are routed to the default target group.'
@jsabor FYI.

2024-01-26 16:37 UTC, jsabor commented on packages/browser-destinations/destinations/google-analytics-4-web/src/ga4-properties.ts
> +  description: 'If a send_to parameter is not set, events are routed to the default target group.'
The condition line was changed yesterday, the latest commit has the changes.   

The default to `true` will happen for net new mappings.  Previous mappings will not have a value mapped and result in `send_to:default`

2024-02-08 16:11 UTC, closed without merging