[STRATCONN] [MAIN] GA4 updates in set config settings default values
segmentio/action-destinations pull request #1817
Opened 2024-01-22 06:36 UTC by AnkitSegment

Updated Set configuration field default settings. 

JIRA TICKET: https://segment.atlassian.net/browse/STRATCONN-3322

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [X] [Segmenters] Tested in the staging environment

2024-01-22 08:58 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/engage-messaging-sendgrid/previewApiLookup.types.ts
> +   * Whether the message should be retried (if the error code is retryable) when the data feed fails or if it should be sent with empty data instead
could you merge master into this branch? I think these changes have already been merged.

2024-01-22 08:58 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
> +    if (settings.cookieUpdate != true) {
Should we add tests? This changeset seems to introduce new `if` conditions.

2024-01-23 04:17 UTC, dossy commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
> +    }
This seems wrong?  If `settings.cookiePath` is set to `/foo`, then `settings.cookiePath.includes('/')` will be true, and the `!` negation will make this `if` evaluate to `false` and `config.cookie_path` will not get set to `settings.cookiePath` which is `/foo` -- this should probably be `if (settings.cookiePath != undefined && settings.cookiePath != '/') { ... }`

2024-01-23 04:20 UTC, dossy commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
> +    }
If `settings.pageView` is `true` then `config.send_page_view` will not be set here, which means it will be `undefined`?  The default value needs to be `true`; see the original line 109:

```
send_page_view: settings.pageView ?? true,
```

2024-01-29 16:41 UTC, dossy commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
>      }
This is still incorrect.

If `settings.cookiePath` is set to `/foo`, then `settings.cookiePath.includes('/')` will be true, and the `!` negation will make this `if` evaluate to `false` and `config.cookie_path` will not get set to `settings.cookiePath` which is `/foo` -- this should probably be `if (settings.cookiePath != undefined && settings.cookiePath != '/') { ... }`

2024-02-02 03:30 UTC, jsabor requested changes

2024-02-02 03:36 UTC, jsabor commented on packages/browser-destinations/destinations/google-analytics-4-web/src/index.ts
>      cookieUpdate: {
`default: true` and edit description

2024-02-21 06:53 UTC, varadarajan-tw reviewed
Thanks for adding tests. Left few more suggestions and comments.

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts
> +    const [trackEventPlugin] = await googleAnalytics4Web({
```suggestion
    const [setConfigurationEventPlugin] = await googleAnalytics4Web({
```

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
> +    const checkCookiePathValue =
Could you add a comment on why we are doing this check?

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts
> +    const [trackEventPlugin] = await googleAnalytics4Web({
```suggestion
    const [setConfigurationEventPlugin] = await googleAnalytics4Web({
```

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts
> +    expect(mockGtag).toHaveBeenCalledWith('config', 'G-XXXXXXXXXX', {
Could you add an expect statement for validating that gtag with 'consent` is never called?

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts
> +  it('should call gtag with the correct config when consent mode is disabled and having values in payload', async () => {
Does this name make sense?

```suggestion
  it('should not configure consent when consent mode is disabled', async () => {
```

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts
> +  it('should call gtag with the correct config when consent mode is enabled', async () => {
```suggestion
  it('should configure consent when consent mode is enabled', async () => {
```

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts
> +  it('should call gtag with the correct config when consent mode is disabled and cookie other then default value', async () => {
Since the focus of this test is on cookies, can we just rename the test to not include consent?
```suggestion
  it('should configure cookie when cookie path is other then default value', async () => {
```

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
> +    if (settings.cookieExpirationInSeconds != defaultCookieExpiryInSecond) {
Do we have a test to validate this if condition? Pls try and add separate tests for each and every if condition.

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
> +    if (settings.pageView != true) {
Do we have a test to validate this if condition? Pls try and add separate tests for each and every if condition.

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
> +    if (settings.cookieFlags) {
Do we have a test to validate this if condition? Pls try and add separate tests for each and every if condition.

2024-02-21 06:53 UTC, varadarajan-tw commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
> +    if (settings.pageView != true) {
Also there are three possible branch conditions here - It could be great if we have tests covering all three.

2024-02-21 07:04 UTC, AnkitSegment commented on packages/browser-destinations/destinations/google-analytics-4-web/src/setConfigurationFields/index.ts
> +    if (settings.cookieExpirationInSeconds != defaultCookieExpiryInSecond) {
added all test cookie related checks in single tests here. 

https://github.com/segmentio/action-destinations/blob/06c43e1c87d41eedcf187561911fe0600f22be55/packages/browser-destinations/destinations/google-analytics-4-web/src/__tests__/setConfigurationFields.test.ts#L146

will add a separate test cases.

2024-02-22 20:54 UTC, jsabor approved these changes
I did not review the tests but the other file changes look good.  Thank you!

2024-02-23 05:33 UTC, varadarajan-tw approved these changes

2024-02-23 11:27 UTC, joe-ayoub-segment commented
Will deploy next Monday/Tuesday

2024-02-27 12:55 UTC, joe-ayoub-segment commented
hi @AnkitSegment there are merge conflicts which need to be resolved.

2024-02-27 13:19 UTC, merged