Am/s2s destination
segmentio/action-destinations pull request #1828
Opened 2024-01-23 19:46 UTC by AlliterativeAlice

This pull request adds a new action destination for StackAdapt. StackAdapt is a demand-side platform customers use to run targeted programmatic ad campaigns. An important part of the programmatic advertising process (and advertising in general) is tracking conversions. This destination forwards Segment events to StackAdapt in order to enable StackAdapt customers who also use Segment to track conversion events based on their own definitions without needing to install the StackAdapt pixel or other tracking tools on their website.

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-01-24 10:23 UTC, joe-ayoub-segment commented
Thanks for raising this PR @AlliterativeAlice . I'll schedule for review.

2024-01-30 16:06 UTC, joe-ayoub-segment requested changes

2024-01-30 16:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/stackadapt/index.ts
> +  },
If you'd like the Integration to start sending data as soon as the customer enables it, then we need to add a preset mapping. This will initialize the Action. 

Here's the code to add: 

```
presets: [
    {
      name: 'Forward Event',
      subscribe: 'type = "identify" or type = "page" or type = "screen" or type = "track"',
      partnerAction: 'forwardEvent',
      mapping: defaultValues(forwardEvent.fields),
      type: 'automatic'
    },
]
```

2024-01-30 16:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/stackadapt/forwardEvent/index.ts
> +          }
I'd recommend splitting the products array into a separate field, maybe named something like 'Ecommerce Product Details' or something like that. 

The reason is that the Segment UI can't handle default mappings for a nested object, so the mappings for the product array won't work as you've defined them. 

You'll need to merge this array into your args in the perform function before sending the data.   

I can't think of any other way to do this unfortunately, but would be happy to chat if you've any thoughts?

2024-01-30 16:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/stackadapt/forwardEvent/index.ts
> +          else: { '@path': '$.properties.firstName' }
```suggestion
          exists: { '@path': '$.traits.first_name' },
          then: { '@path': '$.traits.first_name' },
          else: { '@path': '$.properties.first_name' }
```

2024-01-30 16:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/stackadapt/forwardEvent/index.ts
> +          else: { '@path': '$.properties.lastName' }
```suggestion
          exists: { '@path': '$.traits.last_name' },
          then: { '@path': '$.traits.last_name' },
          else: { '@path': '$.properties.last_name' }
```

2024-01-30 16:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/stackadapt/forwardEvent/index.ts
> +          else: { '@path': '$.properties.firstName' }
I know our docs indicate that you can use camel case for first name, but the convention the vast majority of  customers use is snake_case. Same for last name

2024-02-02 15:29 UTC, AlliterativeAlice commented on packages/destination-actions/src/destinations/stackadapt/index.ts
> +
Thanks for this and the other feedback Joe! We had a company-wide conference this week so I didn't get a chance to action it but I will submit the changes you requested early next week.

2024-02-06 19:17 UTC, joe-ayoub-segment commented
hi @AlliterativeAlice thanks for updating the PR. Only a couple of super minor comments. If you get the code updated today I can deploy tomorrow. Otherwise next deploy is Tuesday 13th.

2024-02-06 21:58 UTC, AlliterativeAlice commented
> hi @AlliterativeAlice thanks for updating the PR. Only a couple of super minor comments. If you get the code updated today I can deploy tomorrow. Otherwise next deploy is Tuesday 13th.

Thanks Joe, I've pushed updates based on your feedback. We probably will not be able to start private beta before the 13th so it should be okay if it doesn't get deployed tomorrow.

2024-02-07 08:42 UTC, joe-ayoub-segment approved these changes

2024-02-07 08:49 UTC, merged

2024-02-07 13:40 UTC, joe-ayoub-segment commented
Hi @AlliterativeAlice this PR has been deployed. I'll send next steps via email.