Add FullStory Browser destination version 2
segmentio/action-destinations pull request #1838
Opened 2024-01-29 20:04 UTC by ScottLNorvell

FullStory recently released a v2 of their browser api. The changes are different enough to warrant a second set of actions (`trackEvent`, `trackEventV2` etc...) I set these new actions to the default presets. I also set the server destination presets to point to version 2 now that the integration is in general availability. 

## Testing

Unit tests updated for browser v1 (adding `viewdPage` tests) as well as a second set of tests for the v2 actions.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-01-30 11:35 UTC, joe-ayoub-segment commented
Thanks for raising this PR @ScottLNorvell . I'll schedule for review.

2024-01-30 11:42 UTC, joe-ayoub-segment commented
Hi @ScottLNorvell - would you be able to confirm that you work for Heap please. You could do this by emailing me from your work address (to jayoub@twilio.com).

2024-01-30 14:34 UTC, ScottLNorvell commented
> Hi @ScottLNorvell - would you be able to confirm that you work for Heap please? You could do this by emailing me from your work address (to [jayoub@twilio.com](mailto:jayoub@twilio.com)).

Hi @joe-ayoub-segment I work for FullStory 😄 I'll email your from my work email. Thanks for reviewing!

2024-01-30 17:11 UTC, joe-ayoub-segment commented
> > Hi @ScottLNorvell - would you be able to confirm that you work for Heap please? You could do this by emailing me from your work address (to [jayoub@twilio.com](mailto:jayoub@twilio.com)).
> 
> Hi @joe-ayoub-segment I work for FullStory 😄 I'll email your from my work email. Thanks for reviewing!

hehe thanks Scott my bad!

2024-02-08 18:47 UTC, ScottLNorvell commented
Hi @joe-ayoub-segment I rebased this to deal with the merge conflicts and bumped the patch version for our `@fullstory/browser` sdk on this. I can't tell if I messed something up 🤔

2024-02-09 13:09 UTC, joe-ayoub-segment requested changes

2024-02-09 13:09 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/fullstory/src/viewedPageV2/index.ts
> +  perform: (FS, event) => {
nit: 

```
perform: (FS, event) => {
  const properties = event.payload.pageName ? { pageName: event.payload.pageName, ...event.payload.properties } : event.payload.properties;
  FS(
    'setProperties',
    {
      type: 'page',
      properties: properties
    },
    segmentEventSource
  );
}
```

2024-02-09 13:10 UTC, joe-ayoub-segment commented
Hi @ScottLNorvell - thanks again for raising this PR. 
Would it be possible to demonstrate that some testing was done to show that the pre-existing Actions continue to work as before please? And also show some proof of tests for the new Actions?

The CI checks are failing for some reason. I'll take a quick look into them.

2024-02-09 13:21 UTC, joe-ayoub-segment commented
Just looking at the original Actions. Is the camelCaseField() no longer needed in the new Actions?

2024-02-09 14:04 UTC, joe-ayoub-segment commented
Hi @ScottLNorvell I copied the PR code to a [new PR](https://github.com/segmentio/action-destinations/pull/1869) and the tests are passing. 
Note I didn't copy the yarn.lock 
I moved the server side code to a [separate PR](https://github.com/segmentio/action-destinations/pull/1872).

2024-02-09 14:07 UTC, closed without merging