Added Consent Signals to Google Enhanced Conversions
segmentio/action-destinations pull request #1847
Opened 2024-01-31 11:38 UTC by Innovative-GauravKochar

This Pull request is to add consent signal to Google  Enhanced Conversion.
Jira ticket :- https://segment.atlassian.net/jira/software/c/projects/STRATCONN/boards/310?assignee=63617339fc0cc7a600b03c6b&selectedIssue=STRATCONN-3396

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-02-02 00:04 UTC, rvadera12 commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts
> +        adUserData: 'GRANTED',
These need to be added as fields the user can change, with no defaults. We only send the consent object if the customer updates the value to denied or granted (with a dropdown menu). 

ad_user_data_consent_state: {
      description:
        'This represents consent for ad user data.',
      label: 'Ad User Data Consent State',
      type: 'string'
    },

ad_personalization_consent_state: {
      description:
        'This represents consent for ad personalization. This can only be set for OfflineUserDataJobService and UserDataService.',
      label: 'Ad Personalization Consent State',

    },

2024-02-02 00:06 UTC, rvadera12 commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +        adUserData: 'GRANTED',
These need to be added as fields the user can change, with no defaults. We only send the consent object if the customer updates the value to denied or granted (with a dropdown menu).

ad_user_data_consent_state: {
description:
'This represents consent for ad user data.',
label: 'Ad User Data Consent State',
type: 'string'
},

ad_personalization_consent_state: {
description:
'This represents consent for ad personalization. This can only be set for OfflineUserDataJobService and UserDataService.',
label: 'Ad Personalization Consent State',

}

2024-02-06 15:55 UTC, aklish requested changes
We should discuss this work and make sure it works with native consent features in cases where the customer is leveraging consent and those fields exist on the events we want to map.

2024-02-14 18:09 UTC, rvadera12 requested changes

2024-02-15 11:54 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadCallConversion.test.ts
> +        `"{\\"conversions\\":[{\\"conversionAction\\":\\"customers/1234/conversionActions/12345\\",\\"callerId\\":\\"+1234567890\\",\\"callStartDateTime\\":\\"2021-06-10 18:08:04+00:00\\",\\"conversi
this won't be possible in any case if we set a default value in a Dropdown.

2024-02-19 13:55 UTC, varadarajan-tw approved these changes

2024-02-22 07:22 UTC, Innovative-GauravKochar commented
@rvadera12  @aklish  Can you please review this PR?

2024-02-22 18:28 UTC, rvadera12 approved these changes

2024-02-22 20:43 UTC, aklish approved these changes

2024-02-22 21:30 UTC, merged