Add null checks for possible null trait
segmentio/action-destinations pull request #1848
Opened 2024-01-31 16:26 UTC by miguelpdiaz8

Adding null checks since it is possible the trait is null and we are calling .trim() function on it

## Testing

Added unit tests for all use cases and I'll test it on staging manually with Ria

2024-01-31 16:58 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
> +          traits: {
`traits` as an object can be null for both email and sms. lets add protection to that

2024-01-31 17:22 UTC, alfrimpong commented
Lets bring in additional reviewers from both our team and the CP team to take a look at this too.

2024-01-31 21:49 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/sendgrid/__tests__/send-email.test.ts
> +          traits: {
done

2024-02-06 19:57 UTC, alfrimpong requested changes

2024-02-06 19:57 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
>      profile: Profile
Lets change the type of `Profile.traits` from `Record<string, string>` to `Record<string, any>`

2024-02-13 10:28 UTC, joe-ayoub-segment commented
hi @miguelpdiaz8 and @alfrimpong  - do you still want to get this code deployed?

2024-02-26 18:17 UTC, miguelpdiaz8 commented
> hi @miguelpdiaz8 and @alfrimpong - do you still want to get this code deployed?

Hi @joe-ayoub-segment I already tested this, and it would be great to deploy it tomorrow but Albert is OOO today and I need his review since he requested a change, at what time are you deploying tomorrow?

2024-02-27 11:03 UTC, joe-ayoub-segment commented
Hi @miguelpdiaz8 I'll be starting the deploy in about 1h from now.

2024-02-27 13:48 UTC, alfrimpong approved these changes

2024-02-27 13:48 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
> +    const traits = liquidData.profile.traits ? { ...liquidData.profile.traits } : liquidData.profile.traits
Nonblocking Nit: This conditional feels a bit weird. `traits = {...liquidData.profile.traits}` instead?

2024-02-27 13:48 UTC, alfrimpong commented
> Hi @miguelpdiaz8 I'll be starting the deploy in about 1h from now. Can you and @alfrimpong please confirm that this code is good to go?

Its good

2024-02-27 13:50 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
> +    const traits = liquidData.profile.traits ? { ...liquidData.profile.traits } : liquidData.profile.traits
Eh, its actually fine. protects in the case of `undefined` (though it shouldnt be possible, we really never know)

2024-02-27 13:57 UTC, joe-ayoub-segment commented
@alfrimpong indicated on Slack that this PR is good to go.

2024-02-27 13:58 UTC, merged

2024-02-27 16:55 UTC, joe-ayoub-segment commented
hi @miguelpdiaz8 and @alfrimpong PR deployed!