Avo inspector destination
segmentio/action-destinations pull request #1850
Opened 2024-01-31 22:11 UTC by bjornj12

### Adding Avo Inspector as a new Segment Destination.
This Pull Requests adds the ability to send event schemas directly from segment to [Avo Inspector ](https://www.avo.app/docs/inspector/start-using-inspector) for observability.

The Destination will extract the property schema out of the event, and send it to the avo API.
No GDPR data is transmitted to the API. 

The destination requires the user to set up a source In Avo, and copy the API key from that source into the config of the segment destination.

It also requires the user to select an environment the data should be mapped to in Avo. (Dev/Staging/Prod)

The API acceps a batch of events by default, so both perform and batchPerform is supported.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-02-02 10:27 UTC, logason commented on packages/destination-actions/src/destinations/avo/index.ts
> +//import { SegmentEvent } from './avo-types'
🧹?

2024-02-02 10:27 UTC, logason commented on packages/destination-actions/src/destinations/avo/index.ts
> +        label: 'Api Key',
```suggestion
        label: 'API Key',
```

2024-02-02 10:27 UTC, logason commented on packages/destination-actions/src/destinations/avo/sendSchemaToInspector/AvoSchemaParser.ts
> +    // XXX TODO fix any types
This a remaining todo here @bjornj12?

2024-02-02 10:27 UTC, logason commented on packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo.ts
> +  const appVersion = event.appVersion ?? 'unversioned Segment app'
```suggestion
  const appVersion = event.appVersion ?? 'Unversioned'
```

2024-02-02 10:27 UTC, logason commented on packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo.ts
> +  const appVersion = event.appVersion ?? 'unversioned Segment app'
@bjornj12 Can we add an optional field to the config where users could overwrite which property we attempt to read here as the app version? (in case they're providing the app version with some other property)

Also: Is there some other way to fetch the app version here? I assume the Segment SDK is picking it up automatically in the mobile SDKs, can we access that here?

2024-02-02 10:27 UTC, logason commented on packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo.ts
> +    trackingId: '_',
Don't we want to generate a unique id here?

2024-02-02 10:56 UTC, bjornj12 commented on packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo.ts
> +  const appVersion = event.appVersion ?? 'unversioned Segment app'
Interesting idea @logason, I've seen examples where we can ask for a specific value, or default to fetching it from a place in the event. But i'm not sure if we can ask the user to give us a location in the event which we pass to the segment field extractor?

We can ask for a property name if they have a property for the version in `properties` and try to extract from there, but allowing them to say any property on the segment event might be more difficult, we'd at least have to receive the whole segment event to attempt to manually extract it ourselves i believe?



maybe @joe-ayoub-segment knows it better?

2024-02-02 10:59 UTC, bjornj12 commented on packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo.ts
> +    trackingId: '_',
We've deprecated trackingId, i've updated the API instead to allow it not be in the object, ill remove this field instead.

2024-02-02 11:01 UTC, bjornj12 commented on packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo.ts
> +    trackingId: '_',
curious though, if we'd want to generate uuid here, is that possible somehow @joe-ayoub-segment ? did not see uuid in package.json

2024-02-02 12:12 UTC, bjornj12 commented on packages/destination-actions/src/destinations/avo/sendSchemaToInspector/avo.ts
> +  const appVersion = event.appVersion ?? 'unversioned Segment app'
I´ve manged to extract it from a property in properties if they assign it in settings 👍

2024-02-02 12:16 UTC, bjornj12 commented
Hey @joe-ayoub-segment 
Thank you for reviewing 🙏

Here are answers to your questions

> Please provide a 1 line explanation for why a customer will want to use this Integration. ie. what's the use-case?

Connecting a Segment source to Avo Inspector enables customers to validate tracking, identify data issues, receive alerts for new issues, and enhance their tracking plan's quality.

> Please indicate which platforms customers will send data to Segment from. This can be any combination or web front end , mobile app, or back end service.

Customers might want to activate any platform that is using the Segment’s “track” method to track event based analytics. We have customers that have connected all of the above.
With this destination we expect one source to be connected to each destination, because the customer needs to provide a different Avo Inspector `apiKey` for each source.

> Please indicate which types of data you wish to forward on to your platform. This can be any combination of:
> user analytics event data
> user profile data
> web page impression data
> mobile screen impression data
> Segment Audience data

We only receive the schemas of the user analytics event data passed into the .track method of the Segment SDKs.. We might add support for more methods in the future.


> Please indicate which types of user identifiers your platform requires when data is forwarded from Segment. If you'll be collecting data from anonymous users please make sure to specify how those users will be identified by your platform.

We collect anonymised data only. We have no way to identify the customer´s users in any way.

Before sending to our API, we strip the event data of all identifiable data, and only send the event schema to our API.
Example:

`{“Event”: “Login Successful”, “properties”: {“user_id”: “johns_id”, “user_name”: “John Doe”}}`

Will be sent to our API as 
`{“eventName: “Login Successful”, “properties”: [{“propertyName”: “user_id”, “propertyType”: “string”}, {“propertyName”: “user_name”, “propertyType”: “string”}]}`

2024-02-06 12:02 UTC, joe-ayoub-segment requested changes

2024-02-06 12:02 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/avo/index.ts
> +          'Optionally set which property represents the app version in your events. If not set, the app version will be taken from the $event.app.version',
```suggestion
          'Optionally set which property represents the app version in your events. If not set, the app version will be taken from the $.context.app.version',
```

2024-02-06 13:18 UTC, joe-ayoub-segment approved these changes

2024-02-06 13:40 UTC, joe-ayoub-segment approved these changes

2024-02-06 13:40 UTC, merged

2024-02-07 13:38 UTC, joe-ayoub-segment commented
Hi @bjornj12 this PR has been deployed.