feat(Jimo/Actions): sendTrackEvent
segmentio/action-destinations pull request #1878
Opened 2024-02-13 13:43 UTC by imsamdez

Adding an action for track events

## Testing

Nothing too hard or specific, we basically subscribe to track events and call a method of our SDK.
That said, I saw that we were not able to access the `receivedAt` property of the event payload. Not sure why because in the testing tool, we do see the mapping happening, yet, the field is undefined.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-02-13 15:35 UTC, joe-ayoub-segment commented
Thanks for raising the PR @imsamdez . I'll schedule for review.

2024-02-15 14:11 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/jimo/src/sendTrackEvent/index.ts
> +    },
I would remove this field as it will always be undefined. 

Values at the $.receivedAt position in the payload are only added when the payload reaches Segment's servers. In your case you are transforming the event in the browser and then calling the Jimo API. So the payload you will be transforming will not contain anything at this location.

2024-02-15 14:12 UTC, joe-ayoub-segment requested changes

2024-02-15 14:12 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/jimo/src/sendTrackEvent/index.ts
> +    const receivedAt = timestamp
receivedAt will always be undefined for a web based Integration.

2024-02-15 14:13 UTC, joe-ayoub-segment commented
Other than the receivedAt issue the PR looks good @imsamdez !

2024-02-19 11:50 UTC, merged

2024-02-22 09:43 UTC, joe-ayoub-segment commented
Hi @imsamdez this PR has been deployed. Please check and let me know if there are any issues!

2024-02-23 19:51 UTC, imsamdez commented
Hey @joe-ayoub-segment,

Quick question, is it normal that the new action isn't mapped automatically for existing project.
For example, i've a project that only have the "Send user data" action mapped. But if i go to New mapping, i'm able to add the new Track action.
Also, after adding it, it seems to work well.
![00a5d5ec04a995078531f4196248e1b7](https://github.com/segmentio/action-destinations/assets/22425976/9baf4e78-5021-4e50-8961-42b4536f2469)
![67c87de2cb6880a0b8acb2986476d4bc](https://github.com/segmentio/action-destinations/assets/22425976/fd419074-0fd1-4887-b8a2-afa8abc01b51)

2024-02-27 10:38 UTC, imsamdez commented
Hey @joe-ayoub-segment. 

Alright, so we need to communicate to our customers each time we had a new action so that they can manually add it to their existing integration?