Channels-1034 Set google Api version for Push
segmentio/action-destinations pull request #1883
Opened 2024-02-14 22:11 UTC by Sneha-Uppalapati

[Channels-1034](https://segment.atlassian.net/browse/CHANNELS-1034) - This PR sets google API version for Push

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-02-20 21:57 UTC, cogwizzle approved these changes

2024-02-20 21:57 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage-messaging-twilio/sendMobilePush.types.ts
> +  googleApiVersion?: string
Nice!

2024-02-20 21:57 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage/twilio/__tests__/send-mobile-push.test.ts
> +      nock(notifyReqUrl).post('', notifyReqBody.toString()).reply(201, externalId)
Huh. I've never heard of nock. That seems relevant to Cesar's work as well.

2024-02-20 21:57 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/actionDefinition.ts
> +      choices: ['legacy', 'v1']
Should we put these in an Enum?

2024-02-20 22:08 UTC, Sneha-Uppalapati commented on packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/actionDefinition.ts
> +      choices: ['legacy', 'v1']
This file follows a pattern of choices always being array of strings or arrays of objects. So followed the same format.

2024-02-21 16:18 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/actionDefinition.ts
> +      choices: ['legacy', 'v1']
Should we set the default choice to `legacy`? Codewise, it behaves that way. We might as well give the align the expectations of mapping with the code-level behavior.

2024-02-21 20:32 UTC, Sneha-Uppalapati commented on packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/actionDefinition.ts
> +      choices: ['legacy', 'v1']
Yes, I agree, added `legacy` as default.

2024-02-22 17:23 UTC, alfrimpong approved these changes

2024-02-23 11:38 UTC, joe-ayoub-segment commented
Hi @Sneha-Uppalapati , @alfrimpong and @cogwizzle - please let me know when this is ready for review + deploy.

2024-02-23 13:03 UTC, Sneha-Uppalapati commented
Hi @joe-ayoub-segment thank you for checking. Yes, we've successfully verified the changes in stage and ready for review + deploy.

2024-02-27 10:08 UTC, joe-ayoub-segment requested changes

2024-02-27 10:08 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/actionDefinition.ts
> +      choices: ['legacy', 'v1'],
Hi @Sneha-Uppalapati, each choice needs to have a label and value. This field won't worth correctly otherwise.  

```
choices: [
  {label: 'legacy', value: 'legacy'},
  {label: 'v1', value: 'v1'}
]
```

2024-02-27 10:08 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/PushSender.ts
> +    if (this.payload.googleApiVersion === 'v1') {
Just FYI that `this.payload.googleApiVersion` will resolve to `undefined` for all customers who already have the Destination configured. While this won't cause a null pointer I want to check that you understand this and that the code is correct for your use-case. Can you confirm that you are OK with this please?

2024-02-27 10:08 UTC, joe-ayoub-segment commented
Hi @Sneha-Uppalapati minor change needed.

2024-02-27 12:15 UTC, joe-ayoub-segment commented
hi @cogwizzle @alfrimpong - can you please take a look prior at my comments prior to me deploying?

2024-02-27 17:39 UTC, alfrimpong commented
Looks like my git pull from main added a bunch of unrelated commits. Going to fix that up

2024-02-27 17:44 UTC, alfrimpong commented on packages/destination-actions/src/destinations/engage/twilio/sendMobilePush/PushSender.ts
> +    if (this.payload.googleApiVersion === 'v1') {
Ready for re-review. It is expected to resolve to `undefined` for existing customers. The code defaults to `legacy` in that case.

2024-03-05 13:12 UTC, merged