Moloco-RMP Destination Integration V1
segmentio/action-destinations pull request #1903
Opened 2024-03-01 01:05 UTC by heonjang

## Testing
- [ ✅ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality

1. `moloco-rmp/__tests__/convert.test.ts`: Testing the conversion logic.
2. `moloco-rmp/__tests__/index.test.ts`: Action-neutral unit tests.

- Default mappings
- Custom mappings
- Overwriting logics
- Special conversion logic (page identifier tokens)

3. `moloco-rmp/{action}/__tests__/index.test.ts`: Unit tests for each action

- [ ✅ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
Done for all action types.
- Tested valid events successfully reached Moloco side
- Tested invalid events threw errors

2024-03-01 01:40 UTC, heonjang commented on packages/destination-actions/src/destinations/moloco-rmp/common/convert.ts
> +import { PayloadValidationError } from '@segment/actions-core'
This module contains the conversion logic. It is responsible for converting the given input data into a Moloco-RMP-compatible format.

2024-03-01 01:40 UTC, heonjang commented on packages/destination-actions/src/destinations/moloco-rmp/common/fields.ts
> +import { InputField } from '@segment/actions-core/destination-kit/types'
This module contains the fields that will be shown in the mapping UI. There are two kinds of fields: Common and Variable fields. The common field will be exposed for all actions identically, but the variable fields can be shown with different requirements as well as their descriptions.

2024-03-01 01:40 UTC, heonjang commented on packages/destination-actions/src/destinations/moloco-rmp/common/request-client.ts
> +import {
This module is responsible for sending the data to the Moloco-RMP's end

2024-03-01 11:19 UTC, joe-ayoub-segment commented
Thanks for raising the PR @heonjang - I'll schedule for review.

2024-03-05 17:00 UTC, joe-ayoub-segment requested changes
Hi @heonjang thanks for raising this PR. 

I spent some time reviewing it and decided to ask that we meet again to discuss how it was put together. 

I believe that it can be simplified a lot. I don't think it will be much work, but it will make the code far easier to understand and maintain. 

Would you be able to schedule a call with me please? Let's go for a 1h meeting if you have the time?

http://calendly.com/joe_ayoub/integration-workshop

Best regards,
Joe

2024-03-05 17:00 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/moloco-rmp/common/fields.ts
> +  ]
Would it make sense to set a default?
e.g. 
default: 'APP'

2024-03-05 17:00 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/moloco-rmp/common/fields.ts
> +}
I recommend offering a list of choices, like this: 

```suggestion
export const DEFAULT_CURRENCY: InputField = {
  label: 'Default Currency',
  description: `The default currency value. If this is set, it will be used as a default currency value for items.',
  choices: [
  {label: 'UNKNOWN_CURRENCY', value: 'UNKNOWN_CURRENCY'},
  {label: 'USD', value: 'USD'},
  {label: 'KRW', value: 'KRW'},
  {label: 'JPY', value: 'JPY'},
  {label: 'EUR', value: 'EUR'},
  {label: 'GBP', value: 'GBP'},
  {label: 'SEK', value: 'SEK'},
  {label: 'INR', value: 'INR'},
  {label: 'THB', value: 'THB'},
  {label: 'IDR', value: 'IDR'},
  {label: 'CNY', value: 'CNY'},
  {label: 'CAD', value: 'CAD'},
  {label: 'RUB', value: 'RUB'},
  {label: 'BRL', value: 'BRL'},
  {label: 'SGD', value: 'SGD'},
  {label: 'HKD', value: 'HKD'},
  {label: 'AUD', value: 'AUD'},
  {label: 'PLN', value: 'PLN'},
  {label: 'DKK', value: 'DKK'},
  {label: 'VND', value: 'VND'},
  {label: 'MYR', value: 'MYR'},
  {label: 'PHP', value: 'PHP'},
  {label: 'TRY', value: 'TRY'},
  {label: 'VEF', value: 'VEF'}
],
  type: 'string',
  required: false
}
```

2024-03-05 17:00 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/moloco-rmp/common/fields.ts
> +  VEF: Venezuela Bolívar.`,
Same as with Default Currency field above. I'd recommend this be a choice array list.

2024-03-05 17:00 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/moloco-rmp/common/settings.ts
> +}
Not sure why this is needed. Why not reference the actual Settings interface from moloco-rmp/generated-types.ts?

2024-03-05 17:00 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/moloco-rmp/addToCart/index.ts
> +  description: 'Represents a user adding an item to his cart',
```suggestion
  description: 'Represents a user adding an item to their cart',
```

2024-03-05 17:00 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/moloco-rmp/common/request-client.ts
> +    }
There is no need for any of this code as you are using a RequestClient to send the data (which is the correct thing to do).    

Segment will automatically retry on a 5XX or 429. 
Errors are displayed to the customer in the delivery tab.

2024-03-06 21:12 UTC, heonjang commented on packages/destination-actions/src/destinations/moloco-rmp/common/fields.ts
> +  // could set a default value to '$.timestamp' but did not do so
Thanks for the suggestion, I will fix so!

2024-03-06 21:12 UTC, heonjang commented on packages/destination-actions/src/destinations/moloco-rmp/common/fields.ts
> +  ]
I don't think having a default value is a great idea.

Normally, if the integrated source uses ANALYTICS.JS, it would be SITE and APP for ANALYTICS.iOS/Android. Choosing any of them as a default value doesn't seem right

2024-03-06 21:13 UTC, heonjang commented on packages/destination-actions/src/destinations/moloco-rmp/common/fields.ts
> +  description: 'User Identifier for the platform. Recommended to hash it before sending for anonymization. The length should not exceed 128 characters.',
It was something recommended but not in a strict way. I will remove the recommendation in the description and consider your suggestion as well!

2024-03-06 21:13 UTC, heonjang commented on packages/destination-actions/src/destinations/moloco-rmp/common/fields.ts
> +}
Much readable. Thank you!

2024-03-08 06:07 UTC, heonjang commented
@joe-ayoub-segment 

Hi Joe, I've applied the reviews given by you earlier today!

Thank you for your detailed guidance, and please let me know if there is any further improvement to be made.

Best,

Shawn

2024-03-08 13:53 UTC, joe-ayoub-segment commented
hi @heonjang - would you be available to catch up before the deploy on Tuesday please?

I refactored the code and added some stuff which I think you might want to include. 

I'm available for the next few hours if you are free?

2024-03-08 14:53 UTC, joe-ayoub-segment commented
Hi @heonjang I raised a separate PR with some recommended changes. https://github.com/segmentio/action-destinations/pull/1917 

I tried to push the commit to a branch on your repo but I didn't have permission. 

Here's a [video](https://drive.google.com/file/d/1ezFARkN5SwFwriNrtpMrfTHX6BRWozsR/view?usp=sharing) of me walking through the changes.

2024-03-08 19:50 UTC, heonjang commented
> hi @heonjang - would you be available to catch up before the deploy on Tuesday please?
> 
> I refactored the code and added some stuff which I think you might want to include.
> 
> I'm available for the next few hours if you are free?

Sorry, I couldn't make it this morning. I will schedule it on Monday morning through Calendly!

2024-03-08 19:50 UTC, heonjang commented
> Hi @heonjang I raised a separate PR with some recommended changes. #1917
> 
> I tried to push the commit to a branch on your repo but I didn't have permission.
> 
> Here's a [video](https://drive.google.com/file/d/1ezFARkN5SwFwriNrtpMrfTHX6BRWozsR/view?usp=sharing) of me walking through the changes.

Thank you so much. I will watch the video and apply the updates you suggested

2024-03-11 18:21 UTC, joe-ayoub-segment commented
Closing PR as replaced by https://github.com/segmentio/action-destinations/pull/1903

2024-03-11 18:21 UTC, closed without merging