Update logic for selecting the app or pixel id based upon the event_c…
segmentio/action-destinations pull request #1913
Opened 2024-03-06 20:16 UTC by bordoley

…onversion_type

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-03-11 09:22 UTC, joe-ayoub-segment requested changes

2024-03-11 09:22 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
> +  } else if (v != null) {
should this be a check for undefined instead of null?

2024-03-11 09:22 UTC, joe-ayoub-segment commented
hi @bordoley just one minor comment to look at/clarify.

2024-03-11 14:13 UTC, bordoley commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/utils.ts
> +  } else if (v != null) {
Weak equality in javascript allows you to use `!= null` to check both the undefined and null object case. It's a trick I learned at FB that allows you be a bit more safe in codebases that don't explicitly ban the use of the null object via linters.

2024-03-12 12:46 UTC, merged

2024-03-12 16:48 UTC, joe-ayoub-segment commented
hi @bordoley PR deployed