Update TikTok Pixel Destination
segmentio/action-destinations pull request #1937
Opened 2024-03-18 21:04 UTC by jae-rhee-tiktok

Update TikTok Pixel Destination to support all TikTok standard web events & event properties.

2024-03-19 15:03 UTC, joe-ayoub-segment requested changes

2024-03-19 23:40 UTC, jae-rhee-tiktok commented on packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
>      }
@joe-ayoub-segment is there a way to set global setting to hidden? It looks like 'hidden' type not supported for `GlobalSetting`.

2024-03-27 10:08 UTC, joe-ayoub-segment requested changes

2024-03-27 10:08 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
>      }
No need. This setting is hidden for nearly all customers.

2024-03-27 10:08 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
> +    initScript(settings)
Hi @jae-rhee-tiktok - as per my email a moment ago let's leave this code as is.

2024-03-27 16:16 UTC, jae-rhee-tiktok commented on packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
>      }
Got it - thank you!

2024-03-27 16:16 UTC, jae-rhee-tiktok commented on packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
> +    initScript(settings)
Reverted back to previous init script logic.

2024-04-03 12:15 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
> +      label: '[Deprecated]Use Existing Pixel',
```suggestion
      label: '[Deprecated] Use Existing Pixel',
```

2024-04-03 12:17 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
> +      initScript(settings)
```suggestion
      initScript(settings.pixelCode)
```

2024-04-03 12:18 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
> +      initScript(settings)
i.e I don't believe this line should change at all.

2024-04-03 12:19 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/tiktok-pixel/src/index.ts
> +      initScript(settings)
Oops my bad - I see you've changed the initScript function itself... please ignore!

2024-04-03 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/generated-types.ts
> +   * A single email address. TikTok Pixel will be hash this value before sending to TikTok.
The same field in the TikTok Offline Conversions Destination also includes the following: 

At least one email value is required if both Phone Number and External ID fields are empty.

Should this apply for TikTok pixel as well?

2024-04-03 12:30 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/generated-types.ts
> +   * Uniquely identifies the user who triggered the conversion event. TikTok Pixel will hash this value before sending to TikTok.
TikTok Offline Conversions also includes the following: 

TikTok Offline Conversions Destination supports both string and string[] types for sending external ID(s). At least one external ID value is required if both Email and Phone Number fields are empty.

Should something similar apply for TikTok Pixel?

2024-04-03 12:45 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/tiktok-pixel/src/reportWebEvent/formatter.ts
> +}
Should we also handle the case where 'array' is empty?
Should we also handle the case where array is a single string? i.e not an array?

2024-04-04 14:53 UTC, jae-rhee-tiktok commented on packages/browser-destinations/destinations/tiktok-pixel/src/common_fields.ts
> +    multiple: true,
I changed this to be a string array to match the s2s destination mappings, so that clients can re-use the same mappings for both Pixel & S2S destinations.

2024-04-15 11:16 UTC, joe-ayoub-segment approved these changes

2024-04-15 11:16 UTC, merged

2024-04-23 14:33 UTC, joe-ayoub-segment commented
PR deployed