Pass eventOccurredTS value to the custom_args of the sendgrid/twilio body
segmentio/action-destinations pull request #1955
Opened 2024-03-27 16:14 UTC by miguelpdiaz8

In the DestinationAction payload we receive eventOccurredTS, which we use to stats event delivery latency which is for some reason called [eventDeliveryTS](https://github.com/segmentio/action-destinations/blob/0a761433021e6310fff08b361debf479a38a9fb0/packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts#L202-L208). Regardless of confusing name - this metric helps to understand how much time it took from the event creation till the end of event processing by Destination Action.

It would be helpful to pass that eventOccurredTS value to the [custom_args](https://github.com/segmentio/action-destinations/blob/0a761433021e6310fff08b361debf479a38a9fb0/packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts#L146) of the sendgrid/twilio body, so it will be returned to a webhook call after email/sms is delivered and we can add that [twilio|sendgrid]_eventDeliveryDuration metric to [engage-events-ingest service](https://github.com/segmentio/engage-events-ingest/blob/be6cbc49d70c49a644ef410ee3a2f4b9f60dac52/internal/eventconsumer/eventconsumer.go#L265C4-L265C4) (supplying all the tags that twilio_total and sendgrid_total have) to track how much time it takes for email/sms to be delivered from the moment of placing it to centrifuge to the moment of delivering it to the user.

## Testing

Updated unit tests

2024-04-03 08:59 UTC, joe-ayoub-segment commented
hi @miguelpdiaz8 please let me know when someone on your team has reviewed, and when you are happy for me to review+deploy.

2024-04-03 16:26 UTC, miguelpdiaz8 commented
> hi @miguelpdiaz8 please let me know when someone on your team has reviewed, and when you are happy for me to review+deploy.

Hi @joe-ayoub-segment I just shared with the team, and you can review it too, thanks

2024-04-03 16:32 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage/twilio/__tests__/send-mobile-push.test.ts
> +    eventOccurredTS: '2024-03-23'
How come the format on this timestamp is different than the timestamps in `send-email.test`?

2024-04-03 18:23 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
> +      event_occurred_ts: (this.payload as any)?.eventOccurredTS,
Why do we need to cast using any here?

2024-04-03 18:32 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/twilio/__tests__/send-mobile-push.test.ts
> +    eventOccurredTS: '2024-03-23'
Updated, thanks

2024-04-03 18:51 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
> +      event_occurred_ts: (this.payload as any)?.eventOccurredTS,
TwilioMessageSender extends MessageSendPerformer and that is the way it is used there too, I think the reason is MessagePayloadBase doesn't have the eventOccurredTS property in it, but during execution time the payload has it as we can see during testing.

2024-04-03 19:07 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
> +      event_occurred_ts: (this.payload as any)?.eventOccurredTS,
Should we fix the type?

2024-04-03 19:40 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
> +      event_occurred_ts: (this.payload as any)?.eventOccurredTS,
Just added it, but I would like to get @pmunin eyes to be sure I'm not breaking anything, since he is the one who created those types, thanks Joe!

2024-04-05 19:08 UTC, pmunin requested changes
Twilio Tags missing

2024-04-05 19:14 UTC, miguelpdiaz8 commented on packages/destination-actions/src/destinations/engage/twilio/utils/TwilioMessageSender.ts
> +      event_occurred_ts: this.payload?.eventOccurredTS,
Yes, I had the tags change but changed it back, I was waiting to ask you about the tags limit knowing it exists and it currently has 10 tags already, do you know which one I could remove safely, or if that limit can be changed? Thanks Philipp

2024-04-11 13:01 UTC, cogwizzle commented
Looks good. I'll defer to @pmunin as he has requested additional changes.

2024-04-11 22:19 UTC, rahul8590 commented
Can you confirm if adding a new field within custom_args impacts the processing of current event payload with [engage-events-ingest service? In theory, it shouldn't. But in the past, we have seen payloads get dropped (4xx response) due to bad format.

2024-04-15 15:27 UTC, miguelpdiaz8 commented
> Can you confirm if adding a new field within custom_args impacts the processing of current event payload with [engage-events-ingest service? In theory, it shouldn't. But in the past, we have seen payloads get dropped (4xx response) due to bad format.

So you are saying there is no a hard limit of 10 custom args?

2024-04-16 10:09 UTC, joe-ayoub-segment commented
hi @miguelpdiaz8 @pmunin @rahul8590 @cogwizzle  - friendly reminder to let me know when this is ready for deploy.

2024-04-23 12:00 UTC, joe-ayoub-segment commented
hi @miguelpdiaz8 - please let me know when this PR is ready for review / and then to be deployed. 
If you need more time please convert it to a draft PR :)

2024-07-16 09:37 UTC, joe-ayoub-segment commented
Hi @miguelpdiaz8 if this PR isn't going to be progressed for the moment can we close it please?

2025-05-06 13:30 UTC, closed without merging