Dynamic Yield: turning Destination into Audience Destination
segmentio/action-destinations pull request #1987
Opened 2024-04-10 12:54 UTC by joe-ayoub-segment

Turning DY Destination into an Audience Destination

## Testing

None done yet. Do not deploy

2024-04-11 10:25 UTC, djluis approved these changes
Looks good for the initial mapping with the primary identifiers, later we must include the custom "dynamic" identifiers. 👍 thanks again for the support @joe-ayoub-segment

2024-04-11 10:25 UTC, djluis commented on packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
> +    switch(settings.identifier_type){
If I'm understanding correctly, this works for the primary identifiers, but later we need to add some dynamic code to fetch a custom identifier, like the example below:
```
default: {
   primaryIdentifier = payload[settings.identifier_type] ?? undefined
}
```

2024-04-11 10:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
> +    switch(settings.identifier_type){
> If I'm understanding correctly, this works for the primary identifiers, but later we need to add some dynamic code to fetch a custom identifier, like the example below:
> 
> ```
> default: {
>    primaryIdentifier = payload[settings.identifier_type] ?? undefined
> }
> ```

hi @djluis I decided to go ahead and hard code the 3 most common identifiers into a dropdown list, and to make email the default. If you are able to expose an API we can use to populate a dynamic list then we can make use of it.

Currently, the code only adds the identifier for the selected identifier_type into the payload which gets sent to DY. We could change this to include all identifiers we have, if you like. Though you'll have to show me how to structure that information in the payload.

2024-04-29 16:15 UTC, djluis requested changes

2024-04-29 16:15 UTC, djluis commented on packages/destination-actions/src/destinations/dynamic-yield-audiences/syncAudience/index.ts
> +            value : hashAndEncode(primaryIdentifier)
@joe-ayoub-segment We need to discuss this on next meeting ⚠️

2024-04-30 12:27 UTC, merged

2024-04-30 14:58 UTC, joe-ayoub-segment commented
PR deployed