Add Magellan AI (Action) Destination
segmentio/action-destinations pull request #2008
Opened 2024-04-24 20:05 UTC by leboshi

Initial PR adding an action destination for [Magellan AI](https://www.magellan.ai)'s measurement and attribution platform ([more information](https://help.magellan.ai/)).

## Testing

- [X] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

Tested locally, and we *think* we properly constructed all the complex e-commerce events. 🤞

## Notes

PR for documentation incoming.  Documentation points out that semantically, the `Signed Up` event maps most closely to our `Lead` action, but our concept of leads would fit better with your e-commerce events.

Thank you, and let us know what next steps you need from us!

2024-04-25 12:34 UTC, joe-ayoub-segment commented
Thanks for raising the PR for a new Integration @leboshi . I'll schedule for review.

2024-04-30 08:40 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/code/index.ts
> +      default: 'promo',
hi @leboshi - is there a limited number of types for coupons/codes? If so, you could restrict the input to only those choices. 

add this line: 

choices: [
   {label: 'Promo', value: 'promo'},
  ...
]

This has the added benefit of validating the field and rejecting the input before the perform() function is invoked. So only payloads which validate will actually result in the perform() function being invoked.

2024-04-30 08:45 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/lead/index.ts
> +      default: { '@path': '$.properties.type' },
If there are a limited number of Lead Types, consider restricting the choices available. 
```
 choices: [
    {label: 'Lead type 1', value: 'lead_type_1'},
     ...
]
```

2024-04-30 08:46 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/lead/index.ts
> +      default: { '@path': '$.properties.category' },
Same here - maybe there are only a limited number of Lead Categories?

2024-04-30 08:48 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/lead/index.ts
> +    },
Should the Lead ID have a default mapping to a user identifier of some sort?
In general this could be something like this: 

```
default: { '@path': '$.userId' }
```
or 

```
default: { '@path': '$.context.traits.email' }
```
or 

```
default: { '@path': '$.anonymousId' }
```

2024-04-30 08:57 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/utils.ts
> +    return request(url, { method: 'post', json: payload })
Do you need to set any specific headers before sending?

2024-04-30 08:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +export function priceFields(valueSource = 'value'): Record<string, InputField> {
usually as per the Segment Spec, the price of a product is contained in this path: 

```
default: { '@path': `$.properties.price` },
```

2024-04-30 09:02 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +    default: { '@path': '$.receivedAt' },
I would recommend using this mapping instead for timestamp: 

```
default: { '@path': '$.timestamp' },
```

This is the clock skew corrected timestamp, and will always be present in every Segment event.

2024-04-30 09:03 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +    label: 'Quantity',
The default value here could be: 

```
default: { '@path': '$.properties.quantity' },
```

2024-04-30 09:07 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +        label: 'Quantity',
```suggestion
        label: 'Price',
```

2024-04-30 09:08 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +        label: 'Product type',
Should this map to product category?

2024-04-30 09:10 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/identify/index.ts
> +      default: { '@path': '$.traits.id' },
The location for userId in the Segment payload is as per below. Note this is only present once the user has been identified by the customer. Typically post login or post registration. 

```suggestion
      default: { '@path': '$.userId' },
```

2024-04-30 09:12 UTC, joe-ayoub-segment requested changes
Hi @leboshi thanks again for raising this PR. 

I left some inline comments for you to look at. 

With most of the Mappings it looks like you are not passing a user identifier of some sort. Why is that? Do you not need one?

2024-04-30 22:23 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/code/index.ts
> +      default: 'promo',
Nope!  All string values are valid.

2024-04-30 22:23 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/lead/index.ts
> +      default: { '@path': '$.properties.type' },
Same here; all string values are valid.

2024-04-30 22:24 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/lead/index.ts
> +      default: { '@path': '$.properties.category' },
Same

2024-04-30 22:25 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/utils.ts
> +    return request(url, { method: 'post', json: payload })
Nope!

2024-04-30 22:28 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +    default: { '@path': '$.receivedAt' },
Sure, I'll change that.  The documentation says `$.timestamp` is "spoofable," and `$.receivedAt` seemed like a more reliable field.

2024-04-30 22:34 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/lead/index.ts
> +    },
We omitted a default mapping because implementing this action, specifically, is so "YMMV".  Some people might use the B2B Saas "Signed Up" event, in which case all the e-commerce-esque fields will be absent (or hard-coded dummy values), or they might use some other e-commerce event, in which case this might be an order ID or a coupon ID or something.  Especially since this is an optional field, the default mapping was deliberately left blank, but if you think that's not ideal, I think the most usable default we're guaranteed to have in the payload would be `default: { '@path': '$.messageId' }`.  Thoughts?

2024-04-30 22:43 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +export function priceFields(valueSource = 'value'): Record<string, InputField> {
Sorry, are you suggesting changing the default value to `'price'` and then explicitly passing `'value'` instead?  I'm not sure what this comment is actually pointing out...

2024-04-30 22:44 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +        label: 'Quantity',
Ooh thanks!

2024-04-30 22:48 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +        label: 'Product type',
Doesn't it, at 156?

2024-04-30 22:51 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/thirdPartyEvent/index.ts
> +  defaultSubscription: 'type = "track" and event in ["foo", "bar"]',
I like omitting it entirely.  Thanks!

2024-04-30 22:55 UTC, leboshi commented
Nope, user IDs should only be sent in Identify calls and GDPR delete requests.

2024-05-01 11:15 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/lead/index.ts
> +    },
hi @leboshi based on your explanation it probably makes sense to let the customer apply the mapping themselves instead of having a default one in place. 

I would steer clear of using `messageId` as it's just a GUID created by Segment to ensure each API call is unique.

2024-05-01 11:16 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +export function priceFields(valueSource = 'value'): Record<string, InputField> {
hi @leboshi yes that's correct. Customers will usually put the value of a product in the `$.properties.price` location in a payload. You can still send it as `value` to your platform. 

Again this is only a suggestion.

2024-05-01 11:19 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +        label: 'Product type',
missed that, thanks !

2024-05-01 11:20 UTC, joe-ayoub-segment approved these changes

2024-05-01 11:21 UTC, joe-ayoub-segment commented
Hi @leboshi I've approved the PR to be deployed. 
Just need to ensure CI checks pass. 
Feel free to change anything you like - I'll re-review and approve. 
The next deploy is scheduled for Tuesday - though I may run one today.

2024-05-01 11:51 UTC, merged

2024-05-01 16:39 UTC, joe-ayoub-segment commented
Hi @leboshi deploy complete. I will email you next steps.

2024-05-01 17:19 UTC, leboshi commented on packages/destination-actions/src/destinations/magellan-ai/schema.ts
> +export function priceFields(valueSource = 'value'): Record<string, InputField> {
OK, I'll commit that change to our fork, and whenever the next time is we need to raise a PR, that'll make it in with it.  Thanks!

2024-05-01 17:19 UTC, leboshi commented
Thank you for all the help with the PR review!