feat: added Contentstack's destination-action.
segmentio/action-destinations pull request #2016
Opened 2024-04-30 11:20 UTC by hanoak20

Added Contentstack's Destination Action.

Description:
Added an action called "customAttributesSync" to sync custom attributes, computed attributes, and audience into Contentstack's Personalization. All of these syncs work on 'identify' events.

2024-05-03 15:05 UTC, joe-ayoub-segment commented
Hi @hanoak20 thanks for raising this PR. 

I'm out of office until 16-May and will review the PR then. 

If you have an urgent query please email partner-support@segment.com 

Kind regards,
Joe

2024-05-08 06:57 UTC, hanoak20 commented on packages/destination-actions/src/destinations/contentstack/index.ts
> +    scheme: 'oauth2',
We've incorporated this change.

2024-05-08 08:01 UTC, hanoak20 commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +  fields: {},
Hi @tcgilbert, Thank you so much for your suggestion on this. As of now, we're okay with just the identify calls. Since we're getting started with the integration, we're concentrated to get this integration up and running with a simple flow. Yes, definitely we'll improve this as we proceed further.

2024-05-08 08:02 UTC, hanoak20 commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +    const customTraitsOfSegment = Object.keys(rawData?.traits || {})
We'll ignore this, for this release, as we're adding them later.

2024-05-08 20:42 UTC, tcgilbert requested changes
You'll need to correct the Custom Attributes Sync description. Adding the requested `extendRequest` is optional, but I believe you'll find that it cleans up your code a good deal. 

One thing you'll need to add eventually are some [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#unit-testing). But considering you primarily want this deployed to test in private, I'll go ahead and mark this ready for release so this will be included in the next deployment.

The next deploy is scheduled on Tuesday.

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +  description: 'This action destination is used to sync custom attributes to your contentstack experience',
```suggestion
  description: 'This action is used to sync custom attributes to your contentstack experience, and is only compatible with Identify events.',
```

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/index.ts
> +  },
```suggestion
  },
  extendRequest({ auth, settings }) {
    return {
      headers: {
        Authorization: `Bearer ${auth?.accessToken}`,
        organization_uid: settings.orgId,
        'x-project-uid': settings.personalizeProjectId
      }
    }
  },
```

Just a recommendation to cleanup code a bit. extendRequest will establish these headers anywhere you use the request object

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/utils.ts
> +  accessToken: string
```suggestion
```

No longer need if use extendRequest

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/utils.ts
> +    }
```suggestion
```
No longer need if use extendRequest

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/utils.ts
> +  accessToken: string
```suggestion
```

No longer need if use extendRequest

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/utils.ts
> +    }
```suggestion
```

No longer need if use extendRequest

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +      await fetchAllAttributes(request, settings?.orgId, settings?.personalizeProjectId, auth?.accessToken || '')
```suggestion
      await fetchAllAttributes(request)
```

No longer need if use extendRequest

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +      )
```suggestion
      const firstAttributeRes = await createCustomAttrbute(request, attributesToCreate[0])
```
No longer need if use extendRequest

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +      )
```suggestion
      await Promise.allSettled(otherAttributes.map((trait: string) => createCustomAttrbute(request, trait)))
```

No longer need if use extendRequest

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +        }
```suggestion
        headers: {
          'x-cs-eclipse-user-uid': rawData?.userId || '',
        }
```

No longer need if use extendRequest

2024-05-08 20:42 UTC, tcgilbert commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +    const { settings, rawData, auth } = d
```suggestion
    const { rawData } = d
```

No longer need if use extendRequest

2024-05-09 14:48 UTC, tcgilbert requested changes

2024-05-09 14:48 UTC, tcgilbert commented on package.json
> +  "packageManager": "yarn@1.22.22+sha1.ac34549e6aa8e7ead463a7407e1c7390f61a6610"
```suggestion
}
```

Can you remove this?

2024-05-10 14:30 UTC, tcgilbert approved these changes

2024-05-16 08:31 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +    const customTraitsOfSegment = Object.keys(rawData?.traits || {})
Can we do this in the standard way instead of accessing the rawData unnecessarily? 
We only allow use of rawData as a workaround as it breaks a platform standard convention. 

Simply add a hidden field called traits.

```
{
   traits: {
       type: "object",
       default: {"@path": "$.traits"}, 
       label: "User traits",
       description: "hidden field to collect traits from Identify() call",
       required: true
    }
    
}
```

2024-05-16 08:39 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +          'x-cs-eclipse-user-uid': rawData?.userId || ''
userId should also be a field. 

```
{
   userId: {
       type: "string",
       default: {"@path": "$.userId"}, 
       label: "User ID",
       description: "ID for the user",
       required: false
    }
}
```

you will then access it like this: 

```
'x-cs-eclipse-user-uid': payload.userId ?? ''
```

2024-05-16 08:39 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +        json: rawData?.traits,
```suggestion
        json: payload.traits,
```

2024-05-16 08:42 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/index.ts
> +    scheme: 'oauth-managed',
```suggestion
    scheme: 'oauth2',
```

2024-05-16 08:44 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/index.ts
> +    scheme: 'oauth-managed',
Using oauth2 will allow you to confire scopes and secrets in the Segment UI.

2024-05-16 08:45 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/types.ts
> +}
This shouldn't be needed if you use regular fields for accessing data.

2024-05-16 08:47 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +    'This action is used to sync custom attributes to your contentstack experience, and is only compatible with Identify events.',
```suggestion
    'Sync Custom Attributes to your Contentstack Experience.',
```

2024-05-16 08:48 UTC, joe-ayoub-segment requested changes
hi @hanoak20 thanks again for raising this PR. 

I'm just back from PTO and noticed that there are some things that we do need to change before we deploy this code. 

I've provided suggestions. These changes are super simple but will reduce the potential for technical debt on our platform. 

Kind regards,
Joe

cc @tcgilbert

2024-05-17 07:13 UTC, joe-ayoub-segment approved these changes

2024-05-17 07:20 UTC, sankartn commented on packages/destination-actions/src/destinations/contentstack/customAttributesSync/index.ts
> +    'This action is used to sync custom attributes to your contentstack experience, and is only compatible with Identify events.',
Hi @joe-ayoub-segment Just to let you know that, the description was like this only even previously. We updated as per Thomas's comments only.

2024-05-21 15:28 UTC, merged

2024-05-21 20:07 UTC, joe-ayoub-segment commented
hi @hanoak20 - PR deployed. Please confirm the change is good !