1flow web sdk event update
segmentio/action-destinations pull request #2019
Opened 2024-05-01 09:31 UTC by namit1Flow

**Updates**

1. Updated SDK Initialization
2. SDK URL Updates
3. SDK Event Call & Payload Updates

2024-05-01 10:59 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/1flow/src/identifyUser/index.ts
> +        '@path': '$.first_name'
hi @namit1Flow - a customer will never place first_name at this location in the payload. In an identify() call it will always be in traits.first_name.

2024-05-01 11:00 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/1flow/src/identifyUser/index.ts
> +        '@path': '$.last_name'
same comment as per above.

2024-05-01 11:00 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/1flow/src/identifyUser/index.ts
> +        '@path': '$.phone'
Same comment as per above.

2024-05-01 11:00 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/1flow/src/identifyUser/index.ts
> +        '@path': '$.email'
Same comment as per above.

2024-05-01 11:01 UTC, joe-ayoub-segment requested changes
hi @namit1Flow thanks for raising this PR. 

Only query I have is related to the change in mapping paths. Please see inline comments.

2024-05-02 04:39 UTC, namit1Flow commented on packages/browser-destinations/destinations/1flow/src/identifyUser/index.ts
> +        '@path': '$.first_name'
You’re correct, fixed it please check

2024-05-03 14:42 UTC, joe-ayoub-segment approved these changes

2024-05-03 14:43 UTC, joe-ayoub-segment commented
Hi @namit1Flow I'm going to be on leave until 16-May. Is deploying this PR urgent? Is it OK to wait until I get back to deploy this?

cc @tcgilbert

2024-05-03 15:10 UTC, namit1Flow commented
Hi @joe-ayoub-segment , Currently one of our internal customers is waiting for these changes so if possible would you be able to deploy these changes asap ?

2024-05-03 15:13 UTC, joe-ayoub-segment commented
> Hi @joe-ayoub-segment , Currently one of our internal customers is waiting for these changes so if possible would you be able to deploy these changes asap ?

FYI @PoojaSrinivasan18 and @tcgilbert  ^

2024-05-17 13:39 UTC, namit1Flow commented
@joe-ayoub-segment  @tcgilbert  When should I expect it to be deployed?

2024-05-20 11:34 UTC, joe-ayoub-segment commented
hi @namit1Flow The PR is good to deploy - however the company has mandated a deploy freeze due to an ongoing internal issue. 
I will deploy the code as soon as this has been resolved. It should hopefully be this week.

2024-05-21 15:28 UTC, merged

2024-05-23 17:25 UTC, joe-ayoub-segment commented
hi @namit1Flow this PR has been deployed. Can you confirm that you are happy with the changes please?