[wip don't review] [Salesforce] username password flow
segmentio/action-destinations pull request #2023
Opened 2024-05-02 21:32 UTC by nick-Ag

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-05-06 23:21 UTC, marinhero requested changes

2024-05-06 23:21 UTC, marinhero commented on packages/destination-actions/src/destinations/salesforce/sf-operations.ts
> +const constructPassword = (password: string, securityToken?: string): string => {
Please add a comment here to indicate when a combination is required and when it isn't

2024-05-06 23:36 UTC, nick-Ag commented on packages/destination-actions/src/destinations/salesforce/sf-operations.ts
> +  const clientId = process.env.SALESFORCE_CLIENT_ID
These have always existed in prod

2024-05-07 00:51 UTC, marinhero approved these changes

2024-05-07 16:17 UTC, marinhero requested changes
Revoking approve until the flagon issue is fixed

2024-05-15 20:45 UTC, marinhero approved these changes

2024-05-16 00:19 UTC, nick-Ag commented
@varadarajan-tw or @joe-ayoub-segment To whoever deploys this, I will handle the `push` operation when I'm ready to release this

2024-05-21 17:05 UTC, joe-ayoub-segment commented
@nick-Ag said this is OK to deploy

2024-05-21 17:05 UTC, merged

2024-05-21 20:08 UTC, joe-ayoub-segment commented
hi @nick-Ag PR deployed! Not pushed as requested.