channels-1094
segmentio/action-destinations pull request #2024
Opened 2024-05-03 14:21 UTC by cogwizzle

refactor: Refactoring the name for dataFeedCache to be
engageDestinationCache. This is because this cache is no longer just intended to be used for DataFeed cache, but is now intended to be used as a more generic cache for the Engage Destination.

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-05-03 14:23 UTC, cogwizzle commented on packages/core/src/create-test-integration.ts
> +  /** Engage internal use only. DO NOT USE. */
Broke this comment apart so that we could get language server support for using each property in the shape of this object.

2024-05-03 14:24 UTC, cogwizzle commented on packages/core/src/destination-kit/types.ts
> +  /** Engage internal use only. DO NOT USE. */
Broke this comment apart so that we could get language server support for using each property in the shape of this object.

2024-05-10 18:39 UTC, pmunin requested changes

2024-05-10 18:39 UTC, pmunin commented on packages/core/src/destination-kit/index.ts
> +  readonly maxResponseSizeBytes: number
"response" still specific to datafeed case, should be maxValueSizeBytes or something as mentioned in https://github.com/segmentio/integrations/pull/2863/files#diff-e241cf2449a32291aa0ff2fa6959ea3e83c8cf8cc3d061588037e535cdf2c07a

Also it's strange that we dup the code of validating that size & expiry [in this repo](https://github.com/segmentio/action-destinations/blob/d52ba57aaad1f6339bc0c3e9af691e9886e134b8/packages/destination-actions/src/destinations/engage/utils/apiLookups.ts#L165-L183) as well as in Integrations (validateSet). 
Maybe instead we just try to cache.setByKey and then handle error that it throws

2024-05-10 18:39 UTC, pmunin commented on packages/core/src/destination-kit/index.ts
> +      this.partnerAction(name, action)
:nice:

2024-05-10 18:39 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +  @track()
I don't think you need this tracked, when the upstream EngageActionPerformer.perform is tracked already

2024-05-10 18:39 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +      await this.engageDestinationCache.setByKey(messageId + recipientId, body)
we don't want to store entire body in cache - that may be costly and not risk free from performance and redis-faultiness standpoint.
We just need response.status (integer).

2024-05-10 18:39 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +      const body = await response.text()
I might be wrong but reading response.text() here will close the stream and will fail next time response body is tried to be read (during actual logic of processing response), so you might want to check it and if it's the case you may use response.clone() or pass here the actual value to be cached, instead of response object

2024-05-10 18:39 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
> +          this.engageDestinationCache
hmm, out of your scope, but just for record: strange to see this in sendgrid code, I'd expect that to happen in base class and be used by both Twilio and Sendgrid.

2024-05-10 18:39 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
I'd do it easier and in EngageActionPerformer.ts/perform method:
```
    const op = this.currentOperation as OperationContext
    op?.onFinally.push(() => {
      const error = op.error as TrackedError
      if(!error) this.cache.setByKey(messageId, stringifySuccess())
      else if (error && !isErrorRetryable(error)) this.cache.setByKey(messageId, stringifyError(error))
    })

    try {
      const cache = parseCache(this.cache.getByKey(messageId))
      if(isCacheSuccess(cache)) return cache.result
      else if(isCachedError) throw cache.error
    }
    catch()
    {
        //log problem with redis
        // in that case we proceed as if nothing is cached
    }
    ... 
    beforePerform()
    return doPerform()
```

2024-05-15 15:48 UTC, cogwizzle commented on packages/core/src/destination-kit/index.ts
> +  readonly maxResponseSizeBytes: number
Great call. Will rename this.

2024-05-15 16:15 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
> +      const body = await response.text()
Since I'm swapping to use the status code I don't think we need to worry about this.

2024-05-15 20:13 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage/sendgrid/sendEmail/SendEmailPerformer.ts
> +          this.engageDestinationCache
I agree.

2024-05-15 20:16 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
Can you help me understand why this belongs in EngageActionPerformer rather than in the MessageSendPerformer? I'm certain you have a reason, but I'm not 100% certain the express purpose of each class.

2024-05-16 10:28 UTC, pmunin commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
EngageActionPerformer is a base class for any engage DA, which contains base logic for logging, stats etc. The only derived class right now is MessageSendPerformer, which is specialized on message sending workflow, i.e. extracting template, personalizing it for profile and then sending it to all recipients.

It's arguable, but I'd suggest for our case it is more practical to dedup on `DA.perform` level rather than on per recipient level - because:
 1) most of actions have single recipient (recently we allowed having multiple recipients per email as a workaround for some subscription related sev, but iirc our strategy is to have a single recipient per `DA.perform`)
2) it is safe to assume that if it message succeeded or failed for one of the recipients - retryability of it will be applicable to the other recipients of that message, because based on what I saw in datadog in 99% of the cases failure happens before hitting TW/SG api call.

Therefore since we're talking about caching of entire DA.perform outcome (and not per each recipient within each perform) for preventing dup calls of DA.perform - that logic belongs to EngageActionPerformer.

Hope it makes sense?

2024-05-16 16:11 UTC, cogwizzle commented on packages/destination-actions/src/destinations/engage/utils/MessageSendPerformer.ts
I would like to keep the current implementation for a few reasons.

I tried to implement the suggested pattern you outlined above. From an outsiders perspective the code was much harder for me to interpret and follow due to the unconventional coding style associated with the suggested change. I really struggled due to the unusual types associated with the onFinally code. I don't think casting the type is a reasonable solution either, because I am not familiar enough with the code base to know what the given type is supposed to be.

The existing implementation handles both the multi-recipient and single-recipient case. If we do support the multi-recipient case shouldn't we build a caching implementation that works this way too? I have concerns about potential side effects if we don't use a compound key such as messageId and recipientId we may return an inappropriate cached value which may cause messages to fail to be sent due to cache collisions. In a sense my fear is that we go from creating duplicates to dropping messages in a way that would not be very transparent to trace through.

If you'd like to discuss this further I recommend we pair on this solution to get the most equitable solution between our two proposed implementations. I'm sure together we can come up with a reasonable solution if you decide it is worth going down this road.

2024-05-16 16:39 UTC, joe-ayoub-segment commented
hi @cogwizzle @pmunin please let me know when you are done with this so I can review prior to deploy

2024-06-03 17:34 UTC, pmunin submitted a review, later dismissed

2024-06-20 09:24 UTC, joe-ayoub-segment commented
hi @cogwizzle - there's a bunch of failing CI checks. Can you address these before I review please?

2024-06-28 16:12 UTC, cogwizzle commented
> hi @cogwizzle - there's a bunch of failing CI checks. Can you address these before I review please?

Fixed the test and pipeline.

2024-07-03 18:34 UTC, alfrimpong commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    await this.engageDestinationCache.setByKey(messageId + recipientId.toLowerCase(), JSON.stringify(status))
Lets keep an eye out for event loop blocking code like stringify and parse. Can we pull out the relevant `value` in the subclasses and pass it down to this? That way we can avoid the stringify

2024-07-03 21:04 UTC, cogwizzle commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    await this.engageDestinationCache.setByKey(messageId + recipientId.toLowerCase(), JSON.stringify(status))
Ok something that makes this extremely difficult is the way that the surrounding code is written. It effectively could be type `any` rather than a response type. Fixing the types would be difficult.

I can give my best attempt to address this problem. I see the issue with parse, and stringify that you're talking about and I was not aware that it was going to be such a performance issue.

2024-07-08 14:34 UTC, cogwizzle commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    await this.engageDestinationCache.setByKey(messageId + recipientId.toLowerCase(), JSON.stringify(status))
So I reworked the code in a way that I created a simple serialization pattern that can be used to communicate all of the data that we need without using JSON.stringify or JSON.parse.

2024-07-08 15:14 UTC, alfrimpong commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    await this.engageDestinationCache.setByKey(messageId + recipientId.toLowerCase(), JSON.stringify(status))
nice! lmk when its time for a re-review

2024-07-16 09:39 UTC, joe-ayoub-segment commented
hi @cogwizzle - converting to draft until this is ready for review.

2024-09-24 16:09 UTC, pmunin commented
Closing towards https://github.com/segmentio/action-destinations/pull/2325

2024-09-24 16:09 UTC, closed without merging