Implement batch support for Attio Actions
segmentio/action-destinations pull request #2057
Opened 2024-05-24 16:04 UTC by nickcampbell18

This pull request adds batch support for the Attio Actions destination. We're looking to make this change because our customers are seeing high failure rates (rate limit exceeded, timeouts and 5xx errors) with the single-event mechanisms.

Our secret batching API supports up to 10,000 Segment events in a single batch that will allow us to process these asynchronously, in order, in our own infrastructure in a more controlled and reliable way.

## Testing

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-05-27 13:00 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/common-fields.ts
> +    required: true,
hi @nickcampbell18 can you make this field optional please?
Its value will be undefined for all instances of the Integration which have already been configured prior to the deploy happening. So you'll need to handle that in the perform() and performBatch() code too.

2024-05-27 13:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/identifyUser/index.ts
> +            received_at: item.received_at.toString()
received_at needs to be handled defensively as it will be undefined for customers who have the Integration already set up.

2024-05-27 13:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/identifyUser/index.ts
> +        received_at: item.received_at.toString()
received_at needs to be handled defensively as it will be undefined for customers who have the Integration already set up.

2024-05-27 13:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/identifyUser/generated-types.ts
> +  received_at: string | number
Needs to be optional.

2024-05-27 13:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/groupWorkspace/index.ts
> +            received_at: item.received_at.toString()
received_at needs to be handled defensively as it will be undefined for customers who have the Integration already set up.

2024-05-27 13:06 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attio/groupWorkspace/index.ts
> +        received_at: item.received_at.toString()
received_at needs to be handled defensively as it will be undefined for customers who have the Integration already set up.

2024-05-27 13:12 UTC, joe-ayoub-segment requested changes
Hi @nickcampbell18 thanks for raising this PR. 
Generally looks good. 
1 major but hopefully simple to fix issue. These 3 new fields you are adding will resolve to undefined for all customers' instances which have already been set up prior to the deploy. So that needs to be handled in code defensively. 

Also note that this means that batching will be disabled for these customers' instances. To enable batching the customer would need to edit the 'Action' , and save the Action. However because the enable_batching field is hidden it might not be possible. 

What's your intention here?

2024-05-28 07:59 UTC, nickcampbell18 commented
Thanks for the feedback! I've addressed both of those points.

What do you think of the wording here on the second commit? At the moment Attio won't tell the user if their mapping is causing validation failures on our side (although you can still use the event tester I guess to see if it would generally work). I can send a PR to the [docs page](https://github.com/segmentio/segment-docs/blob/develop/src/connections/destinations/catalog/actions-attio/index.md) as well, to clarify if that's easier...

2024-05-28 08:10 UTC, joe-ayoub-segment approved these changes

2024-05-28 08:14 UTC, joe-ayoub-segment commented
Looks good. I might reword the batch label and description after I merge the code.

2024-05-28 09:06 UTC, merged

2024-05-28 12:07 UTC, joe-ayoub-segment commented
hi @nickcampbell18 PR deployed. Please check it all looks good!