Bryan/audience to list
segmentio/action-destinations pull request #2077
Opened 2024-06-06 05:19 UTC by bwebs

Adding new audienceToList functionality for Engage Audience to Courier Lists

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-06-10 09:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/courier/audienceToList/index.ts
> +  }
Looks like this just splits out a batch of events into individual API calls. 
I suggest we remove the performBatch() implementation as you've defaulted the enable_batching field to false and made it hidden anyway (so performBatch will never be called anyway).

2024-06-10 09:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/courier/audienceToList/index.ts
> +    },
If you don't intend to handle batches of events, then just delete this field.

2024-06-10 09:58 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/courier/audienceToList/index.ts
> +  LD_API_CUSTOM_AUDIENCE_ENDPOINT: '/segment-targets/segment-audiences',
Let's remove this constant as it is not used.

2024-06-10 10:07 UTC, joe-ayoub-segment requested changes
hi @bwebs thanks for raising this PR. 

Looks like it's a copy of the LaunchDarkly implementation - which is fine. 

I left some comments inline. 

Some additional questions: 

Looks like you are sending the 'segment_audience_id' to your platform as the 'list_id'. Please note that the 'segment_audience_id' looks like a GUID and will probably not be something the customer will recognise on your platform. If your platform is able to accept a more friendly name, you could also send the 'segment_audience_key' value. This is a snake cased version of the Audience name the customer typed into Segment when they created the Audience. I would only send this in addition to the segment_audience_id and not as a replacement, as it would give you something nicer to display to the end user. Does that make sense?

Also - we do have a slightly more robust and flexible way to build Audience Destination now, which involved a little more code. However the advantage is that Segment can make an API call to your platform so you can initialize the Audience before Segment starts sending data to populate the Audience. Please let me know if this is something you would be interested in.

2024-06-24 20:13 UTC, bwebs commented on packages/destination-actions/src/destinations/courier/audienceToList/index.ts
> +  }
👍 removed performBatch until we support a match endpoint

2024-06-24 20:13 UTC, bwebs commented on packages/destination-actions/src/destinations/courier/audienceToList/index.ts
> +  LD_API_CUSTOM_AUDIENCE_ENDPOINT: '/segment-targets/segment-audiences',
👍 removed

2024-06-25 10:59 UTC, joe-ayoub-segment submitted a review, later dismissed

2024-06-25 13:10 UTC, merged