Add Event Properties to Loops Destination
segmentio/action-destinations pull request #2094
Opened 2024-06-13 15:30 UTC by askkaz

_Our platform now supports using event properties as content in emails. This PR adds the ability to send event properties via Segment._

## Testing

_Tested using the local server and verified that payloads arrive on our platform as expected._

- [X] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

https://github.com/segmentio/action-destinations/assets/7975721/e81009fb-6190-4baf-8c35-8e6dbcbc75bc

2024-06-14 15:13 UTC, tcgilbert requested changes
one minor tweak to the description. otherwise lgtm!

2024-06-14 15:13 UTC, tcgilbert commented on packages/destination-actions/src/destinations/loops/sendEvent/index.ts
> +      description: 'Properties tied to this event, which can be included in emails triggered by this event.',
```suggestion
      description: 'Event-specific properties that can be included in emails activated by this event.',
```

2024-06-14 18:15 UTC, askkaz commented on packages/destination-actions/src/destinations/loops/sendEvent/index.ts
> +      description: 'Event-specific properties that can be included in emails activated by this event.',
```suggestion
      description: 'Event-specific properties that can be included in emails triggered by this event.',
```

2024-06-17 17:07 UTC, tcgilbert approved these changes

2024-06-17 21:59 UTC, tcgilbert commented
hey @askkaz - thanks for the update. 

I marked this as `ready for release`. The partner engineer that typically deploys these changes is out until Thursday. That said, I've flagged this with engineering to see if we can get this deployed tomorrow. If not, we will get this deployed as soon as our Partner Engineer is back

2024-06-18 04:47 UTC, varadarajan-tw approved these changes

2024-06-18 05:35 UTC, varadarajan-tw commented
Hey @askkaz , the `validate` check seems to be failing in CI. Could you re-run `yarn types` and commit additional changes?

2024-06-20 09:20 UTC, joe-ayoub-segment commented
hi @askkaz - any chance you could run the following command, and commit the change please?

./bin/run/ generate:types 

We can't deploy unless this is done. Thank you !

2024-06-25 11:33 UTC, merged

2024-06-25 16:08 UTC, joe-ayoub-segment commented
hi @askkaz this PR has been deployed. Please check that it works as expected :)