Add S3 Destination
segmentio/action-destinations pull request #2117
Opened 2024-06-26 21:13 UTC by jpang007

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-06-26 21:34 UTC, marinhero reviewed
Let's focus on cleaning this up

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/__tests__/index.test.ts
> +  describe('testAuthentication', () => {
For now, you can keep the empty test, otherwise this would fail

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/__tests__/snapshot.test.ts
I think you can delete this file for now.

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/index.ts
> +    fields: {
Remove the settings bellow because this isn't an audience destination.
```suggestion
    fields: {}
```

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +    // s3_aws_access_key: {
You can remove these as we switched the auth method

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +// import { sendEventToAWS } from '../awsClient'
Remove

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +import type { ActionDefinition } from '@segment/actions-core' //,PayloadValidationError } from '@segment/actions-core'
Remove the comment on this line

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +    // audience_key: {
Remove

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +  // else {
Remove

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +  // if (input.features) {
Remove

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +// import generateS3RequestOptions from '../../../lib/AWS/s3'
Remove

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +//'arn:aws:iam::058449100246:role/mp-s3-anthony-hung-2', roleSessionName = 'your-session-name2'
Remove

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
Cleanup this file

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/__tests__/index.test.ts
Delete

2024-06-26 21:34 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
What parts of these file are being used and which ones aren't please make sure to only add code related to S3 and not to LiveRamp delete all references to LiveRamp

2024-06-27 17:10 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +  // if (payloads[0].is_audience) {
I think we should clean this up too

2024-06-27 17:11 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +  https://docs.liveramp.com/connect/en/formatting-file-data.html#idm45998667347936
Remember to remove LR's mentions

2024-06-27 17:12 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/__tests__/snapshot.test.ts
Remember to delete this file

2024-06-27 23:48 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +  console.log('Uploading to S3', input)
Please remove this

2024-06-27 23:48 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +    console.log('Batch payload', payload)
Please remove this

2024-06-27 23:50 UTC, marinhero requested changes
@jpang007 please review your unit tests. We need a passing build before we can ship this

2024-07-02 20:51 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/__tests__/index.test.ts
deleted

2024-07-02 20:52 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +//'arn:aws:iam::058449100246:role/mp-s3-anthony-hung-2', roleSessionName = 'your-session-name2'
removed default values

2024-07-02 20:52 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +// import generateS3RequestOptions from '../../../lib/AWS/s3'
removed

2024-07-02 20:52 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +// import { sendEventToAWS } from '../awsClient'
removed

2024-07-02 20:52 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/__tests__/snapshot.test.ts
file deleted

2024-07-02 20:53 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/__tests__/index.test.ts
> +  describe('testAuthentication', () => {
kept empty test for now

2024-07-02 20:58 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/__tests__/snapshot.test.ts
file deleted

2024-07-02 20:59 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
deleted all references to Liveramp + cleaned up file from comments

2024-07-02 21:03 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +  console.log('Uploading to S3', input)
removing causes the destination to not work

2024-07-02 21:04 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +  // if (payloads[0].is_audience) {
cleaned up

2024-07-02 21:05 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +  https://docs.liveramp.com/connect/en/formatting-file-data.html#idm45998667347936
cleaned up

2024-07-02 21:05 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +    console.log('Batch payload', payload)
removing causes destination code to not work

2024-07-02 21:05 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +    // s3_aws_access_key: {
removed old fields

2024-07-02 22:58 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +  console.log('Uploading to S3', input)
These are console.log statements. How would they cause the destination to not work? They don't modify the data in any way.

2024-07-02 23:10 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +  console.log('Uploading to S3', input)
Removed console.log

2024-07-02 23:11 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
Removed lingering comments and cleaned up file to meet unit test and validations

2024-07-02 23:15 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +    console.log('Credentials outside async block:', credentials)
Remove this line
```suggestion
```

2024-07-02 23:15 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +    console.error('Error', err)
Remove this line
```suggestion
```

2024-07-02 23:15 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +    console.log('Upload Success', data)
Remove this line
```suggestion
```

2024-07-02 23:16 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +        console.log('key', Object.prototype.hasOwnProperty.call(payload.identifier_data, key))
Remove this line
```suggestion
```

2024-07-02 23:31 UTC, marinhero requested changes
We don't use console log here. You can either remove the log or replace it with the logger implementation available for every action.

2024-07-02 23:31 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +    console.log('headers', headers)
Remove this line
```suggestion
```

2024-07-02 23:31 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +    console.log('fileContents', row)
Remove this line
```suggestion
```

2024-07-02 23:31 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +    console.error('Error', err)
We don't log errors like this in destinations. Either do a non-retryable error code (400) or let the method fail

2024-07-02 23:31 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +    console.error('Error assuming role', err)
Remove this line
```suggestion
```

2024-07-02 23:31 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +export type RawData = {
Something to keep in mind. This change got rolled out and reverted today https://github.com/segmentio/action-destinations/pull/2100 let's keep an eye on it because I think it will break your implementation.

2024-07-03 16:23 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +    console.error('Error assuming role', err)
removed

2024-07-03 16:24 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +    console.error('Error', err)
Added in correct error throwing

2024-07-03 16:24 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +    console.log('fileContents', row)
removed

2024-07-03 16:24 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +    console.log('headers', headers)
removed

2024-07-03 16:24 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +        console.log('key', Object.prototype.hasOwnProperty.call(payload.identifier_data, key))
removed

2024-07-03 16:24 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/s3.ts
> +    console.error('Error', err)
removed

2024-07-03 17:09 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +  console.log('Uploading to S3', input)
```suggestion
```

2024-07-03 17:14 UTC, jpang007 commented on packages/destination-actions/src/destinations/aws-s3/uploadCsv/index.ts
> +  console.log('Uploading to S3', input)
removed

2024-07-03 17:17 UTC, marinhero submitted a review, later dismissed

2024-07-08 17:16 UTC, marinhero commented on packages/destination-actions/src/destinations/aws-s3/operations.ts
> +import type { Payload as sftpPayload } from './uploadCsv/generated-types'
When is the `sftPayload` used? I think it might be a remnant from the LiveRamp destination. Can you clarify it, please? Thanks!

2024-07-08 17:38 UTC, joe-ayoub-segment commented
Hi @marinhero . Meeting with @jpang007 on Wed to do a detailed review.

2024-07-18 09:09 UTC, joe-ayoub-segment approved these changes

2024-07-18 09:09 UTC, merged