Adjust Action Destination: First implementation + unit tests.
segmentio/action-destinations pull request #2144
Opened 2024-07-08 22:49 UTC by seg-leonelsanches

One of our customers has dozens of apps, and hundreds (to not say thousands) of events that they want to send to Adjust. Additionally, these are all cloud events, sent by a service in their AWS environment. 

To solve the problem, I had to implement something more dynamic: considering a free-form mapping, the customer can send their App Token + Event Token as part of the event, if they wish to do it (and not only in the `context` section, or `integration` section, as the legacy integration works). 

This should work normally with the plugins and libraries that already exist.

## Testing

- [X] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-07-09 07:34 UTC, joe-ayoub-segment commented
@smultani FYI - @seg-leonelsanches raised a PR for a new Destination for Adjust.

2024-07-09 08:14 UTC, joe-ayoub-segment commented
hi @seg-leonelsanches thanks for raising this PR. 
I've asked my team how they'd like me to proceed with this review. Adjust is an important Destination which may need to be designed in such a way that it can be used by all customers. 

As a next step could we meet 1:1 to talk through the design and code please?

2024-07-09 15:09 UTC, seg-leonelsanches commented
Hi @joe-ayoub-segment. Thanks for helping me with this. 

Yes, we can meet. Do you have my calendar?

2024-07-16 08:19 UTC, joe-ayoub-segment commented
Hi @seg-leonelsanches - here's my Calendly. https://calendly.com/joe_ayoub/ 
Could we meet later in the week?

2024-07-17 15:24 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/adjust/index.ts
> +  name: 'Adjust',
```suggestion
  name: 'Adjust (Actions)',
```

2024-07-17 15:27 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/adjust/sendEvent/index.ts
> +    const eventData = (data as any).rawData as { [key: string]: unknown }
Let's remove this line.

2024-07-17 15:31 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/adjust/sendEvent/index.ts
> +    }
Add in a timestamp field

```
 timestamp: {
  label: 'Timestamp', 
  description: 'Timestamp for when the event happened',
  type: 'datetime'
 }
```

2024-07-17 15:32 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/adjust/functions.ts
> +    }
```suggestion
  if (settings.send_event_creation_time && !event.timestamp) {
      throw new Error('Event timestamp is required when send_event_creation_time is enabled.')
   }
```

2024-07-17 15:33 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/adjust/functions.ts
> +    adjustPayload.created_at_unix = parseInt((new Date(String(eventData.timestamp)).getTime() / 1000).toFixed(0))
```suggestion
    adjustPayload.created_at_unix = parseInt((new Date(String(payload.timestamp)).getTime() / 1000).toFixed(0))
```

2024-07-17 15:35 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/adjust/functions.ts
> +}
Please use promise.all

2024-07-17 15:36 UTC, joe-ayoub-segment requested changes
Changes as discussed in meeting and inline.

2024-07-22 15:50 UTC, seg-leonelsanches commented
@joe-ayoub-segment I think the destination is once again ready for review.

2024-07-23 11:01 UTC, joe-ayoub-segment commented
Made some minor changes to get this ready for deploy.

2024-07-23 11:03 UTC, joe-ayoub-segment approved these changes

2024-07-23 11:03 UTC, merged

2024-07-23 17:42 UTC, joe-ayoub-segment commented
hi @seg-leonelsanches PR deployed!