Updated delivr ai activate action destination from AWS S3 and SFTP server to delivr ai REST API
segmentio/action-destinations pull request #2158
Opened 2024-07-10 06:17 UTC by erjakhar96

Updated delivr ai activate action destination where customer can sync Segment.io audience to delivr.ai Audience segmentation and activate to delivr.ai supported  destinations.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-07-10 20:03 UTC, tcgilbert requested changes
hey @erjakhar96 - In general the code looks good, but considering you used the Yahoo destination as a template, please ensure that you have removed anything that is not relevant to Delivr.ai that may have been relevant to Yahoo

2024-07-10 20:03 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts
> +    // }
If you aren't going to use this, please remove

2024-07-10 20:03 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts
> +    // }
If you aren't going to use this please remove

2024-07-10 20:03 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts
> +  //  action_string = action_string.slice(0, -1)
If you aren't going to use this please remove

2024-07-10 20:03 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts
> +// }
If you aren't going to use this please remove

2024-07-12 08:49 UTC, erjakhar96 commented on packages/cli/src/lib/server.ts
removed

2024-07-12 08:49 UTC, erjakhar96 commented on packages/destination-actions/package.json
removed all unused commented code

2024-07-12 08:51 UTC, erjakhar96 commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
> +    // },
done

2024-07-12 08:51 UTC, erjakhar96 commented on packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts
> +// }
done

2024-07-15 09:40 UTC, erjakhar96 commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/__tests__/index.test.ts
> +  })
this is the same we took from yahoo it's commented there as well

2024-07-15 10:32 UTC, erjakhar96 commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/__tests__/index.test.ts
> +  })
added this

2024-07-15 10:32 UTC, erjakhar96 commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/__tests__/index.test.ts
> +      */
this was commented in Yahoo as well so we remove it

2024-07-15 10:42 UTC, erjakhar96 reviewed
Did the code cleanup also added new fields ,user phone , User Mobile Advertising ID

2024-07-16 15:17 UTC, tcgilbert requested changes
Just a few more changes. Let me know if you have any questions

2024-07-16 15:17 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
> +      return process_payload(request, [payload], rt_access_token, settings.client_identifier_id);
```suggestion
    let rt_access_token_response
    // Generate JWT token
    try {
      rt_access_token_response = await generate_jwt(settings.client_identifier_id, request)
    } catch (error) {
      if (error === 401) {
        throw new InvalidAuthenticationError('Invalid Client Identifier ID')
      } else {
        throw new APIError('Error Generating JWT', 400)
      }
    }
    const rt_access_token = rt_access_token_response?.data?.token
    // Process the payload with the valid token
    return process_payload(request, [payload], rt_access_token, settings.client_identifier_id)
```

You can get rid of the settings condition as a user cannot enable the destination without providing a required setting like `client_identifier_id`. 

The suggestion above also standardized the error handling for `generate_jwt` and uses the built in Segment errors for better observability

2024-07-16 15:17 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
> +    }
```suggestion
    let rt_access_token_response
    // Generate JWT token
    try {
      rt_access_token_response = await generate_jwt(settings.client_identifier_id, request)
    } catch (error) {
      if (error === 401) {
        throw new InvalidAuthenticationError('Invalid Client Identifier ID')
      } else {
        throw new APIError('Error Generating JWT', 400)
      }
    }
    const rt_access_token = rt_access_token_response?.data?.token
    // Process the payload with the valid token
    return process_payload(request, payload, rt_access_token, settings.client_identifier_id)
```

You can get rid of the settings condition as a user cannot enable the destination without providing a required setting like client_identifier_id.

The suggestion above also standardized the error handling for generate_jwt and uses the built in Segment errors for better observability

2024-07-16 15:17 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
> +      return [{ status: false, message: 'HTTP error: ' + err.response.message , code: err.response.statusCode}];
```suggestion
      throw new APIError('HTTP error: ' + err.response.message, err.response.statusCode)
```
Use built in Segment error for better observability

2024-07-16 15:17 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
> +import { PayloadValidationError } from '@segment/actions-core'
```suggestion
import { APIError, InvalidAuthenticationError, PayloadValidationError } from '@segment/actions-core'
```

2024-07-16 15:17 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/index.ts
> +    // Placeholder setting will be removed once we make AudienceSettings optional
I'm not sure if this is still needed, so double checking with the Actions team

2024-07-16 15:17 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/types.ts
> +}
```suggestion
```

I believe these are specific to Yahoo? If you are not using, please remove

2024-07-17 10:09 UTC, erjakhar96 commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
> +      // unsafe_hidden: true,
done

2024-07-20 14:58 UTC, tcgilbert commented
@SunilPortqii I saw you made one change from the last review, did you see the other review comments? Once addressed we can move forward. 

If you have any other questions or concerns, let me know. Additionally, if easier to discuss over a call, you can schedule time here: https://calendly.com/tgilbert-segment/segment-partner-call

2024-07-22 05:30 UTC, erjakhar96 commented
Hi @tcgilbert I made the changes suggested by you, please let me know if still anything missing I will schedule a call, Thanks

2024-07-22 13:44 UTC, tcgilbert commented
Hey @SunilPortqii - Thanks for making those updates. 

Last thing to take care of is ensuring the CI checks pass. Right now they are failing for this PR. Please ensure that your tests are passing, and that you have your types up to date. Here are some useful commands to: 

```
# Update Types: 
./bin/run generate:types --path ./packages/destination-actions/src/destinations/delivrai-activate/index.ts

# Run Tests: 
yarn cloud test --testPathPattern=src/destinations/delivrai-activate
```

2024-07-24 05:33 UTC, erjakhar96 commented
Hi @tcgilbert I re-run the types update command, the test cases passed at my end, let me know if anything missing ,Thanks

2024-08-01 16:49 UTC, tcgilbert commented
> Hi @tcgilbert I re-run the types update command, the test cases passed at my end, let me know if anything missing ,Thanks

Okay great. Apologies but, one last update:

We’ve recently updated our CI checks for partner pull requests. Could you please pull from the main branch on your fork and merge the updates into your PR branch once more? This will allow us to run the CI checks with the new config again and ensure they pass.

2024-08-06 19:51 UTC, tcgilbert commented
@erjakhar96 afraid the tests are still failing. Looks like the issue is with the types in the utils file:
 
<img width="1066" alt="Screenshot 2024-08-06 at 3 47 19 PM" src="https://github.com/user-attachments/assets/ed388a04-4c8c-4daa-9edc-86b99dab416f">

- [device_type](https://github.com/segmentio/action-destinations/blob/5a1766deace419eb158bd60d8c0db5544539d9b4/packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts#L82) 
- [seg_id](https://github.com/segmentio/action-destinations/blob/5a1766deace419eb158bd60d8c0db5544539d9b4/packages/destination-actions/src/destinations/delivrai-activate/utils-rt.ts#L113)

2024-08-09 05:06 UTC, erjakhar96 commented
Hi @tcgilbert I added the fix but on my end this command  "yarn cloud test --testPathPattern=src/destinations/delivrai-activate" gives all passed any other command that I am missing

2024-08-09 14:35 UTC, tcgilbert commented
hey @erjakhar96 - The CI is still failing, but I understand the issue now. 

Essentially, you can't add types to the generated types file if they do not exist as a field in the action. With that in mind, you will need to decide if you want to ingest device_type in the action. If you do, then you will need to add a field for it. If not then you will need to remove this from the code. 

If you have any other questions or concerns, let me know. 

![Screenshot 2024-08-09 at 10 30 20 AM](https://github.com/user-attachments/assets/b00285ba-14b4-4d47-8928-a176c033369b)
![Screenshot 2024-08-09 at 10 32 50 AM](https://github.com/user-attachments/assets/4f98fd81-cba6-4544-a345-140c83a5a56f)

2024-08-14 08:55 UTC, erjakhar96 commented
Thanks, @tcgilbert  for highlight the issue , we added device type field , please verify , Thanks

2024-08-15 16:24 UTC, tcgilbert approved these changes

2024-08-15 16:24 UTC, tcgilbert commented on packages/destination-actions/src/destinations/delivrai-activate/updateSegment/index.ts
> +      unsafe_hidden: true
```
      unsafe_hidden: true
```

Just so you know, this^ means that users will not be able to select if they want to batch events or not, and all actions will default to batch processing. This is okay, but just wanted to make sure you are aware in case you want to remove

2024-08-20 11:08 UTC, joe-ayoub-segment approved these changes
Approving as reviewed by @tcgilbert

2024-08-20 11:08 UTC, merged

2024-08-20 17:07 UTC, joe-ayoub-segment commented
hi @erjakhar96 and @tcgilbert this PR has been deployed. Thomas are you OK taking care of moving to Private Beta, etc?