Evolv dest actions
segmentio/action-destinations pull request #2178
Opened 2024-07-15 19:08 UTC by rcowin

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ x ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ x ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-07-16 08:39 UTC, joe-ayoub-segment commented
hi @rcowin thanks for raising this PR. I'll schedule for review.

2024-07-16 08:41 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/identifyUser/index.ts
> +      label: '',
hi @rcowin a label is required here.

2024-07-16 08:41 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/identifyUser/index.ts
> +      description: 'A user’s unique visitor ID. Setting this allows .',
hi @rcowin can you complete the Description please?

2024-07-16 08:43 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/index.ts
> +        'When an environment is provided, this integration will load the Evolv AI snippet for that environment. This should only be used if you are not already loading the evolv snippet.',
Can we explain this a little more clearly please?

2024-07-16 08:44 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/index.ts
> +      },
hi @nick-Ag - qq about this depends_on condition. Will this work in the Settings part of the UI? or does it only work in the Action Fields UI?

2024-07-16 08:45 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/index.ts
> +    // Add any Segment destination settings required here
Please remove unnecessary comments

2024-07-16 08:46 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/trackEvent/index.ts
> +  description: `Sends Segment's track event to Evolv`,
```suggestion
  description: `Send Segment track events to Evolv`,
```

2024-07-16 08:47 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/trackEvent/index.ts
> +      description: 'JSON object containing additional properties that will be associated with the event.',
```suggestion
      description: 'JSON object containing additional properties associated with the event.',
```

2024-07-16 08:47 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/trackEvent/index.ts
> +      description: 'A user’s unique visitor ID. Setting this allows .',
please complete the description

2024-07-16 08:47 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/trackEvent/index.ts
> +      label: '',
Please add a label

2024-07-16 08:48 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/trackEvent/index.ts
> +    // }
Please remove commented code

2024-07-16 08:48 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/evolv-ai/src/types.ts
> +// export type Event = string | { [k: string]: unknown } | undefined
Please remove comment

2024-07-16 08:49 UTC, joe-ayoub-segment commented
Hi @rcowin - thanks for raising the PR. 

I didn't have time to do a proper review yet. I just scanned through the labels and descriptions and left some comments. 
I'll schedule some later this week to review properly. 

Best regards,
Joe

2024-07-16 08:49 UTC, joe-ayoub-segment commented
Oh yes @rcowin please note that some CI checks are failing. Could you take a look at this also?

2024-08-05 09:32 UTC, joe-ayoub-segment commented
hi @rcowin any chance you could address the failing CI checks before I do the review please?

2024-08-12 20:47 UTC, tcgilbert commented
> > hi @rcowin any chance you could address the failing CI checks before I do the review please?
> 
> I just updated the package size limit.
> 
> @joe-ayoub-segment is this the correct approach to resolve the size limit issue?

Hi @rcowin thanks for your patience on this, it is the end of my day here, but I will be reviewing this tomorrow and get back to you. Meanwhile, if you have any questions or concerns, do let me know.

2024-08-12 21:34 UTC, silesky commented on packages/browser-destinations/destinations/evolv-ai/src/index.ts
> +      if (settings.useSegmentId && window.analytics) {
Checking for window.analytics wouldn't work if they've renamed window.analytics or are using the npm version of the library FYI

2024-08-13 18:25 UTC, rcowin commented on packages/browser-destinations/destinations/evolv-ai/src/index.ts
> +      if (settings.useSegmentId && window.analytics) {
Is there a recommended way for a plugin to optionally send data  (via `track` call) to segment?

2024-08-13 20:36 UTC, rcowin commented on packages/browser-destinations/destinations/evolv-ai/src/index.ts
> +      if (settings.useSegmentId && window.analytics) {
@silesky The reason I ask is that this plugin can act as a source as well and references `window.analytics` to do so. 

The above code can be adjusted, but not sure how to accomplish the `source` part of this extension without referencing `window.analytics`.

2024-08-14 01:28 UTC, tcgilbert commented
> > hi @rcowin any chance you could address the failing CI checks before I do the review please?
> 
> I just updated the package size limit.
> 
> @joe-ayoub-segment is this the correct approach to resolve the size limit issue?

hey @rcowin - I see that you bumped the size by 19 KBs. I was unable to see the previous CI error, but this should be only increased enough to pass the checks by a small margin. 

The size limit isn’t meant to be a hard limit - it is just in place alert us in case the size increases by an unexpected amount.  You should totally feel fine increasing the size limit as needed (and adding a buffer of around a kilobyte)

2024-08-14 03:12 UTC, tcgilbert commented on packages/browser-destinations/destinations/evolv-ai/src/index.ts
> +      if (settings.useSegmentId && window.analytics) {
@rcowin how crucial would you say the "source" part of your integration is? This is definitely a new use-case for us

Seth is right, `window.analytics` won't be loaded into the global scope if they use npm version of a.js. 

@silesky, my understanding of web libraries is limited so just thinking out loud, but could adding a setting for users to input their write_key enable posting events to our ingestion API using their own SDK? Or would there be another blocker going that route

2024-08-15 16:21 UTC, tcgilbert requested changes

2024-08-15 16:21 UTC, tcgilbert commented on packages/browser-destinations/destinations/evolv-ai/src/identifyUser/index.ts
> +      description: 'JSON object containing additional attributes associated with the user.',
```suggestion
      description: 'Object containing additional attributes associated with the user.',
```

Removing JSON just to avoid any confusion considering this will be mapped as an Object within Segment

2024-08-15 16:21 UTC, tcgilbert commented on packages/browser-destinations/destinations/evolv-ai/src/index.ts
> +      },
Noticed `depends_on` is used in the google campaign manager integration as a setting, and it is set on the [GlobalSetting type](https://github.com/segmentio/action-destinations/blob/main/packages/core/src/destination-kit/types.ts#L86), so seems okay to me

2024-08-15 16:21 UTC, tcgilbert commented on packages/browser-destinations/destinations/evolv-ai/src/source/index.ts
> +}
```suggestion
  if (window.analytics) {
    // console.info('sending track for analytics', data)
    window.analytics
      .track('Experiment Viewed', data)
      .then(() => true)
      .catch(() => true)
  } else {
    console.warn('window.analytics not available for track of', data)
  }
}
```

So are you okay with this functionality not being available for users that load analytics as a module? I'm not sure what the split would be, but it's fair to say that a lot of users wouldn't be able to make use of this source part.

2024-08-15 16:21 UTC, tcgilbert commented on packages/browser-destinations/destinations/evolv-ai/src/trackEvent/index.ts
> +      description: 'JSON object containing additional properties associated with the event.',
```suggestion
      description: 'Object containing additional properties associated with the event.',
```
Removing JSON just to avoid any confusion considering this will be mapped as an Object within Segment

2024-08-15 16:38 UTC, tcgilbert commented
@rcowin in addition to the review, also noting that CI is failing: 
<img width="1026" alt="Screenshot 2024-08-15 at 12 27 16 PM" src="https://github.com/user-attachments/assets/24c2c1ca-e168-481b-be6a-2678d35daa1f">

2024-08-15 16:42 UTC, tcgilbert requested changes

2024-08-15 16:42 UTC, tcgilbert commented on packages/browser-destinations/package.json
> +      "limit": "188 KB"
```suggestion
      "limit": "188 KB"
```

I see that you bumped the size by 19 KBs. I was unable to see the previous CI error, but this should be only increased enough to pass the checks by a small margin. Do you remember if 188 was within this small margin?

The size limit isn’t meant to be a hard limit - it is just in place to alert us in case the size increases by an unexpected amount. You should totally feel fine increasing the size limit as needed (and adding a buffer of around a kilobyte).

2024-08-16 15:03 UTC, rcowin commented on packages/browser-destinations/destinations/evolv-ai/src/source/index.ts
> +}
Would there be an optional way of doing this that might be more robust?

2024-08-16 15:08 UTC, rcowin commented
@tcgilbert build should be fixed. sorry - one of the files had incomplete update.

2024-08-16 15:15 UTC, rcowin commented on packages/browser-destinations/package.json
> +      "limit": "188 KB"
I bumped it up a couple of KB over size shown in warning message

2024-08-23 15:06 UTC, tcgilbert requested changes
Just a couple of changes to make.

@joe-ayoub-segment and I went over this PR again today, and frankly there is still a good deal of code included that we found difficult to follow.

It's possible there may be something we missed, but we figured easiest to just go ahead and deploy in Private Beta in order that you can test this end-to-end to ensure everything is working as expected.

2024-08-26 17:33 UTC, tcgilbert commented
@rcowin can you pull from main and address the merge conflicts?

2024-08-27 09:59 UTC, joe-ayoub-segment commented
hi @rcowin and @tcgilbert - just FYI there are a number of changes to other Destinations in this PR. Could they be removed please, even if they are just formatting changes?

2024-09-10 17:25 UTC, tcgilbert commented
@rcowin still seeing files unrelated to evolv-ai in the PR. Any file that does not live in the evolv-ai directory should be removed: 
<img width="1000" alt="Screenshot 2024-09-10 at 1 23 46 PM" src="https://github.com/user-attachments/assets/2e8a86f2-436b-4ae0-a96a-44ba03c7e451">

2024-09-24 14:58 UTC, closed without merging