Add authorization header
segmentio/action-destinations pull request #2189
Opened 2024-07-18 07:47 UTC by mihaa1

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-07-18 09:06 UTC, joe-ayoub-segment approved these changes

2024-07-18 09:10 UTC, joe-ayoub-segment requested changes
Hi @mihaa1 , 

This code will break. 

Please do the following: 

```
  perform: (request, {payload, settings}) => {
    return request(baseUrl + 'sendData', {
      headers: { Authorization: `Bearer ${settings.apiKey}` },
      json: { payload }
    })
  }
```

2024-07-18 09:15 UTC, joe-ayoub-segment commented
hi @mihaa1 - I just looked at this again. 
Your original code will work fine. 

Usually the payload object will have data in it, but in your case you don't have any fields defined to populate the payload data. So you are probably just grabbing all the data you need from the rawData object. 

This isn't the way we designed the platform to be used, but since you already have it that way we should leave as is. 

Can you revert back to your original PR and I'll approve it please?

2024-07-18 09:19 UTC, mihaa1 commented
> hi @mihaa1 - I just looked at this again. Your original code will work fine.
> 
> Usually the payload object will have data in it, but in your case you don't have any fields defined to populate the payload data. So you are probably just grabbing all the data you need from the rawData object.
> 
> This isn't the way we designed the platform to be used, but since you already have it that way we should leave as is.
> 
> Can you revert back to your original PR and I'll approve it please?

We are currently rewriting this part of our code.
If this is the correct way of doing things, I would like to change it. We dont have code relying on this currently.

2024-07-18 09:28 UTC, joe-ayoub-segment commented
Ah OK, if you are rewriting it to work in the way our platform expects, then you should define some fields to specify which bits of data you want to collect from the payload. 

If you want to grab the entire payload in a single field you can, but again that's not recommended. 

For example here is a single field capturing the entire payload: 

```
  fields: {
    data: {
      label: 'Payload',
      description: 'All payload data',
      type: 'object',
      required: true,
      default: { '@path': '$.' }
    }
 }
```


To drop this into the body of your request you would do this in the perform function: 

```
  perform: (request, {payload, settings}) => {
    return request(baseUrl + 'sendData', {
      headers: { Authorization: `Bearer ${settings.apiKey}` },
      json: payload.data
    })
  }
```

Again, the 'correct' thing to do is to be selective about the parts of the payload you want to send to your platform, and have separate fields which pick out just those bits of data. You can then compose the json body you want to send to your platform in the perform() function.

2024-07-18 10:28 UTC, mihaa1 commented
> Ah OK, if you are rewriting it to work in the way our platform expects, then you should define some fields to specify which bits of data you want to collect from the payload.
> 
> If you want to grab the entire payload in a single field you can, but again that's not recommended.
> 
> For example here is a single field capturing the entire payload:
> 
> ```
>   fields: {
>     data: {
>       label: 'Payload',
>       description: 'All payload data',
>       type: 'object',
>       required: true,
>       default: { '@path': '$.' }
>     }
>  }
> ```
> 
> To drop this into the body of your request you would do this in the perform function:
> 
> ```
>   perform: (request, {payload, settings}) => {
>     return request(baseUrl + 'sendData', {
>       headers: { Authorization: `Bearer ${settings.apiKey}` },
>       json: payload.data
>     })
>   }
> ```
> 
> Again, the 'correct' thing to do is to be selective about the parts of the payload you want to send to your platform, and have separate fields which pick out just those bits of data. You can then compose the json body you want to send to your platform in the perform() function.

I have modified the code, according to ur comments.
My goal currently is just to see things are working - events are sent and I am able to get the data from them.
So, to test I would need things like the event type, and some data from them. I hope my changes are correct

2024-07-18 12:47 UTC, joe-ayoub-segment commented on .tool-versions
> +nodejs 18.12.1
Please remove this change

2024-07-18 12:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/sendData/index.ts
> +    }
hi @mihaa1 - adding new fields which are required will break data collection for customers who already have the Integration set up. 

If you don't have customers using this Integration already, then it's OK. Please confirm.

2024-07-18 12:50 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/sendData/index.ts
> +    }
Another important note: 
Any new fields you define now will resolve to undefined for customers who already have the Integration configured. 

You'll need to defensively access these fields in the perform() function.

2024-07-18 12:51 UTC, joe-ayoub-segment requested changes
Hi @mihaa1 - left some comments.

2024-07-19 08:02 UTC, mihaa1 commented on packages/destination-actions/src/destinations/blend-ai/sendData/index.ts
> +    }
1. tool-versions file removed
2. removed required from new fields
3. undefined for new fields - here im not sure what I should do. I have customers with existing integrations. I want to continue receiving events from them. I don't care in which format - the old 1 (with the entire payload) or the new 1.
Please advise @joe-ayoub-segment

2024-07-19 08:03 UTC, mihaa1 commented on .tool-versions
> +nodejs 18.12.1
done

2024-07-22 07:40 UTC, joe-ayoub-segment commented
hi @mihaa1 - I think the neatest way to do this would be to add a new Action which has all the fields defined for data points you want to allow customers to send to your platform. 
You could then label your existing Action as 'deprecated' by updating the label name. You could also update the 'preset' to point to the new Action to make it more likely that customers who are setting up the Integration in the figure future will use the new Action. 

Does that make sense?

There is no good way to update the existing Action to work in both the old and new way unfortunately. 

Best regards,
Joe

2024-07-22 12:57 UTC, mihaa1 commented
> hi @mihaa1 - I think the neatest way to do this would be to add a new Action which has all the fields defined for data points you want to allow customers to send to your platform. You could then label your existing Action as 'deprecated' by updating the label name. You could also update the 'preset' to point to the new Action to make it more likely that customers who are setting up the Integration in the figure future will use the new Action.
> 
> Does that make sense?
> 
> There is no good way to update the existing Action to work in both the old and new way unfortunately.
> 
> Best regards, Joe

That sounds great - I will create a new action.
A question - is it possible to update just the url for the old integration?
I would like to change it from segment-api.blnd.ai to api.blnd.ai

2024-07-23 09:13 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/index.ts
>    actions: {
hi @mihaa1 , you need to reference the new Action here or it won't work. 

actions: {
  sendData, 
  trackEvents
}

2024-07-23 09:14 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/trackEvents/index.ts
> +    },
```suggestion
    eventType: {
      label: 'Event Type',
      description: 'The type of event',
      type: 'string',
      default: { '@path': '$.type' }
    },
```

2024-07-23 09:15 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/trackEvents/index.ts
> +    }
```suggestion
    eventProperties: {
      label: 'Event Properties',
      description: 'Properties of the event',
      type: 'object',
      default: {'@path': '$.properties'}
    }
```

2024-07-23 09:18 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/trackEvents/index.ts
> +  fields: {
I recommend also adding in a field to capture the event name. 

eventName: {
      label: 'Event Name',
      description: 'The name of event, page or screen',
      type: 'string',
      default: {
          '@if': {
            exists: { '@path': '$.event' },
            then: { '@path': '$.event' },
            else: { '@path': '$.name' }
          }
      }
}

2024-07-23 09:20 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/trackEvents/index.ts
> +  fields: {
I also recommend adding a field to capture user profile details from identify() calls. 

    userTraits: {
      label: 'User Traits',
      description: 'User profile details / traits',
      type: 'object',
      default: {
        '@if': {
          exists: { '@path': '$.traits' },
          then: { '@path': '$.traits' },
          else: { '@path': '$.context.traits' }
        }
    }

2024-07-25 10:37 UTC, mihaa1 commented on packages/destination-actions/src/destinations/blend-ai/index.ts
>    actions: {
done

2024-07-25 10:37 UTC, mihaa1 commented on packages/destination-actions/src/destinations/blend-ai/trackEvents/index.ts
> +    }
done

2024-07-25 10:37 UTC, mihaa1 commented on packages/destination-actions/src/destinations/blend-ai/trackEvents/index.ts
> +  fields: {
dunzo

2024-07-25 10:38 UTC, mihaa1 commented
@joe-ayoub-segment fixed everything!

2024-07-25 10:42 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/index.ts
> +    },
hi @mihaa1 - just remove this preset please.

2024-07-25 10:43 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/trackEvents/generated-types.ts
> +}
hi @mihaa1 please dun this command from the root of the repo. It will update this file with new types. Then submit the updated file in the PR. 

`./bin/run generate:types`

2024-07-25 10:47 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/trackEventsAction.types.ts
> +}
Ah I see that you did run the ./bin/run generate:types command, but for some reason the file is generated in the wrong location. 

It should be in the /trackEvents/ folder and should be named generated-types.ts.

2024-07-25 10:48 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/trackEvents/index.ts
> +        properties: payload.eventProperties
hi @mihaa1 - you need to add the new fields you created into the json object here otherwise none of the data will be sent to your API.

2024-07-25 10:49 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/index.ts
> +    sendData,
Can you update the label and descriptions for the sendData Action to indicate that the Action are deprecated please? Just prefix the label and description with this: 

[Deprecated]

2024-07-25 11:03 UTC, mihaa1 commented on packages/destination-actions/src/destinations/blend-ai/index.ts
> +    },
Will the events from existing clients still be sent if I remove this?

2024-07-25 11:04 UTC, mihaa1 commented on packages/destination-actions/src/destinations/blend-ai/trackEventsAction.types.ts
> +}
I moved it to the correct location. For some reason the cmd is generating it outside with this path...

2024-07-25 11:04 UTC, mihaa1 commented on packages/destination-actions/src/destinations/blend-ai/trackEvents/index.ts
> +        properties: payload.eventProperties
done

2024-07-25 11:05 UTC, mihaa1 commented on packages/destination-actions/src/destinations/blend-ai/index.ts
> +    sendData,
done

2024-07-29 09:54 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/blend-ai/index.ts
> +    },
> Will the events from existing clients still be sent if I remove this?

yes they will

2024-07-29 09:55 UTC, joe-ayoub-segment approved these changes

2024-07-29 11:25 UTC, merged

2024-07-29 17:43 UTC, joe-ayoub-segment commented
hi @mihaa1 this PR has been deployed. Can you please confirm that the change looks good?

2024-07-29 19:30 UTC, mihaa1 commented
> hi @mihaa1 this PR has been deployed. Can you please confirm that the change looks good?

@joe-ayoub-segment the old integration works. We will need to test with new 1 to see.
Thank you so much for your help