Revert "Revert "[STRATCONN-3832] Validate Audience Field inputs while creating Audience""
segmentio/action-destinations pull request #2212
Opened 2024-07-24 07:42 UTC by Innovative-GauravKochar

Reverts segmentio/action-destinations#2129

2024-07-24 19:27 UTC, marinhero commented on packages/core/src/destination-kit/index.ts
> +export type Personas = { computation_id: 'string'; computation_key: 'string' }
How did we validate that this type works for all of the existing destinations? What would happen if the Personas field comes with an extra parameter that isn't listed here?

See how this payload looks for example:

<img width="605" alt="Screenshot 2024-07-24 at 12 26 56 PM" src="https://github.com/user-attachments/assets/5e9f88df-acba-42e2-a6f0-d100e84e3f7b">

2024-07-31 09:47 UTC, varadarajan-tw commented on packages/browser-destinations/package.json
> +      "limit": "190 KB"
why the bump here?

2024-07-31 09:47 UTC, varadarajan-tw commented on packages/browser-destinations/package.json
> +      "limit": "190 KB"
ah! seems like you used lodash in actions-core.

2024-07-31 09:47 UTC, varadarajan-tw commented on packages/browser-destinations/package.json
> +      "limit": "190 KB"
If you use loadash in actions-core, it affects bundle size of web destinations. Could you not do that?

2024-07-31 09:47 UTC, varadarajan-tw commented on packages/core/src/destination-kit/index.ts
> +export type Personas = { computation_id: 'string'; computation_key: 'string' } & { [key: string]: any }
why not?
```suggestion
export type Personas = { computation_id: 'string'; computation_key: 'string', { [key: string]: any }}
```
whats the need for intersecting types here? `&` can be useful if you are combining two predefined types and in this step, we are creating a plain new type.

2024-07-31 09:47 UTC, varadarajan-tw commented on packages/core/src/destination-kit/index.ts
> +    if (!isEmpty(createAudienceInput.audienceSettings)) {
Could we use a simple method instead of using lodash in actions-core? If you have any other suggestions, pls do shar.
```
function isEmpty(obj) {
  for (const key in obj) {
     if (Object.prototype.hasOwnProperty.call(obj, key)) {
        return false
     }
  } 
  return true
}
```

2024-07-31 13:07 UTC, Innovative-GauravKochar commented on packages/core/src/destination-kit/index.ts
> +    if (!isEmpty(createAudienceInput.audienceSettings)) {
We can do using Native js like 

if (createAudienceInput.audienceSettings && Object.keys(createAudienceInput.audienceSettings).length > 0) {
  validateSchema(createAudienceInput.audienceSettings, fieldsToJsonSchema(audienceDefinition.audienceFields));
}

2024-08-05 05:51 UTC, varadarajan-tw commented on packages/core/src/destination-kit/index.ts
> +export type Personas = { computation_id: 'string'; computation_key: 'string'; [key: string]: any }
nit: Should you use unknown here? You'll probably see a warning in your editor as well.
```suggestion
export type Personas = { computation_id: 'string'; computation_key: 'string'; [key: string]: unknown }
```

2024-08-05 07:32 UTC, Innovative-GauravKochar commented on packages/core/src/destination-kit/index.ts
> +    if (createAudienceInput.audienceSettings && Object.keys(createAudienceInput.audienceSettings).length > 0) {
That's okay. Yes we can add test but test cases for createAudience and getAudience in destination-kit is added in [this](https://github.com/segmentio/action-destinations/pull/2212/files) PR. So we can add that once that is merged otherwise it will be duplicated in both PRs.

2024-08-06 09:24 UTC, joe-ayoub-segment requested changes
please also fix for iterable-lists and aws-s3 destinations

![image](https://github.com/user-attachments/assets/a3662ae4-49d9-42e1-812d-bdfa080ed253)

2024-08-06 10:22 UTC, joe-ayoub-segment requested changes
hi @Innovative-GauravKochar can you remove the unnecessary formatting changes please? It's making the PR difficult to review properly.

2024-08-06 11:07 UTC, Innovative-GauravKochar commented
Created a separate PR as it recieved many identation changes while resolving conflicts
https://github.com/segmentio/action-destinations/pull/2248

2024-08-06 11:07 UTC, closed without merging