Add batching support to Google Enhanced Conversions
segmentio/action-destinations pull request #2265
Opened 2024-08-08 20:53 UTC by sayan-das-in

This PR adds Batching Support to the following actions of Google Enhanced Conversions
- uploadCallConversion
- uploadClickConversion
- uploadConversionAdjustment

## Testing

This is a draft PR and E2E testing is still in process on staging.

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-08-08 23:27 UTC, marinhero requested changes
I left a few questions and would like to get the answers to them, as well as the test document for this PR. Additionally, I noticed you skipped the version 2 actions with the same name. If that is currently out of scope, please create a ticket to follow up on those.

One last thing to consider for the existing implementation:

Right now, the perform blocks handle most of our customers needs effectively. Your changes are modifying that code path. To minimize the impact of your changes, consider leaving the perform block intact until we can validate that this new approach solves our problems. This way, we maintain the existing implementation while offering a new option for those who need batching. Although it might result in some duplicated code, I believe it's a worthwhile tradeoff. What do you think?

2024-08-08 23:27 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +  const request_objects: ClickConversionRequestObjectInterface[] = await Promise.all(
Why do we need a promise here? You are not making any requests and are simply filling and array.

2024-08-08 23:27 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
> +    if (cache.has(customerId)) {
When is this cache getting invalidated? How does it operate between instances of the Integrations Monoservice? Why do we need it?

2024-08-09 06:50 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
> +    if (cache.has(customerId)) {
### Context
We have a function called `getCustomVariables` that calls Google APIs to get custom variables defined in that account. In the [earlier implementation](https://github.com/segmentio/action-destinations/blob/06d0d12b4b40ac708b348fd9ad39b403689b1d78/packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts#L141-L147) we were checking if we even need to call this API by checking if payload has custom variables defined.

While porting the logic to batch, there are two options

1. Make an API call regardless Custom Variables are required or not
2. Defer this checking in the loop, but that would make multiple API calls

If we are opting for 2nd variant, we don't have to make a call unless we really need to, but the trade-off is when we need it for multiple payload items, we would end up making multiple calls, that's where the memoization comes in.

### When is this cache getting invalidated?
In order to take advantage of memoization we have to initialize a memoized instance of the function (example here), the cache would be valid within the scope of each `performBatch` block instance and then it would get garbage collected.

### How does it operate between instances of the Integrations Monoservice?
Every instance has it's individual short-lived cache. In-fact the cache is local to every invocation of `performBatch` block after which it would get garbage collected.

### Why do we need it?
Memoization acts as a wrapper around deterministic, but computationally expensive functions or API calls that would generate the same result if same parameters are passed to it. Here in `f(x) => y`, the value of `y` will always be same as long as x remains same.

2024-08-09 06:52 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +  const request_objects: ClickConversionRequestObjectInterface[] = await Promise.all(
We are calling the `getCustomVariables` function for each payload, for that we would need to to await for the result. More details about the implementation in the comments below.

2024-08-09 06:53 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/google-enhanced-conversions/constants.ts
> +export const GOOGLE_ENHANCED_CONVERSIONS_BATCH_SIZE = 2000
Sure, I will make this change.

2024-08-09 12:11 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/google-enhanced-conversions/constants.ts
> +export const GOOGLE_ENHANCED_CONVERSIONS_BATCH_SIZE = 2000
Changed the batch size to 1500.

2024-08-23 04:11 UTC, varadarajan-tw approved these changes

2024-08-23 22:15 UTC, marinhero approved these changes
Thank you for updating the tests and de-risking the existing actions by splitting the code. Well done.

2024-08-26 19:46 UTC, merged

2024-08-27 11:14 UTC, joe-ayoub-segment commented
hi @sayan-das-in PR deployed