[Topsort] Action destination for Topsort V1
segmentio/action-destinations pull request #2268
Opened 2024-08-08 23:24 UTC by agustinespildora

### Topsort Events Actions Destination

This is a destination so that eCommerce sites that already use Segment (to track action) can integrate Topsort events for sponsored listings seamlessly. 

## Intro to Topsort Events
Topsort allows to monetize through auction ads served in your site while respecting users privacy and helping sellers get the most out of their ads increasing conversions. To learn more about Topsort you can visit our [docs](https://docs2.topsort.com/).
This destination will help you track the 3 main events Topsort needs to serve the most relevant ads and accomplish attribution for the sponsored listings: `impressions`, `clicks` and `purchases`. Here is an explanation of what each one of these means to Topsort:

1. **Impression**: Every time a user sees a promoted product in a listing page or section.
2. **Click**: If the user then clicks or adds the promoted product to a cart, then a `click` should be triggered.
3. **Purchase**: Finally, when an order is completed and confirmed to be successful, a `purchase` event should be reported to Topsort. You can report a purchase whether it has promoted products or not. We will take care of filtering relevant promoted products inside the completed order given the information about promoted clicks.

This destination has 3 presets that map the Track events 'Product Viewed', 'Product Clicked' and 'Order Completed' to Topsort's `impression`, `click` and `purchase` events respectively. You can find more about the different fields that each of these events allow in the [Topsort Events API](https://docs2.topsort.com/api/auctions-events-v2/operations/reportevents/).

## Future improvements
In the future we will map other Segment events these 3 Tosport events, like 'Product List Viewed', 'AddToCart' and others.

## Testing
Added tests for success and failing when a required field is not passed, for every action.

- [x] Added required fields
- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Add Auth test
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)

End to end tests:

Purchase
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/180e88de-43fc-4369-ae64-f72e923f65fc">

Click
<img width="1447" alt="image" src="https://github.com/user-attachments/assets/ce08e7ee-b2ac-404e-b099-9e3cb71d4fbc">

Impression
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/3f534e10-c697-4e63-b06a-b79aa878dff1">

2024-08-09 03:07 UTC, agustinespildora reviewed
To do:
- [ ] ~~ add limits to numeric values~~ (not necessary as values from segment should be greater than 0)
- [x] fix partner actions

2024-08-09 07:10 UTC, joe-ayoub-segment commented
Thanks for raising this PR @agustinespildora . 
Either myself of my colleage @tcgilbert will review the PR once you have marked it as ready for review.

2024-08-09 18:24 UTC, tcgilbert requested changes

2024-08-09 18:24 UTC, tcgilbert commented on packages/destination-actions/src/destinations/topsort/impression/index.ts
> +  description: 'A set of impressions means such promotables have become visible to the consumer.',
```suggestion
description: 'Send impression events to Topsort when a consumer has viewed a promotable.'
```

2024-08-09 18:24 UTC, tcgilbert commented on packages/destination-actions/src/destinations/topsort/purchase/index.ts
> +  description: 'A purchase is sent to Topsort once a consumer places an order.',
```suggestion
  description: 'Send purchase events to Topsort when a consumer places an order.',
```

2024-08-09 18:39 UTC, tcgilbert commented
@agustinespildora thanks for the thorough PR!  just some minor updates to the action descriptions. 

Additionally, the unit test CI is failing. Looks like it is one of the snapshots being outdated. Can you run the command below, and commit the changes? 

```
yarn jest --testPathPattern='./packages/destination-actions/src/destinations/topsort' --updateSnapshot 
```

2024-08-09 18:46 UTC, agustinespildora commented
> @agustinespildora thanks for the thorough PR! just some minor updates to the action descriptions.
> 
> Additionally, the unit test CI is failing. Looks like it is one of the snapshots being outdated. Can you run the command below, and commit the changes?
> 
> ```
> yarn jest --testPathPattern='./packages/destination-actions/src/destinations/topsort' --updateSnapshot 
> ```

Thanks for the quick review @tcgilbert! I updated the snapshots, let me know if anyhting else is needed.

2024-08-09 18:53 UTC, tcgilbert requested changes
one more change

2024-08-09 18:53 UTC, tcgilbert commented on packages/destination-actions/src/destinations/topsort/impression/index.ts
> +description: 'Send impression events to Topsort when a consumer has viewed a promotable.'
```suggestion
description: 'Send impression events to Topsort when a consumer has viewed a promotable.',
```

2024-08-09 19:26 UTC, agustinespildora commented
Hey @tcgilbert corrected the missing comma.
Can you help me figure out how can I fix the snyk CI run that failed?

2024-08-09 19:42 UTC, tcgilbert approved these changes

2024-08-09 19:44 UTC, tcgilbert commented
> Hey @tcgilbert corrected the missing comma. Can you help me figure out how can I fix the snyk CI run that failed?

Snyk is expected to fail for external PRs, so no worries there. 

I've approved the pull request, and we should be able to get this included in the next deploy on Monday. We'll get back to you once that happens, Meanwhile, if you have any questions or concerns, do let me know.

2024-08-12 13:52 UTC, joe-ayoub-segment approved these changes
I didn't review - approving as Thomas labeled ready for release.

2024-08-12 13:52 UTC, merged

2024-08-12 16:43 UTC, joe-ayoub-segment commented
hi @agustinespildora and @tcgilbert this PR has been deployed.