feat: added the device & cloud destinations for the first release.
segmentio/action-destinations pull request #2317
Opened 2024-08-20 18:15 UTC by hanoak20

Added Contentstack's browser and cloud destinations.

Description:
For our first release, we're going ahead with a basic setup to sync traits, audience, etc. In the browser plugin, we're just syncing custom traits and events. And in cloud destination, we're syncing computed traits and audiences. We'd follow up on this integration to improve it after we're good with the first release. 
Thanks.

2024-08-21 05:48 UTC, sankartn commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/customAttributesSync/index.ts
> +        'x-project-uid': settings.personalizeProjectId
'x-project-uid': settings?.personalizeProjectId

2024-08-21 05:48 UTC, sankartn commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/eventsSync/index.ts
> +        'x-project-uid': settings.personalizeProjectId
'x-project-uid': settings?.personalizeProjectId

2024-08-21 05:48 UTC, sankartn commented on packages/destination-actions/src/destinations/contentstack/audienceSync/index.ts
> +        'x-project-uid': settings.personalizeProjectId ?? ''
'x-project-uid': settings?.personalizeProjectId ?? ''

2024-08-21 07:46 UTC, sankartn commented
Hi @joe-ayoub-segment Please review the PR and help us with deployment

2024-08-21 13:32 UTC, joe-ayoub-segment commented
Thanks @hanoak20 - I'll schedule this for review.

2024-08-26 12:10 UTC, joe-ayoub-segment commented
hi @hanoak20 thanks for raising this PR. 

Looks like some large changes. 

I do have some architectural questions to discuss with you - as there's some design decisions in here which I'm unsure about. However I can deploy it and you can see how it looks in production if you like?

Please note that there will now be 2 Destinations. 

1. The server side Destination with 2 Actions
2. The client side Destination with 2 Actions. 

The customer will need to set each of these Destinations up separately. 

Best regards,
Joe

2024-08-26 12:10 UTC, joe-ayoub-segment approved these changes
Please see comment

2024-08-26 12:28 UTC, joe-ayoub-segment requested changes

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/customAttributesSync/index.ts
> +    },
```suggestion
    traits: {
      type: 'object',
       default: {
        '@if': {
          exists: { '@path': '$.traits' },
          then: { '@path': '$.traits' },
          else: { '@path': '$.context.traits' }
        }
      },
      label: 'User traits',
      description: 'User Profile traits to send to Contentstack',
      required: true
    },
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/eventsSync/index.ts
> +      required: false
```suggestion
      required: true
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/eventsSync/index.ts
> +        'x-cs-eclipse-user-uid': userId ?? '',
```suggestion
        'x-cs-eclipse-user-uid': userId,
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/eventsSync/index.ts
> +  defaultSubscription: 'type = "track" or type = "identify"',
```suggestion
  defaultSubscription: 'type = "track"',
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/eventsSync/generated-types.ts
> +  userId?: string
```suggestion
  userId: string
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/eventsSync/generated-types.ts
> +  event?: string
```suggestion
  event: string
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/eventsSync/index.ts
> +      required: false
```suggestion
      required: true
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/index.ts
> +  slug: 'contentstack-browser-plugins',
```suggestion
  name: 'Contentstack Web',
  slug: 'contentstack-web',
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/browser-destinations/destinations/contentstack-browser-plugins/src/index.ts
> +  description: 'Sync data from Segment to Contentstack',
```suggestion
  description: 'Sync web event and user profile data from Segment to Contentstack',
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/audienceSync/index.ts
> +      required: false
```suggestion
      required: true
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/audienceSync/generated-types.ts
> +  userId?: string
```suggestion
  userId: string
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/computedAttributeSync/index.ts
> +      required: false
```suggestion
      required: true
```

2024-08-26 12:28 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/contentstack/computedAttributeSync/generated-types.ts
> +  userId?: string
```suggestion
  userId: string
```

2024-08-26 12:46 UTC, joe-ayoub-segment approved these changes

2024-08-26 12:53 UTC, joe-ayoub-segment approved these changes

2024-08-26 13:11 UTC, joe-ayoub-segment approved these changes

2024-08-27 07:35 UTC, closed without merging