channels-1094: Refactor MessageSendPerformer.ts for caching improvements
segmentio/action-destinations pull request #2324
Opened 2024-08-21 17:36 UTC by pmunin

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-08-21 17:41 UTC, cogwizzle commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    const recipientId = recepient.id!
We probably shouldn't guarantee this if there is a chance it could be undefined.

2024-08-21 17:44 UTC, cogwizzle commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +      () => this.sendToRecepient(recepient) as Promise<ModifiedResponse<unknown>>,
Why do we have to cast this?

2024-08-21 18:11 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    const recipientId = recepient.id!
addressed

2024-08-21 18:13 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +      () => this.sendToRecepient(recepient) as Promise<ModifiedResponse<unknown>>,
not really, addressed

2024-08-21 20:04 UTC, cogwizzle requested changes

2024-08-21 20:16 UTC, cogwizzle commented
Fixed the last batch of TypeScript issues. I think that if we're going to use patterns like this one we should be very strict with types and ensure that we're writing completely type complete code even though it increases the verbosity of our code. The language patterns you've introduced mirror very strongly typed languages and the more TS hacks we use the more likely it is to break.

2024-08-21 20:40 UTC, pmunin reviewed
@cogwizzle plz see comments. I didn't find bugs you were talking about, let's zoom after meetings

2024-08-21 20:40 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    const cacheRead = await getOrCatch(() => engageDestinationCache.getByKey(key))
too much code to make typescript happy for questionable value coming out of it
```suggestion
    if (!this.engageDestinationCache) return createValue()

    const cacheRead = await getOrCatch(() => this.engageDestinationCache!.getByKey(key))
```

2024-08-21 20:40 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    const cacheReadValue = 'value' in cacheRead ? cacheRead.value : undefined
same here - too much code and complexity for questionable value. increases cognitive load is the price we pay for perfectionism :)
```suggestion
    const cacheReadValue = cacheRead.value
```

2024-08-21 20:40 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +      }
same here. this one line 
`const { value: parsedCache, error: parsingError } = getOrCatch(() => serializer.parse(cacheRead.value!))` became this large paragraph with bunch of explicit typings just to make typescript happy

2024-08-21 20:40 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +          return parsedCache.value
same here. Also cache_hit metric tag does not make sense in this implementation. I think cache_hit should include erroneous value which we could not parse

2024-08-21 20:40 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +      }
bug in the code and notably happy typescript didn't help :-)
```suggestion
      const result = await getOrCatch(() => this.engageDestinationCache?.setByKey(key, stringified.value))
      if ('error' in result && result.error) {
        ...
      }
```
also var name result is confusable with line 193. And again, this is less readable code, comparing to what it was:
```
      const { error: cacheSavingError } = await getOrCatch(() => this.engageDestinationCache!.setByKey(key, stringified.value!)
      if (cacheSavingError) {
          ...
      }
      
```

2024-08-21 20:40 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +type ValueOrError<T> = Ok<T> | Err<T>
looks unnecessary to add so much types, i'd just keep it as it was
```suggestion
type ValueOrError<T> = { value?: T; error?: any } 
```

2024-08-27 07:07 UTC, iamsuneeth commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    else return result as T
is this casting because we haven't specified T when calling `getCatch` method ? . Could we avoid this ?

2024-08-27 08:00 UTC, joe-ayoub-segment commented
hi @pmunin @cogwizzle please let me know when this is ready for release.

2024-08-31 15:38 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +    else return result as T
no it's because typescript thinks result can be T | undefined based on types. T avoid this we'll have to make code ugly, verbose and runtime error prone

2024-08-31 15:40 UTC, pmunin commented on packages/actions-shared/src/engage/utils/MessageSendPerformer.ts
> +  async getOrAddCache<T>(
feel free to suggest your implementation that will keep up the same clarity of where the error came from

2024-09-24 16:10 UTC, closed without merging