[STRATCONN-4130]- google sheets increase timeout
segmentio/action-destinations pull request #2378
Opened 2024-09-09 11:15 UTC by varadarajan-tw

This PR increases google sheets timeout to 30s.

Also adds batch_bytes and batch_size properties. Refer [here](https://github.com/segmentio/integrations-go/blob/v3/models/actions/catalog/overrides/google-sheets/integration.go)

## Testing

Testing not required because this simply bumps the timeout.

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-09-09 19:28 UTC, marinhero commented on packages/destination-actions/src/destinations/google-sheets/postSheet/operations.ts
> +  const appendBatchLimit = appendBatch.length * numColumns > CONSTANTS.MAX_CELLS
don't you need to add both limits as they operate on the same sheet?

2024-09-09 19:29 UTC, marinhero requested changes
Left some comments and questions

2024-09-10 05:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +      // unsafe_hidden: true
Yes. This was a mistake. I reverted this change.

2024-09-10 05:20 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/google-sheets/postSheet/operations.ts
> +  const appendBatchLimit = appendBatch.length * numColumns > CONSTANTS.MAX_CELLS
Yes. This was a mistake. I reverted this change.

2024-09-10 16:26 UTC, marinhero commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +      default: 500,
This batch size won't get you over the bulk batching limit (>1000) is that what you intended?

2024-09-10 16:36 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +      default: 500,
This is the limit for this destination before the revert [here](https://github.com/segmentio/integrations-go/pull/428). I didn't test with larger batch sizes because it doesn't impact the sheets limit.

2024-09-10 16:52 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +      default: 500,
upadted to 1001

2024-09-10 16:54 UTC, marinhero approved these changes

2024-09-12 06:46 UTC, merged