[Braze Cloud] Adds sync mode to createAlias action
segmentio/action-destinations pull request #2385
Opened 2024-09-09 23:28 UTC by nick-Ag

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-09-19 17:41 UTC, marinhero requested changes
Some of these are NITs but I do think that we should delete/reset the two files I flagged.

2024-09-19 17:41 UTC, marinhero commented on packages/destination-actions/src/destinations/braze/createAliasV2.types.ts
> +// Generated file. DO NOT MODIFY IT BY HAND.
This file needs to be removed

2024-09-19 17:41 UTC, marinhero commented on packages/destination-actions/src/destinations/braze/createAlias/index.ts
This file does not require any updates

2024-09-19 17:41 UTC, marinhero commented on packages/destination-actions/src/destinations/braze/createAlias2/__tests__/snapshot.test.ts
> +    ).rejects.toThrowError()
NIT: Make sure you are not swallowing other errors as this is a catch all for all the exceptions. It's better if you compare against the actual exception you are throwing.

2024-09-19 17:41 UTC, marinhero commented on packages/destination-actions/src/destinations/braze/createAlias2/__tests__/snapshot.test.ts
> +  it('required fields', async () => {
NIT: be more descriptive with what the test is doing

2024-09-23 15:14 UTC, maryamsharif approved these changes

2024-09-24 11:51 UTC, merged

2024-09-24 16:23 UTC, joe-ayoub-segment commented
hi @nick-Ag PR deployed