Accoil Analytics: Refactor postToAccoil into sub actions
segmentio/action-destinations pull request #2421
Opened 2024-09-19 05:20 UTC by accoilmj

This updates our existing single action into separate action handlers for identify, group, track, page, screen, and adds unit tests for each. I'm hoping this is a simple in place upgrade as it is still private and not publicly available yet but let me know if not.

## Testing

Tested using the local harness.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2024-09-19 09:08 UTC, joe-ayoub-segment commented
Thanks @accoilmj I'll schedule for review

2024-09-19 22:07 UTC, accoilmj commented
I see some test are failing. Looking into it.

2024-09-19 22:38 UTC, accoilmj commented
Looks like a timestamp / zone issue in snapshots where they were drifting in my machine vs remote. I've pushed a fix.

2024-09-20 11:48 UTC, accoilmj commented
I've pushed new changes that may fix the timezone drift problem.

2024-09-21 00:18 UTC, accoilmj commented
It looks like all of the Accoil tests passed this time but now there's:

```
   Failed tasks:
   
   - @segment/actions-cli:test
```

2024-09-22 23:40 UTC, accoilmj commented
The tests pass locally and looked to maybe be intermittent failures so I've rebased and pushed again to be sure.

2024-09-23 10:19 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/accoil-analytics/group/index.ts
> +  defaultSubscription: 'type = "identify"',
should this be group?
```suggestion
  defaultSubscription: 'type = "group"',
```

2024-09-23 10:20 UTC, joe-ayoub-segment requested changes
looks good. Just a minor comment to address.

2024-09-23 23:39 UTC, accoilmj commented
You're right. Good catch. I've pushed a fix for that.

2024-09-24 12:34 UTC, merged

2024-09-24 16:23 UTC, joe-ayoub-segment commented
hi @accoilmj PR deployed

2024-09-24 23:11 UTC, accoilmj commented
Thanks @joe-ayoub-segment