Allow mailingLists in traits
segmentio/action-destinations pull request #2464
Opened 2024-09-27 15:42 UTC by danrowden

Made sure that `mailingLists` added to traits can be successfully sent to the API

- made sure that boolean values are added inside `filterMailingLists()`
- if the user doesn't manually map traits in the UI, we pick them up from `customAttributes`

2024-09-27 17:25 UTC, tcgilbert requested changes

2024-09-27 17:25 UTC, tcgilbert commented on packages/destination-actions/src/destinations/loops/createOrUpdateContact/index.ts
> +  }
```suggestion
for (const key in obj) {
    const value = obj[key];
    
    if (typeof value === 'string') {
      if (value === 'true') {
        result[key] = true;
      } else if (value === 'false') {
        result[key] = false;
      }
    } else if (typeof value === 'boolean') {
      result[key] = value;
    }
  }
```

Getting a type issue here with the build, perhaps try the above^: 
<img width="1030" alt="Screenshot 2024-09-27 at 1 20 33 PM" src="https://github.com/user-attachments/assets/c0ca317d-3966-4ea5-a2bd-91dbf16bb793">

2024-09-30 09:26 UTC, joe-ayoub-segment commented
hi @tcgilbert will you be reviewing this?

2024-09-30 12:47 UTC, tcgilbert approved these changes

2024-10-01 10:36 UTC, joe-ayoub-segment approved these changes

2024-10-01 10:36 UTC, merged

2024-10-02 11:04 UTC, joe-ayoub-segment commented
hi @danrowden and @tcgilbert - PR deployed. Please confirm you are happy with the update.

2024-10-04 06:58 UTC, danrowden commented
@joe-ayoub-segment Yes, happy thanks! I've tested it and it works