[MAIN] [STRATCONN] 4146 Facebook Anon_id and MadId added in Action Field
segmentio/action-destinations pull request #2478
Opened 2024-10-03 07:08 UTC by AnkitSegment

_A summary of your pull request, including the what change you're making and why._

Tested successfully in stage, the parameter is sent to FB and accepted:

<img width="1295" alt="Screenshot 2024-10-03 at 12 22 23 PM" src="https://github.com/user-attachments/assets/4af36a53-ba5b-41f6-a718-09e28df86134">

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [If destination is already live] Tested for backward compatibility of destination. **Note:** New required fields are a breaking change.
- [X] [Segmenters] Tested in the staging environment
- [ ] [Segmenters] [If applicable for this change] Tested for regression with Hadron.

2024-10-03 09:59 UTC, itsarijitray submitted a review, later dismissed

2024-10-03 14:48 UTC, Innovative-GauravKochar commented
@AnkitSegment Changes looks good, Can you please add summary of your pull request, including the what change you're making and why ?
Can you please add evidence when you don't send either of them or both of them ?

2024-10-03 16:18 UTC, nick-Ag commented on packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-user-data.ts
> +      label: 'advertiser ID (madid)',
Nit
```suggestion
      label: 'Advertiser ID (madid)',
```

2024-10-03 16:19 UTC, nick-Ag commented on packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-app-data.ts
> +      label: 'advertiser ID (madid)',
Nit
```suggestion
      label: 'Advertiser ID (madid)',
```

2024-10-03 16:22 UTC, nick-Ag requested changes
Left a couple of nitpicks. Code looks good otherwise. I agree with @Innovative-GauravKochar that we should get some testing evidence in the cases where neither are sent or only one of each are sent

2024-10-07 20:18 UTC, nick-Ag approved these changes

2024-10-08 08:55 UTC, merged

2024-10-08 14:29 UTC, joe-ayoub-segment commented
hi @AnkitSegment PR deployed