Salesforce custom object external
segmentio/action-destinations pull request #2485
Opened 2024-10-07 23:55 UTC by seg-leonelsanches

This modification:

- Updates Salesforce base API from version v53 to v62;
- Adds a new mapping to upsert a custom object by its Id.

## Testing

- [X] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [If destination is already live] Tested for backward compatibility of destination. **Note:** New required fields are a breaking change.
- [ ] [Segmenters] Tested in the staging environment
- [ ] [Segmenters] [If applicable for this change] Tested for regression with Hadron.

2024-10-21 18:56 UTC, rvadera12 requested changes
Left a couple of comments. Can we also clean up the PR to only include the changes you made and not other syntax changes from other destinations.

2024-10-21 18:56 UTC, rvadera12 commented on packages/destination-actions/src/destinations/salesforce/customObjectExternalId/index.ts
> +}
Is there a reason why we are not implementing a performBatch method here?

2024-10-21 18:56 UTC, rvadera12 commented on packages/destination-actions/src/destinations/salesforce/sf-operations.ts
> +export interface SObjectsResponseData {
Why are we changing this to exports, and can we check backwards compatibility? If this interface is already in use, changing it to an export might affect existing consumers of the code. Ensure there are no breaking changes.

2024-10-21 20:25 UTC, seg-leonelsanches commented on packages/destination-actions/src/destinations/salesforce/customObjectExternalId/index.ts
> +}
@rvadera12 The batch doesn't make sense for this endpoint. Each record requires one separate API call. The API endpoint format is `/services/data/v61.0/sobjects/${entityType}/${entityKey}/${entityKeyValue}`. There's no way we can aggregate N records in 1 API call.

2025-05-06 13:24 UTC, joe-ayoub-segment commented
hi @seg-leonelsanches just doing some tidy up - can we close this PR?

2025-07-30 18:57 UTC, closed without merging