Added trackEvent Batch Support in Klaviyo
segmentio/action-destinations pull request #2498
Opened 2024-10-10 13:52 UTC by Innovative-GauravKochar

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [If destination is already live] Tested for backward compatibility of destination. **Note:** New required fields are a breaking change.
- [ ] [Segmenters] Tested in the staging environment
- [ ] [Segmenters] [If applicable for this change] Tested for regression with Hadron.

2024-10-16 20:27 UTC, sayan-das-in requested changes
Thank you for making this change. The core MultiStatus logic looks good, however I have left some review comments mostly to refactor and simplify the code as these will be listed as examples for external contributors.

2024-10-16 20:27 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +  })
```suggestion
  payloads.forEach((payload, originalBatchIndex) => {
    // Filter out and record if payload is invalid
    const { email, phone_number, external_id, anonymous_id, country_code } = payload.profile

    if (!email && !phone_number && !external_id && !anonymous_id) {
      multiStatusResponse.setErrorResponseAtIndex(originalBatchIndex, {
        status: 400,
        errortype: 'PAYLOAD_VALIDATION_FAILED',
        errormessage: 'One of External ID, Anonymous ID, Phone Number or Email is required.'
      })
      return
    }

    if (phone_number) {
      // Validate and convert the phone number if present
      const validPhoneNumber = validateAndConvertPhoneNumber(phone_number, country_code as string)
      // If the phone number is not valid, skip this payload
      if (!validPhoneNumber) {
        multiStatusResponse.setErrorResponseAtIndex(originalBatchIndex, {
          status: 400,
          errortype: 'PAYLOAD_VALIDATION_FAILED',
          errormessage: 'Phone number could not be converted to E.164 format.'
        })
        return // Skip this payload
      }

      // Update the payload's phone number with the validated format
      payload.profile.phone_number = validPhoneNumber
      delete payload?.profile?.country_code
    }

    const profileToAdd = constructProfilePayload(payload)
    filteredPayloads.push(profileToAdd as JSONLikeObject)
    validPayloadIndicesBitmap.push(originalBatchIndex)
    multiStatusResponse.setSuccessResponseAtIndex(originalBatchIndex, {
      status: 200,
      sent: profileToAdd as JSONLikeObject,
      body: 'success'
    })
  })
```

The `validatePayload` is being called only once here, maybe we can delete the function and add the logic here instead and further simplify the code.

2024-10-16 20:27 UTC, sayan-das-in commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +async function handleKlaviyoAPIErrorResponse(
```suggestion
function handleKlaviyoAPIErrorResponse(
```

This function is not handling any Promises or using await, we can remove the async keyword

2024-10-17 11:38 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +  }
Actually I tried that way but unable to parse the response body of error and it is accessible via `await err.response.json()`

2024-10-17 11:40 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +  })
It's okay to remove that function, probably it might be used in other actions. As same kind of check and validation is required in other action.

2024-10-21 13:49 UTC, sayan-das-in submitted a review, later dismissed

2024-10-23 06:54 UTC, varadarajan-tw requested changes
The errorType should not be set to PAYLOAD_VALIDATION_FAILED in scenarios where the problem is not with the payload. The changes are being made to Braze now. We should also do the change in this PR  before we proceed.
cc: @sayan-das-in

2024-10-23 06:54 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +          errortype: 'PAYLOAD_VALIDATION_FAILED',
The errorType should not be set to PAYLOAD_VALIDATION_FAILED in scenarios where the problem is not with the payload. Instead it should be set to a readable version of status. The changes are being made to Braze now. We should also do the change in this PR as well.

2024-10-23 13:31 UTC, varadarajan-tw approved these changes

2024-11-12 08:44 UTC, AnkitSegment commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +      body: 'success'
@Innovative-GauravKochar, instead of hardcoding the `success` value, can we return an API response?

2024-11-12 08:52 UTC, AnkitSegment commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +            "This event wasn't delivered because of few bad events in the same batch to Klaviyo. This will be retried",
Nit: The event wasn't delivered to Klaviyo because of bad events in the batch.

2024-11-12 08:53 UTC, AnkitSegment commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +          body: 'Retry'
Can we add API response from Kalviyo instead of hardcoding ?

2024-11-12 10:55 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +            "This event wasn't delivered because of few bad events in the same batch to Klaviyo. This will be retried",
This Message is suggested by @varadarajan-tw

2024-11-12 11:01 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +      body: 'success'
We are just initialising the multiStatusResponse with success for all valid payload (to avoid traversal of payload array again in case of success) as it returns nothing in case of success .
This Point is already noted !

2024-11-12 11:18 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/klaviyo/functions.ts
> +          body: 'Retry'
@AnkitSegment The Klaviyo API returns an error response for each invalid payload separately. Therefore, there can be multiple reasons for a batch failure, and each invalid payload should be handled individually. Since the retries are meant for valid payloads only, we want to avoid sending an API error response in this case.

2024-12-10 13:34 UTC, merged