First push with CustomEvents Destination Action
segmentio/action-destinations pull request #2570
Opened 2024-11-06 17:09 UTC by wtnelso

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [If destination is already live] Tested for backward compatibility of destination. **Note:** New required fields are a breaking change.
- [ ] [Segmenters] Tested in the staging environment
- [ ] [Segmenters] [If applicable for this change] Tested for regression with Hadron.

2024-11-08 13:17 UTC, joe-ayoub-segment commented
Hi @wtnelso thanks for raising this PR! 
I'll schedule some time to review. 

Could you please remove the yarn version upgrade please? 
The PR contains changes to the package.json and yarn.lock files, which looks like it might have been a mistake.

2024-11-08 13:29 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/index.ts
> +        description: 'API key used to authorize sending data to Attentive.',
```suggestion
        description: 'Your Attentive API Key.',
```

2024-11-08 13:31 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      description: 'Any metadata associated with the event.',
```suggestion
      description: 'Metadata to associate with the event.',
```

2024-11-08 13:32 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      description: 'The type of event. This name is case sensitive. "Order shipped" and "Order Shipped" would be considered different event types.',
hi @wtnelso the value at $.event will always be either 'track', 'identify', 'page', 'screen' or 'group'. Is this information useful to you? If not, then this field probably isn't required.

2024-11-08 13:33 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      description: 'A unique identifier representing this specific event. A UUID is recommended.',
```suggestion
      description: 'A unique identifier for the event.',
```

2024-11-08 13:33 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +    },
```suggestion
    externalEventId: {
      label: 'External Event Id',
      description: 'A unique identifier representing this specific event. A UUID is recommended.',
      type: 'string',
      required: false,
      default: {
            '@path': '$.messageId'
      }
    },
```

2024-11-08 13:34 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      type: 'string', // Keep 'string', as <date-time> is not a valid type in TypeScript.
```suggestion
      type: 'string', 
```

2024-11-08 13:34 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      description: 'Timestamp of when the action occurred in ISO 8601 format.',
```suggestion
      description: 'Timestamp for the event, ISO 8601 format.',
```

2024-11-08 13:36 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      description: 'Phone number of the user associated with the action. E.164 format is required. This field is required if either email or an externalIdentifier is not provided.',
```suggestion
      description: "The user's phone number in E.164 format. One of 'Phone', 'Email' or 'External Event Id' fields is required.",
```

2024-11-08 13:37 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      description: 'Email of the user associated with the action. This field is required if either phone or an externalIdentifier is not provided.',
```suggestion
      description: 'The user's email address. One of 'Email', 'Phone' or 'External Event Id' fields is required.',
```

2024-11-08 13:39 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      required: false,
Please add this default mapping for phone: 
```
default: {
        '@if': {
          exists: { '@path': '$.properties.phone' },
          then: { '@path': '$.properties.phone' },
          else: { '@path': '$.context.traits.phone' }
        }
}
```

2024-11-08 13:41 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +    },
```suggestion
    clientUserId: {
      label: 'Client User ID',
      description: "A primary ID for a user. Required if none of 'Phone', 'Email' and 'External Event Id' are not provided.',
      type: 'string',
      required: false,
    },
```

2024-11-08 13:47 UTC, joe-ayoub-segment commented
hi @wtnelso I just went through the code and would like to make some changes to make the UI simpler. Do you mind granting me permission to push changes to your repo please? joe-ayoub-segment is my Github handle.

2024-11-12 11:24 UTC, joe-ayoub-segment commented
hi @wtnelso just following up on this. Are you still interested in having these changes deployed?

2024-11-12 15:52 UTC, wtnelso commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +    },
@joe-ayoub-segment will the messagId value be unique everytime?

2024-11-12 15:55 UTC, wtnelso commented
> hi @wtnelso just following up on this. Are you still interested in having these changes deployed?

Hi @joe-ayoub-segment apologies for the delay. I didn't get a notification when your comments were made. Just seeing these today.

2024-11-12 15:58 UTC, wtnelso commented
> joe-ayoub-segment

Just added you to my repo

2024-11-12 16:02 UTC, wtnelso commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      description: 'The type of event. This name is case sensitive. "Order shipped" and "Order Shipped" would be considered different event types.',
No, $.event is probably not the correct field then. The "Type" field is typically more descriptive, like "Order Shipped", "Review Completed" or "Loyalty Points Changed". Is there a field similar to that on your end?

2024-11-12 16:07 UTC, wtnelso commented
> Hi @wtnelso thanks for raising this PR! I'll schedule some time to review.
> 
> Could you please remove the yarn version upgrade please? The PR contains changes to the package.json and yarn.lock files, which looks like it might have been a mistake.

Hi @joe-ayoub-segment, apologies but would you be able to clarify where I need to make this change?

2024-11-12 16:10 UTC, wtnelso commented on packages/destination-actions/src/destinations/attentive/customEvents/index.ts
> +      required: false,
added to the file and committed.

2024-11-13 11:52 UTC, joe-ayoub-segment commented on package.json
> +    "yarn": "^1.22.22"
hi @wtnelso this is where the yarn dependency was upgraded. Can this be removed please?

2024-11-13 11:53 UTC, joe-ayoub-segment commented on yarn.lock
> +
Also please remove this @wtnelso .

2024-11-13 13:47 UTC, joe-ayoub-segment commented
Hi @wtnelso thanks for granting me access to the repo. I pushed some changes which I thought would be useful. 
1. Merged the identifier fields into a single Object field
2. Added some basic validation
3. Added some types for the request JSON

The tests do break - perhaps you could address these, or point out which part of the code is incorrect. 

Best regards,
Joe

2024-11-13 15:12 UTC, wtnelso commented on package.json
> +    "yarn": "^1.22.22"
hi @joe-ayoub-segment updated and committed. but to make sure in understand correctly, is this the desired outcome?
"chance": "^1.1.8",
    "yarn": "^1.22.22"

2024-11-13 15:18 UTC, wtnelso commented on yarn.lock
> +
@joe-ayoub-segment I don't see that in my repo under the yarn.lock file.

2024-11-13 15:18 UTC, joe-ayoub-segment commented on package.json
> +    "yarn": "^1.22.22"
Hi @wtnelso I fixed it when I pushed my changes up. 

There should be no changes to the package.json file.

2024-11-13 15:19 UTC, joe-ayoub-segment commented on yarn.lock
> +
Also there should be no changes to the yarn.lock file. 
I corrected this when I pushed my changes up.

2024-11-13 15:38 UTC, joe-ayoub-segment commented on yarn.lock
> +
It's OK you can ignore it now anyway. Just pull the latest code and you can ignore these comments :). 

The only thing to do now is fix the unit tests.

2024-11-14 18:12 UTC, wtnelso commented on yarn.lock
> +
Thanks!

2024-11-14 20:56 UTC, wtnelso commented
> Hi @wtnelso thanks for granting me access to the repo. I pushed some changes which I thought would be useful.
> 
> 1. Merged the identifier fields into a single Object field
> 2. Added some basic validation
> 3. Added some types for the request JSON
> 
> The tests do break - perhaps you could address these, or point out which part of the code is incorrect.
> 
> Best regards, Joe

hi @joe-ayoub-segment, I added the unit tests. Let me know how they look or what else I can do.

2024-11-15 10:03 UTC, joe-ayoub-segment requested changes
Hi @wtnelso there seems to be a missing file being referenced in the tests. 

import { API_URL } from '../../config'

2024-11-15 10:04 UTC, joe-ayoub-segment commented
hi @wtnelso I'm still getting some issues with running the tests. 

![image](https://github.com/user-attachments/assets/6aafdb42-6a80-4f18-a85f-3fc4ec50ce62)

2024-11-15 17:53 UTC, wtnelso commented
Hi @joe-ayoub-segment I believe I made the necessary updates for the tests to now pass.

Is there a way I can test on my side to ensure as well?

2024-11-15 19:56 UTC, wtnelso reviewed
reviewed changes and made updates

2024-11-18 13:11 UTC, joe-ayoub-segment commented
hi @wtnelso 
Would you be able to schedule a call with me so we can fix up this Destination and get it deployed please?
Here's my Calendly: https://calendly.com/joe_ayoub/ 

I look forward to catching up. 
Joe

2024-11-19 21:18 UTC, wtnelso commented
Hi @joe-ayoub-segment, i added a new unit test. other than that new one, not sure there are others to add.

One more question. I used the command `yarn cloud test packages/destination-actions/src/destinations/attentive` and get the below and then following error. Is there anything I need to do different next time?
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/c34dd907-0ebb-40c6-be43-d52605358e42">
Is there something else I need to configure on my end?

2024-11-20 10:58 UTC, joe-ayoub-segment commented
Hi @wtnelso - which folder did you execute the command from? You should be in the repo root folder.

2024-11-20 14:18 UTC, wtnelso commented
@joe-ayoub-segment I've tried at the attentive folder and its sub folder. packages/destination-actions/src/destinations/attentive

besides this one command, are there other changes needed for this PR? If we're good on this one, I'll begin the work on the other endpoints we want to add next

2024-11-20 14:23 UTC, joe-ayoub-segment commented
Hi @wtnelso - the new test doesn't work. 
No probs though, just leave it. I'll fix or remove it. 
Feel free to work on the other Actions.

2024-11-20 16:13 UTC, joe-ayoub-segment commented
Hi @wtnelso I've prepared this PR for deploy. 
If you are going to write any more code (for the other Actions) please do them in a separate branch.

2024-11-20 16:13 UTC, joe-ayoub-segment approved these changes

2024-11-26 12:59 UTC, joe-ayoub-segment approved these changes

2024-11-26 12:59 UTC, merged

2024-11-26 13:15 UTC, joe-ayoub-segment commented
We're in a deploy freeze so next deploy scheduled for 3-Dec

2024-12-03 17:03 UTC, joe-ayoub-segment commented
hi @wtnelso this PR has been deployed. I'll email you next steps.