[LinkedIn Audiences] Necessary fixes for `updateAudience` mapping.
segmentio/action-destinations pull request #2629
Opened 2024-12-06 23:06 UTC by seg-leonelsanches

- User Email is not always `context.traits.email`;
- `sourceSegmentId` in the mapping is not only useless, as it obliges the customer to add one mapping per audience.

## Motivation

- Some customers have emails as normal traits, not identifiers;
- Some customers have different spellings for their emails;
- Some customers use trait enrichment for emails, and they come as properties;
- I don't know any customer that wants to add a mapping per audience in Engage.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [X] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [If destination is already live] Tested for backward compatibility of destination. **Note:** New required fields are a breaking change.
- [ ] [Segmenters] Tested in the staging environment
- [ ] [Segmenters] [If applicable for this change] Tested for regression with Hadron.

2024-12-10 18:15 UTC, brennan commented
@seg-leonelsanches for now, the only changes I would be comfortable making are:

- Exposing the `email` field to customers (but not changing the default)
- Checking whether email addresses are hashed

Happy to review and approve a PR with only these two changes.

`I don't know any customer that wants to add a mapping per audience in Engage.` - For now, this is required to ensure that bulk batching works correctly for this destination.

2024-12-10 18:27 UTC, seg-leonelsanches commented
> @seg-leonelsanches for now, the only changes I would be comfortable making are:
> 
> * Exposing the `email` field to customers (but not changing the default)
> * Checking whether email addresses are hashed
> 
> Happy to review and approve a PR with only these two changes.
> 
> `I don't know any customer that wants to add a mapping per audience in Engage.` - For now, this is required to ensure that bulk batching works correctly for this destination.

Thank you, @brennan. As requested, I reverted the changes regarding `source_segment_id`.

2024-12-10 18:31 UTC, seg-leonelsanches commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +          else: { '@path': '$.context.traits.email' }
@brennan This does the exact same thing as before, but checking an extra field.

2024-12-10 18:36 UTC, seg-leonelsanches commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +          else: { '@path': '$.context.traits.email' }
UI Preview: 
<img width="624" alt="image" src="https://github.com/user-attachments/assets/a85431a6-d223-485b-94b1-b3e10995b706">

2024-12-11 18:04 UTC, brennan commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +    if (!isHashed) {
Can we add a unit test that exercises this code path, please?

2024-12-11 18:10 UTC, brennan commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +    const isHashed = new RegExp(/[0-9abcdef]{64}/gi).test(payload.email)
Can we add a unit test with a pre-hashed email?

2024-12-11 19:04 UTC, seg-leonelsanches commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +    const isHashed = new RegExp(/[0-9abcdef]{64}/gi).test(payload.email)
This is done.

2024-12-12 22:46 UTC, brennan commented
@joe-ayoub-segment When we deploy, this will require a push. The only metadata value to be updated is the default mapping for the `email` field: https://github.com/segmentio/action-destinations/pull/2629/files#diff-79d0d51e489f761c254e9fbbe921303e9a89b54400da18a98f42cdc6e8487c3fR32-R36

cc @rvadera12

2024-12-12 23:00 UTC, marinhero commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +          else: { '@path': '$.context.traits.email' }
Hi @seg-leonelsanches , quick question, why aren't we favoring the existing path value to be the one that gets check first instead of making it the fallback? That would feel like a more incremental change to me. What would you say?

```
{
    '@if': {
        exists: { '@path': '$.context.traits.email' },
        then: { '@path': '$.context.traits.email' },
        else: { '@path': '$.traits.email' }
    }
}
```

2024-12-12 23:04 UTC, marinhero commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +    const isHashed = new RegExp(/[0-9abcdef]{64}/gi).test(payload.email)
instead of implementing this, please use the [Hashing Utils](https://github.com/segmentio/action-destinations/blob/6955920f1a4c6194e86ce6486a510f82a64b7d4e/packages/core/src/hashing-utils.ts#L24) that are used in other destinations. Thanks!

2024-12-12 23:05 UTC, seg-leonelsanches commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +          else: { '@path': '$.context.traits.email' }
@marinhero My first version of this PR had the hardcoded audience key removed, therefore the precedence to work with traits. 

I think the precedence doesn't matter that much here. I prefer to not have this modified right now, since it was very difficult to get it approved on time before the code freeze.

2024-12-12 23:09 UTC, marinhero commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +  const elements: Record<string, unknown>[] = []
Good call 🙇🏽

2024-12-12 23:12 UTC, marinhero commented on packages/destination-actions/src/destinations/linkedin-audiences/updateAudience/index.ts
> +  if (dmp_user_action === 'REMOVE') {
NIT: I would actually discourage unneeded changes on this destination due to its high usage. Up to you wether to keep them or not.

2024-12-12 23:18 UTC, marinhero requested changes
There are some welcome changes here. I'll request an update due to the redundant hashing function. Let's use the Hashing Utils instead.

2024-12-12 23:37 UTC, marinhero approved these changes

2024-12-13 00:44 UTC, brennan approved these changes

2024-12-13 14:32 UTC, merged

2024-12-13 17:44 UTC, joe-ayoub-segment commented
hi @seg-leonelsanches PR deployed. cc @brennan