[SFMC] Add Multistatus Support for SFMC
segmentio/action-destinations pull request #2639
Opened 2024-12-12 06:31 UTC by harsh-joshi99

This PR adds multistatus response `dataExtension` and `contactDataExtension` actions of SFMC.

JIRA -> https://segment.atlassian.net/browse/STRATCONN-5312

## Testing
Testing completed successfully in local via integrations.
Testing completed successfully in staging via sneakerhead.
[Testing Document.](url)

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x] [If destination is already live] Tested for backward compatibility of destination. **Note:** New required fields are a breaking change.
- [x] [Segmenters] Tested in the staging environment
- [ ] [Segmenters] [If applicable for this change] Tested for regression with Hadron.

2024-12-25 07:28 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
> +    if (err?.response?.data?.message === 'Not Authorized') {
Can we check with status code instead of message ?

2024-12-25 07:37 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/types.ts
> +  message: string
I think Error interface should be made up like this 

{
data:ErrorResponseData
}

interface ErrorResponseData {
  message: string
  errorcode: number
  documentation: string
 additionalError: AdditionalError
}

2025-01-02 17:57 UTC, nick-Ag commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/multistatus.test.ts
> +      expect(response[0]).toMatchObject({
Question for my understanding: Why would `response[0]` show an error related to ID: HS2 when `events[0]` is sending ID: HS1?

2025-01-02 17:58 UTC, nick-Ag approved these changes

2025-01-03 06:47 UTC, harsh-joshi99 commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/multistatus.test.ts
> +      expect(response[0]).toMatchObject({
SFMC will return an error if any event in the payload is invalid and will fail the entire batch. Therefore, the error message is returned for all events to indicate that at least one of them has an issue.
Also the error message here is a dummy example, SFMC error messages do not specify the id.

2025-01-03 08:59 UTC, varadarajan-tw submitted a review, later dismissed

2025-01-06 09:00 UTC, Innovative-GauravKochar commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
> +        body: JSON.stringify(response?.data)
@harsh-joshi99 body could be JSONLikeObject | string. We don't need to stringify specifically
 
export type ActionDestinationSuccessResponseType = {
  status: number
  sent: JSONLikeObject | string
  body: JSONLikeObject | string
}

2025-01-06 09:00 UTC, Innovative-GauravKochar commented
LGTM !

2025-01-06 09:01 UTC, Innovative-GauravKochar submitted a review, later dismissed
LGTM !

2025-01-10 10:28 UTC, varadarajan-tw requested changes

2025-01-10 10:28 UTC, varadarajan-tw commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
> +        status: 400,
I just noticed this. We shouldn't set this always to 400. This will impact retries.

2025-01-15 08:16 UTC, varadarajan-tw approved these changes

2025-01-16 09:08 UTC, merged