Add connection overrides on twilio sms status callback url
segmentio/action-destinations pull request #343
Opened 2021-11-16 20:44 UTC by lpediredla

JIRA: https://segment.atlassian.net/browse/GRAMA-169

Adding connection overrides on Twilio Webhook status callback for Twilio sms service to retry on failed policy.

* Retry policy on 5xx, 4xx, connection timeout, and request timeout
* Max retries 5

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2021-11-16 20:48 UTC, lew-gordon requested changes
I think this is a good start, though IMO these should be options as part of the destination definition. See https://github.com/segmentio/action-destinations/blob/main/packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts.

2021-11-16 21:40 UTC, lew-gordon commented
@laurenfb @vikramkumar19 I know this is your area, would you mind adding another review for @lpediredla here?

2021-11-16 22:05 UTC, pmcanseco commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +        description: 'Connection overrides are frasgments that will append on webhook url',
```suggestion
        description: 'Connection overrides are fragments that will append on webhook url',
```

2021-11-16 22:32 UTC, lpediredla commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +        description: 'Connection overrides are frasgments that will append on webhook url',
fixed :)

2021-11-17 00:14 UTC, lew-gordon requested changes
Just a quick thought around the setting being an object if it's not too much extra work.

2021-11-17 00:14 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +        default: "rp=all&rc=5"
If it's not too much work it'd be nice to just specify as an object all of the available options in the table on this page: https://www.twilio.com/docs/usage/webhooks/webhooks-connection-overrides. Bonus points for additional typing.

2021-11-17 00:14 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-twilio/sendSms/index.ts
> +      if(connectionOverrides) {
When is this undefined, since we have that default?

2021-11-17 00:33 UTC, laurenfb commented on packages/destination-actions/src/destinations/personas-messaging-twilio/sendSms/index.ts
> +      if(connectionOverrides) {
nitpick: space between if and paren

2021-11-17 00:33 UTC, laurenfb commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +        description: 'Connection overrides are fragments that will append on webhook url',
I'm not sure I understand what this sentence means. Is there a way to rephrase it?

2021-11-17 00:33 UTC, laurenfb commented on packages/destination-actions/src/destinations/personas-messaging-twilio/generated-types.ts
> +   * Connection overrides are frasgments that will append on webhook url
fragments

2021-11-17 00:33 UTC, laurenfb commented on packages/browser-destinations/src/destinations/braze/__tests__/__snapshots__/integration.test.ts.snap
> +      NodeList [
Is this your change? these look unrelated and a little bit odd.

2021-11-17 00:35 UTC, laurenfb commented
are there any unit tests you can add to test this functionality specifically? I see changes there but looks like they are just to make the current tests pass?

2021-11-17 00:37 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +        description: 'Connection overrides are fragments that will append on webhook url',
Not sure on text length, but I bet we could steal or paraphrase some wording from this doc: https://www.twilio.com/docs/usage/webhooks/webhooks-connection-overrides#connection-overrides

2021-11-17 02:30 UTC, mshwery commented on packages/destination-actions/src/destinations/personas-messaging-twilio/sendSms/index.ts
> +      if(connectionOverrides) {
Keep in mind that `default` values are not applied at runtime. They behave more like "initial" values when a customer first connects the action in the actions editor ui. At runtime we only resolve values provided in the mappings payload from the customer's action config.

2021-11-17 07:56 UTC, lpediredla commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +        description: 'Connection overrides are fragments that will append on webhook url',
Rephrased connection overrides from twilio webhook notes

2021-11-17 07:56 UTC, lpediredla commented on packages/destination-actions/src/destinations/personas-messaging-twilio/generated-types.ts
> +   * Connection overrides are frasgments that will append on webhook url
updated

2021-11-17 15:29 UTC, vikramkumar19 commented on packages/destination-actions/src/destinations/personas-messaging-twilio/sendSms/index.ts
> +      if (connectionOverrides) {
What would happen if connectionOverrides = '' or any invalid string?

2021-11-17 19:55 UTC, lpediredla commented on packages/destination-actions/src/destinations/personas-messaging-twilio/sendSms/index.ts
> +      if (connectionOverrides) {
Could not find any public documentation from Twilio about invalid hash. If I are to take a guess. SendSms will still work as expected. SMS callbacks will ignore fragments that are not part of their service contract.

2021-11-17 21:23 UTC, lpediredla commented on packages/destination-actions/src/destinations/personas-messaging-twilio/sendSms/index.ts
> +      if (connectionOverrides) {
Added a default.

2021-11-18 14:09 UTC, lew-gordon reviewed
Had one quick question on specifying the overrides as options instead? https://github.com/segmentio/action-destinations/pull/343/files#r750785025

2021-11-18 22:58 UTC, vikramkumar19 approved these changes
LGTM!

2021-11-22 21:58 UTC, lpediredla commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +        default: "rp=all&rc=5"
Added all the attributes as properties on the connection overrides

2021-11-22 23:10 UTC, merged

2021-11-23 02:51 UTC, mshwery commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +    choices: getRange(10000)
This seems excessive. Why not let them input a number?

2021-11-23 02:51 UTC, mshwery commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +        properties: ConnectionOverridesProperties
This isnt defined quite right. Looks like it's using features that only exist at the top-level field. Not nested object properties.

2021-11-23 02:51 UTC, mshwery commented on packages/destination-actions/src/destinations/personas-messaging-twilio/index.ts
> +        type: 'string',
Type string doesn't support objects or nested properties