Salesforce (Actions): Lead Action
segmentio/action-destinations pull request #387
Opened 2021-12-10 23:53 UTC by nick-Ag

This PR implements the Salesforce (Actions) Lead action. It is the first action implemented for the destination and will serve as prior art for the following actions.

The action supports the following CRUD operations:

* Create (Implemented)
* Update
* Upsert

## Testing

Tested locally by running `./bin/run serve` and passing in an `auth` object with shape:
```
auth: {
 clientId
 clientSecret
 accessToken
 refreshToken
}
```
<img width="1133" alt="Screen Shot 2021-12-10 at 3 49 30 PM" src="https://user-images.githubusercontent.com/27820201/145654972-b4e0cbb1-97eb-47b7-a07f-a84769278882.png">

Tested in stage via deploying to stage:
<img width="1914" alt="Screen Shot 2021-12-07 at 10 15 26 AM" src="https://user-images.githubusercontent.com/27820201/145655021-4001fd27-2464-4ca3-a549-fbc52abc9c7a.png">

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2021-12-11 00:40 UTC, mericsson commented on packages/destination-actions/src/destinations/salesforce/index.ts
> +      console.log('res', res)
```suggestion
```

2021-12-11 00:41 UTC, mericsson commented on packages/destination-actions/src/destinations/salesforce/lead/index.ts
> +    crud: {
```suggestion
    operation: {
```

Wonder if this field name is more appropriate given:
1. CRUD isn't what we are doing since we may not support delete and we support Upsert -- so would be CRUU :)
2. May not be obvious to users

2021-12-11 00:43 UTC, mericsson commented on packages/destination-actions/src/destinations/salesforce/lead/index.ts
> +        { label: 'Upsert', value: 'upsert' }
I think better to just not support these yet rather than have placeholders. Would rather have thin slices of fully implemented so it's clear as we start testing it what is expected to work.

2021-12-11 00:44 UTC, mericsson commented on packages/destination-actions/src/destinations/salesforce/lead/index.ts
> +        { label: 'Upsert', value: 'upsert' }
```suggestion
        { label: 'Create', value: 'create' }
```

I think better to just not support these yet rather than have placeholders. Would rather have thin slices of fully implemented so it's clear as we start testing it what is expected to work.

2021-12-13 22:30 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/index.ts
> +interface RefreshTokenResponse {
Curious if we'll need all these properties? Even though Salesforce's oauth endpoint returns all these values, I don't think we'll need any of them, except for perhaps `instance_url`.

We may consider just using the [existing`RefreshAccessTokenResult`](https://sourcegraph.segment.com/github.com/segmentio/action-destinations@21cf91ae4c15edda3ec0d850b761c48eed61b44d/-/blob/packages/core/src/destination-kit/index.ts?L95) interface, extended with the `instance_url` property.

2021-12-13 22:32 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/lead/index.ts
> +    first_name: {
Nit - should `first_name` and `last_name` be consecutive in the object?

2021-12-13 22:44 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/lead/index.ts
> +      return request(`${settings.instanceUrl}/services/data/${API_VERSION}/sobjects/Lead`, {
Confirming that the future `settings.instanceUrl` will simple be `auth.instanceUrl`, correct?

2021-12-13 22:45 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/lead/index.ts
> +const API_VERSION = 'v53.0'
Curious how often we should expect to update the API version, if that information is known?

2021-12-28 19:46 UTC, nick-Ag commented on packages/destination-actions/src/destinations/salesforce/lead/index.ts
> +      return request(`${settings.instanceUrl}/services/data/${API_VERSION}/sobjects/Lead`, {
That's correct, just using `settings` for now to send events

2022-01-18 22:46 UTC, nick-Ag commented on packages/destination-actions/src/destinations/salesforce/sf-types.ts
> +export type GenericPayload = Partial<LeadPayload>
Will be able to do `Partial<LeadPayload | AccountPayload | etc >` when adding more actions

2022-01-19 21:33 UTC, brennan commented on packages/destination-actions/src/destinations/index.ts
> +register('61957755c4d820be968457de', './salesforce')
Verified `id` in stage partner portal.

2022-01-19 21:47 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/generated-types.ts
> +   * Base Url of the request. For local testing only. refreshAccessToken will eventually be able to fetch this value via Oauth
Probably want to update the description of `instanceUrl` and regenerate the `Settings` type.

2022-01-19 21:48 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/index.ts
> +          'Base Url of the request. For local testing only. refreshAccessToken will eventually be able to fetch this value via Oauth',
Update `instanceUrl` description.

2022-01-19 21:50 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/index.ts
> +interface SalesforceRefreshAccessTokenResult extends RefreshAccessTokenResult {
I don't think we need this interface since we don't update `instanceUrl` on token refresh, only when a customer authorizes or re-authorizes via the `app` UI.

2022-01-19 21:59 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/sf-operations.ts
> +    if (payload.traits === undefined || Object.keys(payload.traits).length === 0) {
Should we use `!payload` to account for instances where `payload` could be null, an empty string, or other falsy values, or are we pretty sure that it would always be either `undefined` or `{}` here?

2022-01-19 22:01 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/sf-operations.ts
> +    if (err !== undefined) {
```suggestion
    if (err) {
```

2022-01-19 22:04 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/sf-operations.ts
> +    if (err === undefined) {
```suggestion
    if (err) {
      if (err.status === 404) {
        return await this.createRecord(payload, sobject)
      }
      throw err
    }
  return await this.baseUpdate(recordId, sobject, payload)
}
```

2022-01-19 22:10 UTC, brennan requested changes
Generally looks great! Happy to 👍 once the comments are addressed.

2022-01-19 23:06 UTC, nick-Ag commented on packages/destination-actions/src/destinations/salesforce/sf-operations.ts
> +    if (payload.traits === undefined || Object.keys(payload.traits).length === 0) {
Agreed, I also added a unit test for cases where it is null or empty

2022-01-19 23:18 UTC, brennan approved these changes

2022-01-19 23:29 UTC, merged