Gainsight px entire event
segmentio/action-destinations pull request #418
Opened 2022-01-12 23:11 UTC by nwolfe-xx

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-01-25 16:42 UTC, daltonscharff commented on packages/destination-actions/src/destinations/gainsight-px-cloud-action/index.ts
> +  name: 'Gainsight Px Cloud Action',
```suggestion
  name: 'Gainsight Px Cloud (Actions)',
```
Adjusts name to fit naming convention

2022-01-25 16:42 UTC, daltonscharff commented on packages/destination-actions/src/destinations/gainsight-px-cloud-action/index.ts
> +  slug: 'gainsight-px-cloud-action',
```suggestion
  slug: 'actions-gainsight-px-cloud',
```
Adjusts slug to fit naming convention

2022-01-25 16:52 UTC, daltonscharff requested changes
Looks great! I'll merge this after the slight changes are made to the name and slug.

2022-01-31 21:41 UTC, jinapark202 commented
@nwolfe-xx What's the difference between this PR and the one that was merged?

2022-02-02 20:29 UTC, jinapark202 commented
Closing because this PR seems to be a duplicate of PR #388

2022-02-02 20:29 UTC, closed without merging