Moengage-segment integration
segmentio/action-destinations pull request #475
Opened 2022-02-15 11:40 UTC by shubham-engg-data

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-02-15 13:37 UTC, dlasky requested changes
lgtm, a few minor nits!

2022-02-15 13:37 UTC, dlasky commented on packages/destination-actions/src/destinations/actions-moengage/identifyUser/index.ts
> +    if (payload.user_id) {
suggest removing the ifs as the 'event' will run through JSON.stringify which will strip any undefined values

2022-02-15 13:37 UTC, dlasky commented on packages/destination-actions/src/destinations/actions-moengage/index.ts
> +        label: 'Endpoint Region',
suggest making this required due to how our auth settings work currently in the UI

2022-02-15 13:37 UTC, dlasky commented on packages/destination-actions/src/destinations/actions-moengage/trackEvent/index.ts
> +    if (payload.user_id) {
suggest removing ifs similar to above comment

2022-02-17 18:39 UTC, shubham-engg-data commented on packages/destination-actions/src/destinations/actions-moengage/identifyUser/index.ts
> +    if (payload.user_id) {
Done

2022-02-17 18:39 UTC, shubham-engg-data commented on packages/destination-actions/src/destinations/actions-moengage/index.ts
> +        label: 'Endpoint Region',
Done

2022-02-17 18:39 UTC, shubham-engg-data commented on packages/destination-actions/src/destinations/actions-moengage/trackEvent/index.ts
> +    if (payload.user_id) {
Done

2022-02-18 08:41 UTC, shubham-engg-data commented on packages/destination-actions/src/destinations/actions-moengage/index.ts
> +  name: 'Moengage',
Done @nick-Ag , Thanks for the suggestion .

2022-02-18 18:01 UTC, nick-Ag approved these changes

2022-02-18 18:37 UTC, merged