Salesforce Sandbox
segmentio/action-destinations pull request #522
Opened 2022-03-15 22:47 UTC by nick-Ag

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-03-18 18:23 UTC, marinhero commented on packages/destination-actions/src/destinations/salesforce/index.ts
> +        description: 'Turn this on if you would like to oauth into a sandbox environment instead',
You are using `.` to end other sentences. Did you miss one here?

2022-03-18 18:39 UTC, nick-Ag commented on packages/destination-actions/src/destinations/salesforce/index.ts
> +        description: 'Turn this on if you would like to oauth into a sandbox environment instead',
I think I'm just blind 🙈

2022-03-18 19:13 UTC, marinhero approved these changes

2022-03-18 20:36 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce/index.ts
> +      isSandbox: {
Do we need to regenerate types so this setting appears in the `Settings` interface?

2022-03-18 21:00 UTC, marinhero requested changes
Brennan is right, we need to regenerate the types here.

2022-03-19 04:39 UTC, mericsson commented on packages/destination-actions/src/destinations/salesforce/index.ts
> +        description: 'Turn this on if you would like to oauth into a sandbox environment instead.',
```suggestion
        description: 'Enable to authenticate into a sandbox instance.',
```

2022-03-21 16:37 UTC, marinhero approved these changes

2022-03-23 18:12 UTC, merged