Talon.One improve fields descriptions in `trackEvent` action
segmentio/action-destinations pull request #536
Opened 2022-03-23 09:41 UTC by kkupreeva

_A summary of your pull request, including the what change you're making and why._

Improve fields descriptions in `trackEvent` action

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-03-23 13:04 UTC, ArthurFlageul commented on packages/destination-actions/src/destinations/talon-one/trackEvent/index.ts
> +        'Extra attributes associated with the event. [See more details](https://docs.talon.one/docs/product/account/dev-tools/managing-attributes)',
😉 
```suggestion
        'Extra attributes associated with the event. [See more details](https://docs.talon.one/docs/product/account/dev-tools/managing-attributes).',
```

2022-03-23 13:22 UTC, ArthurFlageul approved these changes

2022-03-25 18:20 UTC, benhorowitz approved these changes

2022-03-28 09:53 UTC, kaatinga requested changes
This PR must be closed

2022-03-28 09:54 UTC, closed without merging