Stratconn 1260 - New Destination Action for Google Sheets
segmentio/action-destinations pull request #595
Opened 2022-05-19 18:37 UTC by rhall-twilio

### !!WIP!! 

This pull request covers a new DestinationAction for Google Sheets API. We are pushing the current changes to main to decrease the size of the final pull request.

### Completed
Create/Update

### Pending
Delete https://segment.atlassian.net/browse/STRATCONN-1380
Testcases https://segment.atlassian.net/browse/STRATCONN-1381
Forking of a1-notation external dependency https://segment.atlassian.net/browse/STRATCONN-1379
Limits on Google Spreadsheet size https://segment.atlassian.net/browse/STRATCONN-1375

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Testing Pending

2022-05-19 19:10 UTC, mericsson commented on packages/core/src/destination-kit/types.ts
> +  /** The input data in it's raw form without any transformations */
```suggestion
  /** The input data in its raw form without any transformations */
```

2022-05-19 19:11 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-sheets/googleapis/index.ts
> +      `https://sheets.googleapis.com/${API_VERSION}/spreadsheets/${mappingSettings.spreadsheetId}/values/${mappingSettings.spreadsheetName}!A:A`,
`A:A` should be parameter

2022-05-19 19:11 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-sheets/googleapis/index.ts
> +      `https://sheets.googleapis.com/${API_VERSION}/spreadsheets/${mappingSettings.spreadsheetId}/values/${mappingSettings.spreadsheetName}!A2:append?valueInputOption=${mappingSettings.dataFormat}`,
`A2` should also be a parameter

2022-05-19 19:42 UTC, dlasky commented on packages/core/src/destination-kit/types.ts
> +  readonly rawData?: InputData | InputData[]
I'm strongly opposed to allowing non mapped payloads. Once we allow this for partners we can never take it back, and it will generally encourage devs to ignore mappings in favor of non-transparent logic which is against some of the core principles of actions. Happy to discuss, but hopefully that makes sense.

2022-06-06 20:00 UTC, marinhero commented on packages/destination-actions/src/destinations/google-sheets/constants.ts
> +  MAX_CELLS: 300000
This is only used one time inside one file. What do you think about getting rid of the extra file and just leaving the constant close to the top?

2022-06-06 20:11 UTC, brennan commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +  defaultSubscription: 'type = "track" and event = "updated" or event = "new" or event = "deleted"',
I would caution against a default description with specific track event names—this may result in events flowing to Google Sheets that a customer does not intend.

2022-06-06 20:13 UTC, marinhero commented on packages/core/src/destination-kit/action.ts
> -      rawData: bundle.data,
Is this strictly necessary? What benefits will we be seeing from it? will it make debugging harder?

2022-06-06 20:19 UTC, marinhero commented on packages/destination-actions/src/destinations/google-sheets/generated-types.ts
> +export interface Settings {}
By reading the other actions files I can see that there are no settings but just want it to run it by you since everything seems to be operating according to mappingSettings. Right?

2022-06-06 20:27 UTC, marinhero commented on packages/destination-actions/src/destinations/google-sheets/postSheet/operations.ts
> +  updateBatch: { identifier: string; event: { [k: string]: string }; targetIndex: number }[],
Consider making a type for this instead as it's a bit hard to read.

```ts
type processUpdateBatchInputParams = {
...
}
```

2022-06-06 20:31 UTC, brennan commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +        'The way Google will interpret values. If you select raw, values will not be parsed and will be stored as-is. If you select user entered, values will be parsed as if you typed them into the U
Does Google have documentation describing `strings may be converted to numbers, dates, etc. following the same rules that are applied when entering text into a cell via the Google Sheets UI.`? If so, it may be nice to link to those here.

2022-06-06 20:31 UTC, brennan commented on packages/destination-actions/src/destinations/google-sheets/postSheet/operations.ts
> + * @example
I love this example. Thank you, @rhall-twilio!

2022-06-06 20:31 UTC, brennan commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +      default: { '@path': '$.__segment_id' }
It's not clear to me where `__segment_id` is assigned and/or used. Is this something we'll need in a future iteration of the integration?

2022-06-06 20:31 UTC, brennan commented on packages/destination-actions/src/destinations/google-sheets/postSheet/operations.ts
> +    spreadsheetId: events[0].spreadsheet_id,
I'd love to learn more about how we landed on this approach. This suggests that the pipeline is batching events based on a composite of event attributes `spreadsheetId`, `spreadsheetName`, and `dataFormat`, hence we would be able to simply look at the first event in the batch to infer these values for all subsequent events in the same batch.

As far as I understand, however, events are batched based on a `BatchKey`, which is a combination of the job's `Flow` attribute and the event's `Settings`: https://github.com/segmentio/integrations-consumer/blob/154e0481f7b4d4eadb432fd1fa75a36315ecaf8c/action_batch.go#L52-L53.

2022-06-06 20:31 UTC, marinhero commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +      ---
Do we need this?

2022-06-06 20:33 UTC, brennan commented on packages/destination-actions/src/destinations/index.ts
> +register('627ea052118e3cd530d28963', './google-sheets')
Should we sync the destination definition from stage to production now? Instruction are in step 2 under [this heading in Paper](https://paper.dropbox.com/doc/Destination-Actions-Interface--Bi97OHqmnYKZpOB4B3RWwQmkAg-BS1RKGj9VKTcjqLrCSuBV#:uid=217740603690332222029229&h2=How-to-deploy-new-Cloud-Destin).

2022-06-06 20:37 UTC, brennan requested changes
Thank you for all your work here, @rhall-twilio! I left a few comments/questions. One thing I would like to chat about soon is the best approach to `mappingSettings`.

2022-06-06 20:49 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-sheets/constants.ts
> +  MAX_CELLS: 300000
We originally had it as a constant on the top but ran into issues mocking it with jest. Exporting it in a different file is the only workaround we've found so far.

2022-06-06 20:52 UTC, rhall-twilio commented on packages/core/src/destination-kit/action.ts
> -      rawData: bundle.data,
Yes. Context for this change stems from this thread: https://github.com/segmentio/action-destinations/pull/595#discussion_r877470596

If we don't want to allow any action-destinations to take a dependency on it, then it should not be passed down to the aciton-destinations. I like the idea of doing it in a separate PR.

2022-06-06 20:52 UTC, rhall-twilio commented on yarn.lock
> +"@segment/a1-notation@^2.1.4":
This is a new package.

2022-06-06 20:53 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +      default: { '@path': '$.__segment_id' }
It's how RETL sources uniquely identify an event. We plan to make this field hidden and lock Google Sheets to only support RETL sources only in GA.

2022-06-06 20:59 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-sheets/postSheet/operations.ts
> +    spreadsheetId: events[0].spreadsheet_id,
The `spreadsheetId`, `spreadsheetName` and `dataFormat` are not part of the event payload. They are constants and are supplied by the user while setting up the action destination. In clean world, they would be part of the settings instead of the mappings, but because they may change per action instance, we opted to put them as mappings instead.

2022-06-06 21:01 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +      ---
Yes. This is how customer can specify which properties of the payload will be written to the Google Sheet, as well as what name they will appear as.

2022-06-06 21:02 UTC, marinhero commented on packages/destination-actions/src/destinations/google-sheets/constants.ts
> +  MAX_CELLS: 300000
Got it 👍

2022-06-06 21:03 UTC, marinhero commented on yarn.lock
> +"@segment/a1-notation@^2.1.4":
ooops! My bad

2022-06-06 21:11 UTC, brennan commented on packages/destination-actions/src/destinations/google-sheets/postSheet/operations.ts
> +    spreadsheetId: events[0].spreadsheet_id,
Makes sense - thanks for the clarification!

2022-06-06 21:40 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +  defaultSubscription: 'type = "track" and event = "updated" or event = "new" or event = "deleted"',
Should we just not have a defaultSubscription at all?

2022-06-06 21:59 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/index.ts
> +register('627ea052118e3cd530d28963', './google-sheets')
Isn't it from production to staging? @maryamsharif may have completed this step already.

2022-06-06 22:05 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +        'The way Google will interpret values. If you select raw, values will not be parsed and will be stored as-is. If you select user entered, values will be parsed as if you typed them into the U
I was not able to find additional extensive documentation but added some examples I found.

2022-06-06 22:51 UTC, brennan commented on packages/destination-actions/src/destinations/index.ts
> +register('627ea052118e3cd530d28963', './google-sheets')
Ah, you are right - we do sync from production to stage. But I do want to call out that Google Sheets in prod is out of sync with stage at the moment. The settings in stage AFAICT are the ones we eventually want in production. Here's what I see in prod currently:

<img width="1508" alt="Screen Shot 2022-06-06 at 3 50 45 PM" src="https://user-images.githubusercontent.com/11224497/172262130-fbb19d3e-e7fa-4a6c-a9bf-33613c879414.png">

2022-06-06 23:26 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/index.ts
> +register('627ea052118e3cd530d28963', './google-sheets')
This one is resolved by `./bin/run push` right?

2022-06-06 23:27 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-sheets/postSheet/operations.ts
> +  updateBatch: { identifier: string; event: { [k: string]: string }; targetIndex: number }[],
I added some types, that are not necessarily easier to read. :) Let me know if it's too contrived

2022-06-07 03:39 UTC, mericsson commented on packages/core/src/middleware/after-response/prepare-response.ts
> +  if (_options.skipResponseCloning) {
I think convention is if we are using a variable then it should no longer be `_options`. This convention comes from golang. https://stackoverflow.com/questions/27764421/what-is-underscore-comma-in-a-go-declaration

So you should rename `_options` to `options`.

2022-06-07 03:41 UTC, mericsson commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +        "Describes the nature of the operation being performed. Only supported values are 'new', 'updated', and 'deleted'.",
I guess we need some kind of a 'picklist' type to support this better.

2022-06-07 03:44 UTC, mericsson commented on packages/destination-actions/src/destinations/google-sheets/postSheet/index.ts
> +      On the right-hand side, select the field from your data model that maps to the given field in your sheet.
This looks good. Left vs Right consistent with Salesforce https://github.com/segmentio/action-destinations/blob/main/packages/destination-actions/src/destinations/salesforce/sf-properties.ts#L62-L64

2022-06-07 04:14 UTC, mericsson commented on packages/destination-actions/src/destinations/google-sheets/postSheet/operations.ts
> +  return await Promise.all(promises)
Confirming it's OK for these promises to be processed in parallel?

2022-06-13 16:31 UTC, brennan approved these changes

2022-06-13 16:46 UTC, brennan approved these changes

2022-06-13 17:57 UTC, mericsson commented on packages/core/src/middleware/after-response/prepare-response.ts
> +  if (_options.skipResponseCloning) {
Is `_options` guaranteed to be defined? Wonder if should do something like:

```suggestion
  if (_options && _options.skipResponseCloning) {
```

2022-06-13 17:57 UTC, mericsson commented on packages/destination-actions/package.json
> +    "coverageReporters": [
What will this do?

2022-06-13 18:14 UTC, rhall-twilio commented on packages/destination-actions/package.json
> +    "coverageReporters": [
This specifies how JEST should collect code coverage. 

The `.html` reporter creates a rendered page that shows code coverage details for user-readable consumption:
![image](https://user-images.githubusercontent.com/103517471/173417827-892cfb97-98c0-4d5e-8276-3f4525b43652.png)

The `lcov` reporter is the standard VSCode extensions use to show coverage (see left green/yellow markers in code)
![image](https://user-images.githubusercontent.com/103517471/173417991-45d1ed76-7542-437e-8288-e86ba6dc2059.png)

2022-06-13 18:16 UTC, rhall-twilio commented on packages/core/src/middleware/after-response/prepare-response.ts
> +  if (_options.skipResponseCloning) {
Does not seem that it can be undefined as per Typescript conventions:
![image](https://user-images.githubusercontent.com/103517471/173418391-e3641ac7-60f3-4ba9-8bb9-230cf53410ef.png)

2022-06-13 18:17 UTC, rhall-twilio commented on packages/core/src/middleware/after-response/prepare-response.ts
> +  if (_options.skipResponseCloning) {
^ Manually changing the type to `NormalizedOptions | undefined` results in this linting rule so this check is automated by the framework already 
![image](https://user-images.githubusercontent.com/103517471/173418561-63524ff1-d816-441b-a75d-51022c60d42b.png)

2022-06-13 18:46 UTC, mericsson commented on packages/destination-actions/package.json
> +    "coverageReporters": [
Cool, maybe worthwhile to have a README update as a follow-up or in this PR about how to use / access code coverage?

2022-06-13 18:47 UTC, mericsson approved these changes

2022-06-13 19:01 UTC, rhall-twilio commented on packages/destination-actions/package.json
> +    "coverageReporters": [
Added a note to myself to update README by end of week.

2022-06-13 19:02 UTC, merged