Snap Conversions API Destination
segmentio/action-destinations pull request #608
Opened 2022-05-25 20:31 UTC by rvadera12

_A summary of your pull request, including the what change you're making and why._

This PR adds the new action destination `Snap Conversions API`.  
More information is linked in the [SDD](https://paper.dropbox.com/doc/Snapchat-Conversions-API-SDD-IidrSXW4BL5rpdXYnhQVi) and [SPEC](https://paper.dropbox.com/doc/Snapchat-Conversions-API-Spec-JioOhY8lhoEsUenznGSd3).

## Testing

https://paper.dropbox.com/doc/Snap-Conversions-API-Testing--BiIcEKLA_qNhnysrv3t~Ni2oAg-CdMxX8HjRvMeGCVm8XDLO

- [x ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [x ] [Segmenters] Tested in the staging environment

2022-05-25 21:00 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
> +      nock(`https://tr.snapchat.com/v2/conversion`).post('').reply(200, {})
You might want to make this a global variable since it's used all over. `https://tr.snapchat.com/v2/conversion`

2022-05-25 21:20 UTC, marinhero requested changes
It looks good. Still, I do think we should clean up the test code plus address the comments in the integration code. Well done!

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
> +      const event = createTestEvent({
You should reuse a single object in your tests and use the destruct operator `...` to overwrite individual properties. That will make your tests easier to read and review.

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
> +      expect(responses.length).toBe(1)
I think you can remove this one as it's redundant. The line below will indirectly test this condition as well.

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
> +      expect(responses.length).toBe(1)
Same here

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
> +      expect(responses.length).toBe(1)
Same here

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/index.ts
> +const defaultVals = { ...defaultValues(reportConversionEvent.fields) }
add a line break here so `}` sits by itself below.

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/index.ts
> +/** Used in the Quick SetUp */
As a newcomer, I don't find this comment illustrative. What's the quick setup?  Why do we need this comment?

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/index.ts
> +      const res = await request<RefreshTokenResponse>('https://accounts.snapchat.com/login/oauth2/access_token', {
Move this into a constant at the top of the file.

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  description: 'Custom event label',
Missing `.` at the end

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +    'The Epoch timestamp for when the conversion happened.  The timestamp cannot be more than 28 days in the past',
Missing `.` at the end

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
> +    if (data.payload.event_conversion_type === 'MOBILE_APP') {
In general, you'd want to move hardcoded strings to constants so they are easier to spot and maintain. I recommend moving `MOBILE_APP` to one

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
> +    return request('https://tr.snapchat.com/v2/conversion', {
I'd apply the same principle regarding hardcoded strings here.

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +export const CURRENCY_ISO_CODES = new Set([
```suggestion
export const CURRENCY_ISO_4217_CODES = new Set([
```

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  label: 'Mobile Ad Indeentifier',
```suggestion
  label: 'Mobile Ad Identifier',
```

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  label: 'Indentifier for Vendor',
```suggestion
  label: 'Identifier for Vendor',
```

2022-05-25 21:20 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  label: 'IP Address',
Are we collecting this by default? Since it's PII we might want to not do that.

2022-05-31 14:50 UTC, rvadera12 commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  label: 'IP Address',
@kdaswani

2022-05-31 17:45 UTC, kdaswani commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  label: 'IP Address',
Good question! If a customer is using analytics.js, then yes we will collect ip automatically in `context.ip`. This has not been a concern before, and several integrations automatically map `context.ip` to the downstream tool. If a customer is using a server-side library, then we do not capture ip automatically. 

Snap doesn't want us to hash IP and recommends sending an IP, so I am in favor of keeping this as is with a default.

> IP address of the browser. It should be the public IP and not hashed. To increase the probability of matching website visitor events with TikTok ads, we recommend sending both IP address and User Agent.

We set a default for FB CAPI similar to this and have not had any issues/PII concerns flagged: https://github.com/segmentio/action-destinations/blob/main/packages/destination-actions/src/destinations/facebook-conversions-api/fb-capi-user-data.ts#L142

2022-05-31 18:02 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
> +      const event = createTestEvent({
```suggestion
const event = createTestEvent(testEvent)
```

2022-05-31 18:02 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
> +      const event = createTestEvent({
```suggestion
const event = createTestEvent(testEvent)
```

2022-05-31 18:03 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/_tests_/index.test.ts
> +      const event = createTestEvent({
This is the usage we want. You don't need to destruct the others since you are not overwriting anything

2022-05-31 18:06 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
> +const conversionEventUrl = 'https://tr.snapchat.com/v2/conversion'
Keep your globals capitalized like the one in line 32

2022-05-31 18:09 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/snap-capi-properties.ts
> +  description: 'International Article Number (EAN) when applicable, or other product or category identifier. ',
Remove the trailing whitespace.
```suggestion
  description: 'International Article Number (EAN) when applicable, or other product or category identifier.',
```

2022-05-31 18:17 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
> +        data.settings?.snap_app_id === undefined ||
Consider moving this into a method.

2022-05-31 18:18 UTC, marinhero commented on packages/destination-actions/src/destinations/snap-conversions-api/reportConversionEvent/index.ts
> +      if (
Move this block into its own function.

2022-05-31 20:03 UTC, marinhero approved these changes
Thank you for addressing the comments. :shipit:

2022-05-31 20:52 UTC, marinhero approved these changes

2022-05-31 20:56 UTC, merged