Ik/intercom actions
segmentio/action-destinations pull request #626
Opened 2022-06-13 22:01 UTC by ibbykhazanchi

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-07-20 18:28 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/index.ts
> +    //put settings on the Intercom object
Nit: I would delete this comment because it's clear from the code what's happening here. :)

2022-07-20 18:29 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/index.ts
> +import updateCompany from './updateCompany'
Nit on order and spacing:

```suggestion
import { Intercom } from './api'
import trackEvent from './trackEvent'
import updateUser from './updateUser'
import updateCompany from './updateCompany'
```

2022-07-20 18:34 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +  description: '',
Should we add a description?

2022-07-20 18:37 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateCompany/index.ts
> +        created_at: { '@path': '$.traits.createdAt' },
Should we default to `createdAt`, falling back to `created_at`?

2022-07-20 18:37 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateCompany/index.ts
> +        'selectively show the chat widget. According to Intercom’s docs, you want to first hide the Messenger for all users inside their UI using Messenger settings. Then think about how you want to
Capitalize "S" here.

2022-07-20 18:38 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +  description: '',
Should we add a description?

2022-07-20 18:39 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        '@path': '$.traits.firstName'
Should we fall back to `traits.first_name`?

2022-07-20 18:39 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        '@path': '$.traits.lastName'
Fall back to `traits.last_name`?

2022-07-20 18:40 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        '@path': '$.traits.unsubscribedFromEmails'
Because this field is not required, and it's not in Segment's event spec, I probably wouldn't put a default. https://segment.com/docs/connections/spec/

2022-07-20 18:40 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        '@path': '$.traits.languageOverride'
Same for this field - not in Segment's spec.

2022-07-20 18:41 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        '@path': '$.traits.createdAt'
Same for this field - not in Segment's spec.

2022-07-20 18:42 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +            '@path': '$.traits.avatar'
Not in Segment's spec.

2022-07-20 18:43 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        created_at: { '@path': '$.traits.company.createdAt' },
Should we fall back to `created_at`?

2022-07-20 18:44 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        monthly_spend: { '@path': '$.traits.company.monthlySpend' },
`monthly_spend` also isn't specced, but it might be strange UX if this is the only one of these fields without a default value.

2022-07-20 18:44 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +            created_at: { '@path': '$.createdAt' },
Should we fall back to `created_at`?

2022-07-20 18:45 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +            monthly_spend: { '@path': '$.monthlySpend' },
Should we fall back to `monthly_spend`?

2022-07-20 19:17 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/updateCompany/index.ts
> +        created_at: { '@path': '$.traits.createdAt' },
I think that's a good idea. Curious, do you know how these fallbacks appear in the UI?

2022-07-20 19:19 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateCompany/index.ts
> +        created_at: { '@path': '$.traits.createdAt' },
I'm actually not sure off the top of my head - would you have time to test and share? I'm curious, too. :) cc @nick-Ag 

Also created this ticket for the future: https://segment.atlassian.net/browse/STRATCONN-1544

2022-07-20 19:19 UTC, dlasky commented on packages/browser-destinations/src/destinations/intercom/updateCompany/index.ts
> +        created_at: { '@path': '$.traits.createdAt' },
if you use an `@if` directive they show up as a `coalesce function` in the UI, which has 2 args in this case, primary and fallback value.

2022-07-20 20:17 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        monthly_spend: { '@path': '$.traits.company.monthlySpend' },
Should I provide a fallback to `monthlySpend` here too?

2022-07-20 20:19 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        monthly_spend: { '@path': '$.traits.company.monthlySpend' },
And in general, should we provide fallbacks wherever there's a multi-word property in which there could be confusion between camelCase and snake_case

2022-07-20 21:59 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +            monthly_spend: { '@path': '$.monthlySpend' },
decided to remove mapping for monthly_spend as per 
https://github.com/segmentio/action-destinations/pull/682#discussion_r925955016

2022-07-20 22:00 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        monthly_spend: { '@path': '$.traits.company.monthlySpend' },
@ibbykhazanchi Yeah, I think that's a good rule of thumb. I don't think we're necessarily doing that right now in other integrations, but I think we should start doing so until we can get automatic fallbacks in place.

2022-07-21 19:53 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    description: 'The company id of the company.',
```suggestion
    description: 'The unique identifier of the company.',
```

2022-07-21 19:53 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    label: 'Company Id',
```suggestion
    label: 'Company ID',
```

2022-07-21 19:54 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    label: 'Created At',
```suggestion
    label: 'Company Creation Time',
```

2022-07-21 19:55 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    label: 'Created At',
Should we add the same default as cloud based on the group spec? https://github.com/segmentio/action-destinations/pull/682/files#r925846413

```
default: {
        '@path': '$.traits.createdAt'`
}
```

2022-07-21 19:56 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    description: 'The name of the plan the company is on.',
```suggestion
    description: 'The name of the plan you have associated with the company.',
```

2022-07-21 19:58 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    description: 'How much revenue the company generates for your business.',
```suggestion
    description: 'The monthly spend of the company, e.g. how much revenue the company generates for your business.',
```

2022-07-21 19:59 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    label: 'Size',
```suggestion
    label: 'Company size',
```

2022-07-21 20:00 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    description: 'The industry of the company.',
```suggestion
    description: 'The industry that the company operates in.',
```

2022-07-21 20:01 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    label: 'Website',
```suggestion
    label: 'Company Website',
```

2022-07-21 21:52 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    required: false
I would suggest adding:

`defaultObjectUI: 'keyvalue'`

Since we aren't assigning a default, might make sense to show customers that they can input separate key-value mappings. This was my suggestion for cloud too: https://github.com/segmentio/action-destinations/pull/682/files#r925997362

2022-07-21 21:53 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +  description: 'Track an event',
```suggestion
  description: 'Submit an event to Intercom.',
```

2022-07-21 22:17 UTC, pooyaj approved these changes
🚢🚢🚢

2022-07-21 22:31 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +    price: {
@ibbykhazanchi Is there a reason we have separate mappings for "price" and "currency"? I don't see these fields explicitly called out in the Javascript API docs: https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects

2022-07-21 23:03 UTC, kdaswani requested changes

2022-07-21 23:03 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/updateCompany/index.ts
> +        company_custom_traits: { '@path': '$.traits' }
Ah I now realize this might already be within an object and you probably can't have a key/value object in another object. Is this right?

2022-07-21 23:03 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        company_custom_traits: { '@path': '$.traits.company' }
I think we should remove this default for `company_custom_traits` otherwise we risk sending a whole bunch of stuff that is nested, invalid, etc. What do you think?

2022-07-21 23:03 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        'Selectively show the chat widget. According to Intercom’s docs, you want to first hide the Messenger for all users inside their UI using Messenger settings. Then think about how you want to
```suggestion
        'Selectively show the chat widget. As per [Intercom docs](https://www.intercom.com/help/en/articles/189-turn-off-show-or-hide-the-intercom-messenger), you want to first hide the Messenger for all users inside the Intercom UI using Messenger settings. Then think about how you want to programmatically decide which users you would like to show the widget to.',
```

2022-07-21 23:03 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +            company_custom_traits: { '@path': '$.' }
Remove this default?

2022-07-21 23:06 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +            monthly_spend: { '@path': '$.monthlySpend' },
@ibbykhazanchi we added the default back to maintain parity with the classic destination. Let's make the default `monthly_spend` for the files that send the company object. See here: https://github.com/segmentio/action-destinations/pull/682#discussion_r927148490. Sorry for the back and forth!

2022-07-22 18:12 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/sharedCompanyProperties.ts
> +    required: false
Yes! Agree this will be a better implementation. Users define their custom attributes

2022-07-22 18:39 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +    price: {
Looks like it doesn't need to be sent with the keyword "price", but a nested object is required to be properly formatted. 

As in, it must be sent like this:

`....
  <keyword> {
         amount: <your_amount_multiplied_by_100_since_intercom_requires_in_cents>
         currency:  <your_currency>
  }
`

2022-07-22 18:43 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +    price: {
Also, I think cloud-mode should include this too, because users will likely only send in`revenue` & `currency` without the proper formatting:

https://segment.com/docs/connections/spec/track/#properties

2022-07-22 18:50 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +    price: {
cc @NolanChan

I agree - we should make sure we give customers a way to map these fields if they are sending order data especially to give parity with the classic destination: https://segment.com/docs/connections/destinations/catalog/intercom/#revenue-and-currency. I think we should just have separate mappings for `Revenue` and `Currency` (not within an object in the mappings) and then when we construct the outgoing JSON payload, pop them into an object so that Intercom picks them up

2022-07-22 18:50 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +    price: {
^ @NolanChan can we add that to the cloud mode integration too?

2022-07-22 18:56 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +    price: {
I like that idea, it'll probably be more coherent to the user. 

Do you know what would be a good name to give to this object?

2022-07-22 19:02 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +      default: {
So for web, custom attributes don't need to be pre-created. However, I think it'll be better that way, and will make it consistent between web & cloud.

2022-07-22 19:03 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +    last_name: {
I personally find it overkill too, but It looks like something that was [supported in the classic destination](https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/intercom/test/index.test.js#L143-L170).

Not necessarily a reason to keep it, but what do you think?

2022-07-22 21:21 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +    price: {
Let's call it `price` based on the docs example and what we did in the classic integration to be safe.

`Revenue`
- type = number
- description = `The amount associated with a purchase. Segment will multiply by 100 as Intercom requires the amount in cents.`
- default = `properties.revenue`

`Currency`
- type = string
- description = `The currency of the purchase amount.`
- default = `properties.currency`

2022-07-22 21:23 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +    price: {
Let me know if that makes sense @ibbykhazanchi! We'll need to update some of the logic below to remove it from the `price` object and only set currency if revenue is provided.

2022-07-23 01:55 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +        type: {
agreed 100%.

2022-07-23 02:00 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +    price: {
Sounds good to me!

2022-07-25 16:57 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +      description: "The user's custom traits.",
@kdaswani, unlike server-side, the JS API technically doesn't require you to pre-create your custom attributes. It [says](https://www.intercom.com/help/en/articles/179-send-custom-user-attributes-to-intercom) you should use the dashboard to pre-create them, but it **doesn't throw an error** if you were to send a custom attribute at runtime, unlike the rest API.

2022-07-25 20:21 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +      description: "The user's custom traits.",
Oh great @ibbykhazanchi! Your update is perfect then

2022-07-25 20:21 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +    last_name: {
@ibbykhazanchi I think we should just keep `Name`. With classic, the separate ones were probably needed because we hardcode the mappings but with Actions if a customer uses first and last name fields they could just put both in the mapping and I believe we'd concatenate. Thoughts?

2022-07-25 22:05 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +      required: true,
Should this be `required: false` if the metadata are optional?

2022-07-25 22:14 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/updateUser/__tests__/index.test.ts
> +        tech: {
I know this is a test mapping, but I'm a little confused by this trait. Should it be `weight`?

2022-07-25 22:29 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +      }
Not a blocker, but the below may be very minutely more efficient because you don't have to create a new object and overwrite the existing one initialized on line 71.

```suggestion
      price.amount = payload.revenue * 100
      price.currency = payload.currency ?? 'USD'
```

2022-07-25 22:30 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +      required: true,
@ibbykhazanchi This is the only outstanding comment that I think would block approval/deploy to stage. Let me know what you think!

2022-07-25 22:44 UTC, kdaswani commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +      required: true,
Agree let's make this optional (remove requiredness)!

2022-07-26 16:26 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +      required: true,
Agree 100%

2022-07-26 16:39 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +      }
the only problem with this is that `amount` and `currency` dont exist on the type {}. 

I could define an interface `Price` that has keys `amount?` & `currency?`? And define `price` like:

const price : Price = {}

@brennan

2022-07-26 16:42 UTC, brennan commented on packages/browser-destinations/src/destinations/intercom/trackEvent/index.ts
> +      }
Makes sense - I would just ignore the comment, then, and let's move forward! 🚢

2022-07-26 16:42 UTC, brennan approved these changes

2022-07-26 18:16 UTC, ibbykhazanchi commented on packages/browser-destinations/src/destinations/intercom/updateUser/index.ts
> +    last_name: {
@kdaswani You're totally right. I tested out:

>  `     "name": {
>         "@template": "{{traits.firstName}} {{traits.lastName}}"
>       },`

which works! I will make remove the naming logic.

2022-07-26 21:32 UTC, kdaswani approved these changes
thank you for all your work on this @ibbykhazanchi !

2022-07-26 21:52 UTC, merged