BE-805 Intercom Cloud Action Destination - Identify + Group
segmentio/action-destinations pull request #627
Opened 2022-06-13 23:47 UTC by NolanChan

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-06-15 18:25 UTC, marinhero requested changes
Hey Nolan! Nice work on your first actions PR. Most of the comments are "Missing `.` at the end.`. Sorry for the spam about those but I think it's easier to keep track of them this way.
There are a few comments that are related to the API behavior and conventions. I'm interested in hearing your thoughts about those. Well done!

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/index.ts
> +    // testAuthentication: (request) => {
I think you can test your auth by hitting [this](https://developers.intercom.com/intercom-api-reference/reference/list-admins) endpoint. Should be the lightest of the ones available on Intercom's API.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/index.ts
> +    // refreshAccessToken: async (request, { auth }) => {
You can delete this. See [here](https://github.com/intercom/oauth2-intercom/blob/master/README.md#refreshing-a-token).

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: 'The role of the contact. Accepted values are `user` or `lead`. Can only be updated if `lead`',
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: 'A unique identifier generated outside Intercom',
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: "The user's email",
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: "The user's phone number",
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: "The user's name",
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: 'The timestamp when the contact was created',
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: 'The timestamp the user was last seen',
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: 'The id of an admin that has been assigned account ownership of the contact'
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: 'Whether the contact is unsubscribed from emails'
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      description: 'The custom attributes which are set for the contact',
Missing `.` at the end.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +import { ActionDefinition, ModifiedResponse, RequestClient, RetryableError } from '@segment/actions-core'
Regarding this file and action overall. I strongly believe we should addere to Intercom's naming convention. They have deprecated the use of the concept "User" in favor of "Contact" so I think we should replace it too.

https://developers.intercom.com/intercom-api-reference/reference/users

`:%s/User/Contact/g`
`:%s/user/contact/g`

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      // required if role=user and external_id is blank
The docs say this is an optional param in both scenarios.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +    // https://developers.intercom.com/intercom-api-reference/reference/create-contact
Tell me what am I going to find on these links and why you chose to include them here.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +  perform: async (request, { payload }) => {
How are you enforcing the "required" fields here? looks like the params are just coming thru and we are expecting the API to handle the rest (which is fine) but it'd be nice to see a `createRole` and a `createContact` here so we know what we'll be dealing with.

2022-06-15 18:25 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +    // Create a new intercom user; if it exists, then search for and update the user.
Wrap multi line comment in `/** */`

2022-06-15 23:06 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/groupIdentifyUser/index.ts
> +  description: 'Create or Update A Company',
Thanks for noting them! Will change

2022-06-15 23:19 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/index.ts
> +
Realized that there's no autoformatter for this :)

2022-06-15 23:20 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/index.ts
> +    // testAuthentication: (request) => {
Oh interesting! That's creative, I can do that

2022-06-15 23:23 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/index.ts
> +    // refreshAccessToken: async (request, { auth }) => {
woah! how'd you stumble upon that?

2022-06-15 23:26 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +import { ActionDefinition, ModifiedResponse, RequestClient, RetryableError } from '@segment/actions-core'
Got it, that makes sense! So just to be clear, you're saying that it'd be better to name the file/action `identifyContact`?

2022-06-15 23:30 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +import { ActionDefinition, ModifiedResponse, RequestClient, RetryableError } from '@segment/actions-core'
And I'll replace user -> contact !

2022-06-15 23:39 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +    // https://developers.intercom.com/intercom-api-reference/reference/create-contact
Would you say it's worthwhile to include the URL's here?

2022-06-16 18:00 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/index.ts
> +    // refreshAccessToken: async (request, { auth }) => {
I worked closely with Intercom before in a [previous life](https://www.intercom.com/app-store/apps/wootric) ;)

2022-06-16 18:01 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +import { ActionDefinition, ModifiedResponse, RequestClient, RetryableError } from '@segment/actions-core'
Yes, what do you think? They are using Contact for everything now so I think it's appropriate to rename files and variables accordingly.

2022-06-17 18:24 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +  perform: async (request, { payload }) => {
I'm currently not enforcing the required fields, I'm going to leave that to Intercom; however, I moved the comments into the attribute descriptions so that it'll be more explicit to the user :) 

I'm slightly confused about the purpose of the `createRole` and `createContact` methods? If I could ask for a bit more clarification :)

2022-06-17 21:00 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +  perform: async (request, { payload }) => {
You can disregard this comment since you are leaving everything to the API 👍

2022-06-17 21:43 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyUser/index.ts
> +      // required if role=user and external_id is blank
Thanks for catching this! It was a incorrectly duplicated comment

2022-06-17 22:22 UTC, NolanChan commented
Rerequesting review @marinhero , thank you for all the great comments!

2022-06-21 21:26 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +     * then it's possibly a cache issue, so we'll retry
```suggestion
     * then it's possibly due to a cache issue, so we'll retry
```

2022-06-21 21:27 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +     * Note: When creating a lead, it doesn't accept an external_id (?), but it accepts an email
Why the `(?)` ?

2022-06-21 21:41 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +      label: 'Custom Fields',
These are known as Custom Attributes by the Intercom API. Should we name them the same?

2022-06-21 23:06 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +      const response = await createIntercomContact(request, payload)
I think we can save a few HTTP calls here if we invert the order of operations. What do you think about performing the update first and then create? We know that Creates can only happen once and Updates can happen forever, if we attempt the operation that has more probability of success we'll consistently decrease the number of HTTP calls over time. What do you think?

2022-06-22 17:33 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +     * Note: When creating a lead, it doesn't accept an external_id (?), but it accepts an email
It's mainly because I was confused 😅 There's no indication in the API that `external_id` shouldn't work with `leads` but it just doesn't get properly accepted on creation.

2022-06-22 17:34 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +      label: 'Custom Fields',
That makes sense; Niels had called it custom fields, but I don't think there was a specific reason behind it

2022-06-22 17:35 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +      const response = await createIntercomContact(request, payload)
Marin and I had a convo about this over slack, and overall I think this is a good idea! I'll change it

2022-06-22 17:39 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +      const response = await createIntercomContact(request, payload)
This new way is actually possibly preferred; customers can theoretically create many leads with the same email, although in practice they may just want one that exists and updated continually 👍

2022-06-23 18:31 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +     * Note: When creating a lead, Intercom doesn't accept an external_id (?), it only accepts email
"When creating a lead, Intercom doesn't accept an external_id (possibly a bug), it only accepts email."

2022-06-23 18:33 UTC, marinhero commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +      if (contact) {
I think you can remove the `else` clause since `contact` will always be defined.
```suggestion
      if (contact) {
              return updateIntercomContact(request, contact.id, payload)
      }
      return await createIntercomContact(request, payload)
```

2022-06-23 21:06 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +     * Note: When creating a lead, Intercom doesn't accept an external_id (?), it only accepts email
that's definitely more clear 👍

2022-06-23 21:17 UTC, NolanChan commented on packages/destination-actions/src/destinations/intercom/identifyContact/index.ts
> +      if (contact) {
Discussed on slack - `searchIntercomContact` does return `undefined`, but we should get rid of the else regardless because explicit else cases are not helpful unless they provide value :)

2022-06-23 22:12 UTC, NolanChan commented
Added one more commit to register `Intercom` so I can start testing this on `staging`

2022-07-11 17:57 UTC, NolanChan commented
Sync is now complete, and staging + prod `Intercom (Actions)` has id `62b5f2f40b10eaace2e12b23`, so we should be good to go

2022-07-11 18:55 UTC, marinhero commented on packages/destination-actions/src/destinations/index.ts
> +register('62b5f2f40b10eaace2e12b23', './intercom')
ID matches the one in the DB ✅

2022-07-11 18:57 UTC, marinhero approved these changes

2022-07-11 19:27 UTC, merged