initial draft
segmentio/action-destinations pull request #689
Opened 2022-07-20 20:06 UTC by vikramkumar19

This Pull request Adds datadog metrics for personas messaging sendgrid action

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-07-20 20:12 UTC, lew-gordon requested changes
Looks good to me overall! I think we're capturing the right things. I just had some comments on the metrics' naming.

2022-07-20 20:12 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +    audience_id: {
This needs to be in the settings because the payload is well typed? It seems like we should just grab this from the event.

2022-07-20 20:12 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +      statsClient?.incr?.('te-sendgrid-notsubscribed', 1, tags)
What does the full metric look like here? Maybe it'd be better to represent the destination action name. For example, actions-personas-messaging-sendgrid?

2022-07-20 20:12 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +      if (response.status > 200 && response.status < 300) {
From what I've usually seen it's better to have a generic response metric and include the status code as a tag. I've even seen rough 2xx, 4xx, 5xx as another tag then you can generally decide how you want to display it in a dashboard.

2022-07-20 20:51 UTC, vikramkumar19 commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +      statsClient?.incr?.('te-sendgrid-notsubscribed', 1, tags)
full metric should like this `integration_actions.te-sendgrid-notsubscribed`

2022-07-20 21:28 UTC, vikramkumar19 commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +    audience_id: {
I believe we can only access events from payload. I am not sure if we can access events directly.

2022-07-21 15:46 UTC, lew-gordon approved these changes
LGTM! A few more comments on the metric naming that aren't really blocking and hopefully we can get clarity on the payload.

2022-07-21 15:46 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +      statsClient?.incr?.('actions-personas-messaging-sendgrid-send-disabled', 1, tags)
```suggestion
      statsClient?.incr?.('actions-personas-messaging-sendgrid.send-disabled', 1, tags)
```

2022-07-21 15:46 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +      statsClient?.incr?.('actions-personas-messaging-sendgrid-notsubscribed', 1, tags)
```suggestion
      statsClient?.incr?.('actions-personas-messaging-sendgrid.notsubscribed', 1, tags)
```

2022-07-21 15:46 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +      statsClient?.incr?.('actions-personas-messaging-sendgrid-subscribed', 1, tags)
```suggestion
      statsClient?.incr?.('actions-personas-messaging-sendgrid.subscribed', 1, tags)
```

2022-07-21 15:46 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +      statsClient?.incr?.('actions-personas-messaging-sendgrid-notsubscribed', 1, tags)
It also may be better to group this with subscribed and just have a tag for the status.

2022-07-21 15:46 UTC, lew-gordon commented on packages/destination-actions/src/destinations/personas-messaging-sendgrid/sendEmail/index.ts
> +      statsClient?.incr?.('actions-personas-messaging-sendgrid-response-statuscode', 1, tags)
```suggestion
      statsClient?.incr?.('actions-personas-messaging-sendgrid.response', 1, tags)
```

2022-08-02 20:29 UTC, marinhero approved these changes

2022-08-02 21:13 UTC, merged