Register Pardot (Actions)
segmentio/action-destinations pull request #699
Opened 2022-07-25 23:09 UTC by kwang122

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-07-27 00:17 UTC, marinhero requested changes
Move this to compare against the main branch and not the stage one

2022-08-04 19:44 UTC, kdaswani requested changes
great job @kwang122! added some small comments, but overall LGTM. 🎉

2022-08-04 19:44 UTC, kdaswani commented on packages/destination-actions/src/destinations/pardot/prospects/index.ts
> +  title: 'Prospect',
@kwang122 We should also add a default subscription of `identify`.

`defaultSubscription: 'type = "identify"',`

Here's an example in Salesforce (Actions): https://github.com/segmentio/action-destinations/blob/main/packages/destination-actions/src/destinations/salesforce/lead/index.ts#L20

2022-08-04 19:44 UTC, kdaswani commented on packages/destination-actions/src/destinations/pardot/prospects/index.ts
> +        Used to upsert prospect.  If multiple prospects have the given email, the prospect with the latest activity is updated. If there's no prospect with the given email, a prospect is created. Ple
```suggestion
        Used to upsert a prospect in Pardot. If multiple prospects have the given email, the prospect with the latest activity is updated. If there's no prospect with the given email, a prospect is created. Please note that Pardot treats email address as case sensitive and will create multiple prospects for casing differences.`,
```

2022-08-04 19:44 UTC, kdaswani commented on packages/destination-actions/src/destinations/pardot/pa-properties.ts
> +export const customFields: InputField = {
@kwang122 Since we only have one action, I wonder if we should just put this in the index.ts file for `upsert prospect`? Is there a reason we have it separated out? I know we do that for Salesforce (Actions), but that's because there are multiple actions to use the same field.

2022-08-04 19:44 UTC, kdaswani commented on packages/destination-actions/src/destinations/pardot/pa-properties.ts
> +export const customFields: InputField = {
cc @marinhero in case you have a preference one way or the other. It works this way but might be cleaner to not have it separated out?

2022-08-04 19:44 UTC, kdaswani commented on packages/destination-actions/src/destinations/pardot/index.ts
> +          'Enable to authenticate into a sandbox instance. You can log in to a sandbox by appending the sandbox name to your Salesforce username. For example, if a username for a production org is us
I think these were the instructions for Salesforce Sales Cloud sandboxes. Do we know it's the same instructions for Pardot sandboxes? 

I know our test account is a bit funky since it's a dev account with prod oauth and a sandbox api endpoint 😬  so it's probably not a good example of how to truly auth with a sandbox account.

2022-08-04 22:25 UTC, kdaswani commented on packages/destination-actions/src/destinations/pardot/index.ts
> +          'Enable to authenticate into a sandbox instance. You can log in to a sandbox by appending the sandbox name to your Salesforce username. For example, if a username for a production org is us
biggest thing to confirm - have we been able to test with a "true" sandbox account?

2022-08-05 00:40 UTC, kwang122 commented on packages/destination-actions/src/destinations/pardot/index.ts
> +          'Enable to authenticate into a sandbox instance. You can log in to a sandbox by appending the sandbox name to your Salesforce username. For example, if a username for a production org is us
It's the same instruction for Pardot since they both use the same Salesforce login endpoint. [Salesforce Sandbox Login](https://help.salesforce.com/s/articleView?id=sf.data_sandbox_create.htm&type=5) [Pardot Sandbox Instruction](https://help.salesforce.com/s/articleView?id=sf.pardot_sf_connector_sandbox.htm&type=5)

Unfortunately, we can not test with a "true" Sandbox account. Dev account does not allow the conversion to either Sandbox or Prod edition. Confirmed that Sandbox option does not exist in our Salesforce account.

2022-08-05 00:48 UTC, kwang122 commented on packages/destination-actions/src/destinations/pardot/prospects/index.ts
> +  title: 'Prospect',
That make sense. Just added!

2022-08-05 00:51 UTC, kwang122 commented on packages/destination-actions/src/destinations/pardot/pa-properties.ts
> +export const customFields: InputField = {
I was thinking maybe we'll add more actions in the future. It would be good to add some functionalities in the future.

2022-08-05 03:30 UTC, kdaswani commented on packages/destination-actions/src/destinations/pardot/pa-properties.ts
> +export const customFields: InputField = {
Makes sense! Good thinking. Let's leave it like this in case we do add more actions in the future 😄

2022-08-05 03:31 UTC, kdaswani commented on packages/destination-actions/src/destinations/pardot/index.ts
> +          'Enable to authenticate into a sandbox instance. You can log in to a sandbox by appending the sandbox name to your Salesforce username. For example, if a username for a production org is us
sounds good! We can always rely on an early beta tester to confirm the sandbox functionality is working correctly.

2022-08-05 03:33 UTC, kdaswani commented on packages/destination-actions/src/destinations/pardot/prospects/index.ts
> +  title: 'Prospect',
@kwang122 Can we also update the name of this action to `Upsert Prospect`?

```suggestion
  title: 'Upsert Prospect',
```

2022-09-01 23:55 UTC, closed without merging