[] Scaffold SFMC
segmentio/action-destinations pull request #704
Opened 2022-07-28 21:41 UTC by rvadera12

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-10-17 20:12 UTC, kdaswani reviewed
This looks great @rvadera12! Added super small suggestions but otherwise looking really good. Thanks!

2022-10-17 20:12 UTC, kdaswani commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/index.ts
> +          'The unique subdomain Salesforce Marketing Cloud assigned to your account. Subdomains are tenant specific and should be a 28-character string starting with the letters "mc". Do not include
```suggestion
          'The unique subdomain Salesforce Marketing Cloud assigned to your account. Subdomains are tenant specific and should be a 28-character string starting with the letters "mc". Do not include the .rest.marketingcloudapis.com part of your subdomain URL. See more information on how to find your subdomain [here](https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/your-subdomain-tenant-specific-endpoints.html).',
```

2022-10-17 20:12 UTC, kdaswani commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
> +    'The primary key(s) that uniquely identify a contact in the data extension. At a minimum, Contact Key must exist in your data extension as a Primary Key.On the left-hand side, input the SFMC key
```suggestion
    'The primary key(s) that uniquely identify a contact in the data extension. At a minimum, Contact Key must exist in your data extension as a Primary Key. On the left-hand side, input the SFMC key name. On the right-hand side, map the Segment field that contains the corresponding value. When multiple primary keys are provided, SFMC will update an existing row if all primary keys match, otherwise a new row will be created.',
```

2022-10-17 20:12 UTC, kdaswani commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
> +    'The fields in the data extension that contain data about a contact, such as Email, Last Name, etc. Fields must be created in the data extension before sending data for it.On the left-hand side,
```suggestion
    'The fields in the data extension that contain data about a contact, such as Email, Last Name, etc. Fields must be created in the data extension before sending data for it. On the left-hand side, input the SFMC field name exactly how it appears in the data extension. On the right-hand side, map the Segment field that contains the corresponding value.',
```

2022-10-17 20:12 UTC, kdaswani commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
> +    'The properties of the event. Fields must be created in the event definition schema before sending data for it.On the left-hand side, input the SFMC field name exactly how it appears in the event
```suggestion
    'The properties of the event. Fields must be created in the event definition schema before sending data for it. On the left-hand side, input the SFMC field name exactly how it appears in the event definition schema. On the right-hand side, map the Segment field that contains the corresponding value.',
```

2022-10-17 20:12 UTC, kdaswani commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
> +  label: 'Enable Batching',
```suggestion
  label: 'Batch data to SFMC',
```

2022-10-17 20:12 UTC, kdaswani commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
> +  description: 'If true, data is batched before sending to the SFMC Data Extension to help reduce API calls.',
```suggestion
  description: 'If true, data is batched before sending to the SFMC Data Extension.',
```

2022-10-24 22:59 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/index.ts
> +        type: 'string',
maybe type: 'password' ?

2022-10-24 23:00 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/index.ts
> +    refreshAccessToken: async (request, { settings }) => {
How are we preventing the initial UI connect flow from showing?

2022-10-24 23:04 UTC, rvadera12 commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/index.ts
> +    refreshAccessToken: async (request, { settings }) => {
@rhall-twilio The initial UI connect flow only shows up once you expose it in app here: https://github.com/segmentio/app/blob/master/client/lib/utils/oauth.ts

2022-10-24 23:22 UTC, LLuque-twilio approved these changes
lgtm 🪄🚀

2022-10-24 23:22 UTC, LLuque-twilio commented on packages/destination-actions/src/destinations/index.ts
> +register('62e30bad99f1bfb98ee8ce08', './salesforce-marketing-cloud')
Matches id found in partner portal `62e30bad99f1bfb98ee8ce08`

https://app.segment.com/partner-portal/integration/actions-salesforce-marketing-cloud/profile

2022-10-25 00:24 UTC, maryamsharif approved these changes
Just left one question, otherwise looks good to me! Great job! 🚀

2022-10-25 00:24 UTC, maryamsharif commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/contact/index.ts
> +        attributeSets: []
why is there an empty list sent with the request? is this required?

2022-10-25 03:47 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/index.ts
> +    refreshAccessToken: async (request, { settings }) => {
Should we have a `testAuthentication` method to validate customers' credentials?

2022-10-25 04:14 UTC, brennan requested changes

2022-10-25 04:14 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/contactDataExtension.test.ts
> +  properties: {
A Segment `identify` wouldn't have a `properties` object: https://segment.com/docs/connections/spec/identify/

2022-10-25 04:14 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/contactDataExtension.test.ts
> +const event = createTestEvent(testEvent)
Does `createTestEvent` need to be called twice?

2022-10-25 04:14 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/dataExtension.test.ts
> +const event = createTestEvent(testEvent)
Does `createTestEvent` need to be called twice?

2022-10-25 04:14 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/dataExtension.test.ts
> +  timestamp: timestamp,
What event `type` is this? Obviously a `type` is not strictly required required, but I think it's helpful to create test events that follow the Segment spec.

2022-10-25 04:14 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/apiEvent.test.ts
> +const event = createTestEvent(testEvent)
Do we need to call `createTestEvent` twice?

2022-10-25 04:14 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/apiEvent.test.ts
> +  timestamp: timestamp,
What is the `type` of this event?

2022-10-25 04:14 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/apiEvent.test.ts
> +    it('Fail to send api event due to missing required fields -> contactKey & eventDefinitionKey', async () => {
Nit and optional update - I usually write test descriptions in the present tense so it reads like a sentence when printed out during a test run:

```suggestion
    it('fails to send api event due to missing required fields -> contactKey & eventDefinitionKey', async () => {
```

2022-10-25 04:14 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/index.ts
> +const destination: DestinationDefinition<Settings> = {
I think we should add unit tests for the destination definition. You should actually be able to generate these using the `snapshot` tool: https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#snapshot-testing

2022-10-25 04:15 UTC, brennan commented
@rvadera12 Great job on a touch destination. We're close! 🚀

2022-10-25 05:01 UTC, rvadera12 commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/dataExtension.test.ts
> +  timestamp: timestamp,
Added the type: 'track'

2022-10-25 05:03 UTC, rvadera12 commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/apiEvent/index.ts
> +      method: 'post',
Updated all the requests to `POST`

2022-10-25 05:11 UTC, rvadera12 commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/contact/index.ts
> +        attributeSets: []
@maryamsharif passing `attributeSets` is required for the `/contacts` endpoint. Our plan is to pass an empty object, and advise customers in our docs to pass traits/attributes to a Data Extension, i.e. the `Contact Data Extension Action`. 
The [classic destination](https://github.com/segmentio/integrations/blob/master/integrations/salesforce-marketing-cloud/lib/index.js#L243) also used this strategy. 
Let me know if you have any more questions/concerns about this, happy to chat more!

2022-10-25 05:37 UTC, rvadera12 commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/_tests_/apiEvent.test.ts
> +  timestamp: timestamp,
added type: 'track'

2022-10-25 17:41 UTC, rvadera12 commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/index.ts
> +    refreshAccessToken: async (request, { settings }) => {
Discussed with Kiara, and decided currently the SFMC responses are adequate for beta. I have added screenshots of the responses in the testing doc [here](https://paper.dropbox.com/doc/Salesforce-Marketing-Cloud-Actions-Testing--BrtNtxxMSb6NBQ4GoKfn5Oj9Ag-JIr4CZaYBKcfmeNwsap8i#:h2=TODO---JIRA-TICKET). I will make a ticket to keep track of this to be done before GA.

2022-10-25 18:39 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
> +import { Payload } from './dataExtension/generated-types'
Looks like the `dataExtension` action and `contactDataExtension` action both call `upsertRows` but have different `Payload` type definitions. Here, we should consider merging the `Payload` interface definitions: https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces

Or, alternatively, declaring a new interface type.

2022-10-25 18:58 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
> +}
Nit/not a blocker: Spacing is inconsistent in this file and others. Time permitting, I would add a space between blocks of code.

2022-10-25 19:01 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
> +  default: false
Should we default to `true` since we built with RETL in mind?

2022-10-25 19:08 UTC, rvadera12 commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
> +  default: false
@kdaswani going to default to you, but from my understanding we are defaulting it to `false` for non RETL use cases and asking the RETL customers/team to turn on batching

2022-10-25 19:35 UTC, kdaswani commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-properties.ts
> +  default: false
great question! let's leave as false for now so we have parity with SFMC classic (where batching is disable by default). we can instruct RETL to tell their pilot customers to set this to `true` upon configuration. if we see most customers setting to `true` and/or issues with RETL not setting to `true`, we can reconsider the default value

2022-10-25 20:00 UTC, brennan commented on packages/destination-actions/src/destinations/salesforce-marketing-cloud/sfmc-operations.ts
> +import { Payload as payload_dataExtension } from './dataExtension/generated-types'
Could probably just do something like this instead:

```
import { Payload as payload_dataExtension } from './dataExtension/generated-types'
import { Payload as payload_contactDataExtension } from './contactDataExtension/generated-types'

export function upsertRows(request: RequestClient, subdomain: String, payloads: payload_dataExtension[] | payload_contactDataExtension[]) {
```

2022-10-25 22:21 UTC, brennan approved these changes

2022-10-26 15:24 UTC, merged