[STRATCONN 1413]
segmentio/action-destinations pull request #725
Opened 2022-08-10 22:16 UTC by maryamsharif

_A summary of your pull request, including the what change you're making and why._

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-08-19 00:42 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +        'GA4 does not accept null, array, or nested values for event parameters and item parameters. Please ensure you are using allowed data types.',
Is this supposed to check for null value?

2022-08-19 20:36 UTC, marinhero commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +        'GA4 does not accept null, array, or nested values for event parameters and item parameters. Please ensure you are using allowed data types.',
Does `nested` equals to `object` in this case or should we include `object` in the error message as well?

2022-08-19 20:41 UTC, marinhero commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +    if (typeof value == 'object' || value instanceof Array) {
nit:
```suggestion
const invalidEventType = typeof value == 'object' || value instanceof Array
    if (invalidEventType) {
```

2022-08-19 20:50 UTC, marinhero commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +    // typeof null == 'object' and GA4 accepts nulls for user_properties
Can you reword this statement? As a potential maintainer, I don't quite follow its meaning.

2022-08-19 21:35 UTC, maryamsharif commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +        'GA4 does not accept null, array, or nested values for event parameters and item parameters. Please ensure you are using allowed data types.',
In javascript the type of a null value evaluates to "object" so the check does include not allowing null values!

2022-08-19 21:37 UTC, maryamsharif commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +        'GA4 does not accept null, array, or nested values for event parameters and item parameters. Please ensure you are using allowed data types.',
yeah we are referring to objects when we say nested maybe we should say object instead of nested? @kdaswani

2022-08-19 21:38 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +        'GA4 does not accept null, array, or nested values for event parameters and item parameters. Please ensure you are using allowed data types.',
Can we confirm that if the user passes null, it will arrive here as null instead of undefined?

2022-08-21 00:18 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +        'GA4 does not accept null, array, or nested values for event parameters and item parameters. Please ensure you are using allowed data types.',
yup fine by me to change the wording to:

```suggestion
        'GA4 does not accept null, array, or object values for event parameters and item parameters. Please ensure you are using allowed data types.',
```

2022-08-24 18:17 UTC, maryamsharif commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +        'GA4 does not accept null, array, or nested values for event parameters and item parameters. Please ensure you are using allowed data types.',
yes it arrives as null and not undefined

2022-08-25 19:42 UTC, rhall-twilio commented
Let's make sure we update the Insomnia test cases to include a boolean somewhere before shipping.

2022-08-25 19:43 UTC, rhall-twilio requested changes

2022-08-25 19:43 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +    const invalidEventType = typeof value == 'object' || value instanceof Array
Is there a reason we're doing this here but not below as well?

2022-08-29 23:28 UTC, rhall-twilio commented on packages/destination-actions/src/destinations/google-analytics-4/ga4-functions.ts
> +        `Param [${key}] has unsupported value. GA4 does not accept array values for event parameters and item parameters.`,
We should also include the type of the unsupported parameter.

2022-08-30 15:51 UTC, rhall-twilio approved these changes

2022-08-31 00:12 UTC, merged