[STRATCONN-1595]Update Action descriptions in Salesforce (Actions)
segmentio/action-destinations pull request #731
Opened 2022-08-19 17:06 UTC by kwang122

Jira Ticket: https://segment.atlassian.net/browse/STRATCONN-1595
New Description: https://paper.dropbox.com/doc/Salesforce-Actions-Action-Description-Renames-08102022--BnByRkoPMcciQ1434Y_0SUrHAg-ySvDtvlfsk0gYid5XdxpI

This PR updates action descriptions for Salesforce(Actions), this update makes it clearer about what each action does.

## Testing

No testing required as this is only a description change.

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-08-19 17:26 UTC, marinhero requested changes
Don't you need to `bin/run generate:types` here too so the description on the type files is updated too?

2022-08-19 17:36 UTC, kwang122 commented
> Don't you need to `bin/run generate:types` here too so the description on the type files is updated too?

@marinhero The update is not necessary since it's the actions' description. `bin/run generate:types` won't update anything.

2022-08-19 17:51 UTC, marinhero approved these changes

2022-08-22 16:44 UTC, kdaswani requested changes
Made some super small changes - sorry for only catching/changing these now. I updated the paper doc too: https://paper.dropbox.com/doc/Salesforce-Actions-Action-Description-Renames-08102022--BnsbOFmCnEfEuYhCXXqTHeCtAg-ySvDtvlfsk0gYid5XdxpI. Thanks @kwang122 @marinhero!

2022-08-22 16:44 UTC, kdaswani commented on packages/destination-actions/src/destinations/salesforce/customObject/index.ts
> +  description: 'Create, update, or upsert records in a custom object in Salesforce.',
Making a small change since technically this action can support other standard objects too. thanks Kevin!

```suggestion
  description: 'Create, update, or upsert records in any custom or standard object in Salesforce.',
```

2022-08-22 16:44 UTC, kdaswani commented on packages/destination-actions/src/destinations/salesforce/lead/index.ts
> +  description: 'Create, update, or upsert prospects in Salesforce.',
```suggestion
  description: 'Create, update, or upsert leads in Salesforce.',
```

2022-08-22 16:58 UTC, kwang122 commented
> Made some super small changes - sorry for only catching/changing these now. I updated the paper doc too: https://paper.dropbox.com/doc/Salesforce-Actions-Action-Description-Renames-08102022--BnsbOFmCnEfEuYhCXXqTHeCtAg-ySvDtvlfsk0gYid5XdxpI. Thanks @kwang122 @marinhero!

No worries, just updated!

2022-08-22 16:59 UTC, kdaswani approved these changes
thank you!

2022-08-31 17:57 UTC, merged