STRATCONN-1438 : Google Ads Conversions
segmentio/action-destinations pull request #772
Opened 2022-09-19 19:13 UTC by maryamsharif

This PR is adding new actions to the Google Enhanced Conversions destination. 

[SDD](https://paper.dropbox.com/doc/Google-SDD-Google-Ads-Conversions-Actions--BpR_qq6VlL1Zrtc2~~AIf6HrAg-oEJgQ4cQ0aEgHpuRFB5dR) 

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-09-21 00:27 UTC, kdaswani requested changes
This looks great! Thanks @maryamsharif! I added some comments - mostly small changes to the descriptions or defaults, but had a few questions as well.

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +          else: { '@path': '$context.traits.email' }
```suggestion
          else: { '@path': '$.context.traits.email' }
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +          else: { '@path': '$context.traits.phone' }
```suggestion
          else: { '@path': '$.context.traits.phone' }
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +        'The order ID associated with the conversion. An order id can only be used for one conversion per conversion action.',
```suggestion
        'The order ID associated with the conversion. An order ID can only be used for one conversion per conversion action.',
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +      description: 'The environment this conversion was recorded on. e.g. App or Web.',
```suggestion
      description: 'The environment this conversion was recorded on, e.g. APP or WEB.',
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +        { label: `UNSPECIFIED`, value: 'UNSPECIFIED' }
```suggestion
        { label: 'UNSPECIFIED', value: 'UNSPECIFIED' }
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +        '@path': '$.properties.orderId'
I wonder if we should make this a coalesce of `$.properties.orderId` and `$.properties.order_id` in case some customers use snake case instead. Can we update to that?

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +        'The custom variables associated with this conversion. On the left-hand side, input the name of the custom variable as it appears in your Google Ads account. On the right-hand side, map the S
```suggestion
        'The custom variables associated with this conversion. On the left-hand side, input the name of the custom variable as it appears in your Google Ads account. On the right-hand side, map the Segment field that contains the corresponding value See [Google’s documentation on how to create custom conversion variables](https://developers.google.com/google-ads/api/docs/conversions/conversion-custom-variables). ',
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +        'Customer id is required for this action. Please set it in destination settings.',
```suggestion
        'Customer ID is required for this action. Please set it in destination settings.',
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +        'The ID of the conversion action associated with this conversion. To find the Conversion Action ID, click on your conversion in Google Ads and get the value for ctId in the URL. For example,
```suggestion
        "The ID of the conversion action associated with this conversion. To find the Conversion Action ID, click on your conversion in Google Ads and get the value for `ctId` in the URL. For example, if the URL is `https://ads.google.com/aw/conversions/detail?ocid=00000000&ctId=570000000`, your Conversion Action ID is `570000000`."
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +      description: 'The adjustment type. See Google’s documentation for details on each type.',
```suggestion
      description: 'The adjustment type. See [Google’s documentation](https://developers.google.com/google-ads/api/reference/rpc/v11/ConversionAdjustmentTypeEnum.ConversionAdjustmentType) for details on each type.',
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +        'The date time at which the adjustment occurred. Must be after the conversion_date_time. The timezone must be specified. The format is "yyyy-mm-dd hh:mm:ss+|-hh:mm", e.g. "2019-01-01 12:32:45
```suggestion
        'The date time at which the adjustment occurred. Must be after the conversion timestamp. The timezone must be specified. The format is "yyyy-mm-dd hh:mm:ss+|-hh:mm", e.g. "2019-01-01 12:32:45-08:00".',
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +          else: { '@path': '$context.traits.email' }
```suggestion
          else: { '@path': '$.context.traits.email' }
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +          else: { '@path': '$context.traits.phone' }
```suggestion
          else: { '@path': '$.context.traits.phone' }
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +          else: { '@path': '$context.traits.firstName' }
```suggestion
          else: { '@path': '$.context.traits.firstName' }
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +          else: { '@path': '$context.traits.lastName' }
```suggestion
          else: { '@path': '$.context.traits.lastName' }
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +        '@path': '$.properties.orderId'
I wonder if we should make this a coalesce of `$.properties.orderId` and `$.properties.order_id` in case some customers use snake case instead. Can we update to that?

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +      default: ''
Same thing on this file regarding empty strings for defaults. I think we can just remove default from the field definition if there's not one set.

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +        'The currency of the restated value. If not provided, then the default currency from the conversion action is used, and if that is not set then the account currency is used. This is the ISO 4
```suggestion
        'The currency of the restated value. If not provided, then the default currency from the conversion action is used, and if that is not set then the account currency is used. This is the ISO 4217 3-character currency code, e.g. USD or EUR.',
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +        'Customer id is required for this action. Please set it in destination settings.',
```suggestion
        'Customer ID is required for this action. Please set it in destination settings.',
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +      throw new IntegrationError('Order id required for enhancement conversion', 'INVALID_ARGUMENT', 400)
```suggestion
      throw new IntegrationError('Order ID required for enhancements', 'INVALID_ARGUMENT', 400)
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +        throw new IntegrationError('Gclid required for chosen conversion type', 'INVALID_ARGUMENT', 400)
```suggestion
        throw new IntegrationError('GCLID required for chosen conversion type', 'INVALID_ARGUMENT', 400)
```

2022-09-21 00:27 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +        throw new IntegrationError('Restatement value required for restatement conversion', 'INVALID_ARGUMENT', 400)
```suggestion
        throw new IntegrationError('Restatement value required for restatements', 'INVALID_ARGUMENT', 400)
```

2022-09-21 22:23 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
> +          'You will find this information in the event snippet for your conversion action, for example `send_to: AW-CONVERSION_ID/AW-CONVERSION_LABEL`. In the sample snippet, AW-CONVERSION_ID stands
Let's add this line after we are public: **Required if you are using a mapping that sends data to the legacy Google Enhanced Conversions API.**

2022-09-21 22:28 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts
> +      defaultObjectUI: 'keyvalue'
let's also do this for uploadClickConversion custom variables

2022-09-21 22:29 UTC, kdaswani commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadClickConversion/index.ts
> +        'The custom variables associated with this conversion. On the left-hand side, input the name of the custom variable as it appears in your Google Ads account. On the right-hand side, map the S
change to keyvalue:only

2022-09-22 19:41 UTC, maryamsharif commented on packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
> +      customerId: {
I am pretty sure we can, will double check!

2022-09-23 17:24 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/index.ts
> -      searchParams: {
Nice cleanup! I see you moved this to `postConversion` since it's only used there.

2022-09-23 18:20 UTC, marinhero requested changes
Looks pretty good! I'm leaving a few comments to make the code  DRY-er but the overall structure of the actions look 💯 . Well done!

2022-09-23 18:20 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +    settings.customerId = settings.customerId.replace(/[^0-9.]+/g, '')
Same comment that I left for `uploadCallConversion` applies here.

2022-09-23 18:20 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +      payload.first_name ||
```ts
const containsAddressInfo = 
      payload.first_name ||
      payload.last_name ||
      payload.city ||
      payload.state ||
      payload.country ||
      payload.postal_code ||
      payload.street_address

if (containsAddressInfo) {
      request_object.userIdentifiers.push({
        ...
}
```

2022-09-23 18:20 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +    if (typeof response.data === 'object' && response.data != null) {
Same comment that I left for `uploadCallConversion` applies here.

2022-09-23 19:09 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadConversionAdjustment/index.ts
> +    if (payload.adjustment_type == 'ENHANCEMENT' && !payload.order_id) {
Consider changing this forest of `if` into a clearer switch statement or a dynamic validation like this one:

```ts
type Payload = {
  adjustment_type: string
  order_id: number
}

// const payload: Payload = {
//   adjustment_type: 'ENHANCEMENT',
//   order_id: undefined
// }

const payload: Payload = {
  adjustment_type: 'RESTATEMENT',
  order_id: 42
}

const validations = {
  enhancement: {
    validation: (payload) => !!payload.order_id,
    error: {
      message: 'Order ID required for enhancements', 
      code: 400,
      type: 'INVALID_ARGUMENT'
    }
  },
  restatement: {
    validation: (payload) => !!payload.restatement_value,
    error: {
      message: 'Restatement value required for restatements', 
      code: 400,
      type: 'INVALID_ARGUMENT'
    }
  }
}

const key = payload.adjustment_type.toLocaleLowerCase()
const op = validations[key]

if (!op.validation(payload)) {
  console.log(op.error)
} else {
  console.log('GOOD!')
}

```

2022-09-26 22:03 UTC, maryamsharif commented on packages/destination-actions/src/destinations/google-enhanced-conversions/uploadCallConversion/index.ts
> +      type: 'string'
There is no default for this field. See PRD/Spec https://paper.dropbox.com/doc/Google-PRDSpec-Google-Ads-Conversions--Bp7hxJCZtIdf7ok6e8u76z_vAg-FKiSd9xMs9UB5hZs1ZXuu#:h2=Upload-Call-Conversion

2022-10-05 18:16 UTC, marinhero approved these changes
These comments are non-blocking and should not prevent you from releasing this. Keep track of them and address them later.

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadCallConversion.test.ts
> +    it('should send an event with default mappings', async () => {
```suggestion
    it('sends an event with default mappings', async () => {
```

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadCallConversion.test.ts
> +    it('should map custom variables correctly', async () => {
```suggestion
    it('maps custom variables correctly', async () => {
```

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadCallConversion.test.ts
> +    it('should fail if customerId not set', async () => {
```suggestion
    it('fails if customerId not set', async () => {
```

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
> +    it('should send an event with default mappings', async () => {
```suggestion
    it('sends an event with default mappings', async () => {
```

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
> +    it('should send email and phone user_identifiers', async () => {
```suggestion
    it('sends email and phone user_identifiers', async () => {
```

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
> +    it('should correctly map custom variables', async () => {
```suggestion
    it('correctly maps custom variables', async () => {
```

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
> +    it('should fail if customerId not set', async () => {
```suggestion
    it('fails if customerId not set', async () => {
```

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadClickConversion.test.ts
> +        fail('the test should have thrown an error')
```suggestion
        fail('The test should have thrown an error')
```

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/__tests__/uploadConversionAdjustment.test.ts
> +import nock from 'nock'
Nit: remove the "should" from the tests. You want your test descriptions to be precise about their behavior.

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
> +    return undefined
Why `undefined` and not an empty object? That would simplify the function signature

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
> +  if (value === undefined) return
```suggestion
  if (value === undefined) {
    return
  }
```

2022-10-05 18:16 UTC, marinhero commented on packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
> +export const hash = (value: string | undefined): string | undefined => {
Consider this instead to simplify the code and usage of this function.

`export const hash = (value: string | undefined): string => {`

2022-10-05 19:03 UTC, maryamsharif commented on packages/destination-actions/src/destinations/google-enhanced-conversions/functions.ts
> +export const hash = (value: string | undefined): string | undefined => {
this wouldn't allow me to return undefined if the variable is not actually in the payload

2022-10-05 19:24 UTC, kdaswani approved these changes

2022-10-05 19:26 UTC, merged