Heap 34916
segmentio/action-destinations pull request #787
Opened 2022-09-28 23:34 UTC by murphpdx

_A summary of your pull request, including the what change you're making and why._
- We've added session_id to our payload, we would like customers to be able to pass this parameter in to track user sessions. We will eventually use this with a mobile extension. 
- I've updated the segment library for tracking purposes on our end. 

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [ ] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-09-30 18:21 UTC, nick-Ag commented on packages/browser-destinations/src/destinations/heap/constants.ts
> +export const HEAP_SEGMENT_LIBRARY_NAME = 'browser-destination'
Nit: Maybe rename the two `HEAP_SEGMENT_LIBRARY_NAME` constants to be distinct from each other

2022-10-05 00:11 UTC, zikaari requested changes
Looks good. Please remove console.log statements

2022-10-24 14:19 UTC, jinapark202 approved these changes

2022-10-24 17:51 UTC, jinapark202 commented
@murphpdx I think you may need to update your snapshot tests as they are failing

2022-10-31 17:21 UTC, brennan commented
@murphpdx Quick reminder to please fix the unit tests in this integration - they we can review, approve, and merge! Once fixed, we'll deploy as part of our next release (Nov. 16) after the current change freeze.

2022-12-05 18:58 UTC, dlasky commented
@murphpdx just checking back in here, are we still looking to merge these changes? Looks like nothing has changed on the testing front?

2023-01-17 21:40 UTC, murphpdx commented
> @murphpdx just checking back in here, are we still looking to merge these changes? Looks like nothing has changed on the testing front?

Looks like I lost track of this one. I updated it, I think it's ready to go now?

2023-01-20 01:01 UTC, pooyaj approved these changes

2023-01-23 18:42 UTC, murphpdx commented
Hi @pooyaj @zikaari @jinapark202, I don't have permission to merge this. Can someone merge for me? Thank you.

2023-01-23 21:49 UTC, NolanChan commented
Hi @murphpdx , I just ran the CI and it seems like some Heap tests failed?

2023-01-23 23:41 UTC, merged