Add new @case directive that supports lower() and upper() functions
segmentio/action-destinations pull request #834
Opened 2022-10-24 23:57 UTC by LLuque-twilio

This PR addresses [JIRA ACT-92](https://segment.atlassian.net/browse/ACT-92)

In it, we add a new `@case` directive that will allow mapping a string from its value in the incoming event to its equivalent `toLowercase()` or `toUppercase()` value. This change will have to be accompanied by a change in `app` that supports these new directives, but that is non-blocking since this PR needs to be implemented first.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

Added unit tests to ensure correct functionality.

Next testing stages:
- stage deploy of new actions package => add package in `app` and send test events to see if functionality is correct

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [ ] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2022-10-25 00:21 UTC, NolanChan commented on packages/core/src/mapping-kit/validate.ts
> +  const type = realTypeOrDirective(v)
I think if it's just one case, it'd be a bit clearer to do an `if/else`!

2022-10-25 00:25 UTC, NolanChan commented on packages/core/src/mapping-kit/__tests__/index.test.ts
> +})
Could we have a test handling an error case? :)

2022-10-25 00:30 UTC, NolanChan reviewed
Besides two suggestions, looks good overall! Will wait for a staging test and then will approve!

2022-10-25 13:28 UTC, dlasky requested changes

2022-10-25 13:30 UTC, dlasky commented
Very solid initial start, I have a few nits around the testing specifically, as well as my slightly more important comment around what to do in the case where we have an unexpected type. In general I think mapping kit should be pretty forgiving so we dont lose data potentially due to a strangely formatted incoming segment event.

2022-10-25 17:06 UTC, NolanChan commented on packages/core/src/mapping-kit/validate.ts
> +  const type = realTypeOrDirective(v)
but that should go into `registerDirective` right?

2022-10-25 18:53 UTC, LLuque-twilio commented on packages/core/src/mapping-kit/validate.ts
> +  const type = realTypeOrDirective(v)
Think you are right here Nolan, the check for the specific operator will go in `registerDirective`, this should just be to ensure that the operator is a string in general!

2022-10-25 19:51 UTC, NolanChan commented on packages/core/src/mapping-kit/__tests__/index.test.ts
> +describe.only('@case', () => {
left an `.only` :)

2022-10-25 19:52 UTC, NolanChan commented on packages/core/src/mapping-kit/__tests__/index.test.ts
> +    console.log('number', output)
and `console.log`'s

2022-10-27 18:14 UTC, NolanChan commented on packages/core/src/mapping-kit/__tests__/index.test.ts
> +  test('handle non-string-input correctly', () => {
minor nit: clarify the test description so we know exactly what should happen, like "handle non-string-input by not modifying the value"

2022-10-27 18:16 UTC, NolanChan commented on packages/core/src/mapping-kit/index.ts
> +  // let condition = false
do we need this comment?

2022-11-03 17:56 UTC, ricardo-rossi approved these changes
lgtm

2022-11-04 15:51 UTC, merged