1plusx asset api
segmentio/action-destinations pull request #876
Opened 2022-11-15 17:09 UTC by SyedWasiHaider

This PR does the following:
1. adds a new Segment actions destination integrating with 1plusX Asset API (actions-1plusx-asset-api). The integration implements OAuth authentication and includes one type of the mapping.
2. updates the URL in the existing 1plusX destination (User API, slug actions-1plusx) to https://{settings.client_id}.tagger.opecloud.com/{settings.client_id]/v2/native/event (adds client_id variable in the domain portion) per request from 1PlusX team.

## Testing

_Include any additional information about the testing you have completed to
ensure your changes behave as expected. For a speedy review, please check
any of the tasks you completed below during your testing._

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
All unit tests pass.
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
Tested mapping functionality. Mappings work as expected.
- [x] [Segmenters] Tested in the staging environment. 
Tested authentication and sending the requests to 1PlusX API. Received 200 success responses. Test results can be found [here](https://docs.google.com/document/d/1YHfb53g9daE0oAr4VietFP0ZDtXAvt_xLOYfPWBgjLM/edit?usp=sharing).

2022-12-05 20:25 UTC, dlasky requested changes
1 minor nit, 2 q's

2022-12-05 20:25 UTC, dlasky commented on packages/destination-actions/src/destinations/1plusx-asset-api/__tests__/index.test.ts
> +//import nock from 'nock'
plz remove

2022-12-05 20:25 UTC, dlasky commented on packages/destination-actions/src/destinations/1plusx-asset-api/sendAssetData/index.ts
> +      // TODO still must include Date!
is this comment still relevant?

2022-12-05 20:25 UTC, dlasky commented on packages/destination-actions/src/destinations/1plusx/sendEvent/index.ts
> +      : `https://${settings.client_id}.tagger.opecloud.com/${settings.client_id}/v2/native/event`
just wanted to verify that this shouldn't be `client_name` ? just seems odd to me that the api would differ in that way but I don't know this destination at all.

2022-12-05 21:29 UTC, dlasky approved these changes
lgtm

2022-12-05 21:31 UTC, longstoryshort commented on packages/destination-actions/src/destinations/1plusx-asset-api/sendAssetData/index.ts
> +      // TODO still must include Date!
It is not, removed the comment

2022-12-06 22:40 UTC, longstoryshort commented on packages/destination-actions/src/destinations/1plusx/sendEvent/index.ts
> +      : `https://${settings.client_id}.tagger.opecloud.com/${settings.client_id}/v2/native/event`
updated variable name and setting names to align with the 1plusX original destination

2022-12-06 22:41 UTC, longstoryshort commented on packages/destination-actions/src/destinations/1plusx-asset-api/sendAssetData/index.ts
> +      // TODO still must include Date!
removed the comment

2022-12-06 22:41 UTC, longstoryshort commented on packages/destination-actions/src/destinations/1plusx-asset-api/__tests__/index.test.ts
> +//import nock from 'nock'
removed

2022-12-08 18:38 UTC, merged