Hgi 262 main state context
segmentio/action-destinations pull request #935
Opened 2022-12-13 09:57 UTC by Innovative-GauravKochar

https://segment.atlassian.net/jira/software/projects/HGI/boards/512?assignee=63617339fc0cc7a600b03c6b&selectedIssue=HGI-262

Testing completed successfully in Staging.Please look into this docs for further
https://docs.google.com/document/d/1BvV0LbT1aCYEeHw-vU7eo-aV4XplZNAs6j4gAZEWhwo/edit

2022-12-13 11:08 UTC, varadarajan-tw reviewed
LGTM. However, i would prefer a code-owner to do the approval

2022-12-13 19:37 UTC, brennan commented on packages/core/src/destination-kit/index.ts
> +}
We should ensure the method names match the method names used in the monoservice. I think this will eliminate any confusion about whether these methods correspond to methods used in the monoservice. 

```suggestion
export interface StateContext {
  // getRequestContext reads the `context` field from the request
  getRequestContext(key: string, cb?: (res?: string) => any): any
  // setResponseContext sets values in the `setContext` field in the response
  // values set on the response will be available on subsequent requests
  setResponseContext(key: string, value: string, ttl: { hour?: number; minute?: number; second?: number }): void
}
```

2022-12-13 19:38 UTC, brennan requested changes
@Innovative-GauravKochar The changes/testing look great to me! That said, I think the `stateContext` method names should match the method names used in the monoservice. Keeping the naming schema consistent will eliminate any confusion about what these methods are. Thank you!

2022-12-15 21:22 UTC, brennan approved these changes

2023-01-04 14:43 UTC, dlasky approved these changes

2023-01-04 15:04 UTC, merged