Voucherify-Segment.io Integration using action-destinations
segmentio/action-destinations pull request #970
Opened 2023-01-13 11:46 UTC by weronika-kurczyna

## Why

The existing integration of Voucherify with Segment.io is created using subscription-functions. We want to create a new Segment.io integration with Voucherify based on Webhooks and destination-actions (which makes field mapping and event management very easy), so we are creating this Pull Request. 
We are using the basic events that Segment.io offers. 

## What

We don't want to define a specific address for our application, so we added the 'customURL' option to 'authentication'. 
Event identifyCustomer can create or update data in Voucherify.
Event groupEvent adds the uploaded groups to the customer's metadata in Voucherify.
The track, page and screen events work very similarly and their function is to create custom events in Voucherify.

## Testing
The app has been tested manually and unit tests were created in the __tests__ folder.
Each case has been verified by us, we tested the app locally.

- [x] Added [unit tests](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing) for new functionality
- [x] Tested end-to-end using the [local server](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing)
- [ ] [Segmenters] Tested in the staging environment

2023-01-18 12:16 UTC, joe-ayoub-segment commented
Hi @weronika-kurczyna , thanks for submitting! 

We've updated our process for new Integration submissions slightly to include a face to face deep dive so that I can get a better understanding of how customers will use the Integration. This will allow me to provide you with more contextual feedback and to make sure the Integration follows some Segment best practices. 

Would you be open to meeting with me to discuss the following? 
1. How customers will use the Segment<>Voucherify Integration? main use-cases, etc. 
2. Review the code together and discuss and potentially agree changes

I'm based in EMEA (Ireland) and am in the same timezone as the UK. 
Would you be available to meet with me between 12:00 and 16:00 UK/Ireland time tomorrow (Thursday 19th Jan)?
If so please send me the email addresses for attendees to joe.ayoub@segment.com 

I look forward to hearing back from you. 
Kind regards,
Joe

2023-01-24 19:51 UTC, joe-ayoub-segment commented
hi @weronika-kurczyna please ping me when you are done with your changes to the PR, then I'll review. Thank you :)

2023-01-25 08:59 UTC, weronika-kurczyna commented
Hi,
of course, we're not done yet, but we will let you know about the new
changes :)


On Tue, 24 Jan 2023 at 20:51, Joe Ayoub ***@***.***> wrote:

> hi @weronika-kurczyna <https://github.com/weronika-kurczyna> please ping
> me when you are done with your changes to the PR, then I'll review. Thank
> you :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/segmentio/action-destinations/pull/970#issuecomment-1402509582>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A36ZJWB5RNIEO27AB7NWT7DWUAXDJANCNFSM6AAAAAAT2KDU7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-31 12:25 UTC, joe-ayoub-segment commented
Hi @weronika-kurczyna , just following up on this in case you'd like to get the changes out this week. Would probably need an update to the PR today if you wanted to make tomorrow's deploy.

2023-02-03 15:11 UTC, joe-ayoub-segment requested changes
Hi Weronika, 

I think the approach you've gone for with the 3 X Actions is better than before.
I suggested some minor code changes and recorded a few videos to explain some errors which need fixing. 

Thank you! 
Joe

2023-02-03 15:11 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/voucherify/index.ts
> +  presets: [
Hi @weronika-kurczyna , I recorded another video to discuss presets. This should answer your question from your email I hope! 

https://www.loom.com/share/c254aadc3e104c3f8bcdf4452371f6e1

2023-02-03 15:11 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/voucherify/addCustomEvent/index.ts
> +    event: {
Hi @weronika-kurczyna , here's a quick video discussing the event field and if it should be required or not. 
In your case it would be required if you were only handling track() calls, but you are also handling page() and screen() calls and these don't have the event name as a required field. 

https://www.loom.com/share/b4e33a9b716545ad8c2c0fb6c88e6730

2023-02-06 22:08 UTC, weronika-kurczyna commented on packages/destination-actions/src/destinations/voucherify/addCustomEvent/index.ts
> +      }
Should we get the email from traits even though the track/page/screen events don't have the traits object by default? Or maybe I missed something 😅

2023-02-06 22:22 UTC, weronika-kurczyna commented on packages/destination-actions/src/destinations/voucherify/upsertCustomer/index.ts
> +    traits: {
wow, thank you very much for the guidance! :) I appreciate that, that's exactly what we needed 👍

2023-02-06 22:36 UTC, weronika-kurczyna commented on packages/destination-actions/src/destinations/voucherify/index.ts
> +  presets: [
thanks, I guessed that the `event` is not necessarily required in this situation, but it is better to make sure :)

2023-02-06 22:38 UTC, weronika-kurczyna commented on packages/destination-actions/src/destinations/voucherify/addCustomEvent/index.ts
> +    event: {
thanks, I guessed that the event is not necessarily required in this situation, but it's better to make sure :)

2023-02-07 14:59 UTC, joe-ayoub-segment requested changes
Hi @weronika-kurczyna , only a couple minor items and I think we're done!

2023-02-07 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/voucherify/upsertCustomer/index.ts
> +        email: {
Looks like we might be allowing the customer to track email twice. There's the "Email Address" field, and then the "Custom Attributes" email field as well. Do we need both? Should we remove the "Custom Attributes" email field?

2023-02-07 14:59 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/voucherify/addCustomEvent/index.ts
> +      }
Ah yes you are correct, if a customer is going to pass an email address from a track(), page() or screen() call, it will probably come in via the properties or context.traits object. 
I would update the default to be: 

      default: {
        '@if': {
          exists: { '@path': '$.properties.email' },
          then: { '@path': '$.properties.email' },
          else: { '@path': '$.context.traits' }
        }
      }

2023-02-09 10:32 UTC, joe-ayoub-segment commented
Hi @weronika-kurczyna , just following up on the minor outstanding items. Let me know if you have any questions or you'd like to discuss them in a call. If you can get the change in today we should be able to get this live today. Otherwise the next deployment is next Wednesday.

2023-02-13 11:33 UTC, weronika-kurczyna commented on packages/destination-actions/src/destinations/voucherify/upsertCustomer/index.ts
> +        email: {
you're right, actually we don't need email in attributes

2023-02-14 15:25 UTC, joe-ayoub-segment requested changes
Hi @weronika-kurczyna , @patricioo1 , 

There's a couple of minor changes. If you can get them in I'll merge and the deploy should happen tomorrow. 

Best regards,
Joe

2023-02-15 08:53 UTC, weronika-kurczyna commented on packages/destination-actions/src/destinations/voucherify/assignCustomerToGroup/index.ts
> +      }
It's still a bit confusing to me, shouldn't the 'traits' object in Group https://segment.com/docs/connections/spec/group/ include only the 'traits' about the group? Is it possible to leave email field outside the object? Of course I corrected it the way you suggest but I'm not 100% sure. Or maybe relying on previous integrations you recommend that this email should be sent in the traits object? :)

2023-02-15 09:53 UTC, joe-ayoub-segment commented on packages/destination-actions/src/destinations/voucherify/assignCustomerToGroup/index.ts
> +      }
Hi @weronika-kurczyna , 
I see what you mean. The contents of the traits object in a group call is usually scoped to the organization and not to the user. 

We don't actually have a great way to separate user scoped fields from organization scoped fields in a group() call (everything is scoped to the organization). 

Happy to leave it either way. The customer can always override the default anyway. 
Please let me know which you'd like to go with an I'll approve and merge.

2023-02-15 11:13 UTC, weronika-kurczyna commented
Hi Joe,
Now I understand this 'group' issue. I'd leave it in the old version: ***@***.***':
'$.email'. Of course, if this is not a problem for you, I can always revert
the last change if it's not what you want :)

Anyway, we would be happy with the approval and merge. Thank you again for
your support!



On Wed, 15 Feb 2023 at 10:53, Joe Ayoub ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> packages/destination-actions/src/destinations/voucherify/assignCustomerToGroup/index.ts
> <https://github.com/segmentio/action-destinations/pull/970#discussion_r1106899824>
> :
>
> > +      default: {
> +        ***@***.***': '$.email'
> +      }
>
> Hi @weronika-kurczyna <https://github.com/weronika-kurczyna> ,
> I see what you mean. The contents of the traits object in a group call is
> usually scoped to the organization and not to the user.
>
> We don't actually have a great way to separate user scoped fields from
> organization scoped fields in a group() call (everything is scoped to the
> organization).
>
> Happy to leave it either way. The customer can always override the default
> anyway.
> Please let me know which you'd like to go with an I'll approve and merge.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/segmentio/action-destinations/pull/970#discussion_r1106899824>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A36ZJWFFGMSFMZ3U6JF4YMLWXSRR7ANCNFSM6AAAAAAT2KDU7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-15 14:05 UTC, joe-ayoub-segment approved these changes
Looks good! Thank you @weronika-kurczyna !

2023-02-15 14:17 UTC, merged

2023-02-16 18:05 UTC, joe-ayoub-segment commented
Hi @weronika-kurczyna , just FYI that this PR won't go out until next week.

2023-02-16 21:13 UTC, weronika-kurczyna commented
Hi,
OK, thank u for the information, I just want to make sure, do I understand
correctly that until the documentation is not approved this integration
will be in private beta, as written here:
https://segment.com/docs/partners/destinations/ ? There's also an
information that it could be created through Developer Portal. Of course we
don't want it to be public yet. :)

Best regards,
Weronika K

On Thu, 16 Feb 2023 at 19:06, Joe Ayoub ***@***.***> wrote:

> Hi @weronika-kurczyna <https://github.com/weronika-kurczyna> , just FYI
> that this PR won't go out until next week.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/segmentio/action-destinations/pull/970#issuecomment-1433502229>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A36ZJWCBVMAJBY5WMJNO7ZDWXZUARANCNFSM6AAAAAAT2KDU7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-27 15:18 UTC, joe-ayoub-segment commented
Hi @weronika-kurczyna , 
Confirming that your Integration is only in Private beta until you have completed docs and catalog info/metadata, and until you have done sufficient testing, ideally with a customer if possible. 

Please email partner-support@segment.com if you have any questions about next steps as I don't be monitoring this PR now that it's merged and deployed! 
Thank you,
Joe

2023-02-28 06:07 UTC, weronika-kurczyna commented
Hi,
Thank you for sharing this email contact. We're currently testing the
private beta and preparing the docs and catalog info. I think these steps
will be ready in a few days.:)

Best regards
Weronika


On Mon, 27 Feb 2023 at 16:18, Joe Ayoub ***@***.***> wrote:

> Hi @weronika-kurczyna <https://github.com/weronika-kurczyna> ,
> Confirming that your Integration is only in Private beta until you have
> completed docs and catalog info/metadata, and until you have done
> sufficient testing, ideally with a customer if possible.
>
> Please email ***@***.*** if you have any questions about
> next steps as I don't be monitoring this PR now that it's merged and
> deployed!
> Thank you,
> Joe
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/segmentio/action-destinations/pull/970#issuecomment-1446521677>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A36ZJWE76MULICQZETCIKU3WZTAVFANCNFSM6AAAAAAT2KDU7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>